import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createM13Examples } from '../../apps/web/src/m13-examples';
import { fixtureZip, workbookFiles } from '../helpers/m13-xlsx-fixtures';
import { readFileSync } from 'node:fs';
const m13Map = JSON.parse(readFileSync(new URL('../../docs/m13-implementation-map.json', import.meta.url), 'utf8')) as typeof import('../../docs/m13-implementation-map.json');
import type { CalcModel } from '../../packages/model/src';
async function workspace(page: Page) { await page.goto('/'); await expect(page.locator('.save-indicator')).toContainText('브라우저에 저장됨'); }
async function example(page: Page, id: string) { const entry = createM13Examples().find(example => example.id === id)!; await page.getByRole('button', { name: '예제로 시작', exact: true }).click(); await page.getByLabel('예제 카테고리').selectOption(entry.category); await page.locator(`[data-example-id="${id}"]`).click(); }
async function run(page: Page) { await page.locator('.run-button').click(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과'); }
async function download(page: Page, name: string, container?: ReturnType<Page['locator']>) { const event = page.waitForEvent('download'); await (container ?? page).getByRole('button', { name, exact: true }).click(); return readFile((await (await event).path())!, 'utf8'); }
async function history(page: Page) { await page.getByRole('tab', { name: '실험', exact: true }).click(); await expect(page.locator('.history-card').first()).toBeVisible(); return JSON.parse(await download(page, '기록 JSON', page.locator('.history-card').first())); }
async function importModel(page: Page, model: CalcModel) { await page.getByLabel('CalcWeave 모델 파일 선택').setInputFiles({ name: 'm13.cw.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(model)) }); }

test('M13 Unicode, Compose/Scan and ASCII examples preserve actual tagged output values', async ({ page }) => {
  await workspace(page); await example(page, 'string-unicode-search'); await run(page); let record = await history(page); expect(record.result.samples.at(-1).values['length-result']).toEqual({ kind: 'typed', dtype: 'uint32', shape: [], data: ['4'] }); expect(record.result.samples.at(-1).values['find-result'].data).toEqual(['2']); expect(record.result.samples.at(-1).values['count-result'].data).toEqual(['2']);
  await page.getByRole('tab', { name: '도식', exact: true }).click(); await example(page, 'string-compose-scan'); await run(page); record = await history(page); expect(record.result.samples.at(-1).values['text-result'].data).toEqual(['7,2.50']); expect(record.result.samples.at(-1).values['integer-result']).toMatchObject({ dtype: 'int32', data: ['7'] }); expect(record.result.samples.at(-1).values['fraction-result']).toMatchObject({ dtype: 'float64', data: [2.5] });
  await page.getByRole('tab', { name: '도식', exact: true }).click(); await example(page, 'string-ascii-roundtrip'); await run(page); record = await history(page); expect(record.result.samples.at(-1).values['bytes-result'].data).toEqual(['72', '105', '0', '0', '0', '0', '0', '0']); expect(record.result.samples.at(-1).values['text-result'].data).toEqual(['Hi']);
});

test('M13 bounded JSON drafts block execution and escaped string previews stay inert', async ({ page }) => {
  await workspace(page); await example(page, 'dashboard-recorded-controls'); await page.locator('.react-flow__node[data-id="control"]').click(); const field = page.getByLabel('시간·순서·값 이벤트 JSON', { exact: true }); await field.fill('[{"time":'); await field.blur(); await expect(field).toHaveAttribute('aria-invalid', 'true'); await page.locator('.run-button').click(); await expect(page.locator('.diagnostic-item')).toContainText('INVALID_NUMBER_DRAFT'); await field.fill('[]'); await field.blur(); await run(page);
  await example(page, 'string-ascii-roundtrip'); await page.locator('.react-flow__node[data-id="bytes"]').click(); await page.getByLabel('출력 크기', { exact: true }).fill('64'); await page.getByLabel('출력 크기', { exact: true }).blur(); await page.locator('.react-flow__node[data-id="text"]').click(); const text = page.getByLabel('문자열', { exact: true }); await text.fill('<script>alert(1)</script>'); await expect(page.locator('.react-flow__node[data-id="text"] .block-value')).toContainText('<script>'); expect(await page.locator('.react-flow__node[data-id="text"] script').count()).toBe(0); await run(page); const record = await history(page); expect(record.result.samples.at(-1).values['text-result'].data).toEqual(['<script>alert(1)</script>']);
});

test('M13 CSV formulas are blocked beyond preview while numeric negatives are imported with provenance', async ({ page }) => {
  await workspace(page); await page.getByRole('tab', { name: '데이터', exact: true }).click(); const input = page.getByLabel('데이터 파일', { exact: true }); await input.setInputFiles({ name: 'unsafe.csv', mimeType: 'text/csv', buffer: Buffer.from('time,value\n0,1\n1,2\n2,3\n3,4\n4,5\n5,6\n6,=CMD()') }); await expect(page.getByRole('alert')).toContainText('수식');
  await input.setInputFiles({ name: 'measure.csv', mimeType: 'text/csv', buffer: Buffer.from('\uFEFFtime,value\n0,-2\n1,4\n2,8') }); await page.getByRole('button', { name: '정리 결과 미리보기', exact: true }).click(); await page.getByRole('button', { name: '이 데이터 보관', exact: true }).click(); const card = page.locator('.dataset-card').filter({ hasText: 'measure' }); const dataset = JSON.parse(await download(page, 'JSON 다운로드', card)); expect(dataset.rows).toEqual([[0, -2], [1, 4], [2, 8]]); expect(dataset.provenance).toMatchObject({ format: 'csv', filename: 'measure.csv', sourceHash: dataset.sourceHash }); expect(dataset.sourceHash).toBe('010736b2800599493aed0830a79f0ed1e8e0cd62dabf65f537599dd12340b211');
});

test('M13 XLSX reads verified actual ZIP cells and rejects formula/external workbook files', async ({ page }) => {
  await workspace(page); await page.getByRole('tab', { name: '데이터', exact: true }).click(); const input = page.getByLabel('데이터 파일', { exact: true }); await input.setInputFiles({ name: 'values.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: Buffer.from(fixtureZip(workbookFiles(), 8)) }); await expect(page.getByLabel('XLSX 시트', { exact: true })).toHaveValue('실험'); await page.getByRole('button', { name: '정리 결과 미리보기', exact: true }).click(); await page.getByRole('button', { name: '이 데이터 보관', exact: true }).click(); const dataset = JSON.parse(await download(page, 'JSON 다운로드', page.locator('.dataset-card').filter({ hasText: 'values' }))); expect(dataset.rows).toEqual([[0, 2], [1, 6]]); expect(dataset.provenance).toMatchObject({ format: 'xlsx', filename: 'values.xlsx', sheet: '실험', sourceHash: dataset.sourceHash });
  const formula = workbookFiles(); formula['xl/worksheets/sheet1.xml'] = formula['xl/worksheets/sheet1.xml'].replace('<v>2</v>', '<f>1+1</f><v>2</v>'); await input.setInputFiles({ name: 'formula.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from(fixtureZip(formula)) }); await expect(page.getByRole('alert')).toContainText('수식');
  const external = workbookFiles(); external['xl/_rels/workbook.xml.rels'] = '<Relationships><Relationship Target="https://example.com" TargetMode="External"/></Relationships>'; await input.setInputFiles({ name: 'external.xlsx', mimeType: 'application/octet-stream', buffer: Buffer.from(fixtureZip(external)) }); await expect(page.getByRole('alert')).toContainText('외부');
});

test('M13 scenario editor checks increasing time and saves true named points for interpolation', async ({ page }) => {
  await workspace(page); await page.getByRole('tab', { name: '데이터', exact: true }).click(); await page.getByLabel('시나리오 이름', { exact: true }).fill('MyScenario'); const points = page.getByLabel('시나리오 점', { exact: true }); await points.fill('0,0\n0,1'); await page.getByRole('button', { name: '신호 검증', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('증가'); await expect(page.getByRole('button', { name: '시나리오 보관', exact: true })).toHaveCount(0);
  await points.fill('0,-2\n0.5,4\n1,8'); await page.getByRole('button', { name: '신호 검증', exact: true }).click(); await page.getByRole('button', { name: '시나리오 보관', exact: true }).click(); const dataset = JSON.parse(await download(page, 'JSON 다운로드', page.locator('.dataset-card').filter({ hasText: 'MyScenario' }))); expect(dataset.rows).toEqual([[0, -2], [.5, 4], [1, 8]]); expect(dataset.provenance.format).toBe('editor'); await page.getByRole('button', { name: 'MyScenario 재생 블록 추가', exact: true }).click(); const model = JSON.parse(await download(page, '모델 다운로드')); expect(model.nodes.some((node: { blockType: string; parameters: { datasetId: string } }) => node.blockType === 'data.signal-editor' && node.parameters.datasetId === dataset.id)).toBe(true);
});

test('M13 scheduled dashboard controls expose real gauges/bands and replay stable time orders', async ({ page }) => {
  await workspace(page); await example(page, 'dashboard-recorded-controls'); await run(page); await page.getByRole('tab', { name: '대시보드', exact: true }).click(); await expect(page.getByRole('img', { name: /반원 게이지 half 게이지 0.8/ })).toBeVisible(); await expect(page.locator('.m13-band-state')).toContainText('높음'); const record = await history(page); expect(record.result.samples.at(-1).values.result).toBe(.8); expect(record.result.samples[4].values.result).toBe(.4); expect(JSON.parse(record.model.nodes.find((node: { id: string }) => node.id === 'control').parameters.events)).toEqual([{ time: .3, order: 0, value: .4 }, { time: .6, order: 1, value: .8 }]);
  await page.getByRole('tab', { name: '도식', exact: true }).click(); await example(page, 'dashboard-choice-and-gain'); await run(page); const second = await history(page); expect(second.result.samples.at(-1).values.result).toBe(12);
});

test('M13 XY/floating/record workflow downloads raw points and saves real scalar dataset', async ({ page }) => {
  await workspace(page); await example(page, 'waveform-xy-and-record'); await run(page); await page.getByRole('tab', { name: '대시보드', exact: true }).click(); const xy = page.locator('.m13-widget').filter({ hasText: '실제 XY 궤적' }); await expect(xy.getByRole('img', { name: /XY 궤적 21개 점/ })).toBeVisible(); const saved = JSON.parse(await download(page, '기록 JSON', xy)); expect(saved.records).toHaveLength(21); expect(saved.records[0]).toMatchObject({ time: 0, value: { kind: 'bus', fields: [{ name: 'x', value: 0 }, { name: 'y', value: -1 }] } }); const csv = await download(page, '기록 CSV', xy); expect(csv).toContain('[exact signal JSON]'); expect(csv).toContain('""name"":""x""');
  await page.locator('.m13-widget').filter({ hasText: '데이터셋 기록' }).getByRole('button', { name: '데이터셋 보관', exact: true }).click(); await page.locator('.m13-widget').filter({ hasText: '참조 Scope' }).getByRole('button', { name: '크게 보기', exact: true }).click(); await expect(page.locator('.floating-scope-view')).toBeVisible(); await page.getByRole('button', { name: '크게 보기 닫기', exact: true }).click(); await page.getByRole('tab', { name: '데이터', exact: true }).click(); const dataset = JSON.parse(await download(page, 'JSON 다운로드', page.locator('.dataset-card').filter({ hasText: 'waveform-series' }))); expect(dataset.rows).toHaveLength(21); expect(dataset.rows[0]).toEqual([0, 0]); expect(dataset.rows[5][1]).toBeCloseTo(1, 12);
  const record = await history(page); expect(record.result.stateMemory.xy.m13Records).toEqual(saved.records);
});

test('M13 Stop Simulation returns completed with an exact final valid sample and reason', async ({ page }) => {
  await workspace(page); await example(page, 'bounded-record-and-stop'); await run(page); await page.getByRole('tab', { name: '대시보드', exact: true }).click(); await expect(page.getByRole('status').filter({ hasText: '정상 종료했습니다' })).toContainText('0.5 s'); const record = await history(page); expect(record.result.status).toBe('completed'); expect(record.result.stopReason).toEqual({ nodeId: 'stop', tick: 5, time: .5 }); expect(record.result.samples).toHaveLength(6); expect(record.result.stateMemory.record.m13Records.at(-1)).toEqual({ time: .5, value: .5 });
});

test('M13 live Worker edits apply at next tick, preserve initial values and replay exact raw samples', async ({ page }) => {
  test.setTimeout(60_000);
  await page.addInitScript(() => { const NativeWorker = Worker; let pause = true; class ObservedWorker extends NativeWorker { constructor(url: string | URL, options?: WorkerOptions) { super(url, options); this.addEventListener('message', event => { if (pause && event.data.type === 'progress') { pause = false; const button = [...document.querySelectorAll('button')].find(button => button.textContent?.trim() === '일시정지'); if (!button) throw new Error('Real pause button missing'); button.click(); } }); } } Reflect.set(window, 'Worker', ObservedWorker); });
  await workspace(page); const model = structuredClone(createM13Examples().find(example => example.id === 'dashboard-recorded-controls')!.model); model.nodes = model.nodes.filter(node => ['control', 'result'].includes(node.id)); model.nodes[0].label = '실시간'; model.nodes[0].parameters = { ...model.nodes[0].parameters, kind: 'edit', initial: 1, min: 0, max: 10, events: '[{"time":1500,"order":0,"value":4}]' }; model.edges = []; let previous = 'control'; for (let index = 0; index < 100; index++) { const id = `gain-${index}`; model.nodes.push({ id, blockType: 'math.gain', blockVersion: 1, label: '배율', parameters: { gain: 1 } }); model.edges.push({ id: `wire-${index}`, source: { nodeId: previous, portId: 'out' }, target: { nodeId: id, portId: 'in' } }); previous = id; } model.edges.push({ id: 'to-result', source: { nodeId: previous, portId: 'out' }, target: { nodeId: 'result', portId: 'in' } }); model.layout = {}; model.execution = { mode: 'discrete', startTime: 0, stopTime: 2000, step: 1 }; await importModel(page, model); await page.locator('.run-button').click(); await expect(page.getByRole('button', { name: '재개', exact: true })).toBeVisible(); await page.getByRole('tab', { name: '대시보드', exact: true }).click(); const value = page.getByLabel('실시간 값', { exact: true }); await value.fill('3'); await value.blur(); await expect(page.getByLabel('적용한 대시보드 이벤트')).toHaveText('0개 적용'); await page.getByRole('button', { name: '재개', exact: true }).click(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과', { timeout: 30_000 }); await expect(page.getByLabel('적용한 대시보드 이벤트')).toHaveText('1개 적용'); const controlled = await history(page); const source = controlled.model.nodes.find((node: { id: string }) => node.id === 'control'); expect(source.parameters.initial).toBe(1); const events = JSON.parse(source.parameters.events); expect(events).toHaveLength(2); const live = events.find((event: { value: number }) => event.value === 3); expect(live.time).toBeGreaterThan(0); expect(live.time).toBeLessThan(1500); expect(events.map((event: { order: number }) => event.order)).toEqual([0, 1]); expect(controlled.result.samples[live.time].values.result).toBe(3); expect(controlled.result.samples[live.time - 1].values.result).toBe(1); expect(controlled.result.samples.at(-1).values.result).toBe(4);
  await page.getByRole('button', { name: '이 실행의 모델 열기', exact: true }).first().click(); await page.getByRole('tab', { name: '도식', exact: true }).click(); await run(page); const replayed = await history(page); expect(replayed.result.samples).toEqual(controlled.result.samples); expect(replayed.semanticHash).toBe(controlled.semanticHash);
});

test('M13 data and dashboard controls fit both themes at 320px and 200% text', async ({ page }, testInfo) => {
  await workspace(page); await example(page, 'dashboard-recorded-controls'); await run(page);
  for (const theme of ['dark', 'light']) { if (await page.locator('.app-shell').evaluate(shell => shell.classList.contains('dark')) !== (theme === 'dark')) await page.getByRole('button', { name: `${theme === 'dark' ? '다크' : '라이트'} 테마로 변경`, exact: true }).click(); for (const [width, scale] of [[1440, 1], [1024, 1], [390, 1], [320, 2]]) { await page.setViewportSize({ width, height: 1200 }); await page.addStyleTag({ content: `html { font-size:${16 * scale}px !important; }` }); for (const tab of ['대시보드', '데이터']) { await page.getByRole('tab', { name: tab, exact: true }).click(); await expect.poll(() => page.evaluate(() => ({ document: document.documentElement.scrollWidth <= innerWidth + 1, controls: [...document.querySelectorAll('.workspace-tools input:not([type=file]),.workspace-tools textarea,.workspace-tools select')].filter(element => { const rect = element.getBoundingClientRect(); return rect.width > 0; }).every(element => { const rect = element.getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth + 1; }) }))).toEqual({ document: true, controls: true }); if (width === 1440 || width === 320) await page.locator('.workspace-tools').screenshot({ path: testInfo.outputPath(`${tab === '대시보드' ? 'dashboard' : 'data'}-${theme}-${width}-${scale}x.png`) }); } } }
});


test('M13 all37 source dashboard profiles render real independent controls and observed values', async ({ page }) => {
  test.setTimeout(60_000); await workspace(page);
  const profiles = m13Map.rows.filter(row => row.sourceSection === 3), nodes: CalcModel['nodes'] = [{ id: 'observed', blockType: 'source.constant', blockVersion: 1, label: '관측0.75', parameters: { value: .75 } }], edges: CalcModel['edges'] = [];
  for (const row of profiles) { const id = `profile-${row.id}`, selected = row.selectedImplementation; nodes.push({ id, blockType: selected.canonical, blockVersion: 1, label: row.sourceName, parameters: { ...selected.parameters, title: `${row.id} ${row.sourceName}` } }); if ((selected.requiredBindings as string[]).includes('in')) edges.push({ id: `input-${row.id}`, source: { nodeId: 'observed', portId: 'out' }, target: { nodeId: id, portId: 'in' } }); }
  const model: CalcModel = { schemaVersion: 1, modelId: 'all-dashboard-profiles', name: '37개 조작 표시', nodes, edges, layout: {}, execution: { mode: 'discrete', startTime: 0, stopTime: .1, step: .1 } };
  await importModel(page, model); await page.getByRole('tab', { name: '대시보드', exact: true }).click();
  const expected: Record<string, number> = {};
  for (const row of profiles) { const p = row.selectedImplementation.parameters as Record<string, unknown>, id = `profile-${row.id}`, card = page.locator(`[data-node-id="${id}"]`); await expect(card).toBeVisible(); await expect(card).toHaveAttribute('data-widget-appearance', String(p.appearance)); if (p.orientation === 'vertical') await expect(card).toHaveClass(/vertical-widget/);
    if (row.selectedImplementation.canonical === 'dashboard.control') { const kind = String(p.kind); await expect(card).toHaveAttribute('data-widget-kind', kind); if (['check-box', 'rocker-switch', 'slider-switch', 'toggle-switch'].includes(kind)) { await card.getByRole('checkbox').check(); expected[id] = 1; } else if (kind === 'push-button') { await card.getByRole('button', { name: /누르기/ }).click(); expected[id] = 1; } else if (kind === 'radio-button') { await card.getByRole('radio').last().check(); expected[id] = 1; } else if (['combo-box', 'rotary-switch'].includes(kind)) { await card.getByRole('combobox').selectOption('1'); expected[id] = 1; } else if (kind === 'edit') { await card.getByRole('textbox').fill('.5'); await card.getByRole('textbox').blur(); expected[id] = .5; } else { await card.getByRole('slider').focus(); await card.getByRole('slider').press('ArrowRight'); expected[id] = .1; } }
  }
  const actionRows = profiles.filter(row => row.selectedImplementation.canonical === 'dashboard.action');
  for (const row of actionRows) { await page.locator(`[data-node-id="profile-${row.id}"]`).getByRole('button', { name: '계산 실행', exact: true }).click(); await expect(page.locator('.run-button')).toBeVisible(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과'); }
  for (const row of profiles.filter(row => row.selectedImplementation.canonical === 'dashboard.indicator')) { const p = row.selectedImplementation.parameters as Record<string, unknown>, card = page.locator(`[data-node-id="profile-${row.id}"]`); await expect(card.locator('.comparison-value')).toHaveText('0.75'); if (p.kind === 'gauge') await expect(card.locator(`.gauge-${p.gaugeStyle}`)).toBeVisible(); if (p.kind === 'scope') await expect(card.locator('svg')).toBeVisible(); if (p.kind === 'lamp' || p.kind === 'multi-state-image') await expect(card.getByRole('status')).toContainText('높음'); }
  const record = await history(page); for (const [id, value] of Object.entries(expected)) expect(record.result.samples.at(-1).values[id]).toBeCloseTo(value, 12); expect(Object.keys(expected)).toHaveLength(profiles.filter(row => row.selectedImplementation.canonical === 'dashboard.control').length); for (const row of profiles.filter(row => row.selectedImplementation.canonical === 'dashboard.indicator')) expect(record.result.samples.at(-1).values[`profile-${row.id}`]).toBe(.75);
});
