import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { createM14Examples } from '../../apps/web/src/m14-examples';
import { BUILTIN_ADAPTER_PROFILES, UNAVAILABLE_ADAPTER_PROFILES, type CalcModel } from '../../packages/model/src';

async function workspace(page: Page) { await page.goto('/'); await expect(page.locator('.save-indicator')).toContainText('브라우저에 저장됨'); }
async function example(page: Page, id: string) { await page.getByRole('tab', { name: '도식', exact: true }).click(); await page.getByRole('button', { name: '예제로 시작', exact: true }).click(); await page.getByLabel('예제 카테고리').selectOption('adapters'); await page.locator(`[data-example-id="${id}"]`).click(); }
async function run(page: Page) { await page.locator('.run-button').click(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과'); }
async function download(page: Page, name: string, container?: ReturnType<Page['locator']>) { const event = page.waitForEvent('download'); await (container ?? page).getByRole('button', { name, exact: true }).click(); return readFile((await (await event).path())!, 'utf8'); }
async function history(page: Page) { await page.getByRole('tab', { name: '실험', exact: true }).click(); await expect(page.locator('.history-card').first()).toBeVisible(); return JSON.parse(await download(page, '기록 JSON', page.locator('.history-card').first())); }
async function importModel(page: Page, model: CalcModel) { await page.getByLabel('CalcWeave 모델 파일 선택').setInputFiles({ name: 'm14.cw.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(model)) }); await expect(page.locator('.canvas-topline strong')).toHaveText(model.name); }
async function catalog(page: Page) { await page.getByRole('button', { name: '지원·릴리스', exact: true }).click(); await page.getByRole('button', { name: '확장 실행', exact: true }).click(); return page.getByRole('dialog', { name: '지원·릴리스' }); }

test('M14 catalog shows all three pinned alternatives and eight unavailable native environments without executable inputs', async ({ page }) => {
  const errors: string[] = [], requests: string[] = []; page.on('pageerror', error => errors.push(error.message)); page.on('request', request => requests.push(request.url()));
  await workspace(page); const dialog = await catalog(page); await expect(dialog.locator('[data-adapter-id]')).toHaveCount(11);
  for (const profile of BUILTIN_ADAPTER_PROFILES) { await dialog.locator(`[data-adapter-id="${profile.id}"]`).click(); const details = dialog.locator(`[data-adapter-profile="${profile.id}"]`); await expect(details).toHaveAttribute('data-adapter-available', 'true'); if (profile.artifact) { await expect(details).toContainText(profile.artifact.sha256); await expect(details).toContainText(`${profile.artifact.byteLength} bytes`); for (const entry of profile.artifact.exports) await expect(details).toContainText(`${entry.name}(${entry.parameters.join(', ')})`); } await details.getByText('출처·제품·권리', { exact: true }).click(); await expect(details).toContainText('NOASSERTION'); await expect(details).toContainText(profile.provenance.author); }
  await dialog.getByLabel('확장 제공 상태').selectOption('unavailable'); await expect(dialog.locator('[data-adapter-id]')).toHaveCount(8);
  for (const profile of UNAVAILABLE_ADAPTER_PROFILES) { await dialog.locator(`[data-adapter-id="${profile.id}"]`).click(); const details = dialog.locator(`[data-adapter-profile="${profile.id}"]`); await expect(details).toHaveAttribute('data-adapter-available', 'false'); await expect(details.getByRole('status')).not.toBeEmpty(); await expect(details).toContainText('M14_NATIVE_ENVIRONMENT_UNAVAILABLE'); await expect(details).toContainText('실행하지 않습니다'); expect(await details.locator('button,input,textarea,select').count()).toBe(0); }
  expect(await dialog.locator('input[type="file"],textarea').count()).toBe(0); await dialog.getByLabel('확장 프로파일 검색').fill('no-matching-profile'); await expect(dialog.locator('[data-adapter-profile]')).toHaveCount(0); await expect(dialog).toContainText('일치하는 프로파일이 없습니다'); await page.keyboard.press('Escape'); expect(errors).toEqual([]); const origin = new URL(page.url()).origin; expect(requests.filter(url => !url.startsWith(`${origin}/`))).toEqual([]);
});

test('M14 real static WASM and bounded manual expression agree, inspector pins and saved manifest stay exact', async ({ page }) => {
  await workspace(page); await example(page, 'wasm-affine-and-expression'); await page.locator('.react-flow__node[data-id="affine"]').click(); const inspector = page.getByRole('region', { name: '확장 실행 계약' }); await inspector.getByText('ABI·출처·상한 보기', { exact: true }).click(); await expect(inspector).toContainText(BUILTIN_ADAPTER_PROFILES[0].artifact!.sha256); await expect(page.locator('.react-flow__node[data-id="affine"] .block-name')).toHaveText('WASM Affine'); await run(page); const record = await history(page); expect(record.result.samples[0].values).toMatchObject({ 'wasm-result': 7, 'expression-result': 7 }); expect(record.manifest.adapterReferences).toEqual([{ nodeId: 'affine', profile: BUILTIN_ADAPTER_PROFILES[0] }]); expect(record.model.nodes.find((node: { id: string }) => node.id === 'expression').parameters.expression).toBe('3*x+1'); await page.getByRole('button', { name: '이 실행의 모델 열기', exact: true }).first().click(); await page.reload(); await expect(page.locator('.canvas-topline strong')).toHaveText(record.model.name); await run(page); const rerun = await history(page); expect(rerun.result.samples).toEqual(record.result.samples); expect(rerun.semanticHash).toBe(record.semanticHash);
});

test('M14 pure WASM is evaluated by the continuous Worker solver against analytic decay', async ({ page }) => {
  await workspace(page); await example(page, 'wasm-continuous-decay'); await run(page); const record = await history(page); expect(record.result.samples).toHaveLength(21); expect(record.result.samples.at(-1).values.result).toBeCloseTo(Math.exp(-2), 6); expect(record.result.solverStatistics.evaluations).toBeGreaterThan(0); expect(record.manifest.adapterReferences[0].profile.supportedModes).toEqual(['static', 'discrete', 'continuous']);
});

test('M14 actual reset modes and two independent WASM states terminate with matching lifecycle receipts', async ({ page }) => {
  await workspace(page); await example(page, 'wasm-accumulator-resets'); await run(page); await page.getByText('확장 상태 종료 기록 · 2개', { exact: true }).click(); await expect(page.locator('.adapter-lifecycle-summary')).toContainText('초기화·종료 완료'); let record = await history(page); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values['rising-result'])).toEqual([0, 1, 2, 0, 1, 2, 3]); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values['level-result'])).toEqual([0, 1, 2, 0, 0, 0, 0]); expect(record.result.adapterLifecycle).toHaveLength(2); for (const row of record.result.adapterLifecycle) expect(row).toMatchObject({ profileId: 'calcweave.wasm-accumulator-f64-v1', initialized: true, terminated: true, reason: 'completed' });
  await example(page, 'wasm-independent-instances'); await run(page); record = await history(page); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values['first-result'])).toEqual([0, 1, 2, 3]); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values['second-result'])).toEqual([10, 12, 14, 16]); expect(record.result.adapterLifecycle.map((row: { nodeId: string }) => row.nodeId).sort()).toEqual(['first', 'second']);
});

test('M14 FIFO delay preserves head order, arrival time and exact uint64 message payload', async ({ page }) => {
  await workspace(page); await example(page, 'entity-fifo-delay'); await run(page); const record = await history(page), released = record.result.samples.flatMap((sample: { time: number; values: Record<string, { items: { producer: string; sequence: number; time: number; payload: unknown }[] }> }) => sample.values.messages.items.map(item => ({ acceptedTime: sample.time, item })));
  expect(released.map((entry: { item: { sequence: number } }) => entry.item.sequence)).toEqual([0, 1, 2, 3]); released.forEach((entry: { acceptedTime: number; item: { producer: string; time: number; payload: unknown } }, index: number) => { expect(entry.acceptedTime).toBeCloseTo(.3 + .1 * index, 12); expect(entry.item.time).toBeCloseTo(.1 * index, 12); expect(entry.item.producer).toBe('ticket'); expect(entry.item.payload).toEqual({ kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] }); }); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values.count)).toEqual([1, 2, 3, 3, 2, 1, 0]); expect(record.result.adapterLifecycle ?? []).toEqual([]);
});

test('M14 capacity policies retain distinct first or last message without changing envelope metadata', async ({ page }) => {
  await workspace(page); await example(page, 'entity-capacity-policies'); await run(page); const record = await history(page), values = record.result.samples[2].values; expect(values['newest-result'].items).toEqual([{ producer: 'batch', sequence: 1, time: 0, priority: 0, payload: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } }]); expect(values['oldest-result'].items).toEqual([{ producer: 'batch', sequence: 2, time: 0, priority: 0, payload: { kind: 'typed', dtype: 'uint64', shape: [], data: ['9223372036854775808'] } }]);
});

test('M14 capacity and WASM failure report real nodes, terminate states and recover after inspector repair', async ({ page }) => {
  await workspace(page); const model = structuredClone(createM14Examples()[5].model); model.nodes.find(node => node.id === 'newest')!.parameters.overflow = 'error'; await importModel(page, model); await page.locator('.run-button').click(); await expect(page.locator('.diagnostic-item')).toContainText('M14_ENTITY_CAPACITY'); await page.locator('.diagnostic-item').filter({ hasText: 'M14_ENTITY_CAPACITY' }).click(); await expect(page.getByLabel('초과 처리', { exact: true })).toHaveValue('error'); await page.getByLabel('초과 처리', { exact: true }).selectOption('drop-newest'); await run(page); let record = await history(page); expect(record.result.status).toBe('completed'); expect(record.result.samples[2].values['newest-result'].items[0].sequence).toBe(1);
  await page.getByRole('tab', { name: '도식', exact: true }).click(); const overflow = structuredClone(createM14Examples()[3].model); overflow.nodes.find(node => node.id === 'one')!.parameters.value = 2; overflow.nodes.find(node => node.id === 'first')!.parameters.gain = Number.MAX_VALUE; await importModel(page, overflow); await page.locator('.run-button').click(); await expect(page.locator('.diagnostic-item')).toContainText('M14_ADAPTER_NONFINITE'); record = await history(page); expect(record.result.status).toBe('failed'); expect(record.result.samples).toHaveLength(1); expect(record.result.adapterLifecycle).toHaveLength(2); expect(record.result.adapterLifecycle.every((row: { reason: string }) => row.reason === 'failed')).toBe(true);
  await page.getByRole('tab', { name: '도식', exact: true }).click(); await page.locator('.diagnostic-item').filter({ hasText: 'M14_ADAPTER_NONFINITE' }).click(); const gain = page.getByLabel('샘플별 증분 배율', { exact: true }); await gain.fill('1'); await gain.blur(); await run(page); record = await history(page); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values['first-result'])).toEqual([0, 2, 4, 6]); expect(record.result.adapterLifecycle.every((row: { reason: string }) => row.reason === 'completed')).toBe(true);
});

test('M14 cancelling a real initialized Worker returns terminated receipts and allows a fresh independent run', async ({ page }) => {
  test.setTimeout(60_000);
  await page.addInitScript(() => { const NativeWorker = Worker; let pause = true; const results: unknown[] = []; Reflect.set(window, 'm14WorkerResults', results); class ObservedWorker extends NativeWorker { constructor(url: string | URL, options?: WorkerOptions) { super(url, options); this.addEventListener('message', event => { if (event.data.type === 'result') results.push(event.data.result); if (pause && event.data.type === 'progress') { pause = false; const button = [...document.querySelectorAll('button')].find(button => button.textContent?.trim() === '일시정지'); if (!button) throw new Error('Actual pause button missing'); button.click(); } }); } } Reflect.set(window, 'Worker', ObservedWorker); });
  await workspace(page); const model = structuredClone(createM14Examples()[3].model); model.execution = { mode: 'discrete', startTime: 0, stopTime: 1000, step: 1 }; model.layout = {}; let previous = 'one'; for (let index = 0; index < 64; index++) { const id = `cost-${index}`; model.nodes.push({ id, blockType: 'math.gain', blockVersion: 1, label: '배율', parameters: { gain: 1 } }); model.edges.push({ id: `cost-wire-${index}`, source: { nodeId: previous, portId: 'out' }, target: { nodeId: id, portId: 'in' } }); previous = id; } model.edges.push({ id: 'observed-cost', source: { nodeId: previous, portId: 'out' }, target: { nodeId: 'first', portId: 'in' } }); model.edges = model.edges.filter(edge => edge.id !== 'one-out-first-in'); await importModel(page, model); await page.locator('.run-button').click(); await expect(page.getByRole('button', { name: '재개', exact: true })).toBeVisible(); await page.getByRole('button', { name: '계산 취소', exact: true }).click(); await expect(page.locator('.run-brand')).toHaveAttribute('data-activity', 'cancelled'); await expect.poll(() => page.evaluate(() => Reflect.get(window, 'm14WorkerResults').some((result: { status: string }) => result.status === 'cancelled'))).toBe(true); const cancelled = await page.evaluate(() => Reflect.get(window, 'm14WorkerResults').find((result: { status: string }) => result.status === 'cancelled')); expect(cancelled.samples.length).toBeGreaterThan(0); expect(cancelled.samples.length).toBeLessThan(1001); expect(cancelled.adapterLifecycle).toHaveLength(2); cancelled.adapterLifecycle.forEach((row: { reason: string; initialized: boolean; terminated: boolean }) => expect(row).toMatchObject({ reason: 'cancelled', initialized: true, terminated: true })); await example(page, 'wasm-independent-instances'); await run(page); const fresh = await history(page); expect(fresh.result.samples.map((sample: { values: Record<string, number> }) => sample.values['first-result'])).toEqual([0, 1, 2, 3]); expect(fresh.result.adapterLifecycle.every((row: { reason: string }) => row.reason === 'completed')).toBe(true);
});

test('M14 adapter metadata fits dark and light layouts through 320px with 200% text', async ({ page }, testInfo) => {
  await workspace(page);
  for (const theme of ['dark', 'light']) {
    if (await page.locator('.app-shell').evaluate(shell => shell.classList.contains('dark')) !== (theme === 'dark')) await page.getByRole('button', { name: `${theme === 'dark' ? '다크' : '라이트'} 테마로 변경`, exact: true }).click();
    const dialog = await catalog(page); await dialog.locator(`[data-adapter-id="${BUILTIN_ADAPTER_PROFILES[1].id}"]`).click();
    for (const [width, scale] of [[1440, 1], [1024, 1], [390, 1], [320, 2]]) {
      await page.setViewportSize({ width, height: 1200 }); await page.addStyleTag({ content: `html { font-size:${16 * scale}px !important; }` });
      await expect.poll(() => page.evaluate(() => ({ document: document.documentElement.scrollWidth <= innerWidth + 1, visibleControls: [...document.querySelectorAll('.adapter-catalog input,.adapter-catalog select,.adapter-profile-detail,.adapter-hash')].filter(element => element.getBoundingClientRect().width > 0).every(element => { const r = element.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth + 1; }) }))).toEqual({ document: true, visibleControls: true });
      const hash = dialog.locator('.adapter-hash'); await hash.scrollIntoViewIfNeeded(); await expect(hash).toBeVisible(); await expect(hash).toHaveText(BUILTIN_ADAPTER_PROFILES[1].artifact!.sha256);
      await expect.poll(() => hash.evaluate(element => { const rect = element.getBoundingClientRect(), dialog = element.closest('dialog')!.getBoundingClientRect(); return rect.top >= dialog.top && rect.bottom <= dialog.bottom; })).toBe(true);
      await dialog.screenshot({ path: testInfo.outputPath(`adapters-${theme}-${width}-${scale}x.png`) });
    }
    await page.keyboard.press('Escape');
  }
});
