import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { matFixture, mdlFixture, slxFixture, type FixtureBlock } from '../fixtures/m15-native';

async function workspace(page: Page) { await page.goto('./'); await expect(page.locator('.save-indicator')).toContainText('브라우저에 저장됨'); }
async function open(page: Page) { await page.getByRole('button', { name: '외부 형식 가져오기', exact: true }).click(); return page.getByRole('dialog', { name: '외부 형식 가져오기', exact: true }); }
async function select(page: Page, bytes: Uint8Array, name = 'M15.mdl') { await page.getByLabel('외부 형식 파일 선택').setInputFiles({ name, mimeType: 'application/octet-stream', buffer: Buffer.from(bytes) }); await expect(page.getByTestId('interop-stages')).toBeVisible(); }
async function apply(page: Page, data = false) { await page.getByLabel('변환 손실과 미검증 항목 확인').check(); await page.getByRole('button', { name: data ? '선택 데이터표 적용' : '변환 모델 적용', exact: true }).click(); }
async function download(page: Page, name: string, container?: ReturnType<Page['locator']>): Promise<Buffer> { const event = page.waitForEvent('download'); await (container ?? page).getByRole('button', { name, exact: true }).click(); return readFile((await (await event).path())!); }
async function runHistory(page: Page) { await page.locator('.run-button').click(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과'); await page.getByRole('tab', { name: '실험', exact: true }).click(); await expect(page.locator('.history-card').first()).toBeVisible(); return JSON.parse((await download(page, '기록 JSON', page.locator('.history-card').first())).toString('utf8')); }

test('M15 MDL preview preserves current model until explicit loss review and actual Worker computes the converted graph', async ({ page }) => {
  await workspace(page); const name = await page.locator('.canvas-topline strong').textContent(); await open(page); await select(page, mdlFixture()); await expect(page.locator('.canvas-topline strong')).toHaveText(name!); await expect(page.getByRole('button', { name: '변환 모델 적용', exact: true })).toBeDisabled(); await expect(page.getByTestId('interop-stages')).toContainText('선택 profile 지원'); await expect(page.getByTestId('interop-stages')).toContainText('native 참조 실행 미검증'); await apply(page); await expect(page.locator('.canvas-topline strong')).toHaveText('M15 native fixture'); await expect(page.locator('.result-status')).not.toContainText('현재 모델의 결과'); const record = await runHistory(page); expect(record.result.samples[0].values.Native3).toBe(6); expect(record.model.nodes.map((node: { blockType: string }) => node.blockType)).toEqual(['source.constant', 'math.gain', 'sink.scope']); expect(record.model).not.toHaveProperty('sidecar');
});
test('M15 SLX referenced root system imports and continuous Worker agrees with an analytic integral', async ({ page }) => {
  await workspace(page); await open(page); const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '2' } }, { id: '2', type: 'Integrator', parameters: { InitialCondition: '1' } }, { id: '3', type: 'Scope' }]; await select(page, slxFixture(blocks, undefined, {}, true), 'integral.slx'); await expect(page.getByTestId('interop-stages')).toContainText('선택 profile 지원'); await apply(page); const record = await runHistory(page); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values.Native3)).toEqual([1, 1.5, 2, 2.5, 3]); expect(record.model.execution.mode).toBe('continuous'); expect(record.model.execution.solver.method).toBe('rk4');
});
test('M15 native Unit Delay ordering is retained by the real discrete Worker', async ({ page }) => {
  await workspace(page); await open(page); const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '1' } }, { id: '2', type: 'UnitDelay', parameters: { InitialCondition: '-1', SampleTime: '.25' } }, { id: '3', type: 'Scope' }]; await select(page, mdlFixture(blocks)); await apply(page); const record = await runHistory(page); expect(record.result.samples.map((sample: { values: Record<string, number> }) => sample.values.Native3)).toEqual([-1, 1, 1, 1, 1]); expect(record.model.nodes[1].parameters.initial).toBe(-1);
});
test('M15 unbound Inport stays unsupported and finite explicit inputs are rechecked before applying', async ({ page }) => {
  await workspace(page); await open(page); const blocks: FixtureBlock[] = [{ id: '1', type: 'Inport' }, { id: '2', type: 'Gain', parameters: { Gain: '3' } }, { id: '3', type: 'Outport' }]; await select(page, mdlFixture(blocks)); await expect(page.getByLabel('외부 입력 1')).toHaveValue(''); await expect(page.getByTestId('interop-stages')).toContainText('미지원 항목 확인 필요'); await page.getByLabel('변환 손실과 미검증 항목 확인').check(); await expect(page.getByRole('button', { name: '변환 모델 적용', exact: true })).toBeDisabled(); await page.getByLabel('외부 입력 1').fill('Infinity'); await page.getByRole('button', { name: '입력 설정 다시 검사', exact: true }).click(); await expect(page.getByRole('alert')).toContainText('유한 scalar'); await page.getByLabel('외부 입력 1').fill('2.0'); await page.getByRole('button', { name: '입력 설정 다시 검사', exact: true }).click(); await expect(page.getByLabel('외부 입력 1')).toHaveValue('2'); await expect(page.getByTestId('interop-stages')).toContainText('선택 profile 지원'); await apply(page); const record = await runHistory(page); expect(record.result.samples[0].values.Native3).toBe(6); expect(record.model.nodes[0].parameters.value).toBe(2);
});
test('M15 MAT column-major table imports exact values and preserves raw source in its separate archive', async ({ page }) => {
  await workspace(page); await open(page); const bytes = matFixture('sample', [[0, 1, -3], [.5, 2, 0], [1, 3, 9]]); await select(page, bytes, 'signals.mat'); await page.getByLabel('MAT 변수').selectOption('sample'); await expect(page.locator('.interop-table')).toContainText('시각(s)'); const original = await download(page, '원본 파일 다운로드'); expect(original).toEqual(Buffer.from(bytes)); const archive = JSON.parse((await download(page, '원본·변환 보관 파일')).toString('utf8')); expect(Buffer.from(archive.source.bytes, 'base64')).toEqual(Buffer.from(bytes)); expect(archive.convertedDataset.rows).toEqual([[0, 1, -3], [.5, 2, 0], [1, 3, 9]]); expect(archive.convertedDataset.provenance.format).toBe('mat-v5'); await apply(page, true); const saved = JSON.parse((await download(page, '모델 다운로드')).toString('utf8')); const dataset = saved.datasets.find((item: { name: string }) => item.name === 'sample'); expect(dataset.rows).toEqual(archive.convertedDataset.rows); expect(dataset.sourceHash).toBe(archive.source.sha256); expect(dataset.provenance.format).toBe('mat-v5'); expect(saved).not.toHaveProperty('originalBytes');
});
test('M15 archive reimport rejects altered reports and model claims, then reparses the genuine raw source', async ({ page }) => {
  await workspace(page); const name = await page.locator('.canvas-topline strong').textContent(); await open(page); await select(page, slxFixture(), 'M15.slx'); const buffer = await download(page, '원본·변환 보관 파일'), original = JSON.parse(buffer.toString('utf8')); for (const kind of ['report', 'model']) { const corrupted = structuredClone(original); if (kind === 'report') corrupted.report.numericalEquivalence = 'verified'; else corrupted.convertedModel.nodes[0].parameters.value = 999; await page.getByLabel('외부 형식 파일 선택').setInputFiles({ name: 'forged.cwinterop.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(corrupted)) }); await expect(page.getByRole('alert')).toContainText(kind === 'report' ? '보고서' : '모델'); await expect(page.locator('.canvas-topline strong')).toHaveText(name!); } await page.getByLabel('외부 형식 파일 선택').setInputFiles({ name: 'genuine.cwinterop.json', mimeType: 'application/json', buffer }); await expect(page.getByTestId('interop-stages')).toContainText('선택 profile 지원'); await apply(page); expect((await runHistory(page)).result.samples[0].values.Native3).toBe(6);
});
test('M15 callback, unknown expression and external relationships remain escaped and inert', async ({ page }) => {
  const errors: string[] = [], requests: string[] = [], dialogs: string[] = []; page.on('pageerror', error => errors.push(error.message)); page.on('request', request => requests.push(request.url())); page.on('dialog', dialog => { dialogs.push(dialog.message()); void dialog.dismiss(); }); await workspace(page); const name = await page.locator('.canvas-topline strong').textContent(); const dialog = await open(page); const payload = '<script>alert("native-code")</script>', bytes = mdlFixture(undefined, undefined, { InitFcn: payload }); await select(page, bytes); await expect(dialog).toContainText(payload); await expect(dialog.locator('script')).toHaveCount(0); await expect(page.getByRole('button', { name: '변환 모델 적용', exact: true })).toBeDisabled(); const archived = JSON.parse((await download(page, '원본·변환 보관 파일')).toString('utf8')); expect(archived).not.toHaveProperty('convertedModel'); expect(Buffer.from(archived.source.bytes, 'base64')).toEqual(Buffer.from(bytes)); await select(page, slxFixture(undefined, undefined, { '_rels/.rels': '<Relationships><Relationship Id="external" TargetMode="External" Target="https://evil.test/code"/></Relationships>' }), 'external.slx'); await expect(dialog).toContainText('SLX_EXTERNAL_REFERENCE'); await expect(page.locator('.canvas-topline strong')).toHaveText(name!); expect(errors).toEqual([]); expect(dialogs).toEqual([]); const origin = new URL(page.url()).origin; expect(requests.filter(url => !url.startsWith(origin + '/'))).toEqual([]);
});
test('M15 malformed and oversized files preserve the workspace with distinct parsing failures', async ({ page }) => {
  await workspace(page); const name = await page.locator('.canvas-topline strong').textContent(); await open(page); await select(page, new TextEncoder().encode('Model {\n Name "unterminated')); await expect(page.getByTestId('interop-stages')).toContainText('실패'); await expect(page.getByRole('button', { name: '변환 모델 적용', exact: true })).toBeDisabled(); await page.getByLabel('외부 형식 파일 선택').setInputFiles({ name: 'oversized.mat', mimeType: 'application/octet-stream', buffer: Buffer.alloc(2 * 1024 * 1024 + 1) }); await expect(page.getByRole('alert')).toContainText('2 MiB'); await expect(page.locator('.canvas-topline strong')).toHaveText(name!);
});
test('M15 located loss reports and exact source SHA stay readable in dark/light 320px with 200% text', async ({ page }, testInfo) => {
  await workspace(page); for (const theme of ['dark', 'light']) { if (await page.locator('.app-shell').evaluate(shell => shell.classList.contains('dark')) !== (theme === 'dark')) await page.getByRole('button', { name: `${theme === 'dark' ? '다크' : '라이트'} 테마로 변경`, exact: true }).click(); const dialog = await open(page); await select(page, mdlFixture(undefined, undefined, { InitFcn: 'unknown_callback_with_a_long_original_name_preserved_for_location_review' }));
    for (const [width, scale] of [[1440, 1], [1024, 1], [390, 1], [320, 2]]) { await page.setViewportSize({ width, height: 1200 }); await page.addStyleTag({ content: `html { font-size:${16 * scale}px !important; }` }); await expect.poll(() => page.evaluate(() => ({ document: document.documentElement.scrollWidth <= innerWidth + 1, controls: [...document.querySelectorAll('.interop-content button,.interop-content input,.interop-hash')].filter(node => node.getBoundingClientRect().width > 1).every(node => { const rect = node.getBoundingClientRect(); return rect.left >= 0 && rect.right <= innerWidth + 1; }) }))).toEqual({ document: true, controls: true }); const hash = page.getByTestId('interop-source-hash'); await hash.scrollIntoViewIfNeeded(); await expect(hash).toBeVisible(); await expect(hash).toHaveText(/^[a-f0-9]{64}$/); await expect.poll(() => hash.evaluate(node => { const r = node.getBoundingClientRect(), dialog = node.closest('dialog')!.getBoundingClientRect(); return r.top >= dialog.top && r.bottom <= dialog.bottom; })).toBe(true); await dialog.screenshot({ path: testInfo.outputPath(`interop-${theme}-${width}-${scale}x.png`) }); } await page.keyboard.press('Escape'); const trigger = page.getByRole('button', { name: '외부 형식 가져오기', exact: true }); await expect(trigger).toBeVisible(); await expect.poll(() => trigger.evaluate(node => { const r = node.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth + 1 && r.top >= 0 && r.bottom <= innerHeight; })).toBe(true); }
});
