import { expect, test, type Locator, type Page } from '@playwright/test';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { ENGINE_VERSION, type CalcModel } from '../../packages/model/src';
import { compileModel } from '../../packages/compiler/src';
import { sha256 } from '../../packages/model/src/sha256';
import { APP_VERSION } from '../../packages/release/src';
import type { HistoryRecord } from '../../apps/web/src/run-history';
import type { TimeSeriesSourceSnapshot } from '../../apps/web/src/time-series-analysis-sources';
import type { TimeFrequencyInput, TimeFrequencyOptions, TimeFrequencyReport } from '../../packages/analysis/src/time-frequency';

type ExportedReport = { schemaVersion: number; kind: string; engineVersion: string; previousRun: boolean; source: TimeSeriesSourceSnapshot; input: TimeFrequencyInput; inputFloat64Bits: { times: string[]; values: string[] }; samplesHashEncoding: string; options: TimeFrequencyOptions; result: TimeFrequencyReport };
function sine(count = 64): CalcModel {
  return { schemaVersion: 1, modelId: 'm25-recorded-sine', name: 'Welch와 STFT의 실제 사인 기록',
    execution: { mode: 'discrete', startTime: 0, stopTime: (count - 1) / count, step: 1 / count },
    nodes: [{ id: 'input', blockType: 'source.signal-generator', blockVersion: 1, label: '8 Hz 사인', parameters: { waveform: 'sine', amplitude: 3, frequency: 8, frequencyUnit: 'Hz', phase: Math.PI / 4, bias: 4, seed: 1 } },
      { id: 'scope', blockType: 'sink.scope', blockVersion: 1, label: '실수 기록', parameters: {} }],
    edges: [{ id: 'input-scope', source: { nodeId: 'input', portId: 'out' }, target: { nodeId: 'scope', portId: 'in' } }],
    layout: { input: { x: 40, y: 100 }, scope: { x: 350, y: 100 } } };
}
function chirp(): CalcModel { const model = sine(67); model.modelId = 'm25-recorded-chirp'; model.name = '4~20 Hz 주파수 스윕'; model.execution = { mode: 'discrete', startTime: 0, stopTime: 66 / 64, step: 1 / 64 }; model.nodes[0].blockType = 'source.chirp'; model.nodes[0].parameters = { amplitude: 2, initialFrequency: 4, finalFrequency: 20, duration: 1, phase: .3, bias: 1 }; return model; }
function typedNonFinite(): CalcModel { const model = sine(); model.nodes[0].blockType = 'source.typed'; model.nodes[0].parameters = { value: { kind: 'typed', dtype: 'float64', shape: [2], data: [1, 'NaN'] } }; return model; }
async function open(page: Page) { await page.goto('./'); await expect(page.locator('.research-badge')).toContainText(APP_VERSION); await expect(page.locator('.save-indicator')).toContainText('브라우저에 저장됨'); }
async function importModel(page: Page, model: CalcModel) { await page.getByLabel('CalcWeave 모델 파일 선택').setInputFiles({ name: 'm25.cw.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(model)) }); await expect(page.getByLabel('모델 이름', { exact: true })).toHaveValue(model.name); }
async function record(page: Page, model = sine()) { await importModel(page, model); await page.locator('.run-button').click(); await expect(page.locator('.result-status')).toContainText('현재 모델의 결과'); await expect(page.locator('.run-button')).toBeEnabled(); await expect.poll(async () => (await history(page)).length).toBe(1); }
async function panel(page: Page): Promise<Locator> { await page.getByRole('button', { name: '분석', exact: true }).click(); await page.getByRole('dialog', { name: '수치 분석', exact: true }).locator('.time-frequency-analysis-section > summary').click(); return page.getByTestId('time-frequency-panel'); }
async function download<T>(page: Page, label: string): Promise<T> { const downloading = page.waitForEvent('download'); await page.getByRole('button', { name: label, exact: true }).click(); return JSON.parse(await readFile((await (await downloading).path())!, 'utf8')) as T; }
async function analyze(page: Page, controls: Locator): Promise<ExportedReport> { const button = controls.getByRole('button', { name: '시간·주파수 계산', exact: true }); await button.click(); await expect(controls.getByRole('region', { name: '시간·주파수 분석 결과', exact: true })).toBeVisible(); await expect(button).toBeEnabled(); return download<ExportedReport>(page, '시간·주파수 JSON'); }
async function settings(controls: Locator, length: number, overlap: number, window: 'hann' | 'rectangular' = 'rectangular') { await controls.getByLabel('시간 주파수 창 길이', { exact: true }).fill(String(length)); await controls.getByLabel('시간 주파수 겹침', { exact: true }).fill(String(overlap)); await controls.getByLabel('시간 주파수 창', { exact: true }).selectOption(window); }
async function history(page: Page): Promise<HistoryRecord[]> { return page.evaluate(() => new Promise<HistoryRecord[]>((resolve, reject) => { const request = indexedDB.open('calcweave-m0', 1); request.onerror = () => reject(new Error('History open failed')); request.onsuccess = () => { const db = request.result, tx = db.transaction('models', 'readonly'), read = tx.objectStore('models').get('run-history-v1'); read.onsuccess = () => resolve(read.result ?? []); tx.oncomplete = () => db.close(); tx.onerror = () => reject(new Error('History read failed')); }; })); }

// Independent small-N DFT oracle. It never calls the production FFT, Welch or STFT implementation.
function dft(values: number[], sampleRate: number, window: 'hann' | 'rectangular', removeMean: boolean) {
  const count = values.length, mean = values.reduce((sum, value) => sum + value, 0) / count, weights = values.map((_, index) => window === 'hann' ? .5 - .5 * Math.cos(2 * Math.PI * index / count) : 1), sumWeights = weights.reduce((sum, value) => sum + value, 0), energy = weights.reduce((sum, value) => sum + value * value, 0);
  return Array.from({ length: count / 2 + 1 }, (_, index) => { let real = 0, imag = 0; for (let n = 0; n < count; n++) { const sample = (values[n] - (removeMean ? mean : 0)) * weights[n], angle = -2 * Math.PI * index * n / count; real += sample * Math.cos(angle); imag += sample * Math.sin(angle); } const factor = index === 0 || index === count / 2 ? 1 : 2; return { real, imag, frequency: index * sampleRate / count, amplitude: factor * Math.hypot(real, imag) / sumWeights, powerDensity: factor * (real * real + imag * imag) / (sampleRate * energy) }; });
}

test('M25 no completed recording disables analysis without starting a simulation', async ({ page }) => {
  await open(page); const controls = await panel(page); await expect(controls).toContainText('시간 시뮬레이션을 완료한 뒤'); await expect(controls.getByRole('button', { name: '시간·주파수 계산', exact: true })).toBeDisabled(); await expect(controls.getByLabel('시간 주파수 출력', { exact: true })).toHaveCount(0); await expect(page.locator('.result-status')).toContainText('아직 계산하지');
});

test('M25 actual Worker tone has analytic Welch PSD and preserves recording, model and settings', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); await open(page); await record(page); const original = await download<CalcModel>(page, '모델 다운로드'); await expect.poll(async () => (await history(page)).length).toBe(1); const recorded = (await history(page))[0], controls = await panel(page); await settings(controls, 16, 8); const report = await analyze(page, controls);
  expect(report).toMatchObject({ schemaVersion: 1, kind: 'recorded-time-frequency', engineVersion: ENGINE_VERSION, previousRun: false, options: { segmentLength: 16, overlap: 8, window: 'rectangular', removeMean: true, tail: 'discard' }, source: { outputId: 'scope', startIndex: 0, count: 64, sampleCount: 64 } }); expect(report.source.semanticHash).toBe(sha256(compileModel(original).semanticKey)); expect(report.source.samplesSha256).toBe(sha256(JSON.stringify(report.input))); expect(report.input.times).toEqual(recorded.result.samples.map(sample => sample.time)); expect(report.input.values).toEqual(recorded.result.samples.map(sample => sample.values.scope));
  expect(report.result).toMatchObject({ count: 64, segmentLength: 16, overlap: 8, hop: 8, frameCount: 7, binsPerFrame: 9, totalBins: 63, usedCount: 64, discardedCount: 0, discardedStartTime: null, sampleRate: 64, frequencyResolution: 4, nyquist: 32, averaging: 'arithmetic-periodograms', normalization: 'one-sided-density', coefficients: 'unnormalized-forward-dft', frameTimeConvention: 'midpoint-first-last-sample' }); expect(report.result.integratedPower).toBeCloseTo(4.5, 12); expect(report.result.welchPeak!.frequency).toBe(8); expect(report.result.welchBins[2].powerDensity).toBeCloseTo(1.125, 12);
  for (const frame of report.result.frames) { expect(frame.centerTime).toBe((frame.startTime + frame.endTime) / 2); expect(frame.mean).toBeCloseTo(4, 12); expect(frame.bins[2].amplitude).toBeCloseTo(3, 12); expect(frame.integratedPower).toBeCloseTo(4.5, 12); }
  await expect(controls.getByRole('img', { name: 'Welch 평균 PSD 그래프', exact: true })).toBeVisible(); await expect(controls.getByRole('img', { name: 'STFT 시간·주파수 히트맵', exact: true })).toHaveAttribute('data-display-count', '63'); await controls.getByRole('button', { name: 'dB PSD', exact: true }).click(); await expect(controls).toContainText('10 log₁₀'); await controls.getByLabel('시간 주파수 창', { exact: true }).selectOption('hann'); await controls.getByLabel('시간 주파수 평균 제거', { exact: true }).uncheck(); await controls.getByLabel('시간 주파수 창 길이', { exact: true }).fill('32'); expect(await download<ExportedReport>(page, '시간·주파수 JSON')).toEqual(report); await page.getByRole('button', { name: '수치 분석 닫기', exact: true }).click(); expect(await download<CalcModel>(page, '모델 다운로드')).toEqual(original); expect((await history(page))[0].result.samples).toEqual(recorded.result.samples); expect(errors).toEqual([]);
});

test('M25 selected chirp frames match direct DFT and preserve actual centers and discarded tail', async ({ page }) => {
  await open(page); await record(page, chirp()); const recorded = (await history(page))[0], controls = await panel(page); await controls.getByLabel('시간 주파수 시작 표본', { exact: true }).fill('3'); await controls.getByLabel('시간 주파수 표본 수', { exact: true }).fill('61'); await settings(controls, 16, 8, 'hann'); const report = await analyze(page, controls);
  expect(report.source).toMatchObject({ startIndex: 3, count: 61, sampleCount: 67, startTime: 3 / 64, endTime: 63 / 64 }); expect(report.input.times).toEqual(recorded.result.samples.slice(3, 64).map(sample => sample.time)); expect(report.input.values).toEqual(recorded.result.samples.slice(3, 64).map(sample => sample.values.scope)); expect(report.result).toMatchObject({ frameCount: 6, usedCount: 56, discardedCount: 5, usedEndTime: 58 / 64, discardedStartTime: 59 / 64 }); expect(report.result.windowCoherentGain).toBeCloseTo(.5, 14); expect(report.result.windowPowerGain).toBeCloseTo(.375, 14);
  const expectedFrames = report.result.frames.map((frame, index) => { const start = index * 8, end = start + 15; expect(frame).toMatchObject({ index, startIndex: start, endIndex: end, startTime: (3 + start) / 64, endTime: (3 + end) / 64, centerTime: (3 + start + 7.5) / 64 }); const oracle = dft(report.input.values.slice(start, end + 1), 64, 'hann', true); frame.bins.forEach((bin, binIndex) => { expect(bin.real).toBeCloseTo(oracle[binIndex].real, 10); expect(bin.imag).toBeCloseTo(oracle[binIndex].imag, 10); expect(bin.amplitude).toBeCloseTo(oracle[binIndex].amplitude, 10); expect(bin.powerDensity).toBeCloseTo(oracle[binIndex].powerDensity, 10); }); return oracle; });
  report.result.welchBins.forEach((bin, index) => expect(bin.powerDensity).toBeCloseTo(expectedFrames.reduce((sum, frame) => sum + frame[index].powerDensity, 0) / 6, 10)); await controls.getByLabel('STFT 프레임', { exact: true }).selectOption('5'); await expect(controls).toContainText('원래 기록 표본 43~58'); await controls.locator('.time-frequency-details > summary').filter({ hasText: 'STFT 선택 프레임 원시 빈' }).click(); const rows = controls.getByRole('table', { name: 'STFT 선택 프레임 원시 빈', exact: true }).locator('tbody tr'); await expect(rows).toHaveCount(9); await expect(rows.nth(3).locator('td').nth(2)).toHaveText(String(report.result.frames[5].bins[3].real)); expect(await download<ExportedReport>(page, '시간·주파수 JSON')).toEqual(report);
});

test('M25 one complete frame exposes DC and Nyquist normalization without tail padding', async ({ page }) => {
  const model = sine(8); model.nodes[0].parameters = { waveform: 'sine', amplitude: 3, frequency: 4, frequencyUnit: 'Hz', phase: Math.PI / 2, bias: 4, seed: 1 }; await open(page); await record(page, model); const controls = await panel(page); await settings(controls, 8, 0); await controls.getByLabel('시간 주파수 평균 제거', { exact: true }).uncheck(); const report = await analyze(page, controls);
  expect(report.result).toMatchObject({ frameCount: 1, usedCount: 8, discardedCount: 0, sampleRate: 8, frequencyResolution: 1 }); expect(report.result.frames[0].bins[0].amplitude).toBeCloseTo(4, 12); expect(report.result.frames[0].bins[0].powerDensity).toBeCloseTo(16, 12); expect(report.result.frames[0].bins[4].amplitude).toBeCloseTo(3, 12); expect(report.result.frames[0].bins[4].powerDensity).toBeCloseTo(9, 12); expect(report.result.integratedPower).toBeCloseTo(25, 12); await expect(controls).toContainText('프레임은 1개');
});

test('M25 malformed drafts retain snapshot while a valid nonfinite component clears old report', async ({ page }) => {
  await open(page); await record(page, typedNonFinite()); const controls = await panel(page), report = await analyze(page, controls); expect(report.source).toMatchObject({ valueType: 'typed', shape: [2], componentIndex: 0 });
  for (const value of ['12', '4096', '<img src=x onerror=alert(1)>']) { await controls.getByLabel('시간 주파수 창 길이', { exact: true }).fill(value); await controls.getByRole('button', { name: '시간·주파수 계산', exact: true }).click(); await expect(controls.getByRole('alert')).toBeVisible(); expect(await download<ExportedReport>(page, '시간·주파수 JSON')).toEqual(report); }
  expect(await controls.locator('img').count()).toBe(0); await controls.getByLabel('시간 주파수 창 길이', { exact: true }).fill('64'); await controls.getByLabel('시간 주파수 성분', { exact: true }).selectOption('1'); await controls.getByRole('button', { name: '시간·주파수 계산', exact: true }).click(); await expect(controls.getByRole('alert')).toContainText('비유한'); await expect(controls.getByRole('region', { name: '시간·주파수 분석 결과', exact: true })).toHaveCount(0); await expect(controls.getByRole('button', { name: '시간·주파수 JSON', exact: true })).toHaveCount(0);
});

test('M25 true zero PSD stays distinct in dB and negative zero retains IEEE input provenance', async ({ page }) => {
  const model = sine(); model.nodes[0].blockType = 'source.typed'; model.nodes[0].parameters = { value: { kind: 'typed', dtype: 'float64', shape: [], data: ['-0'] } }; await open(page); await record(page, model); const controls = await panel(page), report = await analyze(page, controls);
  expect(report.samplesHashEncoding).toBe('json-finite-numbers-negative-zero-token-v1'); expect(report.inputFloat64Bits.values).toEqual(Array(64).fill('8000000000000000')); expect(report.source.samplesSha256).toBe(sha256(JSON.stringify({ times: report.input.times, values: Array(64).fill('-0') }))); expect(report.result.welchBins.every(bin => bin.powerDensity === 0)).toBe(true); expect(report.result.welchPeak).toBeNull(); await controls.getByRole('button', { name: 'dB PSD', exact: true }).click(); await expect(controls).toContainText('정의된 양수 PSD 로그값 없음'); await expect(controls.locator('.time-frequency-zero-cell')).toHaveCount(report.result.totalBins); await expect(controls.locator('.time-frequency-zero-point')).toHaveCount(report.result.welchBins.length); expect(await controls.locator('svg').evaluateAll(elements => elements.every(element => !/NaN|Infinity/.test(element.outerHTML)))).toBe(true); expect(await download<ExportedReport>(page, '시간·주파수 JSON')).toEqual(report);
});

test('M25 prior execution stays tied to original semantic hash after new model draft', async ({ page }) => {
  await open(page); await record(page); const original = await download<CalcModel>(page, '모델 다운로드'), changed = structuredClone(original); changed.name = '다른 모델 초안'; changed.nodes[0].parameters.frequency = 16; await importModel(page, changed); const controls = await panel(page); await settings(controls, 16, 8); await expect(controls).toContainText('이전 실행의 기록입니다'); const report = await analyze(page, controls); expect(report.previousRun).toBe(true); expect(report.source.modelName).toBe(original.name); expect(report.source.semanticHash).toBe(sha256(compileModel(original).semanticKey)); expect(report.result.welchPeak!.frequency).toBe(8); await page.getByRole('button', { name: '수치 분석 닫기', exact: true }).click(); expect(await download<CalcModel>(page, '모델 다운로드')).toEqual(changed);
});

test.describe('M25 delayed analysis import', () => {
  test.use({ serviceWorkers: 'block' });
  test('M25 closing pending analysis suppresses a late import and avoids extra runs', async ({ page }) => {
    let release!: () => void; const held = new Promise<void>(resolve => { release = resolve; }); let requested!: () => void; const started = new Promise<void>(resolve => { requested = resolve; }); await page.route('**/time-frequency-*.js', async route => { requested(); await held; await route.continue(); }); await open(page); await record(page); const controls = await panel(page), response = page.waitForResponse(response => /\/time-frequency-[^/]+\.js$/.test(response.url())); await controls.getByRole('button', { name: '시간·주파수 계산', exact: true }).click(); await started; await expect(controls.getByLabel('시간 주파수 표본 수', { exact: true })).toBeDisabled(); await page.getByRole('button', { name: '수치 분석 닫기', exact: true }).click(); release(); await response; const reopened = await panel(page); await expect(reopened.getByRole('region', { name: '시간·주파수 분석 결과', exact: true })).toHaveCount(0); const report = await analyze(page, reopened); expect(report.result.count).toBe(64); expect((await history(page)).length).toBe(1);
  });
});

test('M25 large raw tables paginate 128 bins and bounded heatmap preserves exact selected cell PSD', async ({ page }) => {
  test.setTimeout(90_000); await open(page); const model = sine(4096); model.nodes[0].parameters.frequency = 32; await record(page, model); const controls = await panel(page); await controls.getByLabel('시간 주파수 표본 수', { exact: true }).fill('4096'); await settings(controls, 1024, 896); const report = await analyze(page, controls); expect(report.result).toMatchObject({ frameCount: 25, binsPerFrame: 513, totalBins: 12825 }); await expect(controls.getByRole('img', { name: 'Welch 평균 PSD 그래프', exact: true })).toHaveAttribute('data-display-count', '512'); const heatmap = controls.getByRole('img', { name: 'STFT 시간·주파수 히트맵', exact: true }); await expect(heatmap).toHaveAttribute('data-raw-cell-count', '12825'); const cellCount = Number(await heatmap.getAttribute('data-display-count')); expect(cellCount).toBeLessThanOrEqual(4096); expect(cellCount).toBeLessThan(report.result.totalBins); const cells = await heatmap.locator('.time-frequency-cell').evaluateAll(elements => elements.map(element => ({ frame: Number(element.getAttribute('data-frame-index')), bin: Number(element.getAttribute('data-bin-index')), psd: Number(element.getAttribute('data-power-density')) }))); expect(cells).toHaveLength(cellCount); cells.forEach(cell => expect(cell.psd).toBe(report.result.frames[cell.frame].bins[cell.bin].powerDensity));
  await controls.locator('.time-frequency-details > summary').filter({ hasText: 'Welch 원시 PSD 표' }).click(); const rows = controls.getByRole('table', { name: 'Welch 원시 PSD', exact: true }).locator('tbody tr'); await expect(rows).toHaveCount(128); for (let i = 0; i < 4; i++) await controls.getByRole('button', { name: 'Welch 표 다음 페이지', exact: true }).click(); await expect(rows).toHaveCount(1); await expect(rows.first().locator('td').first()).toHaveText('512'); await expect(controls.getByRole('button', { name: 'Welch 표 다음 페이지', exact: true })).toBeDisabled(); await controls.locator('.time-frequency-details > summary').filter({ hasText: 'STFT 선택 프레임 원시 빈' }).click(); const frameRows = controls.getByRole('table', { name: 'STFT 선택 프레임 원시 빈', exact: true }).locator('tbody tr'); await expect(frameRows).toHaveCount(128); await controls.getByRole('button', { name: 'STFT 표 다음 페이지', exact: true }).click(); await expect(frameRows.first().locator('td').first()).toHaveText('128'); await controls.getByLabel('STFT 프레임', { exact: true }).selectOption('24'); await expect(frameRows.first().locator('td').first()).toHaveText('0'); expect(await download<ExportedReport>(page, '시간·주파수 JSON')).toEqual(report);
  await controls.getByLabel('시간 주파수 겹침', { exact: true }).fill('1023'); await controls.getByRole('button', { name: '시간·주파수 계산', exact: true }).click(); await expect(controls.getByRole('alert')).toContainText('상한 128'); await expect(controls.getByRole('region', { name: '시간·주파수 분석 결과', exact: true })).toHaveCount(0);
});

test('M25 mobile themes and 200-percent text preserve readable controls, escaped labels and internal raw scrolling', async ({ page }) => {
  test.setTimeout(120_000); const errors: string[] = []; page.on('pageerror', error => errors.push(error.message)); const model = chirp(); model.name = '<img src=x onerror=alert(1)> 긴 시간 주파수 기록 출처 이름'; model.nodes[1].label = '길게 붙인 주파수 스윕 출력 기록 이름'; await open(page); await record(page, model); await mkdir('.test-generated/m25-ui', { recursive: true }); const observations: object[] = [];
  for (const [width, theme, scale] of [[390, 'dark', 1], [390, 'light', 1], [320, 'dark', 2], [320, 'light', 2]] as const) {
    await page.setViewportSize({ width, height: 1000 }); const currentTheme = await page.locator('.app-shell').evaluate(element => element.classList.contains('light') ? 'light' : 'dark'); if (currentTheme !== theme) await page.getByRole('button', { name: theme === 'light' ? '라이트 테마로 변경' : '다크 테마로 변경', exact: true }).click(); const controls = await panel(page); await settings(controls, 16, 8, 'hann'); await analyze(page, controls); await controls.getByRole('button', { name: 'dB PSD', exact: true }).click();
    await page.evaluate(scale => { const sizes = [...document.querySelectorAll<HTMLElement>('.time-frequency-panel,.time-frequency-panel *')].map(element => ({ element, size: Number.parseFloat(getComputedStyle(element).fontSize) })); document.documentElement.style.fontSize = `${16 * scale}px`; for (const { element, size } of sizes) element.style.fontSize = `${size * scale}px`; }, scale);
    await controls.locator('.time-frequency-details > summary').filter({ hasText: 'STFT 선택 프레임 원시 빈' }).click(); await controls.getByRole('region', { name: '시간·주파수 분석 결과', exact: true }).scrollIntoViewIfNeeded(); const dimensions = await page.evaluate(() => { const panel = document.querySelector<HTMLElement>('[data-testid=time-frequency-panel]')!, fields = [...panel.querySelectorAll<HTMLElement>('input,select,button')], table = panel.querySelector<HTMLElement>('.time-frequency-details[open] .time-frequency-table-scroll')!; return { viewport: innerWidth, page: document.documentElement.scrollWidth, panel: panel.scrollWidth, client: panel.clientWidth, minimumFieldFont: Math.min(...fields.map(element => Number.parseFloat(getComputedStyle(element).fontSize))), minimumParagraphFont: Math.min(...[...panel.querySelectorAll<HTMLElement>('p')].map(element => Number.parseFloat(getComputedStyle(element).fontSize))), table: table.scrollWidth, tableClient: table.clientWidth }; }); expect(dimensions.page, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.viewport + 1); expect(dimensions.panel, JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.client + 1); expect(dimensions.minimumFieldFont).toBeGreaterThanOrEqual(16 * scale); expect(dimensions.minimumParagraphFont).toBeGreaterThanOrEqual(16 * scale); expect(dimensions.table).toBeGreaterThan(dimensions.tableClient); expect(await controls.locator('img').count()).toBe(0); observations.push({ width, theme, scale, ...dimensions }); await page.screenshot({ path: `.test-generated/m25-ui/time-frequency-${width}-${theme}-${scale}x.png` }); await page.getByRole('button', { name: '수치 분석 닫기', exact: true }).click(); await page.evaluate(() => { document.documentElement.style.fontSize = ''; });
  }
  expect(errors).toEqual([]); await writeFile('.test-generated/m25-ui/observations.json', JSON.stringify({ appVersion: APP_VERSION, observations, pageErrors: errors }, null, 2) + '\n');
});
