import type { CalcEdge, CalcModel, CalcNode, ExecutionMode, SignalValue, StateValue, SubsystemDefinition } from '../packages/model/src/types';

/** Expected series are literals or closed-form mathematics, never production numerical helpers. */
export interface M12IndependentFixture { name: string; model: CalcModel; expected: Record<string, SignalValue[]>; declaredModes: ExecutionMode[]; oracleTolerance: number; sourceIds: string[]; expectedFinalState?: Record<string, SignalValue>; expectedStateMemory?: Record<string, StateValue> }
const n = (id: string, blockType: string, parameters: Record<string, unknown> = {}): CalcNode => ({ id, blockType, blockVersion: 1, label: id, parameters, unit: '1' });
const e = (source: string, target: string, targetPort = 'in', sourcePort = 'out'): CalcEdge => ({ id: `${source}-${sourcePort}-${target}-${targetPort}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId: targetPort } });
const model = (name: string, nodes: CalcNode[], edges: CalcEdge[], stopTime = 1, step = .25, solver: CalcModel['execution']['solver'] = {}): CalcModel => ({ schemaVersion: 1, modelId: name, name, nodes, edges, layout: {}, execution: { mode: 'continuous', startTime: 0, stopTime, step, solver: { method: 'rk4', initialStep: .01, maxStep: .01, discreteStep: step, ...solver } } });
const unary = (name: string, type: string, parameters: Record<string, unknown>, source = n('Source', 'source.constant', { value: 1 }), stop = 1, step = .25): CalcModel => model(name, [source, n('State', type, parameters), n('Result', 'sink.scope')], [e('Source', 'State'), e('State', 'Result')], stop, step);
const times = [0, .25, .5, .75, 1];
const oneMinusExp = times.map(t => 1 - Math.exp(-t));
const descriptor = unary('m12-independent-continuous-descriptor', 'continuous.descriptor', { E: [[2]], A: [[-2]], B: [[2]], C: [[1]], D: [[0]], initial: [0] });
descriptor.nodes.push(n('PhysicalState', 'sink.scope')); descriptor.edges.push(e('State', 'PhysicalState', 'in', 'state'));
const limited = unary('m12-independent-continuous-integrator-limited', 'continuous.integrator-limited', { lower: 0, upper: .5 });
limited.nodes.push(n('Limit', 'sink.scope')); limited.edges.push(e('State', 'Limit', 'in', 'limited'));
const second = unary('m12-independent-continuous-second-order-limited', 'continuous.second-order-limited', { positionLower: -1, positionUpper: .25, velocityLower: -3, velocityUpper: 3 }, n('Source', 'source.constant', { value: 2 }));
second.nodes.push(n('Velocity', 'sink.scope'), n('PositionLimit', 'sink.scope'), n('VelocityLimit', 'sink.scope')); second.edges.push(e('State', 'Velocity', 'in', 'velocity'), e('State', 'PositionLimit', 'in', 'positionLimited'), e('State', 'VelocityLimit', 'in', 'velocityLimited'));
const pid = model('m12-independent-continuous-pid-2dof', [n('Reference', 'source.constant', { value: 1 }), n('Measured', 'source.constant', { value: .25 }), n('State', 'continuous.pid-2dof', { kp: 2, ki: 1, kd: 0, b: .5 }), n('Result', 'sink.scope')], [e('Reference', 'State', 'r'), e('Measured', 'State', 'y'), e('State', 'Result')]);
const variable = (type: string): CalcModel => model(`m12-independent-${type.replaceAll('.', '-')}`, [n('Clock', 'source.clock'), n('Delay', 'source.step', { stepTime: 1, before: 1, after: .5 }), n('State', type, { minDelay: .25, maxDelay: 1, historyLimit: 128 }), n('Result', 'sink.scope')], [e('Clock', 'State'), e('Delay', 'State', 'delay'), e('State', 'Result')], 1.25);
const backlash = unary('m12-independent-nonlinear-backlash', 'nonlinear.backlash', { width: 2 }, n('Source', 'source.repeating-sequence', { times: [0, .5, 1, 1.5, 2, 2.5], values: [0, 2, 2, 0, -2, 0], interpolation: 'linear' }), 2);
const rate = unary('m12-independent-nonlinear-rate-limiter-continuous', 'nonlinear.rate-limiter-continuous', { rising: 1, falling: -1, initial: -8 }, n('Source', 'source.ramp', { initial: 2, slope: 4 }));
const dynamicRate = model('m12-independent-nonlinear-rate-limiter-dynamic', [n('Source', 'source.constant', { value: 4 }), n('Up', 'source.constant', { value: 2 }), n('Down', 'source.constant', { value: -1 }), n('State', 'nonlinear.rate-limiter-dynamic'), n('Result', 'sink.scope')], [e('Source', 'State'), e('Up', 'State', 'rising'), e('Down', 'State', 'falling'), e('State', 'Result')]);
delete dynamicRate.execution.solver;
const algebraic = model('m12-independent-solver-algebraic-constraint', [n('State', 'solver.algebraic-constraint', { initial: 2, tolerance: 1e-11 }), n('Residual', 'math.expression', { expression: 'x*x-9' }), n('Result', 'sink.scope')], [e('State', 'Residual'), e('Residual', 'State'), e('State', 'Result')]);
const plant: SubsystemDefinition = { id: 'Plant', version: 1, name: 'Plant', layout: {}, nodes: [n('Input', 'io.input', { value: 0 }), n('State', 'continuous.state-space', { A: [[-2]], B: [3], C: [4], D: 5, initial: [.5] }), n('Output', 'io.output')], edges: [e('Input', 'State'), e('State', 'Output')], inputs: [{ id: 'in', nodeId: 'Input' }], outputs: [{ id: 'out', nodeId: 'Output' }] };
const abcd: SignalValue = { kind: 'bus', fields: [{ name: 'A', value: [[-2]] }, { name: 'B', value: [[3]] }, { name: 'C', value: [[4]] }, { name: 'D', value: [[5]] }] };
const zeroABCD: SignalValue = { kind: 'bus', fields: ['A', 'B', 'C', 'D'].map(name => ({ name, value: [[0]] })) };
const analysis = model('m12-independent-analysis-linearization', [n('Analysis', 'analysis.linearization', { definitionId: 'Plant', operatingState: [.25], operatingInputs: [2], times: [.5] }), n('Result', 'io.structured-output')], [e('Analysis', 'Result')]); analysis.subsystems = [plant];

export const M12_INDEPENDENT_DEFINITION_FIXTURES: M12IndependentFixture[] = [
  { name: descriptor.name, model: descriptor, expected: { Result: oneMinusExp, PhysicalState: oneMinusExp.map(value => [value]) }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['02-002'], expectedStateMemory: { State: { state: [1 - Math.exp(-1)] } } },
  { name: limited.name, model: limited, expected: { Result: [0, .25, .5, .5, .5], Limit: [true, false, true, true, true] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-005'], expectedFinalState: { State: .5 }, expectedStateMemory: { State: { state: [.5] } } },
  { name: second.name, model: second, expected: { Result: [0, .0625, .25, .25, .25], Velocity: [0, .5, 0, 0, 0], PositionLimit: [false, false, true, true, true], VelocityLimit: [false, false, false, false, false] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-009'], expectedFinalState: { State: .25 }, expectedStateMemory: { State: { state: [.25, 0] } } },
  { name: pid.name, model: pid, expected: { Result: [.5, .6875, .875, 1.0625, 1.25] }, declaredModes: ['continuous'], oracleTolerance: 1e-10, sourceIds: ['02-007'], expectedStateMemory: { State: { state: [.75, 0] } } },
  { name: 'm12-independent-time-variable-delay', model: variable('time.variable-delay'), expected: { Result: [0, 0, 0, 0, .5, .75] }, declaredModes: ['continuous'], oracleTolerance: 2e-8, sourceIds: ['02-013'] },
  { name: 'm12-independent-time-variable-transport-delay', model: variable('time.variable-transport-delay'), expected: { Result: [0, 0, 0, 0, 0, .5] }, declaredModes: ['continuous'], oracleTolerance: 2e-8, sourceIds: ['02-014'] },
  { name: backlash.name, model: backlash, expected: { Result: [0, 0, 1, 1, 1, 1, 1, 0, -1] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['04-001'] },
  { name: rate.name, model: rate, expected: { Result: [2, 2.25, 2.5, 2.75, 3] }, declaredModes: ['continuous'], oracleTolerance: 1e-10, sourceIds: ['04-008'], expectedStateMemory: { State: { value: 3, previousTime: 1 } } },
  { name: dynamicRate.name, model: dynamicRate, expected: { Result: [0, .5, 1, 1.5, 2] }, declaredModes: ['discrete', 'continuous'], oracleTolerance: 1e-12, sourceIds: ['04-009'], expectedStateMemory: { State: { value: 2 } } },
  { name: algebraic.name, model: algebraic, expected: { Result: [3, 3, 3, 3, 3] }, declaredModes: ['continuous'], oracleTolerance: 2e-10, sourceIds: ['08-003'] },
  { name: analysis.name, model: analysis, expected: { Result: [zeroABCD, zeroABCD, abcd, abcd, abcd] }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['12-004'] },
];

const index1 = unary('m12-independent-index1-descriptor', 'continuous.descriptor', { E: [[1, 0], [0, 0]], A: [[-1, 0], [0, 1]], B: [[1], [-1]], C: [[1, 1]], D: [[0]], initial: [0, 1], differentialCount: 1 }); index1.nodes.push(n('PhysicalState', 'sink.scope')); index1.edges.push(e('State', 'PhysicalState', 'in', 'state'));
const discreteRate = unary('m12-independent-rate-limiter-discrete', 'nonlinear.rate-limiter-continuous', { rising: 1, falling: -1, initial: 0 }, n('Source', 'source.constant', { value: 2 })); discreteRate.execution.mode = 'discrete'; delete discreteRate.execution.solver;
const triggered = structuredClone(analysis); triggered.name = triggered.modelId = 'm12-independent-analysis-triggered'; triggered.nodes.find(node => node.id === 'Analysis')!.parameters.mode = 'triggered'; triggered.nodes.push(n('Clock', 'source.clock'), n('Trigger', 'logic.hit-crossing', { threshold: .5, direction: 'rising' })); triggered.edges.push(e('Clock', 'Trigger'), e('Trigger', 'Analysis', 'trigger'));
const stiff = model('m12-independent-implicit-stiff-decay', [n('State', 'continuous.integrator', { initial: 1 }), n('Negative', 'math.gain', { gain: -1000 }), n('Result', 'sink.scope')], [e('State', 'Negative'), e('Negative', 'State'), e('State', 'Result')], .02, .01, { method: 'implicit-euler', initialStep: .01, maxStep: .01, minStep: 1e-9, atol: 5e-10, rtol: 5e-8, newtonTolerance: 1e-13 });
const project = structuredClone(index1); project.name = project.modelId = 'm12-independent-index1-project'; project.nodes.find(node => node.id === 'State')!.parameters.initial = [0, 0]; project.nodes.find(node => node.id === 'State')!.parameters.initialPolicy = 'project';
const zeroDelay = variable('time.variable-delay'); zeroDelay.name = zeroDelay.modelId = 'm12-independent-zero-delay-direct'; zeroDelay.nodes.find(node => node.id === 'State')!.parameters.handleZero = 'yes'; zeroDelay.nodes.find(node => node.id === 'Delay')!.parameters = { stepTime: .5, before: .5, after: 0 }; zeroDelay.execution.stopTime = 1;
const joint = model('m12-independent-joint-algebraic', [n('X', 'solver.algebraic-constraint', { initial: 0, tolerance: 1e-10 }), n('Y', 'solver.algebraic-constraint', { initial: 0, tolerance: 1e-10 }), n('Sum', 'math.sum'), n('Difference', 'math.sum', { signs: '+-' }), n('Three', 'source.constant', { value: 3 }), n('One', 'source.constant', { value: 1 }), n('RX', 'math.sum', { signs: '+-' }), n('RY', 'math.sum', { signs: '+-' }), n('ResultX', 'sink.scope'), n('ResultY', 'sink.scope')], [e('X', 'Sum', 'a'), e('Y', 'Sum', 'b'), e('X', 'Difference', 'a'), e('Y', 'Difference', 'b'), e('Sum', 'RX', 'a'), e('Three', 'RX', 'b'), e('Difference', 'RY', 'a'), e('One', 'RY', 'b'), e('RX', 'X'), e('RY', 'Y'), e('X', 'ResultX'), e('Y', 'ResultY')]);
const nonlinearPlant: SubsystemDefinition = { id: 'Nonlinear', version: 1, name: 'Nonlinear', layout: {}, nodes: [n('Input', 'io.input', { value: .25 }), n('State', 'continuous.integrator', { initial: .5 }), n('Square', 'math.expression', { expression: 'x*x' }), n('Derivative', 'math.sum', { signs: '+-' }), n('Cubic', 'math.expression', { expression: 'x*x*x' }), n('Double', 'math.gain', { gain: 2 }), n('Measure', 'math.sum'), n('Output', 'io.output')], edges: [e('State', 'Square'), e('Input', 'Derivative', 'a'), e('Square', 'Derivative', 'b'), e('Derivative', 'State'), e('State', 'Cubic'), e('Input', 'Double'), e('Cubic', 'Measure', 'a'), e('Double', 'Measure', 'b'), e('Measure', 'Output')], inputs: [{ id: 'in', nodeId: 'Input' }], outputs: [{ id: 'out', nodeId: 'Output' }] };
const nonlinearAnalysis = structuredClone(analysis); nonlinearAnalysis.name = nonlinearAnalysis.modelId = 'm12-independent-analysis-nonlinear-point'; nonlinearAnalysis.subsystems = [nonlinearPlant]; nonlinearAnalysis.nodes.find(node => node.id === 'Analysis')!.parameters = { definitionId: 'Nonlinear', operatingState: [.5], operatingInputs: [.25], times: [0] };
const nonlinearABCD: SignalValue = { kind: 'bus', fields: [{ name: 'A', value: [[-1]] }, { name: 'B', value: [[1]] }, { name: 'C', value: [[.75]] }, { name: 'D', value: [[2]] }] };
const descriptorPlant: SubsystemDefinition = { id: 'DescriptorPlant', version: 1, name: 'DescriptorPlant', layout: {}, nodes: [n('Input', 'io.input', { value: 1 }), n('State', 'continuous.descriptor', { E: [[1, 0], [0, 0]], A: [[-1, 0], [0, 1]], B: [[1], [-1]], C: [[1, 1]], D: [[0]], initial: [0, 1], differentialCount: 1 }), n('Output', 'io.output')], edges: [e('Input', 'State'), e('State', 'Output')], inputs: [{ id: 'in', nodeId: 'Input' }], outputs: [{ id: 'out', nodeId: 'Output' }] };
const descriptorAnalysis = structuredClone(analysis); descriptorAnalysis.name = descriptorAnalysis.modelId = 'm12-independent-analysis-descriptor-reconstruction'; descriptorAnalysis.subsystems = [descriptorPlant]; descriptorAnalysis.nodes.find(node => node.id === 'Analysis')!.parameters = { definitionId: 'DescriptorPlant', operatingState: [.25], operatingInputs: [2], times: [0] };
const descriptorABCD: SignalValue = { kind: 'bus', fields: [{ name: 'A', value: [[-1]] }, { name: 'B', value: [[1]] }, { name: 'C', value: [[1]] }, { name: 'D', value: [[1]] }] };
const pidBranch = (name: string, parameters: Record<string, unknown>): CalcModel => { const value = structuredClone(pid); value.name = value.modelId = name; value.nodes.find(node => node.id === 'State')!.parameters = parameters; value.nodes.find(node => node.id === 'Measured')!.parameters.value = 0; return value; };
const filteredPID = pidBranch('m12-independent-pid-filter', { kp: 0, ki: 0, kd: .5, filterN: 4, c: 1 });
const idealPID = pidBranch('m12-independent-pid-ideal-weights', { kp: 2, ki: 1, kd: .5, b: .5, c: 0, form: 'ideal' });
const clampPID = pidBranch('m12-independent-pid-clamp', { kp: 2, ki: 1, controller: 'PI', limit: 'on', lower: -1, upper: 1, antiWindup: 'clamp' });
const backPID = pidBranch('m12-independent-pid-back-calculation', { kp: 2, ki: 1, controller: 'PI', limit: 'on', lower: -1, upper: 1, antiWindup: 'back-calculation', kb: 2 });
function attachReset(value: CalcModel): void { value.nodes.find(node => node.id === 'State')!.parameters.reset = 'rising'; value.nodes.push(n('ResetClock', 'source.ramp', { initial: 0, slope: 1 }), n('ResetBool', 'logic.hit-crossing', { threshold: .5, direction: 'rising' })); value.edges.push(e('ResetClock', 'ResetBool'), e('ResetBool', 'State', 'reset')); }
const resetPID = pidBranch('m12-independent-pid-reset', { kp: 0, ki: 1, controller: 'I' }); attachReset(resetPID);
const release = structuredClone(limited); release.name = release.modelId = 'm12-independent-limited-release'; release.execution.stopTime = 1.25; Object.assign(release.nodes.find(node => node.id === 'Source')!, { blockType: 'source.step', parameters: { stepTime: .75, before: 1, after: -1 } });
const limitReset = structuredClone(limited); limitReset.name = limitReset.modelId = 'm12-independent-reset-limit-tie'; attachReset(limitReset);
const velocityBound = structuredClone(second); velocityBound.name = velocityBound.modelId = 'm12-independent-velocity-limit'; Object.assign(velocityBound.nodes.find(node => node.id === 'State')!.parameters, { positionLower: -10, positionUpper: 10, velocityUpper: .5 });
const positionVelocityTie = structuredClone(second); positionVelocityTie.name = positionVelocityTie.modelId = 'm12-independent-position-velocity-tie'; positionVelocityTie.nodes.find(node => node.id === 'State')!.parameters.velocityUpper = 1;
export const M12_INDEPENDENT_BOUNDARY_FIXTURES: M12IndependentFixture[] = [
  { name: index1.name, model: index1, expected: { Result: times.map(t => 2 - Math.exp(-t)), PhysicalState: times.map(t => [1 - Math.exp(-t), 1]) }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['02-002'], expectedStateMemory: { State: { state: [1 - Math.exp(-1)] } } },
  { name: project.name, model: project, expected: { Result: times.map(t => 2 - Math.exp(-t)), PhysicalState: times.map(t => [1 - Math.exp(-t), 1]) }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['02-002'] },
  { name: discreteRate.name, model: discreteRate, expected: { Result: [.25, .5, .75, 1, 1.25] }, declaredModes: ['discrete'], oracleTolerance: 1e-12, sourceIds: ['04-008'], expectedStateMemory: { State: { value: 1 } } },
  { name: triggered.name, model: triggered, expected: { Result: [zeroABCD, zeroABCD, abcd, abcd, abcd] }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['12-005'] },
  { name: stiff.name, model: stiff, expected: { Result: [1, 0.000045399929762484854, 0.000000002061153622438558] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: [], expectedStateMemory: { State: { state: [0.000000002061153622438558] } } },
  { name: zeroDelay.name, model: zeroDelay, expected: { Result: [0, 0, .5, .75, 1] }, declaredModes: ['continuous'], oracleTolerance: 2e-8, sourceIds: ['02-013'] },
  { name: joint.name, model: joint, expected: { ResultX: [2, 2, 2, 2, 2], ResultY: [1, 1, 1, 1, 1] }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['08-003'] },
  { name: nonlinearAnalysis.name, model: nonlinearAnalysis, expected: { Result: times.map(() => nonlinearABCD) }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['12-004'] },
  { name: descriptorAnalysis.name, model: descriptorAnalysis, expected: { Result: times.map(() => descriptorABCD) }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['02-002', '12-004'] },
  { name: filteredPID.name, model: filteredPID, expected: { Result: times.map(t => 2 * Math.exp(-4 * t)) }, declaredModes: ['continuous'], oracleTolerance: 2e-8, sourceIds: ['02-007'], expectedStateMemory: { State: { state: [0, 1 - Math.exp(-4)] } } },
  { name: idealPID.name, model: idealPID, expected: { Result: [1, 1.5, 2, 2.5, 3] }, declaredModes: ['continuous'], oracleTolerance: 2e-10, sourceIds: ['02-007'], expectedStateMemory: { State: { state: [2, 0] } } },
  { name: clampPID.name, model: clampPID, expected: { Result: [1, 1, 1, 1, 1] }, declaredModes: ['continuous'], oracleTolerance: 1e-10, sourceIds: ['02-007'], expectedStateMemory: { State: { state: [0, 0] } } },
  { name: backPID.name, model: backPID, expected: { Result: [1, 1, 1, 1, 1] }, declaredModes: ['continuous'], oracleTolerance: 2e-9, sourceIds: ['02-007'], expectedStateMemory: { State: { state: [-.5 * (1 - Math.exp(-2)), 0] } } },
  { name: resetPID.name, model: resetPID, expected: { Result: [0, .25, 0, .25, .5] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-007'], expectedStateMemory: { ResetBool: {}, State: { state: [.5, 0] } } },
  { name: release.name, model: release, expected: { Result: [0, .25, .5, .5, .25, 0], Limit: [true, false, true, true, false, true] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-005'], expectedStateMemory: { State: { state: [0] } } },
  { name: limitReset.name, model: limitReset, expected: { Result: [0, .25, 0, .25, .5], Limit: [true, false, true, false, true] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-005'], expectedStateMemory: { ResetBool: {}, State: { state: [.5] } } },
  { name: velocityBound.name, model: velocityBound, expected: { Result: [0, .0625, .1875, .3125, .4375], Velocity: [0, .5, .5, .5, .5], PositionLimit: [false, false, false, false, false], VelocityLimit: [false, true, true, true, true] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-009'], expectedStateMemory: { State: { state: [.4375, .5] } } },
  { name: positionVelocityTie.name, model: positionVelocityTie, expected: { Result: [0, .0625, .25, .25, .25], Velocity: [0, .5, 0, 0, 0], PositionLimit: [false, false, true, true, true], VelocityLimit: [false, false, false, false, false] }, declaredModes: ['continuous'], oracleTolerance: 2e-7, sourceIds: ['02-009'], expectedStateMemory: { State: { state: [.25, 0] } } },
];

export interface M12IndependentFailureFixture { name: string; model: CalcModel; code: string; phase: 'compile' | 'runtime'; oracleTolerance?: number; expectedPartial?: { samples: number; finalState?: Record<string, SignalValue>; stateMemory?: Record<string, StateValue> } }
const inconsistent = structuredClone(index1); inconsistent.nodes.find(node => node.id === 'State')!.parameters.initial = [0, 0];
const noRoot = structuredClone(algebraic); noRoot.nodes.find(node => node.id === 'State')!.parameters.initial = 0; noRoot.nodes.find(node => node.id === 'Residual')!.parameters.expression = 'x*x+1';
const rejection = structuredClone(stiff); Object.assign(rejection.execution.solver!, { minStep: .01, maxRejects: 0, atol: 1e-12, rtol: 1e-12 });
const history = variable('time.variable-delay'); Object.assign(history.nodes.find(node => node.id === 'State')!.parameters, { minDelay: .1, maxDelay: 2, historyLimit: 4 }); history.nodes.find(node => node.id === 'Delay')!.parameters = { stepTime: 100, before: 1, after: 1 }; Object.assign(history.execution, { stopTime: 1, step: .1, solver: { method: 'rk4', initialStep: .1, maxStep: .1 } });
const transportHistory = structuredClone(history); transportHistory.name = transportHistory.modelId = 'm12-independent-transport-history-overflow-atomic'; transportHistory.nodes.find(node => node.id === 'State')!.blockType = 'time.variable-transport-delay';
export const M12_INDEPENDENT_FAILURE_FIXTURES: M12IndependentFailureFixture[] = [
  { name: 'm12-independent-inconsistent-initial-atomic', model: inconsistent, phase: 'runtime', code: 'M12_DAE_INITIAL_INCONSISTENT', expectedPartial: { samples: 0, finalState: {}, stateMemory: { State: { state: [0] } } } },
  { name: 'm12-independent-no-real-algebraic-root', model: noRoot, phase: 'runtime', code: 'M12_NEWTON_SINGULAR', expectedPartial: { samples: 0, finalState: {}, stateMemory: {} } },
  { name: 'm12-independent-implicit-rejection-atomic', model: rejection, phase: 'runtime', code: 'RUNTIME_REJECTION_BUDGET', expectedPartial: { samples: 1, finalState: { State: 1 }, stateMemory: { State: { state: [1] } } } },
  { name: 'm12-independent-history-overflow-atomic', model: history, phase: 'runtime', code: 'M12_HISTORY_BUDGET', oracleTolerance: 1e-12, expectedPartial: { samples: 4, finalState: { State: 0 }, stateMemory: { State: { m12History: [{ time: 0, value: 0 }, { time: .1, value: .1 }, { time: .2, value: .2 }, { time: .3, value: .3 }], m12Jumps: [0] } } } },
  { name: transportHistory.name, model: transportHistory, phase: 'runtime', code: 'M12_HISTORY_BUDGET', oracleTolerance: 1e-12, expectedPartial: { samples: 4, finalState: { State: 0 }, stateMemory: { State: { state: [.3], m12History: [{ time: 0, value: 0, phase: 0 }, { time: .1, value: .1, phase: .1 }, { time: .2, value: .2, phase: .2 }, { time: .3, value: .3, phase: .3 }], m12Jumps: [0] } } } },
];
