import { describe, expect, it } from 'vitest';
import { compileModel } from '../packages/compiler/src';
import { runModel } from '../packages/runtime/src';
import { createExportManifest } from '../packages/codegen-ts/src';
import { ENGINE_VERSION } from '../packages/model/src';
import { createM13Examples } from '../apps/web/src/m13-examples';
import { appendDashboardReplayEvents } from '../apps/web/src/dashboard-replay';
import { historySnapshot, type HistoryRecord } from '../apps/web/src/run-history';
async function record(id = 'waveform-xy-and-record'): Promise<HistoryRecord> { const model = createM13Examples().find(example => example.id === id)!.model, compiled = compileModel(model), manifest = await createExportManifest(compiled); return { id: 'M13record', label: 'M13', createdAt: '2026-10-03T09:00:00Z', model: compiled.model, semanticHash: manifest.modelHash, engineVersion: ENGINE_VERSION, manifest, result: await runModel(compiled), outputIds: compiled.outputIds, outputTypes: compiled.outputTypes }; }
describe('M13 deterministic replay and bounded recorded history', () => {
  it('merges planned future events with actual receipts, reindexes order and never overwrites initial/source', async () => { const original = createM13Examples().find(example => example.id === 'dashboard-recorded-controls')!.model, before = structuredClone(original); const replay = appendDashboardReplayEvents(original, [{ nodeId: 'control', time: .2, order: 3, value: .2 }, { nodeId: 'control', time: .3, order: 4, value: .7 }]); expect(original).toEqual(before); const control = replay.nodes[0]; expect(control.parameters.initial).toBe(0); expect(JSON.parse(String(control.parameters.events))).toEqual([{ time: .2, order: 0, value: .2 }, { time: .3, order: 1, value: .4 }, { time: .3, order: 2, value: .7 }, { time: .6, order: 3, value: .8 }]); const result = await runModel(compileModel(replay)); expect(result.samples[3].values.result).toBe(.7); expect(result.samples.at(-1)!.values.result).toBe(.8); });
  it('rejects nonfinite values, unknown targets, outside run time and receipts over256', () => { const model = createM13Examples()[3].model; for (const receipt of [{ nodeId: 'missing', time: .2, order: 0, value: .2 }, { nodeId: 'control', time: 2, order: 0, value: .2 }, { nodeId: 'control', time: .2, order: 0, value: Infinity }, { nodeId: 'control', time: .2, order: -1, value: .2 }]) expect(() => appendDashboardReplayEvents(model, [receipt])).toThrow(); expect(() => appendDashboardReplayEvents(model, Array.from({ length: 257 }, (_, order) => ({ nodeId: 'control', time: .2, order, value: .2 })))).toThrow(); });
  it('roundtrips exact XY and numeric records with independent detached samples', async () => { const original = await record(), saved = historySnapshot(original); expect(saved).toEqual(original); (original.result.stateMemory!.xy as { m13Records: { time: number; value: unknown }[] }).m13Records[0].value = 99; expect(historySnapshot(saved)).toEqual(saved); });
  for (const mutation of ['type', 'shape', 'time', 'capacity', 'tick', 'id']) it(`rejects forged recorded ${mutation}`, async () => { const changed = await record(), memory = changed.result.stateMemory!.xy as { m13Records: { time: number; value: unknown }[]; m13RecordTick: number }; if (mutation === 'type') memory.m13Records[0].value = 1; if (mutation === 'shape') memory.m13Records[0].value = { kind: 'bus', fields: [{ name: 'x', value: [1, 2] }, { name: 'y', value: 1 }] }; if (mutation === 'time') memory.m13Records[1].time = memory.m13Records[0].time; if (mutation === 'capacity') memory.m13Records = Array.from({ length: 129 }, (_, time) => ({ time: time / 1000, value: memory.m13Records[0].value })); if (mutation === 'tick') memory.m13RecordTick = -1; if (mutation === 'id') { changed.result.stateMemory!.other = changed.result.stateMemory!.xy; delete changed.result.stateMemory!.xy; } expect(() => historySnapshot(changed)).toThrow(); });
  it('validates graceful stop reason against node and final complete sample', async () => { const changed = await record('bounded-record-and-stop'); expect(historySnapshot(changed).result.stopReason).toEqual({ nodeId: 'stop', time: .5, tick: 5 }); changed.result.stopReason!.time = .4; expect(() => historySnapshot(changed)).toThrow(); });
});
