import { readFileSync } from 'node:fs';
import { registryWithoutApprovedObserverInputs } from '../scripts/m16-support-source';
import { describe, expect, it } from 'vitest';
import { blockRegistry, getBlockDefinition, getBlockPorts } from '../packages/block-library/src';
import { M13_BLOCK_IDS, parseM13Format } from '../packages/block-library/src/m13';
import { compileModel } from '../packages/compiler/src';
import { ModelError, datasetContentHash, type CalcEdge, type CalcModel, type CalcNode, type Dataset, type SignalValue, type SubsystemDefinition } from '../packages/model/src';
const node = (id: string, blockType: string, parameters: Record<string, unknown> = {}): CalcNode => ({ id, blockType, blockVersion: 1, label: id, parameters });
const edge = (source: string, target: string, port = 'in', output = 'out'): CalcEdge => ({ id: `${source}-${output}-${target}-${port}`, source: { nodeId: source, portId: output }, target: { nodeId: target, portId: port } });
const graph = (nodes: CalcNode[], edges: CalcEdge[], mode: CalcModel['execution']['mode'] = 'static'): CalcModel => ({ schemaVersion: 1, modelId: 'M13Compiler', name: 'M13Compiler', nodes, edges, layout: {}, execution: { mode, startTime: 0, stopTime: mode === 'static' ? 0 : 2, step: 1 } });
const string = (text: string): SignalValue => ({ kind: 'typed', dtype: 'string', shape: [], data: [text] });
function operation(id: string, parameters: Record<string, unknown> = {}, inputs: Record<string, SignalValue> = { in: string('hello') }, output = 'out', mode: CalcModel['execution']['mode'] = 'static'): CalcModel { const nodes = [node('Operation', id, parameters), node('Result', 'io.structured-output')], edges = [edge('Operation', 'Result', 'in', output)]; for (const [port,value] of Object.entries(inputs)) { const source = `Input_${port}`; nodes.push(node(source, typeof value === 'number' || typeof value === 'boolean' || Array.isArray(value) ? 'source.constant' : 'source.signal', { value })); edges.push(edge(source,'Operation',port)); } return graph(nodes,edges,mode); }
const codes = (model: CalcModel): string[] => { try { compileModel(model); return []; } catch (error) { if (!(error instanceof ModelError)) throw error; return error.diagnostics.map(item=>item.code); } };
function dataset(kind: 'number' | 'string' = 'number'): Dataset { const value: Dataset = { id:'data',name:'data',version:1,sourceHash:'a'.repeat(64),contentHash:'',timeColumn:'time',columns:[{name:'time',kind:'number',unit:'s'},{name:'value',kind,unit:'1'}],rows:kind==='number'?[[0,2],[1,4]]:[[0,'one'],[1,'two']],provenance:{format:'csv',filename:'data.csv',sourceHash:'a'.repeat(64),transforms:[]} }; value.contentHash=datasetContentHash(value); return value; }

describe('M13 bounded string/dashboard/data compiler',()=>{
  it('preserves304 historical definition objects beyond two approved observer inputs and adds30 bounded actual definitions',()=>{ const baseline=JSON.parse(readFileSync(new URL('../docs/baselines/m12-registry.json',import.meta.url),'utf8')) as {id:string}[]; const historical=new Map<string,(typeof blockRegistry)[number]>(registryWithoutApprovedObserverInputs(blockRegistry).map(definition=>[definition.id,definition])); expect(baseline).toHaveLength(304); for(const definition of baseline)expect(historical.get(definition.id)).toEqual(definition); expect(M13_BLOCK_IDS).toHaveLength(30); expect(new Set(M13_BLOCK_IDS).size).toBe(30); for(const id of M13_BLOCK_IDS)expect(Object.keys(getBlockDefinition(id)!.parameters).length).toBeLessThanOrEqual(16); expect(blockRegistry.length).toBeGreaterThanOrEqual(334); });
  it.each([
    ['source.string-constant',{},{}], ['string.ascii-to-string',{}, {in:{kind:'typed',dtype:'uint8',shape:[3],data:['65','66','0']}}], ['string.compose',{format:'%s %.2f'},{arg1:string('value'),arg2:2.25}], ['string.scan',{format:'%s %lf'}, {in:string('value 2.25')}],
    ['string.string-compare',{}, {a:string('hello'),b:string('hello')}],['string.string-concatenate',{}, {in1:string('hello'),in2:string('world')}],['string.string-contains',{}, {in:string('hello'),pattern:string('ell')}],['string.string-count',{}, {in:string('hello'),pattern:string('l')}],['string.string-find',{}, {in:string('hello'),pattern:string('ll')}],['string.string-length',{}, {in:string('한😀')}],['string.string-to-ascii',{capacity:8},{in:string('hello')}],['string.parse-number',{dtype:'float32'},{in:string('1.25')}],['string.parse-enum',{}, {in:string('On')}],['string.substring',{}, {in:string('hello'),start:2,length:2}],['string.to-string',{}, {in:1.25}],
  ] as const)('compiles real %s ports/type IR without mutating source', (id,p,inputs)=>{ const model=operation(id,p,inputs as unknown as Record<string,SignalValue>,id==='string.scan'?'out1':'out'),before=JSON.stringify(model),compiled=compileModel(model); expect(JSON.stringify(model)).toBe(before); expect(Object.isFrozen(compiled)).toBe(true); const reverse=structuredClone(compiled.model);reverse.nodes.reverse();reverse.edges.reverse();expect(compileModel(reverse).nodes).toEqual(compiled.nodes);expect(compileModel(JSON.parse(JSON.stringify(compiled.model))).semanticKey).toBe(compiled.semanticKey); });
  it('uses exact grammar-derived ports and rejects unsupported tokens',()=>{ expect(getBlockPorts(node('Compose','string.compose',{format:'%s:%d:%.3f:%%'}))).toEqual({inputs:['arg1','arg2','arg3'],outputs:['out']});expect(getBlockPorts(node('Scan','string.scan',{format:'%s %d %u %f %lf %c'})).outputs).toEqual(['out1','out2','out3','out4','out5','out6']);expect(parseM13Format('%s %d %u %f %lf %c','scan').filter(token=>token.kind).map(token=>token.dtype)).toEqual(['string','int32','uint32','float32','float64','string']); expect(codes(operation('string.compose',{format:'%999999s'},{arg1:string('x')}))).toContain('M13_FORMAT_UNSUPPORTED');expect(codes(operation('string.to-string',{format:'%s'},{in:1}))).toContain('M13_FORMAT_INPUT'); });
  it('bounded UI fallback never allocates an invalid concatenation port count',()=>{for(const count of [1,1e9,-1,NaN,'constructor'])expect(getBlockPorts(node('C','string.string-concatenate',{count})).inputs).toHaveLength(2);expect(getBlockPorts(node('S','string.substring',{toEnd:'yes'})).inputs).toEqual(['in','start']);});
  it('requires real string/integer/enum types and explicit ASCII vectors',()=>{ expect(codes(operation('string.string-length',{}, {in:2}))).toContain('M13_STRING_SCALAR');expect(codes(operation('string.ascii-to-string',{}, {in:[65,66]}))).toContain('M13_ASCII_VECTOR');expect(codes(operation('string.parse-enum',{type:{dtype:'float64'}}))).toContain('M13_ENUM_TYPE');expect(codes(operation('string.substring',{}, {in:string('x'),start:true,length:1}))).toContain('M13_INTEGER_INDEX');expect(codes(operation('string.compose',{format:'%f'},{arg1:{kind:'typed',dtype:'int64',shape:[],data:['9007199254740993']}}))).toContain('M13_FORMAT_INPUT');});
  it('resolves a floating observer to a real endpoint and current dependency',()=>{ const model=graph([node('AObserver','sink.floating-scope',{sourceNodeId:'ZSource'}),node('ZSource','source.string-constant',{value:'one'})],[]);const compiled=compileModel(model);expect(compiled.nodes.map(n=>n.id)).toEqual(['ZSource','AObserver']);expect(compiled.nodes[1]!.inputs.in).toEqual({nodeId:'ZSource',portId:'out'});expect(compiled.outputTypes.AObserver!.typed?.dtype).toBe('string');expect(codes(graph([node('Observer','sink.floating-scope',{sourceNodeId:'Missing'})],[]))).toContain('M13_FLOATING_REFERENCE');});
  it('preserves actual two-axis units and charges owned recording storage',()=>{const x=node('X','source.constant',{value:1});x.unit='m';const y=node('Y','source.constant',{value:2});y.unit='s';const compiled=compileModel(graph([x,y,node('Record','sink.xy-graph',{capacity:3})],[edge('X','Record','x'),edge('Y','Record','y')],'discrete'));const recorder=compiled.nodes.find(n=>n.id==='Record')!;expect(compiled.outputTypes.Record!.bus!.fields.map(f=>f.descriptor.unit)).toEqual(['m','s']);expect(recorder.parameters.m13StateElements).toBeGreaterThan(8);expect(compiled.stateElements).toBeGreaterThanOrEqual(Number(recorder.parameters.m13StateElements));expect(compiled.model.nodes.find(n=>n.id==='Record')!.parameters).not.toHaveProperty('recordDescriptor');});
  it('rejects capacity exceeding actual persistent state budget',()=>{const model=graph([node('S','source.signal',{value:{kind:'typed',dtype:'string',shape:[16],data:Array(16).fill('x')}}),node('R','sink.record',{capacity:1024})],[edge('S','R')],'discrete');expect(codes(model)).toContain('STATE_BUDGET_EXCEEDED');});
  it('validates sorted unique due replay events, finite grid and registered choices',()=>{const make=(events:string,extra:Record<string,unknown>={})=>graph([node('Control','dashboard.control',{events,...extra})],[],'discrete');expect(codes(make('[{"time":0,"order":11,"value":0},{"time":1,"order":10,"value":1}]'))).toEqual([]);expect(codes(make('[{"time":1,"order":1,"value":1},{"time":0,"order":0,"value":0}]'))).toContain('M13_CONTROL_EVENTS');expect(codes(make('[{"time":1,"order":1,"value":1},{"time":2,"order":1,"value":1}]'))).toContain('M13_CONTROL_EVENTS');expect(codes(make('[{"time":1,"order":0,"value":0.15}]'))).toContain('M13_CONTROL_STEP');expect(codes(make('[{"time":1,"order":0,"value":0.5}]',{kind:'check-box'}))).toContain('M13_CONTROL_CHOICE');expect(codes(make('[{"time":1,"order":0,"value":0.5,"callback":"alert(1)"}]'))).toContain('M13_CONTROL_EVENTS');expect(codes(make('{"__proto__":{}}'))).toContain('INVALID_PARAMETERS');});
  it('validates bounded indicator classification and labels rather than arbitrary markup execution',()=>{expect(codes(operation('dashboard.indicator',{thresholds:[2,1]},{in:1}))).toContain('M13_INDICATOR_RANGE');expect(codes(operation('dashboard.indicator',{labels:'["one"]'},{in:1}))).toContain('M13_INDICATOR_LABELS');const compiled=compileModel(operation('dashboard.indicator',{labels:'["<script>raw text</script>","two"]'},{in:1}));expect(compiled.nodes.find(n=>n.id==='Operation')!.parameters.indicatorLabels).toEqual(['<script>raw text</script>','two']);});
  it('compiles string tables with source/content/provenance hashes in IR only',()=>{const model=operation('data.input-table',{},{});model.datasets=[dataset('string')];const compiled=compileModel(model),ir=compiled.nodes.find(n=>n.id==='Operation')!;expect(ir.parameters.values).toEqual(['one','two']);expect(ir.outputs.out.typed?.dtype).toBe('string');expect(ir.parameters.dataProvenance).toEqual(model.datasets[0]!.provenance);expect(compiled.model.nodes.find(n=>n.id==='Operation')!.parameters).not.toHaveProperty('times');const linear=structuredClone(model);linear.nodes[0]!.parameters.interpolation='linear';expect(codes(linear)).toContain('DATASET_INTERPOLATION');});
  it('enforces original typed string cap when a general dataset cell is longer',()=>{const model=operation('data.signal-editor',{},{}),data=dataset('string');data.rows[0]![1]='x'.repeat(257);data.contentHash=datasetContentHash(data);model.datasets=[data];expect(codes(model)).toContain('M13_STRING_BOUND');});
  it('derives actual input width, complex type, rank and source constant sample metadata',()=>{const model=operation('signal.probe',{}, {in:{kind:'typed',dtype:'complex128',shape:[2,1],data:[{re:1,im:2},{re:3,im:4}]}}),ir=compileModel(model).nodes.find(n=>n.id==='Operation')!;expect(ir.parameters.probeValue).toMatchObject({kind:'bus',fields:[{name:'width',value:2},{name:'rank',value:2},{name:'dimensions',value:[2,1,0,0,0,0,0,0]},{name:'complex',value:true},{name:'samplePeriod',value:0},{name:'sampleOffset',value:0}]});});
  it('compiles actual current catalog values without claiming source-equivalence count',()=>{const ir=compileModel(operation('model.support-catalog',{},{})).nodes.find(n=>n.id==='Operation')!,value=ir.parameters.catalogValue as {kind:string;fields:{name:string;value:SignalValue}[]};expect(value.kind).toBe('bus');expect(value.fields.find(field=>field.name==='blockCount')!.value).toBe(blockRegistry.length);expect(value.fields.some(field=>field.name==='sourceSubset')).toBe(false);});
  it('requires explicit sampled recording/string boundary and rejects nonsine continuous waveform',()=>{const raw=node('Source','source.ramp'),toString=node('Text','string.to-string'),sink=node('Result','io.structured-output');expect(codes(graph([raw,toString,sink],[edge('Source','Text'),edge('Text','Result')],'continuous'))).toContain('M13_STRING_BOUNDARY_REQUIRED');expect(codes(graph([raw,node('Record','sink.record')],[edge('Source','Record')],'continuous'))).toContain('HYBRID_BOUNDARY_REQUIRED');expect(codes(operation('source.waveform',{kind:'square'}, {},'out','continuous'))).toContain('M13_WAVEFORM_CONTINUOUS_BOUNDARY');});
  it('rejects root-stop requests hidden inside child invocation scope',()=>{const definition:SubsystemDefinition={id:'Child',version:1,name:'Child',nodes:[node('Input','io.input'),node('Stop','sink.stop'),node('Output','io.output')],edges:[edge('Input','Stop'),edge('Input','Output')],layout:{},inputs:[{id:'in',nodeId:'Input'}],outputs:[{id:'out',nodeId:'Output'}]};const model=operation('hierarchy.atomic',{definitionId:'Child'}, {in:1},'out','discrete');model.subsystems=[definition];expect(codes(model)).toContain('M13_STOP_ROOT_ONLY');});
  it('allows smooth indicator out but rejects an unregistered band jump into continuous state',()=>{ const source=node('Source','source.ramp'),indicator=node('Indicator','dashboard.indicator'),state=node('State','continuous.integrator'); const direct=graph([source,indicator,state],[edge('Source','Indicator'),edge('Indicator','State')],'continuous');expect(codes(direct)).toEqual([]);const band=graph([source,indicator,node('Legacy','signal.to-legacy'),state],[edge('Source','Indicator'),edge('Indicator','Legacy','in','band'),edge('Legacy','State')],'continuous');expect(codes(band)).toContain('M13_INDICATOR_BOUNDARY_REQUIRED'); });
});
