import { describe, expect, it } from 'vitest';
import { importBoundedWorkbook, readBoundedXlsxZip } from '../packages/data/src/bounded-xlsx';
import { inspectLocalDataFile, workbookSheetSource, importLocalDataSource, scenarioSource } from '../packages/data/src/file-import';
import { validateDataset } from '../packages/model/src';
import { fixtureZip, workbookFiles } from './helpers/m13-xlsx-fixtures';
const encoder = new TextEncoder();
const options = { id: 'experiment', name: '실험', timeColumn: 'time', columns: [{ name: 'time', kind: 'number' as const, unit: 's' }, { name: 'value', kind: 'number' as const, unit: '1' }] };
describe('M13 bounded local spreadsheet and scenario workflows', () => {
  for (const compression of [0, 8]) it(`imports real ${compression ? 'deflated' : 'stored'} ZIP XML cells and raw-byte provenance`, async () => { const bytes = fixtureZip(workbookFiles(), compression), result = await inspectLocalDataFile(bytes, '실험.xlsx'); expect(result.workbook!.sheets[0].rows).toEqual([[0, 2], [1, 6]]); const source = workbookSheetSource(result.workbook!, '실험', '실험.xlsx'), dataset = importLocalDataSource(source, options); expect(validateDataset(dataset).rows).toEqual([[0, 2], [1, 6]]); expect(dataset.sourceHash).toBe(result.workbook!.sourceHash); expect(dataset.provenance).toMatchObject({ format: 'xlsx', sheet: '실험', filename: '실험.xlsx', sourceHash: dataset.sourceHash }); });
  it('supports internal absolute package worksheet URI used by common XLSX writers', async () => { const files = workbookFiles(); files['xl/_rels/workbook.xml.rels'] = files['xl/_rels/workbook.xml.rels'].replace('worksheets/', '/xl/worksheets/'); expect((await importBoundedWorkbook(fixtureZip(files))).sheets[0].rows[0]).toEqual([0, 2]); });
  it('reads shared strings, explicit boolean, sparse value cells and sheet selection', async () => { const files = workbookFiles('<row r="1"><c r="A1" t="s"><v>0</v></c><c r="B1" t="s"><v>1</v></c></row><row r="2"><c r="A2"><v>0</v></c><c r="B2" t="b"><v>1</v></c></row><row r="3"><c r="A3"><v>1</v></c></row>'); files['xl/sharedStrings.xml'] = '<sst><si><t>time</t></si><si><t>value</t></si></sst>'; const workbook = await importBoundedWorkbook(fixtureZip(files)); expect(workbook.sheets[0].rows).toEqual([[0, true], [1, null]]); expect(() => workbookSheetSource(workbook, 'unknown', 'table.xlsx')).toThrow(); });
  it('reads UTF8 CSV quoted newlines and JSON and preserves numeric negatives', async () => { const csv = await inspectLocalDataFile(encoder.encode('time,value\r\n0,-2\r\n1,+3\r\n'), 'table.csv'); expect(importLocalDataSource(csv.source!, options).rows).toEqual([[0, -2], [1, 3]]); const json = await inspectLocalDataFile(encoder.encode('\uFEFF[{"time":0,"value":2},{"time":1,"value":4}]'), 'table.json'); expect(importLocalDataSource(json.source!, options).rows[1][1]).toBe(4); });
  it('preserves original UTF8 BOM bytes in independently golden CSV/JSON SHA256 provenance', async () => {
    for (const [filename, text, hash, rows] of [
      ['bom.csv', '\uFEFFtime,value\n0,-2\n1,4\n2,8', '010736b2800599493aed0830a79f0ed1e8e0cd62dabf65f537599dd12340b211', [[0, -2], [1, 4], [2, 8]]],
      ['bom.json', '\uFEFF[{"time":0,"value":2},{"time":1,"value":4}]', 'dd8bb5125bff96b334471d362b4d97ca54572b49e3380ad9a7682477ecb935c9', [[0, 2], [1, 4]]],
    ] as const) {
      const source = (await inspectLocalDataFile(encoder.encode(text), filename)).source!;
      const dataset = importLocalDataSource(source, options);
      expect(source.text).toBe(text); expect(source.sourceHash).toBe(hash);
      expect(dataset.provenance?.sourceHash).toBe(hash); expect(dataset.rows).toEqual(rows);
    }
  });
  it('rejects formula cells beyond the five-row preview', async () => { const rows = Array.from({ length: 8 }, (_, i) => `${i},${i === 7 ? '=WEBSERVICE("url")' : 1}`).join('\n'); await expect(inspectLocalDataFile(encoder.encode(`time,value\n${rows}`), 'data.csv')).rejects.toThrow(); });
  for (const payload of ['=1+2', '@SUM(A1)', ' +CMD', '-WEBSERVICE()', '"=1+2"']) it(`rejects formula-like CSV cell ${payload}`, async () => { await expect(inspectLocalDataFile(encoder.encode(`time,value\n0,${payload}\n1,2`), 'data.csv')).rejects.toThrow(); });
  for (const [name, edit] of [
    ['formula', (files: Record<string, string>) => { files['xl/worksheets/sheet1.xml'] = files['xl/worksheets/sheet1.xml'].replace('<v>2</v>', '<f>1+1</f><v>2</v>'); }],
    ['external relationship', (files: Record<string, string>) => { files['xl/_rels/workbook.xml.rels'] = '<Relationships><Relationship Id="rId1" Target="https://example.com/table.xml" TargetMode="External"/></Relationships>'; }],
    ['macro content type', (files: Record<string, string>) => { files['[Content_Types].xml'] = '<Types><Override ContentType="application/vnd.ms-excel.sheet.macroEnabled.main+xml"/></Types>'; }],
    ['DTD', (files: Record<string, string>) => { files['xl/workbook.xml'] = '<!DOCTYPE workbook [<!ENTITY x SYSTEM "file:///secret">]>' + files['xl/workbook.xml']; }],
    ['unknown entity', (files: Record<string, string>) => { files['xl/workbook.xml'] = files['xl/workbook.xml'].replace('실험', '&secret;'); }],
    ['unsafe path', (files: Record<string, string>) => { files['xl/../secret.xml'] = '<x/>'; }],
    ['macro ZIP member', (files: Record<string, string>) => { files['xl/vbaProject.bin'] = 'macro'; }],
    ['merged cells', (files: Record<string, string>) => { files['xl/worksheets/sheet1.xml'] = files['xl/worksheets/sheet1.xml'].replace('</worksheet>', '<mergeCells><mergeCell ref="A1:B1"/></mergeCells></worksheet>'); }],
    ['nonfinite number', (files: Record<string, string>) => { files['xl/worksheets/sheet1.xml'] = files['xl/worksheets/sheet1.xml'].replace('<v>2</v>', '<v>1e999</v>'); }],
    ['overwide column', (files: Record<string, string>) => { files['xl/worksheets/sheet1.xml'] = files['xl/worksheets/sheet1.xml'].replace('B3', 'Q3'); }],
    ['overlong cell', (files: Record<string, string>) => { files['xl/worksheets/sheet1.xml'] = files['xl/worksheets/sheet1.xml'].replace('<t>value</t>', `<t>${'s'.repeat(1001)}</t>`); }],
  ] as const) it(`rejects ${name} before dataset creation`, async () => { const files = workbookFiles(); edit(files); await expect(importBoundedWorkbook(fixtureZip(files, 8))).rejects.toThrow(); });
  it('rejects forged lengths before expansion, wrong CRC and central/local mismatch', async () => { for (const type of ['expanded', 'crc', 'local-name']) { const bytes = fixtureZip(workbookFiles(), 8), view = new DataView(bytes.buffer), end = bytes.length - 22, directory = view.getUint32(end + 16, true); if (type === 'expanded') view.setUint32(directory + 24, 2 * 1024 * 1024 + 1, true); if (type === 'crc') { view.setUint32(directory + 16, 123, true); view.setUint32(14, 123, true); } if (type === 'local-name') bytes[30] = 120; await expect(readBoundedXlsxZip(bytes)).rejects.toThrow(); } });
  it('rejects extension/content mismatch and byte limits', async () => { await expect(inspectLocalDataFile(encoder.encode('not a zip'), 'table.xlsx')).rejects.toThrow(); await expect(inspectLocalDataFile(new Uint8Array(2 * 1024 * 1024 + 1), 'table.csv')).rejects.toThrow(); await expect(inspectLocalDataFile(encoder.encode('time,value\n0,1'), 'file.xlsm')).rejects.toThrow(); });
  it('rejects formula-like JSON headers and macro Default types', async () => { await expect(inspectLocalDataFile(encoder.encode('[{"time":0,"=CMD()":1}]'), 'values.json')).rejects.toThrow(); const files = workbookFiles(); files['[Content_Types].xml'] = '<Types><Default Extension="bin" ContentType="application/vnd.ms-office.vbaProject"/></Types>'; await expect(importBoundedWorkbook(fixtureZip(files))).rejects.toThrow(); });
  it('bounds XML attributes and the whole workbook node count', async () => { const attributes = workbookFiles(); attributes['xl/workbook.xml'] = `<workbook ${Array.from({ length: 65 }, (_, i) => `a${i}="x"`).join(' ')}></workbook>`; await expect(importBoundedWorkbook(fixtureZip(attributes, 8))).rejects.toThrow(); const nodes = workbookFiles(); nodes['xl/styles.xml'] = `<styles>${'<x/>'.repeat(60_000)}</styles>`; nodes['xl/theme/theme1.xml'] = `<theme>${'<x/>'.repeat(60_000)}</theme>`; await expect(importBoundedWorkbook(fixtureZip(nodes, 8))).rejects.toThrow(); });
  it('creates exact named scenario points and independent content/raw hashes', () => { const source = scenarioSource({ name: 'Ramp', points: [{ time: 0, value: -2 }, { time: .5, value: 4 }, { time: 1, value: 8 }] }); const dataset = importLocalDataSource(source, options); expect(dataset.rows).toEqual([[0, -2], [.5, 4], [1, 8]]); expect(dataset.provenance?.format).toBe('editor'); expect(validateDataset(dataset)).toEqual(dataset); });
  it('blocks duplicate time, nonfinite data, too many points, accessors and sparse inputs', () => { expect(() => scenarioSource({ name: 'bad', points: [{ time: 1, value: 0 }, { time: 1, value: 2 }] })).toThrow(); expect(() => scenarioSource({ name: 'bad', points: [{ time: 0, value: Infinity }, { time: 1, value: 2 }] })).toThrow(); expect(() => scenarioSource({ name: 'bad', points: Array.from({ length: 1001 }, (_, time) => ({ time, value: time })) })).toThrow(); let invoked = false; const input = { name: 'bad', get points() { invoked = true; return []; } }; expect(() => scenarioSource(input)).toThrow(); expect(invoked).toBe(false); const sparse = new Array(2); expect(() => scenarioSource({ name: 'bad', points: sparse })).toThrow(); });
  it('validates provenance hash while preserving the old eight-field dataset', () => { const source = scenarioSource({ name: 'test', points: [{ time: 0, value: 1 }, { time: 1, value: 2 }] }), dataset = importLocalDataSource(source, options); expect(() => validateDataset({ ...dataset, provenance: { ...dataset.provenance, sourceHash: '0'.repeat(64) } })).toThrow(); const { provenance, ...old } = dataset; expect(validateDataset(old)).toEqual(old); });
});
