import type { CalcEdge, CalcModel, CalcNode, Dataset, ExecutionMode, SignalValue, StateValue } from '../packages/model/src/types';
import { ENGINE_VERSION } from '../packages/model/src/types';
import { blockRegistry } from '../packages/block-library/src';

/** Numerical/string expectations are independent literals; catalog metadata reads only public declarations. */
export interface M13IndependentFixture { name: string; model: CalcModel; expected: Record<string, SignalValue[]>; declaredModes: ExecutionMode[]; oracleTolerance: number; sourceIds: string[]; expectedFinalState?: Record<string, SignalValue>; expectedStateMemory?: Record<string, StateValue>; expectedStopReason?: { nodeId: string; tick: number; time: number }; metadataOracleFromDeclaredRegistry?: boolean }
export interface M13IndependentFailureFixture { name: string; model: CalcModel; code: string; phase: 'compile' | 'runtime'; sourceIds: string[]; oracleTolerance?: number; expectedPartial?: { samples: number; finalState?: Record<string, SignalValue>; stateMemory?: Record<string, StateValue> } }
const n = (id: string, blockType: string, parameters: Record<string, unknown> = {}): CalcNode => ({ id, blockType, blockVersion: 1, label: id, parameters, unit: '1' });
const e = (source: string, target: string, targetPort = 'in', sourcePort = 'out'): CalcEdge => ({ id: `${source}-${sourcePort}-${target}-${targetPort}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId: targetPort } });
const model = (name: string, nodes: CalcNode[], edges: CalcEdge[] = []): CalcModel => ({ schemaVersion: 1, modelId: name, name, nodes, edges, layout: {}, execution: { mode: 'discrete', startTime: 0, stopTime: 1, step: .5 } });
const text = (value: string): SignalValue => ({ kind: 'typed', dtype: 'string', shape: [], data: [value] });
const scalar = (dtype: 'int32' | 'uint32' | 'float32' | 'float64', value: string | number): SignalValue => ({ kind: 'typed', dtype, shape: [], data: [value] });
const series = (value: SignalValue): SignalValue[] => [value, value, value];
const all: ExecutionMode[] = ['static', 'discrete', 'continuous'];
const fixture = (value: CalcModel, expected: Record<string, SignalValue[]>, modes = all, sourceIds: string[] = []): M13IndependentFixture => ({ name: value.name, model: value, expected, declaredModes: modes === all && value.nodes.some(node => typeof node.parameters.events === 'string' && node.parameters.events !== '[]') ? ['discrete', 'continuous'] : modes, oracleTolerance: 1e-12, sourceIds });
const unary = (type: string, value: SignalValue | string | number, parameters: Record<string, unknown> = {}, name = type.replaceAll('.', '-')): CalcModel => model(`m13-independent-${name}`, [typeof value === 'string' ? n('Source', 'source.string-constant', { value }) : typeof value === 'number' ? n('Source', 'source.constant', { value }) : n('Source', 'source.signal', { value }), n('Block', type, parameters), n('Result', 'sink.display')], [e('Source', 'Block'), e('Block', 'Result')]);
const binaryString = (type: string, a: string, b: string, parameters: Record<string, unknown> = {}, name = type.replaceAll('.', '-')): CalcModel => model(`m13-independent-${name}`, [n('First', 'source.string-constant', { value: a }), n('Second', 'source.string-constant', { value: b }), n('Block', type, parameters), n('Result', 'sink.display')], [e('First', 'Block', type === 'string.string-compare' ? 'a' : type === 'string.string-concatenate' ? 'in1' : 'in'), e('Second', 'Block', type === 'string.string-compare' ? 'b' : type === 'string.string-concatenate' ? 'in2' : 'pattern'), e('Block', 'Result')]);
const scan = unary('string.scan', 'count=7 value=0.1 tag=A', { format: 'count=%d value=%f tag=%s' }); scan.edges = scan.edges.filter(edge => edge.target.nodeId !== 'Result'); scan.nodes = scan.nodes.filter(node => node.id !== 'Result'); for (let index = 1; index <= 3; index++) { scan.nodes.push(n(`Result${index}`, 'sink.display')); scan.edges.push(e('Block', `Result${index}`, 'in', `out${index}`)); }
const compose = model('m13-independent-string-compose', [n('Word', 'source.string-constant', { value: '速度' }), n('Integer', 'source.typed', { value: { kind: 'typed', dtype: 'int64', shape: [], data: ['9007199254740993'] } }), n('Number', 'source.constant', { value: 1.25 }), n('Block', 'string.compose', { format: '%s=%d %.2f %%' }), n('Result', 'sink.display')], [e('Word', 'Block', 'arg1'), e('Integer', 'Block', 'arg2'), e('Number', 'Block', 'arg3'), e('Block', 'Result')]);
const substring = unary('string.substring', 'A😀한B'); substring.nodes.push(n('Start', 'source.constant', { value: 2 }), n('Length', 'source.constant', { value: 2 })); substring.edges.push(e('Start', 'Block', 'start'), e('Length', 'Block', 'length'));
const ascii = unary('string.string-to-ascii', 'AB', { capacity: 4 }); ascii.nodes.push(n('Length', 'sink.display')); ascii.edges.push(e('Block', 'Length', 'in', 'length'));
const control = model('m13-independent-dashboard-control', [n('Control', 'dashboard.control', { events: '[{"time":0.5,"order":0,"value":0.5},{"time":1,"order":1,"value":1}]' }), n('Result', 'sink.display')], [e('Control', 'Result')]);
const indicator = unary('dashboard.indicator', .75); indicator.nodes.push(n('Band', 'sink.display')); indicator.edges.push(e('Block', 'Band', 'in', 'band'));
const action = model('m13-independent-dashboard-action', [n('Action', 'dashboard.action', { action: 'fit', events: '[{"time":0.5,"order":0,"value":true}]' }), n('Result', 'sink.display')], [e('Action', 'Result')]);
const record = (type: string, name = type.replaceAll('.', '-')): CalcModel => model(`m13-independent-${name}`, [n('Source', 'source.step', { stepTime: .5, before: 2, after: 4 }), n('Block', type, { capacity: 3 })], [e('Source', 'Block')]);
const xy = model('m13-independent-sink-xy-graph', [n('X', 'source.step', { stepTime: .5, before: 1, after: 2 }), n('Y', 'source.constant', { value: -3 }), n('Block', 'sink.xy-graph', { capacity: 3 })], [e('X', 'Block', 'x'), e('Y', 'Block', 'y')]);
const xyValue = (x: number): SignalValue => ({ kind: 'bus', fields: [{ name: 'x', value: x }, { name: 'y', value: -3 }] });
const floating = model('m13-independent-sink-floating-scope', [n('Source', 'source.constant', { value: 3 }), n('Block', 'sink.floating-scope', { sourceNodeId: 'Source', sourcePortId: 'out' })]);
const stop = model('m13-independent-sink-stop', [n('Source', 'source.step', { stepTime: .5, before: 0, after: 1 }), n('Stop', 'sink.stop'), n('Delay', 'discrete.unit-delay', { initial: -1 }), n('Result', 'sink.display')], [e('Source', 'Stop'), e('Source', 'Delay'), e('Delay', 'Result')]);
const probe = unary('signal.probe', { kind: 'typed', dtype: 'complex128', shape: [2], data: [{ re: 1, im: 2 }, { re: 3, im: 4 }] });
const probeValue: SignalValue = { kind: 'bus', fields: [{ name: 'width', value: 2 }, { name: 'rank', value: 1 }, { name: 'dimensions', value: [2, 0, 0, 0, 0, 0, 0, 0] }, { name: 'complex', value: true }, { name: 'samplePeriod', value: 0 }, { name: 'sampleOffset', value: 0 }] };
const gain = unary('math.slider-gain', 2, { gain: 1, events: '[{"time":0.5,"order":0,"value":2},{"time":1,"order":1,"value":3}]' });
const data = (kind: 'number' | 'string' | 'boolean'): Dataset => ({ id: 'data', name: 'Literal source table', version: 1, sourceHash: '1'.repeat(64), contentHash: kind === 'number' ? 'e29e1d9177b1daa0e8f4f735eda37407abdd0e440e52248b1a8408e32804b1fe' : kind === 'string' ? '42f9ad95b7ce562c38ee45bb70d76eb7742b1445e2b8614f1f3eb637572917e2' : 'c21388d414477794a50ab921d6fc9e2f945052baae6aa6f9fb891cc639e1e3c4', timeColumn: 'time', columns: [{ name: 'time', kind: 'number', unit: 's' }, { name: 'value', kind, unit: '1' }], rows: kind === 'number' ? [[0, 2], [1, 6]] : kind === 'string' ? [[0, 'Off'], [1, 'On']] : [[0, false], [1, true]] });
const playback = (type: string, kind: 'number' | 'string' | 'boolean' = 'number', interpolation = 'linear'): CalcModel => { const value = model(`m13-independent-${type.replaceAll('.', '-')}-${kind}-${interpolation}`, [n('Block', type, { datasetId: 'data', column: 'value', interpolation }), n('Result', 'sink.display')], [e('Block', 'Result')]); value.datasets = [data(kind)]; return value; };
const waveform = (kind = 'sine'): CalcModel => model(`m13-independent-source-waveform-${kind}`, [n('Block', 'source.waveform', { kind, frequency: .5 }), n('Result', 'sink.display')], [e('Block', 'Result')]);
const catalog = model('m13-independent-model-support-catalog', [n('Block', 'model.support-catalog'), n('Result', 'sink.display')], [e('Block', 'Result')]);
const catalogValue: SignalValue = { kind: 'bus', fields: [{ name: 'blockCount', value: blockRegistry.length }, { name: 'engine', value: text(ENGINE_VERSION) }, { name: 'staticSupported', value: blockRegistry.filter(def => def.supportedModes.includes('static')).length }, { name: 'discreteSupported', value: blockRegistry.filter(def => def.supportedModes.includes('discrete')).length }, { name: 'continuousSupported', value: blockRegistry.filter(def => def.supportedModes.includes('continuous')).length }] };
const recordFixture = (type: string): M13IndependentFixture => ({ ...fixture(record(type), { Block: [2, 4, 4] }, ['discrete']), expectedFinalState: { Block: 4 }, expectedStateMemory: { Block: { m13Records: [{ time: 0, value: 2 }, { time: .5, value: 4 }, { time: 1, value: 4 }], m13RecordTick: 2 } } });
export const M13_INDEPENDENT_DEFINITION_FIXTURES: M13IndependentFixture[] = [
  fixture(model('m13-independent-source-string-constant', [n('Block', 'source.string-constant', { value: '수학😀' }), n('Result', 'sink.display')], [e('Block', 'Result')]), { Result: series(text('수학😀')) }),
  fixture(unary('string.ascii-to-string', { kind: 'typed', dtype: 'uint8', shape: [4], data: ['65', '66', '0', '67'] }), { Result: series(text('AB')) }),
  fixture(compose, { Result: series(text('速度=9007199254740993 1.25 %')) }),
  fixture(scan, { Result1: series(scalar('int32', '7')), Result2: series(scalar('float32', 0.10000000149011612)), Result3: series(text('A')) }),
  fixture(binaryString('string.string-compare', 'ABCtail', 'abcOTHER', { firstN: 3, caseSensitive: 'no' }), { Result: series(true) }),
  fixture(binaryString('string.string-concatenate', '한', '😀'), { Result: series(text('한😀')) }),
  fixture(binaryString('string.string-contains', 'A😀BC', '😀B'), { Result: series(true) }),
  fixture(binaryString('string.string-count', 'aaaaa', 'aa'), { Result: series(scalar('uint32', '2')) }),
  fixture(binaryString('string.string-find', 'A😀BC', 'B'), { Result: series(scalar('int32', '3')) }),
  fixture(unary('string.string-length', '한😀é'), { Result: series(scalar('uint32', '4')) }),
  fixture(ascii, { Result: series({ kind: 'typed', dtype: 'uint8', shape: [4], data: ['65', '66', '0', '0'] }), Length: series(scalar('uint32', '2')) }),
  fixture(unary('string.parse-number', ' -1.25e2 '), { Result: series(scalar('float64', -125)) }),
  fixture(unary('string.parse-enum', 'On'), { Result: series({ kind: 'typed', dtype: 'enum', enum: { name: 'State', labels: ['Off', 'On'] }, shape: [], data: ['On'] }) }),
  fixture(substring, { Result: series(text('😀한')) }),
  fixture(unary('string.to-string', 1.25, { format: '%.2f' }), { Result: series(text('1.25')) }),
  fixture(control, { Control: [0, .5, 1], Result: [0, .5, 1] }),
  fixture(indicator, { Block: series(.75), Result: series(.75), Band: series(scalar('uint32', '1')) }),
  fixture(action, { Action: [false, true, false], Result: [false, true, false] }),
  recordFixture('sink.record'),
  { ...fixture(xy, { Block: [xyValue(1), xyValue(2), xyValue(2)] }, ['discrete']), expectedFinalState: { Block: xyValue(2) }, expectedStateMemory: { Block: { m13Records: [{ time: 0, value: xyValue(1) }, { time: .5, value: xyValue(2) }, { time: 1, value: xyValue(2) }], m13RecordTick: 2 } } },
  fixture(floating, { Block: series(3) }),
  { ...fixture(stop, { Result: [-1, 0] }, ['discrete']), expectedFinalState: { Delay: 0 }, expectedStopReason: { nodeId: 'Stop', tick: 1, time: .5 } },
  fixture(probe, { Result: series(probeValue) }),
  fixture(gain, { Result: [2, 4, 6] }),
  recordFixture('data.output-file'), recordFixture('data.output-dataset'),
  fixture(playback('data.input-table'), { Result: [2, 4, 6] }),
  fixture(playback('data.signal-editor', 'string', 'previous'), { Result: [text('Off'), text('Off'), text('On')] }),
  fixture(waveform(), { Result: [0, 1, 0] }, ['discrete', 'continuous']),
  { ...fixture(catalog, { Result: series(catalogValue) }), metadataOracleFromDeclaredRegistry: true },
];

export const M13_INDEPENDENT_BOUNDARY_FIXTURES: M13IndependentFixture[] = [];
for (const kind of ['check-box', 'combo-box', 'edit', 'knob', 'push-button', 'radio-button', 'rocker-switch', 'rotary-switch', 'slider-switch', 'toggle-switch']) { const value = structuredClone(control); value.name = value.modelId = `m13-independent-control-${kind}`; value.nodes[0]!.parameters = { kind, events: '[{"time":0.5,"order":0,"value":1},{"time":1,"order":1,"value":0}]' }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, { Control: [0, 1, 0], Result: [0, 1, 0] })); }
for (const kind of ['gauge', 'lamp', 'multi-state-image', 'scope']) { const value = structuredClone(indicator); value.name = value.modelId = `m13-independent-indicator-${kind}`; value.nodes.find(node => node.id === 'Block')!.parameters.kind = kind; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, { Block: series(.75), Result: series(.75), Band: series(scalar('uint32', '1')) })); }
for (const [kind, expected] of [['square', [1, 1, -1]], ['triangle', [-1, 0, 1]], ['sawtooth', [-1, -.5, 0]]] as const) M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(waveform(kind), { Result: [...expected] }, ['discrete']));
for (const [kind, expected] of [['boolean', [false, false, true]], ['string', [text('Off'), text('Off'), text('On')]]] as const) M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(playback('data.input-table', kind, 'previous'), { Result: [...expected] }));
M13_INDEPENDENT_BOUNDARY_FIXTURES.push(
  fixture(unary('string.parse-number', '0.1', { dtype: 'float32' }, 'parse-single'), { Result: series(scalar('float32', 0.10000000149011612)) }),
  fixture(unary('string.parse-number', '-0', { dtype: 'float32' }, 'parse-signed-zero'), { Result: series(scalar('float32', '-0')) }),
  fixture(unary('string.parse-number', 'NaN', { special: 'preserve' }, 'parse-special'), { Result: series(scalar('float64', 'NaN')) }),
  fixture(unary('string.parse-number', '42junk', { invalid: 'zero' }, 'parse-invalid-zero'), { Result: series(scalar('float64', 0)) }),
  fixture(binaryString('string.string-find', 'A😀', '', {}, 'find-empty'), { Result: series(scalar('int32', '1')) }),
  fixture(binaryString('string.string-find', 'A😀', 'X', {}, 'find-missing'), { Result: series(scalar('int32', '-1')) }),
  fixture(binaryString('string.string-count', 'aaa', '', {}, 'count-empty'), { Result: series(scalar('uint32', '4')) }),
  fixture(binaryString('string.string-count', 'aAaA', 'AA', { caseSensitive: 'no' }, 'count-ascii-fold'), { Result: series(scalar('uint32', '2')) }),
  fixture(binaryString('string.string-compare', 'ß', 'SS', { caseSensitive: 'no' }, 'compare-no-unicode-expansion'), { Result: series(false) }),
  fixture(unary('string.to-string', { kind: 'typed', dtype: 'boolean', shape: [], data: [true] }, {}, 'to-string-boolean'), { Result: series(text('true')) }),
  fixture(unary('string.to-string', { kind: 'typed', dtype: 'int64', shape: [], data: ['9007199254740993'] }, {}, 'to-string-exact-int64'), { Result: series(text('9007199254740993')) }),
  fixture(unary('string.to-string', { kind: 'typed', dtype: 'enum', enum: { name: 'Mode', labels: ['A', 'B'] }, shape: [], data: ['B'] }, {}, 'to-string-enum'), { Result: series(text('B')) }),
);
const scanPartial = structuredClone(scan); scanPartial.name = scanPartial.modelId = 'm13-independent-scan-partial-zero'; scanPartial.nodes.find(node => node.id === 'Source')!.parameters.value = 'count=7 wrong'; scanPartial.nodes.find(node => node.id === 'Block')!.parameters.invalid = 'zero'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(scanPartial, { Result1: series(scalar('int32', '7')), Result2: series(scalar('float32', 0)), Result3: series(text('')) }));
const scanDouble = unary('string.scan', '0.1', { format: '%lf' }, 'scan-double'); scanDouble.edges.find(edge => edge.source.nodeId === 'Block')!.source.portId = 'out1'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(scanDouble, { Result: series(scalar('float64', .1)) }));
const scanCharacter = unary('string.scan', '😀', { format: '%c' }, 'scan-codepoint'); scanCharacter.edges.find(edge => edge.source.nodeId === 'Block')!.source.portId = 'out1'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(scanCharacter, { Result: series(text('😀')) }));
const toEnd = structuredClone(substring); toEnd.name = toEnd.modelId = 'm13-independent-substring-to-end'; toEnd.nodes.find(node => node.id === 'Block')!.parameters.toEnd = 'yes'; toEnd.nodes = toEnd.nodes.filter(node => node.id !== 'Length'); toEnd.edges = toEnd.edges.filter(edge => edge.source.nodeId !== 'Length'); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(toEnd, { Result: series(text('😀한B')) }));
const matrixGain = structuredClone(gain); matrixGain.name = matrixGain.modelId = 'm13-independent-slider-matrix'; matrixGain.nodes[0]!.parameters.value = [[1, -2], [0, 4]]; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(matrixGain, { Result: [[[1, -2], [0, 4]], [[2, -4], [0, 8]], [[3, -6], [0, 12]]] }));
const sameTime = structuredClone(control); sameTime.name = sameTime.modelId = 'm13-independent-control-same-time-order'; sameTime.nodes[0]!.parameters.events = '[{"time":0.5,"order":7,"value":0.2},{"time":0.5,"order":9,"value":0.8}]'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(sameTime, { Control: [0, .8, .8], Result: [0, .8, .8] }));
const scheduledFuture = structuredClone(control); scheduledFuture.name = scheduledFuture.modelId = 'm13-independent-control-future-order'; scheduledFuture.nodes[0]!.parameters.events = '[{"time":0.5,"order":5,"value":0.5},{"time":1,"order":0,"value":1}]'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(scheduledFuture, { Control: [0, .5, 1], Result: [0, .5, 1] }));
for (const base of [control, action, gain]) { const value = structuredClone(base); value.name = value.modelId = `${base.modelId}-static-initial`; value.nodes.find(node => ['dashboard.control', 'dashboard.action', 'math.slider-gain'].includes(node.blockType))!.parameters.events = '[]'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, base === control ? { Control: series(0), Result: series(0) } : base === action ? { Action: series(false), Result: series(false) } : { Result: series(2) }, ['static'])); }
for (const type of ['sink.record', 'data.output-file', 'data.output-dataset']) { const entry = recordFixture(type); entry.model.name = entry.model.modelId += '-continuous-hold'; entry.name = entry.model.name; entry.model.nodes.push(n('Hold', 'time.zero-order-hold')); entry.model.edges = [e('Source', 'Hold'), e('Hold', 'Block')]; entry.declaredModes = ['continuous']; entry.expectedFinalState = { Block: 4, Hold: 4 }; entry.expectedStateMemory!.Hold = { value: 4 }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(entry); }
const xyHold = structuredClone(xy); xyHold.name = xyHold.modelId = 'm13-independent-xy-continuous-hold'; xyHold.nodes.push(n('Hold', 'time.zero-order-hold')); xyHold.edges = [e('X', 'Hold'), e('Hold', 'Block', 'x'), e('Y', 'Block', 'y')]; M13_INDEPENDENT_BOUNDARY_FIXTURES.push({ ...fixture(xyHold, { Block: [xyValue(1), xyValue(2), xyValue(2)] }, ['continuous']), expectedFinalState: { Block: xyValue(2), Hold: 2 }, expectedStateMemory: { Block: { m13Records: [{ time: 0, value: xyValue(1) }, { time: .5, value: xyValue(2) }, { time: 1, value: xyValue(2) }], m13RecordTick: 2 }, Hold: { value: 2 } } });
const stopHold = structuredClone(stop); stopHold.name = stopHold.modelId = 'm13-independent-stop-continuous-hold'; stopHold.nodes.push(n('Hold', 'time.zero-order-hold')); stopHold.edges = [e('Source', 'Stop'), e('Source', 'Hold'), e('Hold', 'Delay'), e('Delay', 'Result')]; M13_INDEPENDENT_BOUNDARY_FIXTURES.push({ ...fixture(stopHold, { Result: [-1, 0] }, ['continuous']), expectedFinalState: { Delay: 0, Hold: 1 }, expectedStopReason: { nodeId: 'Stop', tick: 1, time: .5 } });

// Source-specific configured profiles are literal inputs, independent of implementation-map edits.
const controls: [string, string, string, string?][] = [
  ['03-002', 'check-box', 'standard'], ['03-003', 'combo-box', 'standard'], ['03-006', 'edit', 'standard'], ['03-009', 'knob', 'standard'], ['03-013', 'push-button', 'standard'], ['03-015', 'radio-button', 'standard'], ['03-016', 'rocker-switch', 'standard'], ['03-017', 'rotary-switch', 'standard'], ['03-019', 'slider-switch', 'standard'],
  ['03-022', 'check-box', 'custom'], ['03-027', 'slider', 'custom'], ['03-028', 'knob', 'custom'], ['03-030', 'push-button', 'custom'], ['03-032', 'rocker-switch', 'custom'], ['03-033', 'rotary-switch', 'custom'], ['03-034', 'slider-switch', 'custom'], ['03-035', 'toggle-switch', 'custom'], ['03-037', 'slider', 'custom', 'vertical'],
];
for (const [id, kind, appearance, orientation = 'horizontal'] of controls) { const value = model(`m13-source-${id}`, [n('Control', 'dashboard.control', { kind, appearance, orientation, events: '[]', initial: 0, min: 0, max: 1, step: .1, choices: [0, 1], title: '' }), n('Result', 'sink.display')], [e('Control', 'Result')]); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, { Control: series(0), Result: series(0) }, all, [id])); }
const indicators: [string, string, string, string, string?][] = [
  ['03-008', 'gauge', 'half', 'standard'], ['03-010', 'lamp', 'full', 'standard'], ['03-011', 'gauge', 'linear', 'standard'], ['03-012', 'multi-state-image', 'full', 'standard'], ['03-014', 'gauge', 'quarter', 'standard'],
  ['03-023', 'gauge', 'full', 'custom'], ['03-024', 'display', 'full', 'custom'], ['03-025', 'gauge', 'half', 'custom'], ['03-026', 'gauge', 'linear', 'custom'], ['03-029', 'lamp', 'full', 'custom'], ['03-031', 'gauge', 'quarter', 'custom'], ['03-036', 'gauge', 'linear', 'custom', 'vertical'],
];
for (const [id, kind, gaugeStyle, appearance, orientation = 'horizontal'] of indicators) { const value = unary('dashboard.indicator', .75, { kind, gaugeStyle, appearance, orientation, min: 0, max: 1, thresholds: [.5], labels: '["낮음","높음"]', title: '' }, `source-${id}`); value.nodes.push(n('Band', 'sink.display')); value.edges.push(e('Block', 'Band', 'in', 'band')); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, { Block: series(.75), Result: series(.75), Band: series(scalar('uint32', '1')) }, all, [id])); }
for (const [id, appearance] of [['03-001', 'standard'], ['03-021', 'custom']]) { const value = model(`m13-source-${id}`, [n('Action', 'dashboard.action', { action: 'run', appearance, orientation: 'horizontal', title: '', events: '[]' }), n('Result', 'sink.display')], [e('Action', 'Result')]); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(value, { Action: series(false), Result: series(false) }, all, [id])); }
const sourceTypes: [string, string][] = [['18-001', 'string.ascii-to-string'], ['18-008', 'string.string-count'], ['18-012', 'string.parse-number'], ['18-013', 'string.parse-enum'], ['14-008', 'signal.probe'], ['12-001', 'model.support-catalog']];
for (const [id, type] of sourceTypes) { const entry = M13_INDEPENDENT_DEFINITION_FIXTURES.find(candidate => candidate.model.nodes.some(node => node.blockType === type))!; entry.sourceIds.push(id); }
M13_INDEPENDENT_BOUNDARY_FIXTURES.find(entry => entry.name === 'm13-independent-parse-single')!.sourceIds.push('18-014');
const defaultCompose = model('m13-source-18-002', [n('Source', 'source.string-constant', { value: 'CalcWeave' }), n('Block', 'string.compose', { format: '%s' }), n('Result', 'sink.display')], [e('Source', 'Block', 'arg1'), e('Block', 'Result')]);
const defaultScan = unary('string.scan', 'CalcWeave', { format: '%s', invalid: 'error' }, 'source-18-003'); defaultScan.edges.find(edge => edge.source.nodeId === 'Block')!.source.portId = 'out1';
const defaultAscii = unary('string.string-to-ascii', 'AB', { capacity: 128 }, 'source-18-011'); defaultAscii.nodes.push(n('Length', 'sink.display')); defaultAscii.edges.push(e('Block', 'Length', 'in', 'length'));
M13_INDEPENDENT_BOUNDARY_FIXTURES.push(
  fixture(defaultCompose, { Result: series(text('CalcWeave')) }, all, ['18-002']),
  fixture(defaultScan, { Result: series(text('CalcWeave')) }, all, ['18-003']),
  fixture(binaryString('string.string-compare', 'ABC', 'ABC', { caseSensitive: 'yes', firstN: 0 }, 'source-18-004'), { Result: series(true) }, all, ['18-004']),
  fixture(model('m13-source-18-006', [n('Block', 'source.string-constant', { value: 'CalcWeave' }), n('Result', 'sink.display')], [e('Block', 'Result')]), { Result: series(text('CalcWeave')) }, all, ['18-006']),
  fixture(defaultAscii, { Result: series({ kind: 'typed', dtype: 'uint8', shape: [128], data: ['65', '66', ...Array(126).fill('0') as string[]] }), Length: series(scalar('uint32', '2')) }, all, ['18-011']),
  fixture(unary('string.to-string', 1.25, { format: '%g' }, 'source-18-016'), { Result: series(text('1.25')) }, all, ['18-016']),
  fixture(playback('data.input-table', 'number', 'previous'), { Result: [2, 2, 6] }, all, ['17-010']),
  fixture(playback('data.signal-editor', 'number', 'previous'), { Result: [2, 2, 6] }, all, ['17-022']),
);
for (const [id, type] of [['16-005', 'sink.record'], ['16-009', 'data.output-file'], ['16-010', 'data.output-dataset']]) { const entry = recordFixture(type!); entry.name = entry.model.name = entry.model.modelId = `m13-source-${id}`; entry.model.nodes.find(node => node.id === 'Block')!.parameters = { name: 'record', capacity: 128, ...(type === 'data.output-file' ? { format: 'json' } : {}) }; entry.sourceIds = [id!]; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(entry); }
const sourceXY = structuredClone(xy); sourceXY.name = sourceXY.modelId = 'm13-source-16-011'; sourceXY.nodes.find(node => node.id === 'Block')!.parameters = { name: 'record', capacity: 128 }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(sourceXY, { Block: [xyValue(1), xyValue(2), xyValue(2)] }, ['discrete'], ['16-011']));
const sourceFloating = structuredClone(floating); sourceFloating.name = sourceFloating.modelId = 'm13-source-16-002'; sourceFloating.nodes.find(node => node.id === 'Source')!.id = 'source'; sourceFloating.nodes.find(node => node.id === 'Block')!.parameters.sourceNodeId = 'source'; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(sourceFloating, { Block: series(3) }, all, ['16-002']));
M13_INDEPENDENT_DEFINITION_FIXTURES.find(entry => entry.name === stop.name)!.sourceIds.push('16-007');
const sourceWave = waveform(); sourceWave.name = sourceWave.modelId = 'm13-source-17-027'; sourceWave.execution.step = .25; sourceWave.execution.stopTime = .5; sourceWave.nodes[0]!.parameters = { kind: 'sine', amplitude: 1, frequency: 1, phase: 0, bias: 0, duty: .5 }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(sourceWave, { Result: [0, 1, 0] }, ['discrete', 'continuous'], ['17-027']));
const immediateStop = model('m13-independent-stop-static-true', [n('Source', 'source.constant', { value: 1 }), n('Stop', 'sink.stop'), n('Result', 'sink.display')], [e('Source', 'Stop'), e('Source', 'Result')]); M13_INDEPENDENT_BOUNDARY_FIXTURES.push({ ...fixture(immediateStop, { Result: [1] }, ['static'], ['16-007']), expectedStopReason: { nodeId: 'Stop', tick: 0, time: 0 } });
const falseStop = structuredClone(immediateStop); falseStop.name = falseStop.modelId = 'm13-independent-stop-static-false'; falseStop.nodes[0]!.parameters.value = 0; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(falseStop, { Result: [0] }, ['static'], ['16-007']));
for (const [name, value, format, expected] of [['g-small-exponent', .00001, '%g', '1e-05'], ['g-fixed-threshold', .0001, '%g', '0.0001'], ['g-rounding-exponent', 999999.9, '%g', '1e+06'], ['g-negative', -12.125, '%.4g', '-12.13'], ['e-padded', .1, '%.2e', '1.00e-01'], ['f-large-exact', 1e21, '%.2f', '1000000000000000000000.00']] as const) M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(unary('string.to-string', value, { format }, name), { Result: series(text(expected)) }, all, ['18-016']));
const exactMaximumASCII = unary('string.string-to-ascii', 'A'.repeat(256), { capacity: 256 }, 'ascii-max'); exactMaximumASCII.nodes.push(n('Length', 'sink.display')); exactMaximumASCII.edges.push(e('Block', 'Length', 'in', 'length')); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(exactMaximumASCII, { Result: series({ kind: 'typed', dtype: 'uint8', shape: [256], data: Array(256).fill('65') as string[] }), Length: series(scalar('uint32', '256')) }));
const dynamicSubstring = structuredClone(substring); dynamicSubstring.name = dynamicSubstring.modelId = 'm13-independent-substring-dynamic-index'; dynamicSubstring.nodes.find(node => node.id === 'Start')!.blockType = 'source.step'; dynamicSubstring.nodes.find(node => node.id === 'Start')!.parameters = { stepTime: .5, before: 1, after: 3 }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(dynamicSubstring, { Result: [text('A😀'), text('한B'), text('한B')] }, ['discrete']));
const dynamicIndexHold = structuredClone(dynamicSubstring); dynamicIndexHold.name = dynamicIndexHold.modelId = 'm13-independent-substring-dynamic-index-hold'; dynamicIndexHold.nodes.push(n('Hold', 'time.zero-order-hold')); dynamicIndexHold.edges = dynamicIndexHold.edges.filter(edge => edge.source.nodeId !== 'Start'); dynamicIndexHold.edges.push(e('Start', 'Hold'), e('Hold', 'Block', 'start')); M13_INDEPENDENT_BOUNDARY_FIXTURES.push(fixture(dynamicIndexHold, { Result: [text('A😀'), text('한B'), text('한B')] }, ['continuous']));
const asciiSubstring = structuredClone(substring); asciiSubstring.name = asciiSubstring.modelId = 'm13-source-18-015-ascii'; asciiSubstring.nodes.find(node => node.id === 'Source')!.parameters.value = 'ABCD';
M13_INDEPENDENT_BOUNDARY_FIXTURES.push(
  fixture(binaryString('string.string-concatenate', 'Cal', 'c', { count: 2 }, 'source-18-005-ascii'), { Result: series(text('Calc')) }, all, ['18-005']),
  fixture(binaryString('string.string-contains', 'CalcWeave', 'Weave', { caseSensitive: 'yes' }, 'source-18-007-ascii'), { Result: series(true) }, all, ['18-007']),
  fixture(binaryString('string.string-find', 'ABCABC', 'B', { caseSensitive: 'yes' }, 'source-18-009-ascii'), { Result: series(scalar('int32', '2')) }, all, ['18-009']),
  fixture(unary('string.string-length', 'CalcWeave', {}, 'source-18-010-ascii'), { Result: series(scalar('uint32', '9')) }, all, ['18-010']),
  fixture(asciiSubstring, { Result: series(text('BC')) }, all, ['18-015']),
);
const typedRecord = record('sink.record', 'record-complex-bus'); typedRecord.nodes[0]!.blockType = 'source.signal'; typedRecord.nodes[0]!.parameters = { value: { kind: 'bus', fields: [{ name: 'z', value: { kind: 'typed', dtype: 'complex128', shape: [], data: [{ re: '-0', im: 2 }] } }, { name: 'label', value: text('😀') }] } }; const typedRecorded: SignalValue = { kind: 'bus', fields: [{ name: 'z', value: { kind: 'typed', dtype: 'complex128', shape: [], data: [{ re: '-0', im: 2 }] } }, { name: 'label', value: text('😀') }] }; M13_INDEPENDENT_BOUNDARY_FIXTURES.push({ ...fixture(typedRecord, { Block: series(typedRecorded) }, ['discrete', 'continuous'], ['16-005']), expectedFinalState: { Block: typedRecorded }, expectedStateMemory: { Block: { m13RecordTick: 2, m13Records: [{ time: 0, value: typedRecorded }, { time: .5, value: typedRecorded }, { time: 1, value: typedRecorded }] } } });

const failures: M13IndependentFailureFixture[] = [
  { name: 'm13-independent-ascii-non-ascii', model: unary('string.string-to-ascii', '한'), code: 'M13_ASCII_RANGE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-ascii-capacity', model: unary('string.string-to-ascii', 'ABC', { capacity: 2 }), code: 'M13_ASCII_CAPACITY', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-unpaired-surrogate', model: unary('string.string-length', '\ud800'), code: 'M13_UNICODE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-number-junk', model: unary('string.parse-number', '12junk'), code: 'M13_NUMBER_PARSE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-number-underflow', model: unary('string.parse-number', '1e-50', { dtype: 'float32' }), code: 'M13_NUMBER_PARSE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-number-overflow', model: unary('string.parse-number', '1e50', { dtype: 'float32' }), code: 'M13_NUMBER_PARSE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-enum-label', model: unary('string.parse-enum', 'Unknown'), code: 'M13_ENUM_PARSE', phase: 'runtime', sourceIds: [] },
  { name: 'm13-independent-format-code', model: unary('string.to-string', 1, { format: '%n' }), code: 'M13_FORMAT_UNSUPPORTED', phase: 'compile', sourceIds: [] },
];
const cap = record('sink.record', 'record-capacity-failure'); cap.nodes.find(node => node.id === 'Block')!.parameters.capacity = 2; failures.push({ name: cap.name, model: cap, code: 'M13_RECORD_CAPACITY', phase: 'runtime', sourceIds: [], expectedPartial: { samples: 2, finalState: { Block: 4 }, stateMemory: { Block: { m13Records: [{ time: 0, value: 2 }, { time: .5, value: 4 }], m13RecordTick: 1 } } } });
const offgrid = structuredClone(control); offgrid.nodes[0]!.parameters.events = '[{"time":0.5,"order":0,"value":0.35}]'; failures.push({ name: 'm13-independent-control-offgrid', model: offgrid, code: 'M13_CONTROL_STEP', phase: 'compile', sourceIds: [] });
const outofrange = structuredClone(control); outofrange.nodes[0]!.parameters.events = '[{"time":0.5,"order":0,"value":2}]'; failures.push({ name: 'm13-independent-control-range', model: outofrange, code: 'M13_CONTROL_RANGE', phase: 'compile', sourceIds: [] });
const duplicate = structuredClone(control); duplicate.nodes[0]!.parameters.events = '[{"time":0.5,"order":0,"value":0.5},{"time":1,"order":0,"value":1}]'; failures.push({ name: 'm13-independent-control-duplicate-order', model: duplicate, code: 'M13_CONTROL_EVENTS', phase: 'compile', sourceIds: [] });
const asciiHigh = unary('string.ascii-to-string', { kind: 'typed', dtype: 'uint8', shape: [2], data: ['0', '200'] }); failures.push({ name: 'm13-independent-ascii-after-nul-strict', model: asciiHigh, code: 'M13_ASCII_RANGE', phase: 'runtime', sourceIds: [] });
const long = binaryString('string.string-concatenate', 'a'.repeat(200), 'b'.repeat(100)); failures.push({ name: 'm13-independent-concatenate-budget', model: long, code: 'M13_STRING_BUDGET', phase: 'runtime', sourceIds: [] });
const lateString = unary('string.parse-number', '0'); lateString.name = lateString.modelId = 'm13-independent-late-string-failure'; lateString.nodes[0]!.blockType = 'data.signal-editor'; lateString.nodes[0]!.parameters = { datasetId: 'data', column: 'value', interpolation: 'previous' }; lateString.datasets = [{ id: 'data', name: 'Late literal', version: 1, sourceHash: '1'.repeat(64), contentHash: 'fa7cb3e83a19f6733facc137b411566966c3762cd24a5a2399f465a7740ce54b', timeColumn: 'time', columns: [{ name: 'time', kind: 'number', unit: 's' }, { name: 'value', kind: 'string', unit: '1' }], rows: [[0, '2'], [1, 'bad']] }]; lateString.nodes.push(n('Numeric', 'source.step', { stepTime: .5, before: 2, after: 4 }), n('ARecord', 'sink.record', { capacity: 3 }), n('Delay', 'discrete.unit-delay', { initial: -1 }), n('Delayed', 'sink.display'), n('Stop', 'sink.stop'), n('StopSource', 'source.step', { stepTime: 1, before: 0, after: 1 })); lateString.edges.push(e('Numeric', 'ARecord'), e('Numeric', 'Delay'), e('Delay', 'Delayed'), e('StopSource', 'Stop')); failures.push({ name: lateString.name, model: lateString, code: 'M13_NUMBER_PARSE', phase: 'runtime', sourceIds: ['18-012', '16-005', '16-007'], expectedPartial: { samples: 2, finalState: { ARecord: 4, Delay: 2 }, stateMemory: { ARecord: { m13RecordTick: 1, m13Records: [{ time: 0, value: 2 }, { time: .5, value: 4 }] }, Delay: { value: 2 } } } });
export const M13_INDEPENDENT_FAILURE_FIXTURES = failures;

/** Live controls use the same literal source but receipt insertion happens only on actual due ticks. */
export const M13_LIVE_CONTROL_MODEL = model('m13-live-control-independent', [n('Control', 'dashboard.control', { events: '[{"time":1,"order":0,"value":1}]', initial: 0 }), n('Result', 'sink.display')], [e('Control', 'Result')]);
