import m13Map from '../docs/m13-implementation-map.json';
import { createElement } from 'react';
import { describe, expect, it } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import { compileModel } from '../packages/compiler/src';
import { runModel } from '../packages/runtime/src';
import { EXAMPLES, EXAMPLE_CATEGORIES } from '../apps/web/src/examples';
import { createM13Examples } from '../apps/web/src/m13-examples';
import { M13DashboardPanel, m13RecordedEntries, recordingDataset } from '../apps/web/src/components/M13DashboardPanel';
import { validateDataset } from '../packages/model/src';
describe('M13 actual UI models and exact recording boundaries', () => {
  it('preserves61 predecessor IDs and all9 category IDs, adds8 models to real new workflows', () => { expect(EXAMPLES.length).toBeGreaterThanOrEqual(69); expect(new Set(EXAMPLES.map(example => example.id)).size).toBe(EXAMPLES.length); for (const id of ['basics', 'signals', 'discrete', 'continuous', 'workspace', 'advanced', 'typed', 'hierarchy', 'solver', 'dashboard', 'strings']) expect(EXAMPLE_CATEGORIES.some(category => category.id === id)).toBe(true); expect(createM13Examples()).toHaveLength(8); });
  for (const example of createM13Examples()) it(`executes compiled example ${example.id} with real samples`, async () => { const compiled = compileModel(example.model), result = await runModel(compiled); expect(result.status).toBe('completed'); expect(result.samples.length).toBeGreaterThan(1); if (example.id === 'string-unicode-search') { const final = result.samples.at(-1)!.values; expect(final['length-result']).toMatchObject({ dtype: 'uint32', data: ['4'] }); expect(final['find-result']).toMatchObject({ dtype: 'int32', data: ['2'] }); expect(final['count-result']).toMatchObject({ dtype: 'uint32', data: ['2'] }); } if (example.id === 'string-compose-scan') { expect(result.samples.at(-1)!.values['text-result']).toMatchObject({ dtype: 'string', data: ['7,2.50'] }); expect(result.samples.at(-1)!.values['integer-result']).toMatchObject({ dtype: 'int32', data: ['7'] }); } if (example.id === 'dashboard-recorded-controls') expect(result.samples.at(-1)!.values.result).toBe(.8); if (example.id === 'dashboard-choice-and-gain') expect(result.samples.at(-1)!.values.result).toBe(12); if (example.id === 'named-signal-editor-playback') { expect(result.samples[3].values['linear-result']).toBeCloseTo(1.2, 12); expect(result.samples[3].values['previous-result']).toBe(0); } if (example.id === 'waveform-xy-and-record') { const entries = m13RecordedEntries(result, 'xy'); expect(entries).toHaveLength(21); expect(entries[0].value).toMatchObject({ kind: 'bus', fields: [{ name: 'x', value: 0 }, { name: 'y', value: -1 }] }); expect(m13RecordedEntries(result, 'record')).toHaveLength(21); } if (example.id === 'bounded-record-and-stop') { expect(result.stopReason).toEqual({ nodeId: 'stop', tick: 5, time: .5 }); expect(result.samples).toHaveLength(6); expect(m13RecordedEntries(result, 'record').at(-1)).toEqual({ time: .5, value: .5 }); } });
  for (const row of m13Map.rows.filter(row => row.sourceSection === 3)) it(`renders and executes source-specific dashboard profile ${row.id}`, async () => {
    const selected = row.selectedImplementation, base = createM13Examples()[3].model, node = { id: 'Profile', blockType: selected.canonical, blockVersion: 1, label: row.sourceName, parameters: selected.parameters };
    const model = { ...base, layout: {}, nodes: [node, { id: 'Source', blockType: 'source.constant', blockVersion: 1, label: '0.75', parameters: { value: .75 } }], edges: (selected.requiredBindings as string[]).includes('in') ? [{ id: 'ProfileInput', source: { nodeId: 'Source', portId: 'out' }, target: { nodeId: 'Profile', portId: 'in' } }] : [] };
    const compiled = compileModel(model), result = await runModel(compiled);
    const html = renderToStaticMarkup(createElement(M13DashboardPanel, { tab: 'dashboard', model: compiled.model, onChange: () => {}, notice: () => {}, onPlayback: () => {}, history: [], historyError: '', onDeleteRecord: () => {}, onRestoreRecord: () => {}, onHistoryRecovery: () => {}, busy: false, onSweep: async () => {}, onCancelSweep: () => {}, sweepProgress: { completed: 0, total: 0 }, resultCurrent: true, result: { model: compiled.model, result, outputTypes: compiled.outputTypes }, outputTypes: compiled.outputTypes, onScopeRange: async () => {} }));
    const p = selected.parameters as Record<string, unknown>; expect(html).toContain(`data-widget-appearance="${p.appearance}"`); if (p.orientation === 'vertical') expect(html).toContain('vertical-widget'); if (selected.canonical === 'dashboard.control') { expect(html).toContain(`data-widget-kind="${p.kind}"`); expect(result.samples.at(-1)!.values.Profile).toBe(0); } else if (selected.canonical === 'dashboard.indicator') { expect(result.samples.at(-1)!.values.Profile).toBe(.75); if (p.kind === 'gauge') expect(html).toContain(`gauge-${p.gaugeStyle}`); } else expect(html).toContain('계산 실행');
  });
  it('stores scalar recordings with physical unit and rejects structured coercion', () => { const entries = [{ time: 0, value: 2 }, { time: 1, value: 3 }]; expect(validateDataset(recordingDataset(entries, 'velocity', 'm/s')).columns[1].unit).toBe('m/s'); expect(recordingDataset([{ time: 0, value: 2 }], 'one')).toMatchObject({ rows: [[0, 2]], provenance: { format: 'json', transforms: ['simulation-recording'] } }); expect(() => recordingDataset([{ time: 0, value: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } }], 'bad')).toThrow(); });
  it('renders every source control normal/custom without executable callbacks or unescaped strings', () => { const base = createM13Examples().find(example => example.id === 'dashboard-recorded-controls')!.model, original = base.nodes[0]; for (const kind of ['check-box', 'combo-box', 'edit', 'knob', 'push-button', 'radio-button', 'rocker-switch', 'rotary-switch', 'slider', 'slider-switch', 'toggle-switch']) for (const appearance of ['standard', 'custom']) { const model = { ...base, nodes: [{ ...original, parameters: { ...original.parameters, kind, appearance, title: '<img src=x onerror=alert(1)>' } }] }; const html = renderToStaticMarkup(createElement(M13DashboardPanel, { tab: 'dashboard', model, onChange: () => {}, notice: () => {}, onPlayback: () => {}, history: [], historyError: '', onDeleteRecord: () => {}, onRestoreRecord: () => {}, onHistoryRecovery: () => {}, busy: false, onSweep: async () => {}, onCancelSweep: () => {}, sweepProgress: { completed: 0, total: 0 }, resultCurrent: false, outputTypes: {}, onScopeRange: async () => {} })); expect(html).toContain(`data-widget-kind="${kind}"`); expect(html).toContain(`data-widget-appearance="${appearance}"`); expect(html).toContain('&lt;img'); expect(html).not.toContain('<img src=x'); } });
});
