import type { AdapterLifecycle, CalcEdge, CalcModel, CalcNode, ExecutionMode, MessageItem, MessageSignal, SignalValue, StateValue, SubsystemDefinition } from '../packages/model/src/types';

/** All numerical, message and state expectations are independent literals, never production kernels. */
export interface M14IndependentFixture { name: string; model: CalcModel; expected: Record<string, SignalValue[]>; declaredModes: ExecutionMode[]; oracleTolerance: number; sourceIds: string[]; expectedFinalState?: Record<string, SignalValue>; expectedStateMemory?: Record<string, StateValue>; expectedAdapterLifecycle?: AdapterLifecycle[]; expectedStopReason?: { nodeId: string; tick: number; time: number } }
export interface M14IndependentFailureFixture { name: string; model: CalcModel; code: string; phase: 'compile' | 'runtime'; sourceIds: string[]; oracleTolerance?: number; expectedPartial?: { samples: number; finalState?: Record<string, SignalValue>; stateMemory?: Record<string, StateValue>; adapterLifecycle?: AdapterLifecycle[] } }
const node = (id: string, blockType: string, parameters: Record<string, unknown> = {}, unit = '1'): CalcNode => ({ id, blockType, blockVersion: 1, label: id, parameters, unit });
const edge = (source: string, target: string, port = 'in', output = 'out'): CalcEdge => ({ id: `${source}-${output}-${target}-${port}`, source: { nodeId: source, portId: output }, target: { nodeId: target, portId: port } });
const graph = (name: string, nodes: CalcNode[], edges: CalcEdge[], stopTime = 1): CalcModel => ({ schemaVersion: 1, modelId: name, name, nodes, edges, layout: {}, execution: { mode: 'discrete', startTime: 0, stopTime, step: .5 } });
const fixture = (model: CalcModel, expected: Record<string, SignalValue[]>, declaredModes: ExecutionMode[] = ['discrete'], sourceIds: string[] = []): M14IndependentFixture => ({ name: model.name, model, expected, declaredModes, oracleTolerance: 1e-12, sourceIds });
const affine = (name: string, gain = 3, bias = -1, input = 2): CalcModel => graph(name, [node('Input', 'source.constant', { value: input }), node('Block', 'adapter.wasm-affine', { gain, bias }), node('Result', 'sink.display')], [edge('Input', 'Block'), edge('Block', 'Result')]);
const accumulator = (name: string, resetMode = 'rising', initial = 1, gain = 2, input = 2, stopTime = 1): CalcModel => graph(name, [node('Input', 'source.constant', { value: input }), node('Reset', 'source.signal', { value: false }), node('Block', 'adapter.wasm-accumulator', { initial, gain, resetMode }), node('Result', 'sink.display')], [edge('Input', 'Block'), edge('Reset', 'Block', 'reset'), edge('Block', 'Result')], stopTime);
const accumulatorMemory = (value: number, updates: number, reads: number, resets = 0, previousReset = false, active = false): StateValue => ({ m14Value: value, m14PreviousReset: previousReset, m14ResetActive: active, m14Updates: updates, m14Resets: resets, m14Reads: reads, m14Initialized: true });
const lifecycle = (reason: AdapterLifecycle['reason'] = 'completed', nodeId = 'Block'): AdapterLifecycle[] => [{ nodeId, profileId: 'calcweave.wasm-accumulator-f64-v1', initialized: true, terminated: true, reason }];
const item = (sequence: number, payload: SignalValue = sequence + 10, time = 0, producer = 'Sender', priority = 0): MessageItem => ({ producer, sequence, time, priority, payload });
const messages = (...items: MessageItem[]): MessageSignal => ({ kind: 'messages', items });
const entity = (name: string, batch: MessageSignal = messages(item(0), item(1)), parameters: Record<string, unknown> = { capacity: 4, maxRelease: 2, overflow: 'error' }, delay = 1, stopTime = 1): CalcModel => graph(name, [node('Input', 'source.signal', { value: batch }), node('Delay', 'source.constant', { value: delay }, 's'), node('Block', 'adapter.entity-transport', parameters), node('Result', 'sink.display'), node('Count', 'sink.display')], [edge('Input', 'Block'), edge('Delay', 'Block', 'delay'), edge('Block', 'Result'), edge('Block', 'Count', 'in', 'count')], stopTime);
const dynamicEntity = (name: string, parameters: Record<string, unknown> = { capacity: 4, maxRelease: 2 }, delay = 1, stopTime = 1.5): CalcModel => graph(name, [node('Payload', 'source.constant', { value: 7 }), node('Send', 'source.signal', { value: true }), node('Input', 'events.send', { producer: 'Sender', priority: 0 }), node('Delay', 'source.constant', { value: delay }, 's'), node('Block', 'adapter.entity-transport', parameters), node('Result', 'sink.display'), node('Count', 'sink.display')], [edge('Payload', 'Input', 'payload'), edge('Send', 'Input', 'send'), edge('Input', 'Block'), edge('Delay', 'Block', 'delay'), edge('Block', 'Result'), edge('Block', 'Count', 'in', 'count')], stopTime);
const queueItem = (value: MessageItem, deadline: number, earliestTick: number, arrival: number): StateValue => ({ ...value, deadline, earliestTick, arrival });
const entityMemory = (queue: StateValue[], seen: { producer: string; sequence: number }[], arrival: number): StateValue => ({ m14Queue: queue, m14Seen: seen, m14Arrival: arrival });

export const M14_INDEPENDENT_DEFINITION_FIXTURES: M14IndependentFixture[] = [
  fixture(affine('m14-independent-wasm-affine'), { Result: [5,5,5] }, ['static', 'discrete', 'continuous'], ['19-001']),
  { ...fixture(accumulator('m14-independent-wasm-accumulator'), { Result: [1,5,9] }, ['discrete'], ['19-002']), expectedFinalState: { Block: 9 }, expectedStateMemory: { Block: accumulatorMemory(9,2,3) }, expectedAdapterLifecycle: lifecycle() },
  { ...fixture(entity('m14-independent-entity-transport'), { Result: [messages(),messages(),messages(item(0),item(1))], Count: [2,2,0] }, ['discrete'], ['02-016']), expectedFinalState: { Block: messages(item(0),item(1)) }, expectedStateMemory: { Block: entityMemory([], [{ producer: 'Sender', sequence: 1 }], 2) } },
];

const boundaries: M14IndependentFixture[] = [];
boundaries.push(fixture(affine('m14-boundary-affine-negative', -2, .5, -3), { Result: [6.5,6.5,6.5] }, ['static', 'discrete', 'continuous']));
boundaries.push(fixture(affine('m14-boundary-affine-zero-gain', 0, -7, Number.MAX_VALUE), { Result: [-7,-7,-7] }, ['static', 'discrete', 'continuous']));
const ramp = affine('m14-boundary-affine-time-varying', 2, -1); ramp.nodes[0] = node('Input', 'source.ramp', { slope: 1, initial: 0, startTime: 0 }); boundaries.push(fixture(ramp, { Result: [-1,0,1] }, ['discrete', 'continuous']));
for (const resetMode of ['rising', 'level']) {
  const model = accumulator(`m14-boundary-accumulator-${resetMode}`, resetMode, 1, 2, 2, 2); model.nodes[1] = node('Reset', 'logic.compare-constant', { operator: 'gt', constant: 0 }); model.nodes.push(node('ResetStep', 'source.step', { stepTime: .5, before: 0, after: 1 })); model.edges.push(edge('ResetStep','Reset'));
  const rising = resetMode === 'rising'; boundaries.push({ ...fixture(model, { Result: rising ? [1,1,5,9,13] : [1,1,1,1,1] }), expectedFinalState: { Block: rising ? 13 : 1 }, expectedStateMemory: { Block: accumulatorMemory(rising ? 13 : 1, 4, 5, rising ? 1 : 4, true, !rising) }, expectedAdapterLifecycle: lifecycle() });
}
const feedback = accumulator('m14-boundary-accumulator-feedback', 'rising', 1, 1, 0, 1.5); feedback.nodes[0] = node('Input', 'math.gain', { gain: 1 }); feedback.edges.push(edge('Block', 'Input')); boundaries.push({ ...fixture(feedback, { Result: [1,2,4,8] }), expectedFinalState: { Block: 8 }, expectedStateMemory: { Block: accumulatorMemory(8,3,4) }, expectedAdapterLifecycle: lifecycle() });
const two = accumulator('m14-boundary-independent-accumulators', 'rising', 1, 2, 2); two.nodes.push(node('Other', 'adapter.wasm-accumulator', { initial: -2, gain: -1 }), node('OtherResult', 'sink.display')); two.edges.push(edge('Input', 'Other'), edge('Reset', 'Other', 'reset'), edge('Other', 'OtherResult')); boundaries.push({ ...fixture(two, { Result: [1,5,9], OtherResult: [-2,-4,-6] }), expectedFinalState: { Block: 9, Other: -6 }, expectedStateMemory: { Block: accumulatorMemory(9,2,3), Other: accumulatorMemory(-6,2,3) }, expectedAdapterLifecycle: [...lifecycle(),...lifecycle('completed','Other')] });
const offset = accumulator('m14-boundary-accumulator-multirate', 'rising', 3, -1, 2, 2); offset.nodes.forEach(value => value.sampleTime = { period: 2, offset: 1 }); boundaries.push({ ...fixture(offset, { Result: [0,3,3,1,1] }), expectedFinalState: { Block: 1 }, expectedStateMemory: { Block: accumulatorMemory(-1,2,2) }, expectedAdapterLifecycle: lifecycle() });
const stop = accumulator('m14-boundary-accumulator-stop', 'rising', 1, 2, 2); stop.nodes.push(node('StopSource', 'source.step', { stepTime: .5, before: 0, after: 1 }), node('Stop', 'sink.stop')); stop.edges.push(edge('StopSource', 'Stop')); boundaries.push({ ...fixture(stop, { Result: [1,5] }), expectedFinalState: { Block: 5 }, expectedStateMemory: { Block: accumulatorMemory(5,1,2) }, expectedAdapterLifecycle: lifecycle(), expectedStopReason: { nodeId: 'Stop', tick: 1, time: .5 } });
boundaries.push({ ...fixture(entity('m14-boundary-zero-delay', messages(item(0)), { capacity: 1, maxRelease: 1 }, 0), { Result: [messages(),messages(item(0)),messages()], Count: [1,0,0] }), expectedFinalState: { Block: messages() }, expectedStateMemory: { Block: entityMemory([], [{ producer: 'Sender', sequence: 0 }], 1) } });
const releaseOne = entity('m14-boundary-max-release-one', messages(item(0),item(1)), { capacity: 4, maxRelease: 1 }, 0); boundaries.push({ ...fixture(releaseOne, { Result: [messages(),messages(item(0)),messages(item(1))], Count: [2,1,0] }), expectedFinalState: { Block: messages(item(1)) }, expectedStateMemory: { Block: entityMemory([], [{ producer: 'Sender', sequence: 1 }], 2) } });
for (const overflow of ['drop-newest', 'drop-oldest']) { const kept = item(overflow === 'drop-newest' ? 0 : 1), value = entity(`m14-boundary-${overflow}`, messages(item(0),item(1)), { capacity: 1, maxRelease: 1, overflow }, 0); boundaries.push({ ...fixture(value, { Result: [messages(),messages(kept),messages()], Count: [1,0,0] }), expectedFinalState: { Block: messages() }, expectedStateMemory: { Block: entityMemory([], [{ producer: 'Sender', sequence: 1 }], 2) } }); }
const fifo = dynamicEntity('m14-boundary-variable-duration-fifo'); fifo.nodes.find(value => value.id === 'Delay')!.blockType = 'source.step'; fifo.nodes.find(value => value.id === 'Delay')!.parameters = { stepTime: .5, before: 1, after: 0 }; boundaries.push({ ...fixture(fifo, { Result: [messages(),messages(),messages(item(0,7,0),item(1,7,.5)),messages(item(2,7,1))], Count: [1,2,1,1] }), expectedFinalState: { Block: messages(item(2,7,1)), Input: messages(item(3,7,1.5)) }, expectedStateMemory: { Block: entityMemory([queueItem(item(3,7,1.5),1.5,4,4)], [{ producer: 'Sender', sequence: 3 }], 4), Input: { sequence: 4 } } });
const priority = entity('m14-boundary-fifo-ignores-priority', messages(item(0,10,0,'First',100),item(0,20,0,'Second',-100)), { capacity: 2, maxRelease: 1 }, 0); boundaries.push(fixture(priority, { Result: [messages(),messages(item(0,10,0,'First',100)),messages(item(0,20,0,'Second',-100))], Count: [2,1,0] }));
const typedPayload: SignalValue = { kind: 'bus', fields: [{ name: 'label', value: { kind: 'typed', dtype: 'string', shape: [], data: ['A😀'] } }, { name: 'code', value: { kind: 'typed', dtype: 'uint64', shape: [], data: ['9007199254740993'] } }] };
boundaries.push(fixture(entity('m14-boundary-typed-payload-metadata', messages(item(7,typedPayload,-5,'Typed',-9)), { capacity: 2, maxRelease: 1 }, .25), { Result: [messages(),messages(item(7,typedPayload,-5,'Typed',-9)),messages()], Count: [1,0,0] }));
const nestedAffine = affine('m14-boundary-nested-affine'); nestedAffine.nodes.find(value=>value.id==='Result')!.blockType='io.output'; const definition: SubsystemDefinition = { id: 'Affine', version: 1, name: 'Affine', nodes: nestedAffine.nodes, edges: nestedAffine.edges, inputs: [], outputs: [{ id: 'out', nodeId: 'Result' }], layout: {} }; const nested = graph(nestedAffine.name, [node('Scope', 'hierarchy.atomic', { definitionId: 'Affine' }), node('Result','sink.display')], [edge('Scope','Result')]); nested.subsystems = [definition]; boundaries.push(fixture(nested, { Result: [5,5,5] }, ['discrete','continuous']));
export const M14_INDEPENDENT_BOUNDARY_FIXTURES = boundaries;

const failures: M14IndependentFailureFixture[] = [];
const badAffine = affine('m14-failure-affine-overflow',2,0,Number.MAX_VALUE); failures.push({ name: badAffine.name, model: badAffine, code: 'M14_ADAPTER_NONFINITE', phase: 'runtime', sourceIds: [], expectedPartial: { samples: 0, finalState: {} } });
const badAccum = accumulator('m14-failure-accumulator-overflow','rising',1,2,Number.MAX_VALUE); failures.push({ name: badAccum.name, model: badAccum, code: 'M14_ADAPTER_NONFINITE', phase: 'runtime', sourceIds: [], expectedPartial: { samples: 1, finalState: { Block: 1 }, stateMemory: { Block: accumulatorMemory(1,0,1) }, adapterLifecycle: lifecycle('failed') } });
const cap = dynamicEntity('m14-failure-entity-late-capacity',{capacity:1,maxRelease:1,overflow:'error'},2,1); failures.push({ name: cap.name, model: cap, code: 'M14_ENTITY_CAPACITY', phase: 'runtime', sourceIds: [], expectedPartial: { samples: 1, finalState: { Block: messages(), Input: messages(item(0,7,0)) }, stateMemory: { Block: entityMemory([queueItem(item(0,7,0),2,1,1)],[{producer:'Sender',sequence:0}],1), Input: {sequence:1} } } });
const negative = entity('m14-failure-negative-delay',messages(item(0)),{capacity:2,maxRelease:1}); negative.nodes.find(value=>value.id==='Delay')!.blockType='source.step'; negative.nodes.find(value=>value.id==='Delay')!.parameters={stepTime:.5,before:1,after:-1}; failures.push({name:negative.name,model:negative,code:'M14_ENTITY_DELAY',phase:'runtime',sourceIds:[],expectedPartial:{samples:1,finalState:{Block:messages()},stateMemory:{Block:entityMemory([queueItem(item(0),1,1,1)],[{producer:'Sender',sequence:0}],1)}}});
for (const value of [true,[1,2],{kind:'typed',dtype:'float64',shape:[],data:[2]}] as SignalValue[]) { const model=affine(`m14-failure-abi-${failures.length}`); model.nodes[0]!.blockType='source.signal'; model.nodes[0]!.parameters.value=value; failures.push({name:model.name,model,code:'M14_ABI_SCALAR_REQUIRED',phase:'compile',sourceIds:[]}); }
const injected=affine('m14-failure-user-bytes'); injected.nodes[1]!.parameters.moduleBytes=[0,97,115,109]; failures.push({name:injected.name,model:injected,code:'INVALID_PARAMETERS',phase:'compile',sourceIds:[]});
for(const type of ['adapter.wasm-accumulator','adapter.entity-transport']) { const body=type.endsWith('transport')?entity(`m14-failure-nested-${type.replaceAll('.','-')}`):accumulator(`m14-failure-nested-${type.replaceAll('.','-')}`), output=body.nodes.find(value=>value.id==='Result')!; output.blockType='io.output'; const model=graph(body.name,[node('Scope','hierarchy.atomic',{definitionId:'Stateful'}),node('Result','sink.display')],[edge('Scope','Result')]); model.subsystems=[{id:'Stateful',version:1,name:'Stateful',nodes:body.nodes,edges:body.edges,inputs:[],outputs:[{id:'out',nodeId:output.id}],layout:{}}]; failures.push({name:model.name,model,code:'M14_STATEFUL_ROOT_ONLY',phase:'compile',sourceIds:[]}); }
for(const id of ['entity-transport-delay','c-caller','c-function','interpreted-matlab-function','level-2-matlab-s-function','matlab-system','s-function','s-function-builder']) { const model=affine(`m14-failure-native-${id}`); model.nodes[1]!.blockType=`native.${id}`; failures.push({name:model.name,model,code:'M14_NATIVE_ENVIRONMENT_UNAVAILABLE',phase:'compile',sourceIds:[]}); }
export const M14_INDEPENDENT_FAILURE_FIXTURES = failures;
