import { describe, expect, it } from 'vitest';
import { compileModel } from '../packages/compiler/src';
import { runModel } from '../packages/runtime/src';
import { parseModel, validateDataset } from '../packages/model/src';
import { createInteropArchive, inspectInteropArchive, inspectNativeImport, matVariableDataset, NATIVE_IMPORT_LIMITS, originalNativeFile } from '../packages/interop/src';
import { inflateBounded, parseNativeXml, readNativeZip } from '../packages/interop/src/bounded-format';
import { compressedMatFixture, matFixture, mixedExpandedMatFixture, mdlFixture, slxFixture, storedZip, type FixtureBlock } from './fixtures/m15-native';

describe('M15 selected native model conversion', () => {
  for (const [format, fixture] of [['mdl', mdlFixture], ['slx', slxFixture]] as const) {
    it(`${format} scalar Constant/Gain/Scope executes actual analytic 6`, async () => { const value = await inspectNativeImport(fixture(), `fixture.${format}`); expect(value.report).toMatchObject({ parse: 'passed', graphCompile: 'passed', execution: 'supported', numericalEquivalence: 'unverified', convertedBlocks: 3 }); const result = await runModel(compileModel(value.model!)); expect(result.samples[0].values.Native3).toBe(6); expect(value.model!.nodes.map(node => node.blockType)).toEqual(['source.constant', 'math.gain', 'sink.scope']); });
    it(`${format} signed Sum and Product map ordered inputs and branch fanout`, async () => { const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '2' } }, { id: '2', type: 'Constant', parameters: { Value: '4' } }, { id: '3', type: 'Sum', parameters: { Inputs: '|+-' } }, { id: '4', type: 'Product', parameters: { Inputs: '**' } }, { id: '5', type: 'Outport' }, { id: '6', type: 'Scope' }], wires = [{ source: '1', target: '3' }, { source: '2', target: '3', targetPort: 2 }, { source: '1', target: '4' }, { source: '2', target: '4', targetPort: 2 }, { source: '3', target: '5' }, { source: '4', target: '6' }]; const value = await inspectNativeImport(fixture(blocks, wires), `fixture.${format}`); expect(value.report.execution).toBe('supported'); const result = await runModel(compileModel(value.model!)); expect(result.samples[0].values).toMatchObject({ Native5: -2, Native6: 8 }); });
    it(`${format} Unit Delay commits once per due sample`, async () => { const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '1' } }, { id: '2', type: 'UnitDelay', parameters: { InitialCondition: '0', SampleTime: '.25' } }, { id: '3', type: 'Scope' }]; const value = await inspectNativeImport(fixture(blocks), `fixture.${format}`); expect(value.report.execution).toBe('supported'); const result = await runModel(compileModel(value.model!)); expect(result.samples.map(sample => sample.values.Native3)).toEqual([0, 1, 1, 1, 1]); });
    it(`${format} Integrator uses explicit ode4 selected solver with analytic trajectory`, async () => { const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '2' } }, { id: '2', type: 'Integrator', parameters: { InitialCondition: '1' } }, { id: '3', type: 'Scope' }]; const value = await inspectNativeImport(fixture(blocks), `fixture.${format}`); expect(value.report.execution).toBe('supported'); const result = await runModel(compileModel(value.model!)); expect(result.samples.map(sample => sample.values.Native3)).toEqual([1, 1.5, 2, 2.5, 3]); });
    it(`${format} Inport cannot silently become zero and requires explicit user binding`, async () => { const blocks: FixtureBlock[] = [{ id: '1', type: 'Inport' }, { id: '2', type: 'Gain', parameters: { Gain: '3' } }, { id: '3', type: 'Outport' }], bytes = fixture(blocks), blocked = await inspectNativeImport(bytes, `fixture.${format}`); expect(blocked.model).toBeUndefined(); expect(blocked.report.execution).toBe('unsupported'); expect(blocked.report.issues.some(issue => issue.code === 'NATIVE_INPORT_REQUIRED')).toBe(true); const value = await inspectNativeImport(bytes, `fixture.${format}`, { inports: { '1': 2 } }); expect(value.report.execution).toBe('supported'); expect((await runModel(compileModel(value.model!))).samples[0].values.Native3).toBe(6); });
    it(`${format} unknown options/expressions stay located and inert`, async () => { const blocks: FixtureBlock[] = [{ id: '1', type: 'Constant', parameters: { Value: '2', InitFcn: '<script>alert(1)</script>', UnknownNativeOption: 'native-setting' } }, { id: '2', type: 'Gain', parameters: { Gain: 'K' } }, { id: '3', type: 'Scope' }]; const value = await inspectNativeImport(fixture(blocks), `fixture.${format}`); expect(value.report.parse).toBe('passed'); expect(value.model).toBeUndefined(); expect(value.report.issues.filter(issue => issue.parameter === 'InitFcn' || issue.parameter === 'UnknownNativeOption')).toHaveLength(2); expect(value.report.issues.find(issue => issue.parameter === 'InitFcn')!.original).toBe('<script>alert(1)</script>'); expect(value.report.issues.every(issue => issue.location.offset >= 0)).toBe(true); });
  }
  it('SLX root System part references resolve only inside the bounded archive', async () => { const value = await inspectNativeImport(slxFixture(undefined, undefined, {}, true), 'fixture.slx'); expect(value.report.execution).toBe('supported'); expect(value.model?.nodes).toHaveLength(3); });
  it('SLX Ref stubs cannot discard inline callback, blocks, text or unrecognized attributes', async () => { const parts = await readNativeZip(slxFixture(undefined, undefined, {}, true)); const document = new TextDecoder().decode(parts.get('simulink/blockdiagram.xml')); const mixed = document.replace('<System Ref="system_root"/>', '<System Ref="system_root" UnknownFlag="on">inline text<P Name="InitFcn">native_callback()</P><Block BlockType="Constant" SID="90" Name="override"><P Name="Value">99</P></Block></System>'); const bytes = storedZip({ ...Object.fromEntries(parts), 'simulink/blockdiagram.xml': mixed }), value = await inspectNativeImport(bytes, 'mixed.slx'); expect(value.report.parse).toBe('passed'); expect(value.report.execution).toBe('unsupported'); expect(value.model).toBeUndefined(); expect(value.report.issues.find(issue => issue.parameter === 'InitFcn')).toMatchObject({ original: 'native_callback()', location: { member: 'simulink/blockdiagram.xml' } }); expect(value.report.issues.map(issue => issue.code)).toEqual(expect.arrayContaining(['SLX_REFERENCE_CONTENT_UNSUPPORTED', 'SLX_REFERENCE_ATTRIBUTE_UNSUPPORTED'])); const restored = await inspectInteropArchive(await createInteropArchive(value)); expect(restored.inspection.sourceBytes).toEqual(bytes); expect(restored.inspection.model).toBeUndefined(); });
  it('unsupported native blocks and variable-step solvers do not become runnable approximations', async () => { const value = await inspectNativeImport(mdlFixture([{ id: '1', type: 'S-Function' }, { id: '2', type: 'Scope' }], [{ source: '1', target: '2' }], { SolverType: 'Variable-step', Solver: 'ode45' }), 'unsupported.mdl'); expect(value.report.parse).toBe('passed'); expect(value.report.execution).toBe('unsupported'); expect(value.report.issues.map(issue => issue.code)).toContain('NATIVE_BLOCK_UNSUPPORTED'); expect(value.model).toBeUndefined(); });
});
describe('M15 MAT selected data profile', () => {
  for (const little of [true, false]) it(`dense column-major doubles preserve first-column time with endian ${little}`, async () => { const rows = [[0, 1, -3], [.5, 2, 0], [1, 3, 9]], value = await inspectNativeImport(matFixture('x', rows, little, 6, true), 'signals.mat'); expect(value.report.parse).toBe('passed'); expect(value.variables[0].rows).toEqual(rows); const dataset = matVariableDataset(value, 'x'); expect(validateDataset(dataset).rows).toEqual(rows); expect(dataset.provenance).toMatchObject({ format: 'mat-v5', sourceHash: value.sourceHash }); expect(dataset.columns.map(column => column.unit)).toEqual(['s', '1', '1']); });
  it('compressed miMATRIX is actually inflated and preserves values', async () => { const value = await inspectNativeImport(await compressedMatFixture(), 'compressed.mat'); expect(value.variables[0].rows).toEqual([[0, 1], [.5, 2], [1, 3]]); });
  it('the expanded MAT budget includes raw and compressed matrix bytes together', async () => { const bytes = await mixedExpandedMatFixture(); expect(bytes.length).toBeLessThan(NATIVE_IMPORT_LIMITS.maxInputBytes); const result = await inspectNativeImport(bytes, 'mixed.mat'); expect(result.report.parse).toBe('failed'); expect(result.report.issues[0].code).toBe('NATIVE_EXPANSION_LIMIT'); });
  it('MAT signed zero is explicit unsupported while original negative-zero bytes survive archive restore', async () => { const bytes = matFixture('signed', [[0, -0], [1, 2]]), inspected = await inspectNativeImport(bytes, 'signed.mat'); expect(inspected.variables[0].supported).toBe(false); expect(inspected.variables[0].reason).toContain('signed zero'); expect(() => matVariableDataset(inspected, 'signed')).toThrow(); const restored = await inspectInteropArchive(await createInteropArchive(inspected)); expect(restored.inspection.sourceBytes).toEqual(bytes); expect(restored.inspection.variables[0].supported).toBe(false); });
  for (const [name, rows, flags] of [['complex', [[0, 1], [1, 2]], 0x806], ['nonfinite', [[0, NaN], [1, 2]], 6], ['nonmonotonic', [[1, 1], [0, 2]], 6]] as const) it(`unsupported ${name} is reported, not coerced`, async () => { const value = await inspectNativeImport(matFixture(name, rows.map(row => [...row]), true, flags), 'unsupported.mat'); expect(value.report.parse).toBe('passed'); expect(value.variables[0].supported).toBe(false); expect(() => matVariableDataset(value, name)).toThrow(); });
  it('malformed tag, unsupported HDF5 and truncated header fail separately from graph compile', async () => { const corrupt = matFixture(); new DataView(corrupt.buffer).setUint32(132, 0xffffffff, true); for (const bytes of [corrupt, new TextEncoder().encode('\u0089HDF\r\n'), new Uint8Array(127)]) { const value = await inspectNativeImport(bytes, 'bad.mat'); expect(value.report.parse).toBe('failed'); expect(value.report.graphCompile).toBe('not-applicable'); } });
});
describe('M15 exact original archive and hostile boundary', () => {
  it('model archive reparses original and verifies report, model hashes and byte-exact original', async () => { const input = mdlFixture(), inspected = await inspectNativeImport(input, 'fixture.mdl'), text = await createInteropArchive(inspected), restored = await inspectInteropArchive(text); expect(originalNativeFile(restored.inspection)).toEqual(input); expect(restored.inspection.model).toEqual(inspected.model); expect(parseModel(restored.inspection.model).nodes).toHaveLength(3); expect(JSON.parse(text).source.sha256).toBe(inspected.sourceHash); });
  it('MAT archive preserves raw bytes and selected variable dataset through reimport', async () => { const input = await compressedMatFixture(), inspected = await inspectNativeImport(input, 'signals.mat'), restored = await inspectInteropArchive(await createInteropArchive(inspected, 'signal')); expect(restored.dataset?.rows).toEqual([[0, 1], [.5, 2], [1, 3]]); expect(restored.dataset?.provenance?.format).toBe('mat-v5'); expect(restored.inspection.sourceBytes).toEqual(input); });
  for (const field of ['source', 'report', 'model', 'hash', 'extra']) it(`archive rejects forged ${field} claims`, async () => { const value = JSON.parse(await createInteropArchive(await inspectNativeImport(mdlFixture(), 'fixture.mdl'))); if (field === 'source') value.source.bytes = value.source.bytes.replace(/^./, 'A'); if (field === 'report') value.report.numericalEquivalence = 'verified'; if (field === 'model') value.convertedModel.nodes[0].parameters.value = 999; if (field === 'hash') value.convertedModelHash = '0'.repeat(64); if (field === 'extra') value.runCallback = 'alert(1)'; await expect(inspectInteropArchive(JSON.stringify(value))).rejects.toThrow(); });
  it('unsupported callbacks can be byte-preserved but never turned into an executable archive model', async () => { const bytes = mdlFixture(undefined, undefined, { InitFcn: 'system("touch file")' }), value = await inspectNativeImport(bytes, 'callback.mdl'), restored = await inspectInteropArchive(await createInteropArchive(value)); expect(restored.inspection.sourceBytes).toEqual(bytes); expect(restored.inspection.model).toBeUndefined(); expect(restored.inspection.report.issues.some(issue => issue.parameter === 'InitFcn')).toBe(true); });
  it('bounded parsers reject unsafe ZIP paths, corrupt CRC and external XML entities', async () => { await expect(readNativeZip(storedZip({ '../unsafe.xml': 'x' }))).rejects.toThrow(); const corrupted = storedZip({ 'safe.xml': '<Root/>' }); corrupted[30 + 'safe.xml'.length] ^= 1; await expect(readNativeZip(corrupted)).rejects.toThrow(); expect(() => parseNativeXml('<!DOCTYPE x [<!ENTITY e SYSTEM "https://evil.test/x">]><x>&e;</x>', 'a.xml')).toThrow(); expect(() => parseNativeXml('<x>&unknown;</x>', 'a.xml')).toThrow(); });
  it('external OPC relationships are inert unsupported information', async () => { const bytes = slxFixture(undefined, undefined, { '_rels/.rels': '<Relationships><Relationship Id="x" TargetMode="External" Target="https://evil.test/model.slx"/></Relationships>' }), value = await inspectNativeImport(bytes, 'external.slx'); expect(value.report.parse).toBe('passed'); expect(value.report.execution).toBe('unsupported'); expect(value.report.issues.find(issue => issue.code === 'SLX_EXTERNAL_REFERENCE')?.original).toBe('https://evil.test/model.slx'); });
  it('quote-aware XML preserves harmless > and escaped script text', () => { const tree = parseNativeXml('<x label="a > b"><p>&lt;script&gt;alert(1)&lt;/script&gt;</p></x>', 'a.xml'); expect(tree.attrs.label).toBe('a > b'); expect(tree.children[0].text).toBe('<script>alert(1)</script>'); });
  it('malformed/deep MDL/XML and overbudget inputs cannot consume unbounded parsing', async () => { for (const text of ['Model { Name "unterminated', 'Model {\nSystem {\n', `Model {\n${'X {\n'.repeat(35)}${'}\n'.repeat(36)}`]) expect((await inspectNativeImport(new TextEncoder().encode(text), 'bad.mdl')).report.parse).toBe('failed'); expect(() => parseNativeXml('<x>'.repeat(34) + '</x>'.repeat(34), 'a.xml')).toThrow(); await expect(inspectNativeImport(new Uint8Array(NATIVE_IMPORT_LIMITS.maxInputBytes + 1), 'big.mdl')).rejects.toThrow(); const compressed = new Uint8Array(await new Response(new Blob([new Uint8Array(4096)]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer()); await expect(inflateBounded(compressed, 'deflate', 100)).rejects.toThrow(); });
  it('Inport options do not invoke accessors', async () => { let called = false; const options = Object.defineProperty({}, 'inports', { get() { called = true; return {}; }, enumerable: true }); await expect(inspectNativeImport(mdlFixture(), 'safe.mdl', options)).rejects.toThrow(); expect(called).toBe(false); });
  it('unknown ConfigSet, System and Line parameters preserve their original member and value', async () => { const value = await inspectNativeImport(slxFixture(undefined, undefined, { 'simulink/configSet0.xml': '<ConfigSet><P Name="InitFcn">native_callback()</P></ConfigSet>' }), 'config.slx'); expect(value.report.execution).toBe('unsupported'); expect(value.report.issues.find(issue => issue.parameter === 'InitFcn')).toMatchObject({ original: 'native_callback()', location: { member: 'simulink/configSet0.xml', line: 1 } }); });
  it('unused input bindings and unconverted auxiliary systems are not silently accepted', async () => { const value = await inspectNativeImport(slxFixture(undefined, undefined, { 'simulink/systems/system_unused.xml': '<System><Block BlockType="S-Function" Name="native" SID="99"/></System>' }), 'aux.slx', { inports: { ghost: 1 } }); expect(value.report.execution).toBe('unsupported'); expect(value.report.issues.map(issue => issue.code)).toEqual(expect.arrayContaining(['SLX_UNUSED_SYSTEM', 'NATIVE_INPUT_UNUSED'])); });
  it('native declared port counts are verified instead of silently dropping extra ports', async () => { const value = await inspectNativeImport(slxFixture([{ id: '1', type: 'Constant', parameters: { Value: '2', Ports: '[0, 1]' } }, { id: '2', type: 'Gain', parameters: { Gain: '3', Ports: '[1, 2]' } }, { id: '3', type: 'Scope' }]), 'ports.slx'); expect(value.report.execution).toBe('unsupported'); expect(value.report.issues.some(issue => issue.code === 'NATIVE_PORT_LAYOUT')).toBe(true); });
  it('long valid original names keep their extension and remain reimportable without truncation', async () => { const filename = 'original-'.repeat(20) + '.mdl', value = await inspectNativeImport(mdlFixture(), filename), restored = await inspectInteropArchive(await createInteropArchive(value)); expect(restored.inspection.filename).toBe(filename); expect(restored.inspection.sourceBytes).toEqual(value.sourceBytes); });
  it('native scalar negative zero and user Inport negative zero cannot be silently serialized as positive zero', async () => { const value = await inspectNativeImport(mdlFixture([{ id: '1', type: 'Constant', parameters: { Value: '-0' } }, { id: '2', type: 'Gain', parameters: { Gain: '3' } }, { id: '3', type: 'Scope' }]), 'zero.mdl'); expect(value.model).toBeUndefined(); expect(value.report.issues.find(issue => issue.code === 'NATIVE_SIGNED_ZERO_UNSUPPORTED')).toMatchObject({ parameter: 'Value', original: '-0' }); await expect(inspectNativeImport(mdlFixture(), 'input.mdl', { inports: { '1': -0 } })).rejects.toThrow('signed zero'); });
  it('all successfully mapped blocks, parameters and connections retain source locations verified on archive restore', async () => { const value = await inspectNativeImport(slxFixture(), 'location.slx'); expect(value.locations.filter(origin => origin.kind === 'block')).toHaveLength(3); expect(value.locations.filter(origin => origin.kind === 'connection')).toHaveLength(2); expect(value.locations[1]).toMatchObject({ nativeId: '2', convertedId: 'Native2', parameters: [{ name: 'Gain', location: { member: 'simulink/blockdiagram.xml' } }] }); const archive = JSON.parse(await createInteropArchive(value)); archive.locations[1].convertedId = 'Native999'; await expect(inspectInteropArchive(JSON.stringify(archive))).rejects.toThrow('위치'); });
});
