import type { CalcModel, SignalValue } from '../packages/model/src';

export interface M8Fixture { name: string; id: string; inputs: Record<string, SignalValue>; parameters: Record<string, unknown>; expected: Record<string, SignalValue> }
const fixture = (id: string, inputs: M8Fixture['inputs'], expected: SignalValue, parameters: Record<string, unknown> = {}, name = id): M8Fixture => ({ name, id, inputs, parameters, expected: { out: expected } });
const unary = (id: string, input: SignalValue, expected: SignalValue, parameters: Record<string, unknown> = {}, name = id) => fixture(id, { in: input }, expected, parameters, name);

/** Literal hand calculations and analytic identities; no runtime/compiler helpers generate the oracle. */
export const M8_FIXTURES: readonly M8Fixture[] = [
  unary('nonlinear.friction', [-2, 0, 3], [-7, 0, 10], { gain: 3, offset: 1 }),
  fixture('nonlinear.dead-zone-dynamic', { in: [-3, -1, 0, 2, 4], lower: -1, upper: 2 }, [-2, 0, 0, 0, 2]),
  fixture('nonlinear.saturation-dynamic', { in: [-3, 0, 4], lower: [-2, -1, 1], upper: [0, 2, 3] }, [-2, 0, 3]),
  unary('nonlinear.wrap-to-zero', [-1, 1, 2], [-1, 1, 0], { threshold: 1, comparator: 'gt' }),
  unary('nonlinear.wrap-to-zero', [-1, 1, 2], [-1, 0, 0], { threshold: 1, comparator: 'ge' }, 'wrap-inclusive-equality'),
  unary('logic.compare-constant', [-1, 0, 1], [false, true, true], { operator: 'gte', constant: 0 }),
  fixture('logic.interval-dynamic', { in: [0, 1, 2], lower: 0, upper: 2 }, [false, true, false], { lowerClosed: 'open', upperClosed: 'open' }),
  unary('logic.truth-table', [true, false], true, { table: [false, false, true, false] }),
  unary('logic.truth-table', [false, true], false, { table: [false, false, true, false] }, 'truth-table-first-bit-is-MSB'),
  unary('math.signed-sqrt', [-9, 0, 16], [-3, 0, 4]),
  unary('math.reciprocal-sqrt', [1, 4, 16], [1, .5, .25]),
  unary('math.negate', [[-1, 2], [3, -4]], [[1, -2], [-3, 4]]),
  unary('math.sine-wave-function', [0, Math.PI / 2, Math.PI], [1, 3, 1], { amplitude: 2, frequency: 1, phase: 0, bias: 1 }),
  unary('math.increment', [-1, 0, .5, 3], [0, 0, 0, 2], { delta: -1, clamp: 'zero' }),
  fixture('matrix.assign', { in: [[1, 2], [3, 4]], value: [20, 30] }, [[1, 20], [30, 4]], { indices: [1, 2] }),
  fixture('matrix.assign', { in: [true, false, false], value: true }, [true, true, true], { indices: [1, 2] }, 'assignment-boolean-storage'),
  { name: 'matrix.find-nonzero', id: 'matrix.find-nonzero', inputs: { in: [[0, 5], [4, 0]] }, parameters: { indexBase: 0 }, expected: { indices: [1, 2, -1, -1], rows: [1, 0, -1, -1], columns: [0, 1, -1, -1], count: 2 } },
  { name: 'find-nonzero-empty-padded-independent-alternative', id: 'matrix.find-nonzero', inputs: { in: [0, 0] }, parameters: { indexBase: 1 }, expected: { indices: [0, 0], rows: [0, 0], columns: [0, 0], count: 0 } },
  { name: 'find-nonzero-scalar-and-boolean', id: 'matrix.find-nonzero', inputs: { in: true }, parameters: { indexBase: 1 }, expected: { indices: [1], rows: [1], columns: [1], count: 1 } },
  unary('matrix.permute-dimensions', [[1, 2, 3], [4, 5, 6]], [[1, 4], [2, 5], [3, 6]], { order: [1, 0] }),
  unary('matrix.squeeze', [[1], [2], [3]], [[1], [2], [3]]),
  unary('matrix.squeeze', [[5]], [[5]], {}, 'squeeze-rank-two-singletons-are-preserved'),
  fixture('matrix.expand-scalar', {}, [[7, 7], [7, 7]], { value: 7, form: 'matrix', rows: 2, columns: 2 }),
  unary('matrix.is-symmetric', [[1, 2], [2, 3]], true),
  unary('matrix.is-symmetric', [[1, 2], [3, 4]], false, {}, 'symmetry-is-structural'),
  unary('matrix.is-triangular', [[1, 2], [0, 3]], true, { part: 'upper', tolerance: 0 }),
  unary('matrix.is-triangular', [[1, 2], [3, 4]], false, { part: 'either', tolerance: 0 }, 'neither-triangle'),
  unary('matrix.square', [[1, 2], [3, 4]], [[10, 14], [14, 20]]),
  unary('matrix.square', [[1, 2, 3], [4, 5, 6]], [[17, 22, 27], [22, 29, 36], [27, 36, 45]], {}, 'rectangular-matrix-square-is-Gram'),
  unary('matrix.square', [1, 2, 3], [[14]], {}, 'unoriented-vector-square-is-column-Gram'),
  unary('matrix.permute-rows-cols', [[1, 2, 3], [4, 5, 6]], [[6, 4, 5], [3, 1, 2]], { rows: [1, 0], columns: [2, 0, 1] }),
  fixture('route.manual-switch', { a: [1, 2], b: [3, 4] }, [3, 4], { selected: 2 }),
  fixture('route.multiport-switch', { index: 2, in1: 10, in2: 20, in3: 30 }, 30, { count: 3, indexBase: 0 }),
  fixture('route.multiport-switch', { index: 5, in1: false, in2: true }, true, { count: 2, indexBase: 1, outside: 'clamp' }, 'multiport-clamps-to-last-boolean-input'),
  unary('verify.assert', [true, true], true, { mode: 'all' }),
  unary('verify.assert', [false, true], true, { mode: 'any' }, 'assert-any'),
  unary('verify.bounds', [0, .5, 1], [true, true, true], { source: 'static', kind: 'range', lower: 0, upper: 1 }),
  fixture('verify.bounds', { in: [-1, 3], lower: 0, upper: 2 }, [true, true], { source: 'dynamic', kind: 'gap' }, 'dynamic-gap-complement'),
  fixture('verify.bounds', { in: [1, 2], lower: [0, 1] }, [true, true], { source: 'dynamic', kind: 'lower' }, 'dynamic-lower-only-port'),
  unary('lookup.direct', [1, 0, 1], 5, { dimensions: [2, 2, 2], table: [0, 1, 2, 3, 4, 5, 6, 7], indexBase: 0 }),
  unary('lookup.direct', [3, 0], 20, { dimensions: [2, 2], table: [10, 11, 20, 21], indexBase: 1, outside: 'clamp' }, 'direct-lookup-index-base-and-clamp'),
  fixture('lookup.interpolate-prelookup', { index: 1, fraction: .25 }, 12.5, { table: [0, 10, 20] }),
  fixture('lookup.interpolate-prelookup', { index: 0, fraction: .5 }, 0, { table: [0, 10], interpolation: 'nearest' }, 'nearest-half-chooses-lower'),
  fixture('lookup.dynamic', { in: 1.5, breakpoints: [0, 1, 2], table: [0, 10, 30] }, 20),
  fixture('lookup.dynamic', { in: 3, breakpoints: [0, 1, 2], table: [0, 10, 30] }, 50, { outside: 'extrapolate' }, 'dynamic-linear-extrapolation'),
  unary('lookup.nd', [.5, .25, .75], 78, { rank: 3, axis1: [0, 1], axis2: [0, 1], axis3: [0, 1], table: [0, 100, 10, 110, 1, 101, 11, 111] }),
  unary('lookup.nd', [1, 1, 1, 1], 15, { rank: 4, table: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] }, 'rank-four-exact-corner'),
  unary('lookup.nd', 3, 7, { rank: 1, axis1: [0, 1], table: [7, 7], outside: 'extrapolate' }, 'constant-table-extrapolation'),
  unary('lookup.nd', [.5, .5], 15, { rank: 2, table: [0, 10, 20, 30] }, 'rank-two-center'),
  unary('lookup.nd', 2, 20, { rank: 1, axis1: [0, 1], table: [0, 10], outside: 'extrapolate' }, 'rank-one-extrapolation'),
  unary('lookup.nd', [.5, .5], 0, { rank: 2, table: [0, 10, 20, 30], interpolation: 'nearest' }, 'ND-nearest-half-lower'),
  unary('lookup.nd', [1, .5], 20, { rank: 2, table: [0, 10, 20, 30], interpolation: 'previous' }, 'ND-flat-exact-upper-axis'),
  unary('lookup.nd', [-1, 2], 10, { rank: 2, table: [0, 10, 20, 30], outside: 'clamp' }, 'ND-clamp-all-axes'),
  unary('lookup.nd', Array(10).fill(.5), 511.5, { rank: 10, table: Array.from({ length: 1024 }, (_, index) => index) }, 'maximum-bounded-rank-ten-center'),
  unary('lookup.direct', Array(10).fill(1), 1023, { dimensions: Array(10).fill(2), table: Array.from({ length: 1024 }, (_, index) => index) }, 'maximum-bounded-direct-rank-ten-corner'),
  unary('math.gain-matrix', [1, 2], [5, 11], { K: [[1, 2], [3, 4]], mode: 'left' }),
  unary('math.gain-matrix', [[1, 2]], [[7, 10]], { K: [[1, 2], [3, 4]], mode: 'right' }, 'right-matrix-gain'),
  unary('math.gain-matrix', [[1, 2], [3, 4]], [[2, 6], [12, 20]], { K: [[2, 3], [4, 5]], mode: 'elementwise' }, 'elementwise-parameter-matrix-gain'),
  fixture('math.sum-inputs', { in1: [1, 2], in2: 3, in3: [4, 5] }, [2, 4], { count: 3, signs: [1, -1, 1] }),
  fixture('math.product-inputs', { in1: [12, 18], in2: 3, in3: [2, 3] }, [8, 18], { count: 3, operations: '*/*', mode: 'elementwise' }),
  fixture('math.product-inputs', { in1: [2, 4] }, [.5, .25], { count: 1, operations: '/', mode: 'elementwise' }, 'single-reciprocal-product'),
  fixture('math.product-inputs', { in1: [[1, 2]], in2: [[3], [4]] }, [[11]], { count: 2, operations: '**', mode: 'matrix' }, 'multiple-input-matrix-product'),
  fixture('logic.combine', { in1: [0, 2], in2: [true, true], in3: true }, [true, false], { count: 3, operation: 'nand' }),
  fixture('logic.combine', { in1: [false, true], in2: false }, [true, false], { count: 2, operation: 'nor' }, 'numeric-truth-nor'),
  fixture('logic.combine', { in1: [true, false], in2: true }, [true, false], { count: 2, operation: 'xnor' }, 'numeric-truth-xnor'),
  fixture('logic.combine', { in1: [0, 1] }, [true, false], { count: 1, operation: 'not' }, 'numeric-truth-not'),
  fixture('route.switch-threshold', { condition: [-1, 0, 1], a: [10, 20, 30], b: 0 }, [0, 20, 30], { criterion: 'ge', threshold: 0 }),
  fixture('route.switch-threshold', { condition: [false, true], a: true, b: false }, [false, true], { criterion: 'ne', threshold: 0 }, 'elementwise-boolean-switch'),
  fixture('vector.select-dynamic', { in: [10, 20, 30], indices: [3, 1, 3] }, [30, 10, 30], { indexBase: 1 }),
  fixture('vector.select-dynamic', { in: [true, false], indices: 1 }, false, { indexBase: 0 }, 'dynamic-scalar-boolean-selector'),
  fixture('matrix.select-dynamic', { in: [[1, 2], [3, 4]], rows: [1, 0], columns: 1 }, [[4], [2]], { indexBase: 0 }),
  fixture('route.mux-inputs', { in1: [true, false], in2: true, in3: false }, [true, false, true, false], { count: 3 }),
  { name: 'route.demux-widths', id: 'route.demux-widths', inputs: { in: [1, 2, 3, 4] }, parameters: { widths: [1, 2, 1] }, expected: { out1: 1, out2: [2, 3], out3: 4 } },
  fixture('math.concatenate-inputs', { in1: [[1], [2]], in2: [[3, 4], [5, 6]], in3: [[7], [8]] }, [[1, 3, 4, 7], [2, 5, 6, 8]], { count: 3, axis: 1 }),
  fixture('math.concatenate-inputs', { in1: [[1, 2]], in2: [[3, 4]], in3: [[5, 6]] }, [[1, 2], [3, 4], [5, 6]], { count: 3, axis: 0 }, 'concatenate-rows'),
  fixture('math.concatenate-inputs', { in1: [1, 2], in2: 3, in3: [4, 5] }, [1, 2, 3, 4, 5], { count: 3, axis: 0 }, 'concatenate-vectors-and-scalars'),
  unary('matrix.reshape-column-major', [1, 2, 3, 4], [[1, 3], [2, 4]], { form: 'matrix', rows: 2, columns: 2 }),
  unary('matrix.reshape-column-major', [[1, 2], [3, 4]], [1, 3, 2, 4], { form: 'vector', length: 4 }, 'column-major-read-order'),
  unary('reduce.axis', [[1, 2, 3], [4, 5, 6]], [5, 7, 9], { operation: 'sum', axis: 'rows' }),
  unary('reduce.axis', [[1, 2, 3], [4, 5, 6]], [2, 5], { operation: 'mean', axis: 'columns' }, 'reduce-mean-over-columns'),
  unary('reduce.axis', [[true, false], [true, true]], [true, false], { operation: 'all', axis: 'rows' }, 'reduce-boolean-axis'),
  unary('reduce.axis', [2, 3, 4], 24, { operation: 'product', axis: 'all' }, 'reduce-product-entire-vector'),
  unary('reduce.axis', [Number.MAX_VALUE, Number.MAX_VALUE], Number.MAX_VALUE, { operation: 'mean', axis: 'all' }, 'mean-does-not-overflow-for-finite-answer'),
  unary('math.gain-matrix', [[1, 2], [3, 4]], [[3, 6], [9, 12]], { K: 3, mode: 'left' }, 'scalar-K-in-matrix-gain'),
  unary('math.gain-matrix', 2, [[2, 4], [6, 8]], { K: [[1, 2], [3, 4]], mode: 'right' }, 'scalar-input-in-matrix-gain'),
  fixture('math.product-inputs', { in1: 2, in2: [[1, 2], [3, 4]], in3: .5 }, [[1, 2], [3, 4]], { count: 3, operations: '***', mode: 'matrix' }, 'scalar-matrix-scalar-product'),
  fixture('math.product-inputs', { in1: 3, in2: 4 }, 12, { count: 2, operations: '**', mode: 'matrix' }, 'matrix-mode-scalar-product'),
  fixture('math.sum-inputs', { in1: [-1, 2] }, [1, -2], { count: 1, signs: [-1] }, 'single-negating-sum'),
  ...(['and', 'or', 'xor'] as const).map((operation, index) => fixture('logic.combine', { in1: [true, true, false], in2: [true, false, false] }, [[true, false, false], [true, true, false], [false, true, false]][index]! as boolean[], { count: 2, operation }, `logic-${operation}`)),
  ...(['gt', 'lt', 'lte', 'eq', 'neq'] as const).map((operator, index) => unary('logic.compare-constant', [-1, 0, 1], [[false, false, true], [true, false, false], [true, true, false], [false, true, false], [true, false, true]][index]! as boolean[], { operator, constant: 0 }, `compare-${operator}`)),
  fixture('route.switch-threshold', { condition: [0, 1], a: 7, b: 2 }, [2, 7], { criterion: 'gt', threshold: 0 }, 'switch-condition-expands-scalar-data'),
  fixture('verify.bounds', { in: [-1, 0], upper: 0 }, [true, true], { source: 'dynamic', kind: 'upper' }, 'dynamic-upper-only-port'),
  unary('verify.bounds', [-1, 2], [true, true], { source: 'static', kind: 'gap', lower: 0, upper: 1 }, 'static-gap'),
  unary('verify.bounds', [1, 2], [true, true], { source: 'static', kind: 'lower', lower: 0, lowerClosed: 'open' }, 'static-open-lower'),
  unary('verify.bounds', [-1, 0], [true, true], { source: 'static', kind: 'upper', upper: 1, upperClosed: 'open' }, 'static-open-upper'),
  fixture('verify.bounds', { in: [0, 1], lower: 0, upper: 1 }, [true, true], { source: 'dynamic', kind: 'range' }, 'dynamic-closed-range'),
  unary('matrix.permute-dimensions', [true, false], [true, false], { order: [0] }, 'identity-vector-permutation'),
  unary('matrix.is-triangular', [[1, 0], [2, 3]], true, { part: 'lower' }, 'lower-triangle'),
  unary('matrix.is-triangular', [[1, 2], [.001, 3]], true, { part: 'upper', tolerance: .001 }, 'triangle-explicit-CalcWeave-tolerance'),
  unary('matrix.is-symmetric', [[1, 2], [2.001, 3]], true, { tolerance: .0011 }, 'symmetry-explicit-CalcWeave-tolerance'),
  fixture('matrix.expand-scalar', {}, [2, 2, 2], { value: 2, form: 'vector', length: 3 }, 'expand-source-vector'),
  fixture('lookup.dynamic', { in: .5, breakpoints: [0, 1, 2], table: [0, 10, 30] }, 0, { interpolation: 'nearest' }, 'dynamic-nearest-tie'),
  fixture('lookup.dynamic', { in: 2, breakpoints: [0, 1, 2], table: [0, 10, 30] }, 30, { interpolation: 'previous' }, 'dynamic-flat-exact-last-knot'),
  fixture('lookup.dynamic', { in: -1, breakpoints: [0, 1, 2], table: [0, 10, 30] }, 0, { outside: 'clamp' }, 'dynamic-clamp'),
  fixture('lookup.dynamic', { in: 1022.5, breakpoints: Array.from({ length: 1024 }, (_, index) => index), table: Array.from({ length: 1024 }, (_, index) => 2 * index) }, 2045, {}, 'dynamic-maximum-bounded-axis'),
  fixture('lookup.interpolate-prelookup', { index: 1, fraction: .5 }, 10, { table: [0, 10, 20], interpolation: 'previous' }, 'prelookup-flat'),
  fixture('lookup.interpolate-prelookup', { index: 99, fraction: 2 }, 20, { table: [0, 10, 20], outside: 'clamp' }, 'prelookup-clamp'),
  unary('reduce.axis', [[1, 2], [3, 4]], [1, 2], { operation: 'min', axis: 'rows' }, 'reduce-min-rows'),
  unary('reduce.axis', [[1, 2], [3, 4]], [2, 4], { operation: 'max', axis: 'columns' }, 'reduce-max-columns'),
  unary('reduce.axis', [[false, true], [false, false]], [true, false], { operation: 'any', axis: 'columns' }, 'reduce-any-columns'),
  fixture('lookup.interpolate-prelookup', { index: 0, fraction: .5 }, 2 * Number.MIN_VALUE, { table: [Number.MIN_VALUE, 2 * Number.MIN_VALUE], interpolation: 'linear' }, 'subnormal-midpoint-rounds-to-even'),
  unary('lookup.nd', [1, 2], 1, { rank: 2, axis1: [0, 1], axis2: [0, 1], table: [0, Number.MAX_VALUE, 1, 1], interpolation: 'linear', outside: 'extrapolate' }, 'upper-knot-does-not-evaluate-zero-weight-overflow-branch'),
  unary('matrix.square', Array(33).fill(1), [[33]], {}, 'vector-Gram-does-not-use-matrix-axis-limit'),
  unary('matrix.square', Array(1024).fill(1), [[1024]], {}, 'maximum-bounded-vector-Gram'),
];

export function m8Model(entry: M8Fixture, mode: CalcModel['execution']['mode'] = 'static'): CalcModel {
  const ports = Object.keys(entry.expected);
  return { schemaVersion: 1, modelId: 'm8_fixture', name: entry.name,
    nodes: [...Object.entries(entry.inputs).map(([port, value]) => ({ id: `input_${port}`, blockType: 'source.constant', blockVersion: 1 as const, label: port, parameters: { value: structuredClone(value) } })),
      { id: 'operation', blockType: entry.id, blockVersion: 1, label: entry.name, parameters: structuredClone(entry.parameters) },
      ...ports.map(port => ({ id: `result_${port}`, blockType: 'sink.display', blockVersion: 1 as const, label: port, parameters: {} }))],
    edges: [...Object.keys(entry.inputs).map(port => ({ id: `input_edge_${port}`, source: { nodeId: `input_${port}`, portId: 'out' }, target: { nodeId: 'operation', portId: port } })),
      ...ports.map(port => ({ id: `output_edge_${port}`, source: { nodeId: 'operation', portId: port }, target: { nodeId: `result_${port}`, portId: 'in' } }))],
    execution: { mode, startTime: 0, stopTime: .2, step: .1 }, layout: {},
  };
}

export function m8Expected(entry: M8Fixture): Record<string, SignalValue> { return Object.fromEntries(Object.entries(entry.expected).map(([port, value]) => [`result_${port}`, value])); }
