import { executionLiteral } from './literal';
import type { CompiledModel } from '../../model/src';
import type { ExportManifest } from './manifest';
import { KERNEL_TEMPLATE } from './kernels-template';
import { DISCRETE_TEMPLATE } from './discrete-template';
import { CONTINUOUS_TEMPLATE } from './continuous-template';

/** The browser and export use the same pure integration and event machine. */
export function exportContinuousTypeScript(compiled: CompiledModel, manifest: ExportManifest): string {
  const data = {
    model: { schemaVersion: 1, modelId: '', name: '', nodes: [], edges: [], layout: {}, execution: compiled.model.execution },
    nodes: compiled.nodes.map((node) => ({ ...node,
      parameters: Object.fromEntries(Object.entries(node.parameters).filter(([key]) => node.blockType !== 'math.expression' || key !== 'expression')) })),
    stateIds: compiled.stateIds, outputIds: compiled.outputIds, outputTypes: compiled.outputTypes,
    semanticKey: '', stateElements: compiled.stateElements,
  };
  const literal = executionLiteral;
  return `// Generated by CalcWeave. Standalone RK4/RK45/implicit Euler and bounded hybrid execution.
${CONTINUOUS_TEMPLATE}
${KERNEL_TEMPLATE}
${DISCRETE_TEMPLATE}
const compiled: CompiledModel = ${literal(data)};
const exportManifest = ${literal(manifest)};
export function getManifest(): typeof exportManifest { return JSON.parse(JSON.stringify(exportManifest)) as typeof exportManifest; }
export function run(): Omit<RunResult, 'elapsedMs'> {
  const clock = (globalThis as { performance?: { now(): number } }).performance;
  const now = typeof clock?.now === 'function' ? () => clock.now() : () => Date.now();
  const started = now();
  const execution = createContinuousExecution(compiled, { check: () => {
    if (now() - started > 30000) throw new ModelError([{ code: 'RUNTIME_WALL_BUDGET', message: '실행 시간 한도를 초과했습니다.' }]);
  } });
  while (execution.advance()) { /* bounded solver trials */ }
  const { elapsedMs: _elapsed, ...result } = execution.result('completed');
  return result;
}
`;
}
