// Generated from repository-owned runtime sources by sync-runtime-templates.ts.
export const CONTINUOUS_TEMPLATE = [
  "type ExecutionMode = 'static' | 'discrete' | 'continuous';",
  "type BlockType = 'math.matrix-multiply' | 'matrix.transpose' | 'matrix.determinant' | 'matrix.inverse' | 'matrix.solve' | 'matrix.cholesky' | 'matrix.lu' | 'lookup.2d' | 'lookup.prelookup' | 'fixed.quantize' | 'source.constant' | 'io.input' | 'math.gain' | 'math.sum' | 'math.multiply' | 'sink.display' | 'discrete.unit-delay' | 'continuous.integrator' | 'math.abs' | 'math.function' | 'math.trigonometric' | 'math.round' | 'math.minmax' | 'math.sqrt' | 'logic.compare' | 'logic.boolean' | 'route.switch' | 'nonlinear.saturation' | 'route.mux' | 'route.demux' | 'math.concatenate' | 'matrix.reshape' | 'io.output' | 'io.terminator' | 'math.expression' | 'source.step' | 'source.ramp' | 'source.sine-wave' | 'source.pulse' | 'source.clock' | 'source.digital-clock' | 'source.random' | 'source.repeating-sequence' | 'discrete.delay' | 'discrete.integrator' | 'discrete.difference' | 'discrete.derivative' | 'discrete.fir' | 'discrete.transfer-function' | 'discrete.state-space' | 'logic.edge-detect' | 'time.rate-transition' | 'lookup.interpolated' | 'logic.bitwise' | 'sink.scope' | 'continuous.second-order-integrator' | 'continuous.state-space' | 'continuous.transfer-function' | 'continuous.zero-pole' | 'continuous.pid' | 'continuous.derivative' | 'time.memory' | 'time.zero-order-hold' | 'time.first-order-hold' | 'time.transport-delay' | 'logic.hit-crossing' | 'nonlinear.relay' | 'source.dataset' | 'unit.convert' | 'route.bus-create' | 'route.bus-select' | 'hierarchy.subsystem' | 'annotation.note' | 'annotation.model-info';",
  "type SignalValue = number | boolean | number[] | boolean[] | number[][] | boolean[][];",
  "type StateValue = number | boolean | string | null | StateValue[] | {",
  "    [key: string]: StateValue;",
  "};",
  "interface SampleTime {",
  "    period: number;",
  "    offset: number;",
  "}",
  "interface SignalDescriptor {",
  "    valueType: 'float64' | 'boolean';",
  "    /** Scalar [], vector [length], or row-major matrix [rows, columns]. */",
  "    shape: number[];",
  "    unit: string;",
  "    /** A homogeneous scalar bus is represented as a vector with named fields. */",
  "    fields?: string[];",
  "}",
  "type ExpressionNode = {",
  "    type: 'number';",
  "    value: number;",
  "} | {",
  "    type: 'variable';",
  "    name: 'x' | 'pi' | 'e';",
  "} | {",
  "    type: 'unary';",
  "    operator: '+' | '-';",
  "    argument: ExpressionNode;",
  "} | {",
  "    type: 'binary';",
  "    operator: '+' | '-' | '*' | '/' | '^';",
  "    left: ExpressionNode;",
  "    right: ExpressionNode;",
  "} | {",
  "    type: 'call';",
  "    name: string;",
  "    args: ExpressionNode[];",
  "};",
  "interface CalcNode {",
  "    id: string;",
  "    blockType: string;",
  "    blockVersion: 1;",
  "    label: string;",
  "    parameters: Record<string, unknown>;",
  "    unit?: string;",
  "    sampleTime?: SampleTime;",
  "}",
  "interface Endpoint {",
  "    nodeId: string;",
  "    portId: string;",
  "}",
  "interface CalcEdge {",
  "    id: string;",
  "    source: Endpoint;",
  "    target: Endpoint;",
  "}",
  "interface ExecutionSettings {",
  "    mode: ExecutionMode;",
  "    startTime: number;",
  "    stopTime: number;",
  "    step: number;",
  "    solver?: Partial<SolverSettings>;",
  "}",
  "interface SolverSettings {",
  "    method: 'rk4' | 'rk45';",
  "    initialStep: number;",
  "    minStep: number;",
  "    maxStep: number;",
  "    atol: number;",
  "    rtol: number;",
  "    maxSteps: number;",
  "    maxRejects: number;",
  "    maxEvaluations: number;",
  "    eventTolerance: number;",
  "    maxEvents: number;",
  "    discreteStep: number;",
  "}",
  "type DatasetCell = number | boolean | string;",
  "interface DatasetColumn {",
  "    name: string;",
  "    kind: 'number' | 'boolean' | 'string';",
  "    unit: string;",
  "}",
  "interface Dataset {",
  "    id: string;",
  "    name: string;",
  "    version: number;",
  "    sourceHash: string;",
  "    contentHash: string;",
  "    timeColumn: string;",
  "    columns: DatasetColumn[];",
  "    rows: DatasetCell[][];",
  "}",
  "interface SubsystemDefinition {",
  "    id: string;",
  "    version: number;",
  "    name: string;",
  "    nodes: CalcNode[];",
  "    edges: CalcEdge[];",
  "    layout: Record<string, {",
  "        x: number;",
  "        y: number;",
  "    }>;",
  "    inputs: {",
  "        id: string;",
  "        nodeId: string;",
  "    }[];",
  "    outputs: {",
  "        id: string;",
  "        nodeId: string;",
  "    }[];",
  "}",
  "interface DashboardWidget {",
  "    id: string;",
  "    kind: 'slider' | 'toggle' | 'display' | 'gauge' | 'scope';",
  "    title: string;",
  "    nodeId: string;",
  "    parameter?: string;",
  "    min?: number;",
  "    max?: number;",
  "    step?: number;",
  "}",
  "interface CalcModel {",
  "    schemaVersion: 1;",
  "    modelId: string;",
  "    name: string;",
  "    nodes: CalcNode[];",
  "    edges: CalcEdge[];",
  "    execution: ExecutionSettings;",
  "    layout: Record<string, {",
  "        x: number;",
  "        y: number;",
  "    }>;",
  "    datasets?: Dataset[];",
  "    subsystems?: SubsystemDefinition[];",
  "    dashboard?: DashboardWidget[];",
  "    notes?: string;",
  "}",
  "interface Diagnostic {",
  "    code: string;",
  "    message: string;",
  "    nodeId?: string;",
  "    portId?: string;",
  "    /** Discrete execution failure location; compiler diagnostics omit these fields. */",
  "    tick?: number;",
  "    time?: number;",
  "}",
  "interface IRNode {",
  "    id: string;",
  "    blockType: BlockType;",
  "    parameters: Record<string, unknown>;",
  "    /** Preserve the selected producer port, including Demux outputs. */",
  "    inputs: Record<string, Endpoint>;",
  "    outputs: Record<string, SignalDescriptor>;",
  "    expression?: ExpressionNode;",
  "    /** Fixed rate expressed in integer base ticks. */",
  "    sampleTime: SampleTime;",
  "    /** Continuous compilation annotates the time domain; M0/M2 IR remains unchanged. */",
  "    executionDomain?: 'continuous' | 'discrete' | 'constant';",
  "}",
  "interface CompiledModel {",
  "    model: CalcModel;",
  "    nodes: IRNode[];",
  "    stateIds: string[];",
  "    outputIds: string[];",
  "    outputTypes: Record<string, SignalDescriptor>;",
  "    /** Canonical semantic JSON, excluding names and layout. SHA-256 computed at run boundary. */",
  "    semanticKey: string;",
  "    /** Persistent discrete state plus held and boundary signal elements. */",
  "    stateElements: number;",
  "    hierarchy?: HierarchyMetadata;",
  "}",
  "interface HierarchyOrigin {",
  "    path: string[];",
  "    rootNodeId: string;",
  "    definitionId: string;",
  "}",
  "interface HierarchyInstance {",
  "    nodeId: string;",
  "    path: string[];",
  "    definitionId: string;",
  "    version: number;",
  "    definitionHash: string;",
  "}",
  "interface HierarchyMetadata {",
  "    origins: Record<string, HierarchyOrigin>;",
  "    instances: HierarchyInstance[];",
  "}",
  "interface RunSample {",
  "    time: number;",
  "    values: Record<string, SignalValue>;",
  "}",
  "interface RunResult {",
  "    samples: RunSample[];",
  "    finalState: Record<string, SignalValue>;",
  "    stateMemory?: Record<string, StateValue>;",
  "    status: 'completed' | 'cancelled' | 'failed';",
  "    elapsedMs: number;",
  "    /** Continuous finalState endpoint; raw samples use their own output grid. */",
  "    stateTime?: number;",
  "    steps: number;",
  "    solverStatistics?: SolverStatistics;",
  "    events?: SimulationEvent[];",
  "    resources?: {",
  "        operations: number;",
  "    };",
  "}",
  "interface SolverStatistics {",
  "    method: 'rk4' | 'rk45';",
  "    acceptedSteps: number;",
  "    rejectedSteps: number;",
  "    evaluations: number;",
  "    events: number;",
  "    lastStep: number;",
  "    minAcceptedStep: number;",
  "    maxAcceptedStep: number;",
  "}",
  "interface SimulationEvent {",
  "    time: number;",
  "    nodeIds: string[];",
  "    kind: 'crossing' | 'reset' | 'relay';",
  "}",
  "const UNITS = Object.freeze(['1', 'm', 'cm', 'mm', 'km', 's', 'ms', 'min', 'kg', 'g', 'A', 'K', 'C', 'mol', 'cd', 'rad', 'deg', 'V', 'mV', 'Hz', 'N', 'Pa', 'J', 'W', 'm/s', 'm/s^2', 'm^2'] as const);",
  "const SIGNAL_LIMITS = Object.freeze({ maxElements: 1024, maxAxis: 1024, maxIntermediateElements: 100000 });",
  "function invalid(message: string): never { throw new ModelError([{ code: 'INVALID_SIGNAL', message }]); }",
  "/** Inspect arrays without invoking accessors; finite, homogeneous, dense JSON values only. */",
  "function arrayItems(value: unknown[]): unknown[] {",
  "    if (Object.getPrototypeOf(value) !== Array.prototype || value.length === 0 || value.length > SIGNAL_LIMITS.maxAxis) {",
  "        invalid('배열은 1~1,024개 원소를 가진 일반 배열이어야 합니다.');",
  "    }",
  "    const descriptors = Object.getOwnPropertyDescriptors(value);",
  "    if (Reflect.ownKeys(descriptors).length !== value.length + 1)",
  "        invalid('배열에는 빈 칸이나 추가 속성을 사용할 수 없습니다.');",
  "    const items: unknown[] = [];",
  "    for (let index = 0; index < value.length; index++) {",
  "        const descriptor = descriptors[String(index)];",
  "        if (!descriptor || !('value' in descriptor) || !descriptor.enumerable)",
  "            invalid('배열에는 빈 칸이나 접근자를 사용할 수 없습니다.');",
  "        items.push(descriptor.value);",
  "    }",
  "    return items;",
  "}",
  "/** Infer a bounded signal shape without converting boolean to numbers. */",
  "function validateSignal(value: unknown): SignalDescriptor {",
  "    let valueType: SignalDescriptor['valueType'] | undefined;",
  "    let count = 0;",
  "    const scalar = (item: unknown): void => {",
  "        const type = typeof item === 'number' && Number.isFinite(item) ? 'float64' : typeof item === 'boolean' ? 'boolean' : undefined;",
  "        if (!type)",
  "            invalid('신호 값은 유한한 float64 또는 boolean이어야 합니다.');",
  "        if (valueType && type !== valueType)",
  "            invalid('한 신호에는 숫자와 boolean을 섞을 수 없습니다.');",
  "        valueType = type;",
  "        if (++count > SIGNAL_LIMITS.maxElements)",
  "            invalid('한 신호는 1,024개 원소 이하여야 합니다.');",
  "    };",
  "    let shape: number[] = [];",
  "    if (Array.isArray(value)) {",
  "        const items = arrayItems(value);",
  "        if (Array.isArray(items[0])) {",
  "            let columns = 0;",
  "            for (const row of items) {",
  "                if (!Array.isArray(row))",
  "                    invalid('2D 신호의 모든 행은 같은 길이의 배열이어야 합니다.');",
  "                const cells = arrayItems(row);",
  "                if (!columns)",
  "                    columns = cells.length;",
  "                if (cells.length !== columns)",
  "                    invalid('2D 신호의 모든 행은 같은 길이여야 합니다.');",
  "                for (const item of cells)",
  "                    scalar(item);",
  "            }",
  "            shape = [items.length, columns];",
  "        }",
  "        else {",
  "            for (const item of items)",
  "                scalar(item);",
  "            shape = [items.length];",
  "        }",
  "    }",
  "    else",
  "        scalar(value);",
  "    return { valueType: valueType!, shape, unit: '1' };",
  "}",
  "function signalElementCount(descriptor: SignalDescriptor): number {",
  "    return descriptor.shape.reduce((product, length) => product * length, 1);",
  "}",
  "function formatSignalShape(descriptor: SignalDescriptor): string {",
  "    return descriptor.shape.length === 0 ? 'scalar' : descriptor.shape.length === 1 ? `vector[${descriptor.shape[0]}]` : `matrix[${descriptor.shape.join('×')}]`;",
  "}",
  "/** Logical persistent memory, excluding temporary atomic-commit copies. Input is validated IR. */",
  "function discreteStateElementCount(node: IRNode): number {",
  "    const initialCount = (): number => signalElementCount(validateSignal(node.parameters.initial));",
  "    switch (node.blockType) {",
  "        case 'discrete.unit-delay':",
  "        case 'discrete.integrator':",
  "        case 'discrete.difference':",
  "        case 'discrete.derivative':",
  "        case 'time.rate-transition': return initialCount();",
  "        case 'discrete.delay': return (node.parameters.steps as number) * initialCount();",
  "        case 'discrete.fir': return Math.max(0, (node.parameters.coefficients as number[]).length - 1) * initialCount();",
  "        case 'discrete.transfer-function': return (node.parameters.numerator as number[]).length + (node.parameters.denominator as number[]).length - 2;",
  "        case 'discrete.state-space': return (node.parameters.initial as number[]).length;",
  "        case 'logic.edge-detect':",
  "        case 'source.random': return 1;",
  "        default: return 0;",
  "    }",
  "}",
  "function discreteMemoryElementCount(nodes: readonly IRNode[]): number {",
  "    return nodes.reduce((count, node) => count + discreteStateElementCount(node)",
  "        + Object.values(node.outputs).reduce((held, descriptor) => held + signalElementCount(descriptor), 0), 0);",
  "}",
  "const SOLVER_LIMITS = Object.freeze({",
  "    minStep: 1e-12, maxStep: 1e9, minTolerance: 1e-12, maxTolerance: 1,",
  "    maxSteps: 100000, maxRejects: 10000, maxEvaluations: 1000000,",
  "    maxEvents: 10000, minEventTolerance: 1e-12, maxEventTolerance: 1,",
  "});",
  "/** One bounded normalized solver contract shared by compiler, Worker, UI and exports. */",
  "function normalizeSolverSettings(execution: ExecutionSettings): SolverSettings {",
  "    const defaults: SolverSettings = {",
  "        method: 'rk4', initialStep: execution.step, minStep: Math.min(execution.step, 1e-8),",
  "        maxStep: execution.step, atol: 1e-8, rtol: 1e-6,",
  "        maxSteps: SOLVER_LIMITS.maxSteps, maxRejects: SOLVER_LIMITS.maxRejects,",
  "        maxEvaluations: SOLVER_LIMITS.maxEvaluations, eventTolerance: 1e-8,",
  "        maxEvents: SOLVER_LIMITS.maxEvents, discreteStep: execution.step,",
  "    };",
  "    const value = { ...defaults, ...execution.solver };",
  "    const invalid = (message: string): never => { throw new ModelError([{ code: 'INVALID_SOLVER', message }]); };",
  "    if (Object.keys(execution.solver ?? {}).some((key) => !Object.hasOwn(defaults, key)))",
  "        invalid('지원하지 않는 솔버 필드입니다.');",
  "    if (value.method !== 'rk4' && value.method !== 'rk45')",
  "        invalid('솔버는 rk4 또는 rk45여야 합니다.');",
  "    for (const key of ['initialStep', 'minStep', 'maxStep', 'discreteStep'] as const) {",
  "        const min = key === 'discreteStep' ? 1e-9 : SOLVER_LIMITS.minStep;",
  "        if (!Number.isFinite(value[key]) || value[key] < min || value[key] > SOLVER_LIMITS.maxStep)",
  "            invalid(`${key}는 ${min}~${SOLVER_LIMITS.maxStep}의 유한한 양수여야 합니다.`);",
  "    }",
  "    if (value.minStep > value.initialStep || value.initialStep > value.maxStep)",
  "        invalid('minStep ≤ initialStep ≤ maxStep이어야 합니다.');",
  "    for (const key of ['atol', 'rtol'] as const)",
  "        if (!Number.isFinite(value[key]) || value[key] < SOLVER_LIMITS.minTolerance || value[key] > SOLVER_LIMITS.maxTolerance)",
  "            invalid(`${key} 허용오차는 1e-12~1이어야 합니다.`);",
  "    if (!Number.isFinite(value.eventTolerance) || value.eventTolerance < SOLVER_LIMITS.minEventTolerance || value.eventTolerance > SOLVER_LIMITS.maxEventTolerance)",
  "        invalid('eventTolerance는 1e-12~1이어야 합니다.');",
  "    for (const key of ['maxSteps', 'maxRejects', 'maxEvaluations', 'maxEvents'] as const) {",
  "        const min = key === 'maxRejects' ? 0 : 1;",
  "        if (!Number.isSafeInteger(value[key]) || value[key] < min || value[key] > SOLVER_LIMITS[key])",
  "            invalid(`${key}는 ${min}~${SOLVER_LIMITS[key]}의 정수여야 합니다.`);",
  "    }",
  "    return value;",
  "}",
  "const CONTINUOUS_STATE_TYPES: readonly string[] = Object.freeze([",
  "    'continuous.integrator', 'continuous.second-order-integrator', 'continuous.state-space',",
  "    'continuous.transfer-function', 'continuous.zero-pole', 'continuous.pid', 'continuous.derivative',",
  "]);",
  "const CONTINUOUS_BOUNDARY_TYPES: readonly string[] = Object.freeze([",
  "    'time.memory', 'time.zero-order-hold', 'time.first-order-hold', 'time.transport-delay',",
  "    'logic.hit-crossing', 'nonlinear.relay',",
  "]);",
  "function continuousStateElementCount(node: IRNode): number {",
  "    switch (node.blockType) {",
  "        case 'continuous.integrator':",
  "        case 'continuous.derivative': return 1;",
  "        case 'continuous.second-order-integrator':",
  "        case 'continuous.pid': return 2;",
  "        case 'continuous.state-space':",
  "        case 'continuous.zero-pole': return (node.parameters.initial as number[]).length;",
  "        case 'continuous.transfer-function': return (node.parameters.denominator as number[]).length - 1;",
  "        case 'time.memory':",
  "        case 'time.zero-order-hold':",
  "        case 'logic.hit-crossing':",
  "        case 'nonlinear.relay': return 1;",
  "        case 'time.first-order-hold': return 5;",
  "        default: return 0;",
  "    }",
  "}",
  "const EXPRESSION_LIMITS = Object.freeze({ maxLength: 512, maxNodes: 128, maxDepth: 32 });",
  "function children(node: ExpressionNode): ExpressionNode[] {",
  "    if (node.type === 'unary')",
  "        return [node.argument];",
  "    if (node.type === 'binary')",
  "        return [node.left, node.right];",
  "    if (node.type === 'call')",
  "        return node.args;",
  "    return [];",
  "}",
  "function expressionNodeCount(ast: ExpressionNode): number {",
  "    let count = 0;",
  "    const pending = [ast];",
  "    while (pending.length) {",
  "        const node = pending.pop()!;",
  "        if (++count > EXPRESSION_LIMITS.maxNodes)",
  "            fail('EXPRESSION_LIMIT', '수식 AST 노드 상한을 초과했습니다.');",
  "        pending.push(...children(node));",
  "    }",
  "    return count;",
  "}",
  "function nodeOperationCost(node: IRNode, byId: Map<string, IRNode>): number {",
  "    const outputSize = Object.values(node.outputs).reduce((count, descriptor) => count + signalElements(descriptor), 0);",
  "    const inputSize = Object.values(node.inputs).reduce((count, endpoint) => {",
  "        const descriptor = byId.get(endpoint.nodeId)?.outputs[endpoint.portId];",
  "        if (!descriptor)",
  "            numericFailure('RUNTIME_INVALID_IR', node.id, '입력 포트의 자료형 정보가 없습니다.');",
  "        return Math.max(count, signalElements(descriptor));",
  "    }, 0);",
  "    const inputShape = (port: string): number[] => {",
  "        const endpoint = node.inputs[port];",
  "        return endpoint ? byId.get(endpoint.nodeId)!.outputs[endpoint.portId]!.shape : [];",
  "    };",
  "    if (node.blockType === 'math.matrix-multiply') {",
  "        const a = inputShape('a'), b = inputShape('b');",
  "        return 8 * a[0]! * a[1]! * b[1]! + a[0]! * a[1]! + b[0]! * b[1]! + outputSize;",
  "    }",
  "    if (['matrix.determinant', 'matrix.inverse', 'matrix.solve', 'matrix.cholesky', 'matrix.lu'].includes(node.blockType)) {",
  "        const size = inputShape(node.blockType === 'matrix.solve' ? 'a' : 'in')[0]!;",
  "        // Pivoting, scale handling, residual/condition work and multi-RHS storage are charged.",
  "        return 32 * size ** 3 + 32 * size ** 2 + 8 * size * inputSize + outputSize;",
  "    }",
  "    let factor = node.expression ? expressionNodeCount(node.expression) : 1;",
  "    if (node.blockType === 'matrix.transpose')",
  "        factor = 3;",
  "    if (node.blockType === 'fixed.quantize')",
  "        factor = 1100; // bounded binary64 BigInt work (≤1,074-bit shifts), per emitted element",
  "    if (node.blockType === 'lookup.prelookup')",
  "        factor = (node.parameters.breakpoints as number[]).length + 8;",
  "    if (node.blockType === 'lookup.2d')",
  "        factor = (node.parameters.rowBreakpoints as number[]).length * (node.parameters.columnBreakpoints as number[]).length + (node.parameters.rowBreakpoints as number[]).length + (node.parameters.columnBreakpoints as number[]).length + 24;",
  "    if (node.blockType === 'discrete.fir')",
  "        factor = (node.parameters.coefficients as number[]).length * 2;",
  "    if (node.blockType === 'discrete.transfer-function')",
  "        factor = ((node.parameters.numerator as number[]).length + (node.parameters.denominator as number[]).length) * 2;",
  "    if (node.blockType === 'discrete.state-space')",
  "        factor = (node.parameters.initial as number[]).length ** 2 + 3 * (node.parameters.initial as number[]).length;",
  "    if (node.blockType === 'continuous.state-space')",
  "        factor = (node.parameters.initial as number[]).length ** 2 + 3 * (node.parameters.initial as number[]).length;",
  "    if (node.blockType === 'continuous.transfer-function' || node.blockType === 'continuous.zero-pole')",
  "        factor = Math.max(1, (node.parameters.initial as number[]).length * 3);",
  "    if (node.blockType === 'time.transport-delay')",
  "        factor = 32;",
  "    if (node.blockType === 'discrete.delay')",
  "        factor = Number(node.parameters.steps) + 1;",
  "    if (node.blockType === 'lookup.interpolated')",
  "        factor = Math.ceil(Math.log2((node.parameters.breakpoints as number[]).length)) + 3;",
  "    if (node.blockType === 'source.repeating-sequence')",
  "        factor = Math.ceil(Math.log2((node.parameters.times as number[]).length)) + 3;",
  "    if (node.blockType === 'source.dataset')",
  "        factor = Math.ceil(Math.log2((node.parameters.times as number[]).length)) + 5;",
  "    return Math.max(1, outputSize, inputSize) * factor;",
  "}",
  "/** Pure Runge–Kutta stages: trial evaluation cannot commit model memory. */",
  "function rkTrial(method: 'rk4' | 'rk45', t: number, x: number[], h: number, derivative: (time: number, state: number[]) => number[]): {",
  "    state: number[];",
  "    error: number[];",
  "} {",
  "    const stage = (weights: number[], slopes: number[][]): number[] => x.map((value, index) => value + h * weights.reduce((sum, weight, j) => sum + weight * slopes[j]![index]!, 0));",
  "    const k1 = derivative(t, x);",
  "    if (method === 'rk4') {",
  "        const k2 = derivative(t + h / 2, stage([1 / 2], [k1]));",
  "        const k3 = derivative(t + h / 2, stage([0, 1 / 2], [k1, k2]));",
  "        const k4 = derivative(t + h, stage([0, 0, 1], [k1, k2, k3]));",
  "        return { state: stage([1 / 6, 1 / 3, 1 / 3, 1 / 6], [k1, k2, k3, k4]), error: x.map(() => 0) };",
  "    }",
  "    const k2 = derivative(t + h / 5, stage([1 / 5], [k1]));",
  "    const k3 = derivative(t + 3 * h / 10, stage([3 / 40, 9 / 40], [k1, k2]));",
  "    const k4 = derivative(t + 4 * h / 5, stage([44 / 45, -56 / 15, 32 / 9], [k1, k2, k3]));",
  "    const k5 = derivative(t + 8 * h / 9, stage([19372 / 6561, -25360 / 2187, 64448 / 6561, -212 / 729], [k1, k2, k3, k4]));",
  "    const k6 = derivative(t + h, stage([9017 / 3168, -355 / 33, 46732 / 5247, 49 / 176, -5103 / 18656], [k1, k2, k3, k4, k5]));",
  "    const state = stage([35 / 384, 0, 500 / 1113, 125 / 192, -2187 / 6784, 11 / 84], [k1, k2, k3, k4, k5, k6]);",
  "    const k7 = derivative(t + h, state);",
  "    const fourth = stage([5179 / 57600, 0, 7571 / 16695, 393 / 640, -92097 / 339200, 187 / 2100, 1 / 40], [k1, k2, k3, k4, k5, k6, k7]);",
  "    return { state, error: state.map((value, index) => value - fourth[index]!) };",
  "}",
  "/** Weighted infinity norm: each state must meet its own absolute/relative bound. */",
  "function rkErrorNorm(before: number[], after: number[], error: number[], atol: number, rtol: number): number {",
  "    return error.reduce((maximum, value, index) => Math.max(maximum, Math.abs(value) / (atol + rtol * Math.max(Math.abs(before[index]!), Math.abs(after[index]!)))), 0);",
  "}",
  "function rkNextStep(h: number, error: number, accepted: boolean, minimum: number, maximum: number): number {",
  "    const factor = error === 0 ? 5 : Math.min(accepted ? 5 : 1, Math.max(0.1, 0.9 * error ** -0.2));",
  "    return Math.min(maximum, Math.max(minimum, h * factor));",
  "}",
  "type ContinuousValues = Map<string, Record<string, SignalValue>>;",
  "interface ContinuousEvent {",
  "    nodeId: string;",
  "    kind: 'crossing' | 'reset' | 'relay';",
  "    direction: number;",
  "    threshold?: number;",
  "}",
  "type ContinuousMemory = {",
  "    value?: SignalValue;",
  "    previous?: number;",
  "    previousTime?: number;",
  "    priorTime?: number;",
  "    slope?: number;",
  "    on?: boolean;",
  "    history?: {",
  "        time: number;",
  "        value: number;",
  "    }[];",
  "    historyStart?: number;",
  "    historyLength?: number;",
  "    jumpTimes?: number[];",
  "    jumpStart?: number;",
  "    jumpLength?: number;",
  "};",
  "/** Scalar ODE state and accepted-boundary memory. evaluate/derivative are pure. */",
  "function createContinuousMachine(compiled: CompiledModel, charge: (node: IRNode) => void) {",
  "    const nodes = compiled.nodes;",
  "    const byId = new Map(nodes.map((node) => [node.id, node]));",
  "    const ranges = new Map<string, {",
  "        start: number;",
  "        length: number;",
  "    }>();",
  "    const memories = new Map<string, ContinuousMemory>();",
  "    const initial: number[] = [];",
  "    const initialFor = (node: IRNode): number[] => {",
  "        const p = node.parameters;",
  "        switch (node.blockType) {",
  "            case 'continuous.integrator': return [Number(p.initial)];",
  "            case 'continuous.second-order-integrator': return [Number(p.initialPosition), Number(p.initialVelocity)];",
  "            case 'continuous.state-space':",
  "            case 'continuous.transfer-function':",
  "            case 'continuous.zero-pole': return [...p.initial as number[]];",
  "            case 'continuous.pid': return [Number(p.initialIntegral), Number(p.initialFilter)];",
  "            case 'continuous.derivative': return [Number(p.initial)];",
  "            default: return [];",
  "        }",
  "    };",
  "    for (const node of nodes) {",
  "        const values = initialFor(node);",
  "        if (values.length) {",
  "            ranges.set(node.id, { start: initial.length, length: values.length });",
  "            initial.push(...values);",
  "        }",
  "        switch (node.blockType) {",
  "            case 'time.memory':",
  "            case 'time.zero-order-hold':",
  "                memories.set(node.id, { value: copySignal(node.parameters.initial as SignalValue) });",
  "                break;",
  "            case 'time.first-order-hold':",
  "                memories.set(node.id, { value: copySignal(node.parameters.initial as SignalValue), slope: 0 });",
  "                break;",
  "            case 'time.transport-delay':",
  "                memories.set(node.id, { history: [], jumpTimes: [] });",
  "                break;",
  "            case 'logic.hit-crossing':",
  "                memories.set(node.id, {});",
  "                break;",
  "            case 'nonlinear.relay':",
  "                memories.set(node.id, { on: node.parameters.initial === 'on' });",
  "                break;",
  "        }",
  "    }",
  "    const input = (values: ContinuousValues, node: IRNode, port = 'in'): SignalValue => {",
  "        const endpoint = node.inputs[port];",
  "        const value = endpoint && values.get(endpoint.nodeId)?.[endpoint.portId];",
  "        if (value === undefined)",
  "            numericFailure('RUNTIME_INVALID_IR', node.id, '연속 단계의 입력을 읽을 수 없습니다.');",
  "        return value;",
  "    };",
  "    const scalar = (values: ContinuousValues, node: IRNode, port = 'in'): number => finiteNumber(input(values, node, port), node.id);",
  "    const vector = (state: number[], node: IRNode): number[] => {",
  "        const range = ranges.get(node.id);",
  "        return range ? state.slice(range.start, range.start + range.length) : [];",
  "    };",
  "    const dot = (a: number[], b: number[], id: string): number => a.reduce((sum, coefficient, index) => finiteNumber(sum + coefficient * b[index]!, id), 0);",
  "    const polynomial = (roots: number[]): number[] => roots.reduce((coefficients, root) => {",
  "        const next = Array(coefficients.length + 1).fill(0) as number[];",
  "        coefficients.forEach((coefficient, index) => { next[index] += coefficient; next[index + 1] -= coefficient * root; });",
  "        return next;",
  "    }, [1]);",
  "    const transferParameters = (node: IRNode): {",
  "        a: number[];",
  "        b: number[];",
  "        d: number;",
  "    } => {",
  "        const p = node.parameters;",
  "        const denominator = node.blockType === 'continuous.zero-pole' ? polynomial(p.poles as number[]) : p.denominator as number[];",
  "        const numerator = node.blockType === 'continuous.zero-pole' ? polynomial(p.zeros as number[]).map((value) => value * Number(p.gain)) : p.numerator as number[];",
  "        const a = denominator.map((value) => finiteNumber(value / denominator[0]!, node.id));",
  "        const b = [...Array(Math.max(0, a.length - numerator.length)).fill(0), ...numerator].map((value) => finiteNumber(value / denominator[0]!, node.id));",
  "        return { a, b, d: b[0]! };",
  "    };",
  "    const transfers = new Map(nodes.filter((node) => node.blockType === 'continuous.transfer-function' || node.blockType === 'continuous.zero-pole').map((node) => [node.id, transferParameters(node)]));",
  "    function delayed(node: IRNode, time: number): number {",
  "        const memory = memories.get(node.id)!, history = memory.history!, start = memory.historyStart ?? 0, target = time - Number(node.parameters.delay);",
  "        if (target < compiled.model.execution.startTime || history.length === start)",
  "            return Number(node.parameters.initial);",
  "        if (target <= history[start]!.time)",
  "            return history[start]!.value;",
  "        let low = start, high = history.length - 1;",
  "        while (high - low > 1) {",
  "            const middle = (low + high) >>> 1;",
  "            if (history[middle]!.time <= target)",
  "                low = middle;",
  "            else",
  "                high = middle;",
  "        }",
  "        if (target >= history[high]!.time)",
  "            return history[high]!.value;",
  "        const a = history[low]!, b = history[high]!, ratio = (target - a.time) / (b.time - a.time);",
  "        return finiteNumber(a.value * (1 - ratio) + b.value * ratio, node.id);",
  "    }",
  "    function independent(node: IRNode): boolean {",
  "        switch (node.blockType) {",
  "            case 'continuous.integrator':",
  "            case 'continuous.second-order-integrator':",
  "            case 'time.memory':",
  "            case 'time.transport-delay':",
  "            case 'time.zero-order-hold':",
  "            case 'time.first-order-hold':",
  "            case 'logic.hit-crossing':",
  "            case 'nonlinear.relay': return true;",
  "            case 'continuous.state-space': return node.parameters.D === 0;",
  "            case 'continuous.transfer-function':",
  "            case 'continuous.zero-pole': return transfers.get(node.id)!.d === 0;",
  "            case 'continuous.pid': return Number(node.parameters.kp) + Number(node.parameters.kd) * Number(node.parameters.filterN) === 0;",
  "            default: return false;",
  "        }",
  "    }",
  "    function output(node: IRNode, state: number[], time: number, values: ContinuousValues, eventMask: Set<string>, sourceTime = time, reader?: (port: string) => SignalValue): Record<string, SignalValue> {",
  "        const p = node.parameters, x = vector(state, node), number = (key: string) => finiteNumber(p[key], node.id);",
  "        const read = (port: string): SignalValue => reader ? reader(port) : input(values, node, port);",
  "        const scalarInput = (): number => finiteNumber(read('in'), node.id);",
  "        switch (node.blockType) {",
  "            case 'continuous.integrator': return { out: x[0]! };",
  "            case 'continuous.second-order-integrator': return { out: x[0]!, velocity: x[1]! };",
  "            case 'continuous.state-space': return { out: finiteNumber(dot(p.C as number[], x, node.id) + (p.D === 0 ? 0 : number('D') * scalarInput()), node.id) };",
  "            case 'continuous.transfer-function':",
  "            case 'continuous.zero-pole': {",
  "                const { a, b, d } = transfers.get(node.id)!;",
  "                return { out: finiteNumber(x.reduce((sum, value, index) => sum + (b[a.length - 1 - index]! - d * a[a.length - 1 - index]!) * value, 0) + (d === 0 ? 0 : d * scalarInput()), node.id) };",
  "            }",
  "            case 'continuous.pid': return { out: finiteNumber(number('ki') * x[0]! - number('kd') * number('filterN') * x[1]! + (independent(node) ? 0 : (number('kp') + number('kd') * number('filterN')) * scalarInput()), node.id) };",
  "            case 'continuous.derivative': return { out: finiteNumber(number('filterN') * (scalarInput() - x[0]!), node.id) };",
  "            case 'time.memory':",
  "            case 'time.zero-order-hold': return { out: memories.get(node.id)!.value! };",
  "            case 'time.first-order-hold': {",
  "                const memory = memories.get(node.id)!;",
  "                return { out: finiteNumber(Number(memory.value) + (memory.previousTime === undefined ? 0 : (time - memory.previousTime) * memory.slope!), node.id) };",
  "            }",
  "            case 'time.transport-delay': return { out: delayed(node, sourceTime) };",
  "            case 'logic.hit-crossing': return { out: eventMask.has(node.id) };",
  "            case 'nonlinear.relay': return { out: memories.get(node.id)!.on ? number('onValue') : number('offValue') };",
  "            case 'source.step': return { out: sourceTime < number('stepTime') ? number('before') : number('after') };",
  "            case 'source.ramp': return { out: finiteNumber(number('initial') + number('slope') * Math.max(0, time - number('startTime')), node.id) };",
  "            case 'source.sine-wave': return { out: finiteNumber(number('amplitude') * Math.sin(2 * Math.PI * number('frequency') * time + number('phase')) + number('bias'), node.id) };",
  "            case 'source.clock': return { out: time };",
  "            case 'source.dataset': return { out: replayDataset(node, sourceTime) };",
  "            case 'source.repeating-sequence': {",
  "                const times = p.times as number[], period = times.at(-1)!, remainder = sourceTime % period, phase = remainder < 0 ? remainder + period : remainder;",
  "                return { out: interpolateTable(phase, times, p.values as number[], String(p.interpolation), 'clip', node.id) };",
  "            }",
  "            default: return evaluateSignalNode(node, read);",
  "        }",
  "    }",
  "    function evaluateNode(node: IRNode, time: number, state: number[], reader: (port: string) => SignalValue, eventMask: Set<string>): Record<string, SignalValue> {",
  "        charge(node);",
  "        const outputs = output(node, state, time, new Map(), eventMask, time, reader);",
  "        for (const [port, descriptor] of Object.entries(node.outputs))",
  "            checkSignal(outputs[port], descriptor, node.id);",
  "        return outputs;",
  "    }",
  "    function evaluate(time: number, state: number[], frozen: ContinuousValues, eventMask = new Set<string>(), sourceTime = time): ContinuousValues {",
  "        const values = new Map(frozen);",
  "        const emit = (node: IRNode): void => {",
  "            charge(node);",
  "            const outputs = output(node, state, time, values, eventMask, sourceTime);",
  "            for (const [port, descriptor] of Object.entries(node.outputs))",
  "                checkSignal(outputs[port], descriptor, node.id);",
  "            values.set(node.id, outputs);",
  "        };",
  "        for (const node of nodes)",
  "            if ((node.executionDomain !== 'discrete' || node.blockType === 'time.zero-order-hold') && independent(node))",
  "                emit(node);",
  "        for (const node of nodes)",
  "            if (node.executionDomain !== 'discrete' && !independent(node))",
  "                emit(node);",
  "        // Boundary blocks remain available even when their domain is discrete.",
  "        for (const node of nodes)",
  "            if (node.blockType === 'time.zero-order-hold')",
  "                values.set(node.id, output(node, state, time, values, eventMask));",
  "        return values;",
  "    }",
  "    function derivative(time: number, state: number[], frozen: ContinuousValues, sourceTime = time): number[] {",
  "        const values = evaluate(time, state, frozen, new Set(), sourceTime), slopes: number[] = [];",
  "        for (const [id, range] of ranges) {",
  "            const node = byId.get(id)!, p = node.parameters, x = state.slice(range.start, range.start + range.length), u = scalar(values, node);",
  "            let result: number[];",
  "            switch (node.blockType) {",
  "                case 'continuous.integrator':",
  "                    result = [u];",
  "                    break;",
  "                case 'continuous.second-order-integrator':",
  "                    result = [x[1]!, u];",
  "                    break;",
  "                case 'continuous.state-space':",
  "                    result = (p.A as number[][]).map((row, index) => dot(row, x, id) + (p.B as number[])[index]! * u);",
  "                    break;",
  "                case 'continuous.transfer-function':",
  "                case 'continuous.zero-pole': {",
  "                    const { a } = transfers.get(id)!;",
  "                    result = [...x.slice(1), u - x.reduce((sum, value, index) => sum + a[a.length - 1 - index]! * value, 0)];",
  "                    break;",
  "                }",
  "                case 'continuous.pid':",
  "                    result = [u, Number(p.filterN) * (u - x[1]!)];",
  "                    break;",
  "                case 'continuous.derivative':",
  "                    result = [Number(p.filterN) * (u - x[0]!)];",
  "                    break;",
  "                default: result = [];",
  "            }",
  "            slopes.push(...result.map((value) => finiteNumber(value, id)));",
  "        }",
  "        return slopes;",
  "    }",
  "    function eventCandidates(before: ContinuousValues, after: ContinuousValues): ContinuousEvent[] {",
  "        const events: ContinuousEvent[] = [];",
  "        for (const node of nodes) {",
  "            if (node.blockType === 'nonlinear.saturation' && node.executionDomain !== 'discrete' && node.outputs.out?.shape.length === 0) {",
  "                const a = scalar(before, node), b = scalar(after, node);",
  "                for (const threshold of [Number(node.parameters.lower), Number(node.parameters.upper)]) {",
  "                    if (a < threshold && b >= threshold || a > threshold && b <= threshold)",
  "                        events.push({ nodeId: node.id, kind: 'crossing', direction: b > a ? 1 : -1, threshold });",
  "                }",
  "            }",
  "            if (node.blockType === 'logic.hit-crossing' || node.blockType === 'nonlinear.relay') {",
  "                const a = scalar(before, node), b = scalar(after, node);",
  "                const on = memories.get(node.id)!.on;",
  "                const threshold = Number(node.parameters[node.blockType === 'logic.hit-crossing' ? 'threshold' : on ? 'offThreshold' : 'onThreshold']);",
  "                const rising = a < threshold && b >= threshold, falling = a > threshold && b <= threshold;",
  "                const direction = node.blockType === 'nonlinear.relay' ? on ? 'falling' : 'rising' : String(node.parameters.direction);",
  "                if ((direction !== 'falling' && rising) || (direction !== 'rising' && falling))",
  "                    events.push({ nodeId: node.id, kind: node.blockType === 'nonlinear.relay' ? 'relay' : 'crossing', direction: rising ? 1 : -1 });",
  "            }",
  "            if (node.blockType === 'continuous.integrator' && node.parameters.reset === 'rising' && input(before, node, 'reset') === false && input(after, node, 'reset') === true)",
  "                events.push({ nodeId: node.id, kind: 'reset', direction: 1 });",
  "        }",
  "        return events;",
  "    }",
  "    function eventReached(event: ContinuousEvent, values: ContinuousValues): boolean {",
  "        const node = byId.get(event.nodeId)!;",
  "        if (event.kind === 'reset')",
  "            return input(values, node, 'reset') === true;",
  "        const threshold = event.threshold ?? Number(node.parameters[event.kind === 'crossing' ? 'threshold' : memories.get(node.id)!.on ? 'offThreshold' : 'onThreshold']);",
  "        const value = scalar(values, node);",
  "        return event.direction > 0 ? value >= threshold : value <= threshold;",
  "    }",
  "    function relaySettlingEvents(values: ContinuousValues): ContinuousEvent[] {",
  "        return nodes.filter((node) => node.blockType === 'nonlinear.relay').flatMap((node) => {",
  "            const on = memories.get(node.id)!.on, value = scalar(values, node);",
  "            return !on && value >= Number(node.parameters.onThreshold) ? [{ nodeId: node.id, kind: 'relay' as const, direction: 1 }]",
  "                : on && value <= Number(node.parameters.offThreshold) ? [{ nodeId: node.id, kind: 'relay' as const, direction: -1 }] : [];",
  "        });",
  "    }",
  "    function applyEvents(state: number[], events: ContinuousEvent[], time: number, frozen: ContinuousValues): {",
  "        state: number[];",
  "        mask: Set<string>;",
  "    } {",
  "        const next = [...state], mask = new Set(events.filter((event) => event.kind === 'crossing' && byId.get(event.nodeId)!.blockType === 'logic.hit-crossing').map((event) => event.nodeId));",
  "        for (const event of events)",
  "            if (event.kind === 'relay')",
  "                memories.get(event.nodeId)!.on = event.direction > 0;",
  "        const values = evaluate(time, next, frozen, mask);",
  "        for (const node of nodes)",
  "            if (node.blockType === 'continuous.integrator' && node.parameters.reset === 'rising' && (events.some((event) => event.nodeId === node.id && event.kind === 'reset') || input(values, node, 'reset') === true && mask.has(node.inputs.reset!.nodeId)))",
  "                next[ranges.get(node.id)!.start] = Number(node.parameters.initial);",
  "        return { state: next, mask };",
  "    }",
  "    function acceptMemory(time: number, previousValues: ContinuousValues, currentValues: ContinuousValues, leftValues?: ContinuousValues): void {",
  "        for (const node of nodes) {",
  "            if (node.blockType === 'time.memory')",
  "                memories.get(node.id)!.value = copySignal(input(previousValues, node));",
  "            if (node.blockType === 'time.transport-delay') {",
  "                const memory = memories.get(node.id)!, history = memory.history!, value = scalar(currentValues, node);",
  "                if (leftValues) {",
  "                    const left = scalar(leftValues, node);",
  "                    if (left !== value) {",
  "                        history.push({ time, value: left });",
  "                        memory.jumpTimes!.push(time);",
  "                    }",
  "                }",
  "                history.push({ time, value });",
  "                const cutoff = time - Number(node.parameters.delay);",
  "                let start = memory.historyStart ?? 0;",
  "                while (history.length - start > 2 && history[start + 1]!.time < cutoff)",
  "                    start += 1;",
  "                memory.historyStart = start;",
  "                if (start > 1024 && start > history.length / 2) {",
  "                    memory.history = history.slice(start);",
  "                    memory.historyStart = 0;",
  "                }",
  "                let jumpStart = memory.jumpStart ?? 0;",
  "                while (jumpStart < memory.jumpTimes!.length && memory.jumpTimes![jumpStart]! <= cutoff)",
  "                    jumpStart += 1;",
  "                memory.jumpStart = jumpStart;",
  "                if (jumpStart > 1024 && jumpStart > memory.jumpTimes!.length / 2) {",
  "                    memory.jumpTimes = memory.jumpTimes!.slice(jumpStart);",
  "                    memory.jumpStart = 0;",
  "                }",
  "                if (history.length - start > 100000)",
  "                    numericFailure('RUNTIME_HISTORY_BUDGET', node.id, '지연 이력의 보관 한도를 초과했습니다.');",
  "            }",
  "        }",
  "        const stored = [...memories.values()].reduce((count, memory) => count + ((memory.history?.length ?? 0) - (memory.historyStart ?? 0)) * 2 + (memory.jumpTimes?.length ?? 0) - (memory.jumpStart ?? 0), compiled.stateElements);",
  "        if (stored > 100000)",
  "            numericFailure('RUNTIME_HISTORY_BUDGET', nodes.find((node) => node.blockType === 'time.transport-delay')?.id ?? nodes[0]!.id, '전체 상태와 지연 이력 한도를 초과했습니다.');",
  "    }",
  "    function captureHolds(time: number, tick: number, values: ContinuousValues, phase?: 'continuous' | 'discrete', only?: string): void {",
  "        for (const node of nodes)",
  "            if ((!only || node.id === only) && (node.blockType === 'time.zero-order-hold' || node.blockType === 'time.first-order-hold') && tick >= node.sampleTime.offset && (tick - node.sampleTime.offset) % node.sampleTime.period === 0) {",
  "                const producer = byId.get(node.inputs.in!.nodeId)!;",
  "                if (phase && (producer.executionDomain === 'discrete' ? 'discrete' : 'continuous') !== phase)",
  "                    continue;",
  "                const memory = memories.get(node.id)!, value = scalar(values, node);",
  "                if (node.blockType === 'time.zero-order-hold') {",
  "                    memory.value = value;",
  "                    continue;",
  "                }",
  "                if (memory.previousTime === time) {",
  "                    memory.slope = memory.priorTime === undefined ? 0 : finiteNumber((value - Number(memory.previous)) / (time - memory.priorTime), node.id);",
  "                }",
  "                else {",
  "                    memory.slope = memory.previousTime === undefined ? 0 : finiteNumber((value - Number(memory.value)) / (time - memory.previousTime), node.id);",
  "                    memory.previous = Number(memory.value);",
  "                    memory.priorTime = memory.previousTime;",
  "                    memory.previousTime = time;",
  "                }",
  "                memory.value = value;",
  "            }",
  "    }",
  "    function finalState(state: number[], values: ContinuousValues): Record<string, SignalValue> {",
  "        return Object.fromEntries(compiled.stateIds.filter((id) => byId.get(id)!.executionDomain !== 'discrete' || byId.get(id)!.blockType === 'time.zero-order-hold').map((id) => [id, copySignal(values.get(id)?.out ?? vector(state, byId.get(id)!)[0] ?? 0)]));",
  "    }",
  "    function stateMemory(state: number[]): Record<string, StateValue> {",
  "        return Object.fromEntries([...ranges].map(([id]) => [id, { state: vector(state, byId.get(id)!) } as StateValue]).concat([...memories].map(([id, memory]) => {",
  "            const { historyStart, historyLength: _length, jumpTimes: _jumps, jumpStart: _head, jumpLength: _jumpLength, ...snapshot } = memory;",
  "            if (snapshot.history)",
  "                snapshot.history = snapshot.history.slice(historyStart ?? 0);",
  "            return [id, JSON.parse(JSON.stringify(snapshot)) as StateValue];",
  "        })));",
  "    }",
  "    function validateState(state: number[]): void {",
  "        for (const [id, range] of ranges)",
  "            for (let index = range.start; index < range.start + range.length; index += 1)",
  "                finiteNumber(state[index], id);",
  "    }",
  "    const maximumDelayStep = nodes.filter((node) => node.blockType === 'time.transport-delay').reduce((minimum, node) => Math.min(minimum, Number(node.parameters.delay)), Infinity);",
  "    function nextDelayBoundary(time: number): number {",
  "        let next = Infinity;",
  "        for (const node of nodes)",
  "            if (node.blockType === 'time.transport-delay') {",
  "                const delay = Number(node.parameters.delay), memory = memories.get(node.id)!, jumps = memory.jumpTimes!;",
  "                const first = compiled.model.execution.startTime + delay;",
  "                const threshold = time + Math.abs(time) * Number.EPSILON * 8;",
  "                if (first > threshold)",
  "                    next = Math.min(next, first);",
  "                // A separate sorted index keeps lookup logarithmic even with long history.",
  "                let low = memory.jumpStart ?? 0, high = jumps.length;",
  "                while (low < high) {",
  "                    const middle = (low + high) >>> 1;",
  "                    if (jumps[middle]! + delay <= threshold)",
  "                        low = middle + 1;",
  "                    else",
  "                        high = middle;",
  "                }",
  "                if (low < jumps.length)",
  "                    next = Math.min(next, jumps[low]! + delay);",
  "            }",
  "        return next;",
  "    }",
  "    const checkpoint = (): Map<string, ContinuousMemory> => new Map([...memories].map(([id, memory]) => [id, { ...memory, historyLength: memory.history?.length, jumpLength: memory.jumpTimes?.length }]));",
  "    const restore = (saved: Map<string, ContinuousMemory>): void => {",
  "        memories.clear();",
  "        for (const [id, memory] of saved) {",
  "            if (memory.history && memory.historyLength !== undefined)",
  "                memory.history.length = memory.historyLength;",
  "            if (memory.jumpTimes && memory.jumpLength !== undefined)",
  "                memory.jumpTimes.length = memory.jumpLength;",
  "            delete memory.historyLength;",
  "            delete memory.jumpLength;",
  "            memories.set(id, memory);",
  "        }",
  "    };",
  "    return { initial, evaluate, evaluateNode, derivative, eventCandidates, eventReached, relaySettlingEvents, applyEvents, acceptMemory, captureHolds, finalState, stateMemory, validateState, maximumDelayStep, nextDelayBoundary, checkpoint, restore };",
  "}",
  "/** Pure, bounded state machine shared by browser execution and independent TS. */",
  "function createContinuousExecution(compiled: CompiledModel, hooks: {",
  "    check?: () => void;",
  "    maxRecordedValues?: number;",
  "    maxOperations?: number;",
  "    trackOperations?: boolean;",
  "} = {}) {",
  "    const execution = compiled.model.execution, solver = normalizeSolverSettings(execution);",
  "    const nodes = compiled.nodes, byId = new Map(nodes.map((node) => [node.id, node]));",
  "    const intervalCount = Math.round((execution.stopTime - execution.startTime) / execution.step);",
  "    const outputElements = compiled.outputIds.reduce((sum, id) => sum + signalElements(compiled.outputTypes[id]!), 1);",
  "    const fail = (code: string, message: string, nodeId?: string): never => { throw new ModelError([{ code, message, time: failureTime, ...(nodeId === undefined ? {} : { nodeId }) }]); };",
  "    let failureTime = execution.startTime;",
  "    if (hooks.maxOperations !== undefined && (!Number.isSafeInteger(hooks.maxOperations) || hooks.maxOperations < 1 || hooks.maxOperations > 50000000))",
  "        fail('RUNTIME_OPTIONS', '연산 한도를 확인해 주세요.');",
  "    if (hooks.maxRecordedValues !== undefined && (!Number.isSafeInteger(hooks.maxRecordedValues) || hooks.maxRecordedValues < 1 || hooks.maxRecordedValues > 1000000))",
  "        fail('RUNTIME_OPTIONS', '기록 한도를 확인해 주세요.');",
  "    if (intervalCount > 10000 || !Number.isSafeInteger(intervalCount) || intervalCount < 0)",
  "        fail('RUNTIME_STEP_BUDGET', '출력 시간 격자의 한도를 초과했습니다.');",
  "    if ((intervalCount + 1) * outputElements > (hooks.maxRecordedValues ?? 1000000))",
  "        fail('RUNTIME_RECORD_BUDGET', '결과 기록 한도를 초과했습니다.');",
  "    const discreteNodes = nodes.filter((node) => node.executionDomain === 'discrete' && node.blockType !== 'time.zero-order-hold');",
  "    const hasDiscreteBoundary = discreteNodes.length > 0 || nodes.some((node) => node.blockType === 'time.zero-order-hold' || node.blockType === 'time.first-order-hold');",
  "    const discreteIds = compiled.stateIds.filter((id) => discreteNodes.some((node) => node.id === id));",
  "    if (compiled.stateElements > 100000 || discreteMemoryElementCount(discreteNodes) > 100000)",
  "        fail('RUNTIME_STATE_BUDGET', '상태 메모리 한도를 초과했습니다.');",
  "    const costs = new Map(nodes.map((node) => [node.id, nodeOperationCost(node, byId)]));",
  "    const minimumTrials = Math.max(intervalCount, Math.ceil((execution.stopTime - execution.startTime) / solver.maxStep));",
  "    const minimumOperations = [...costs.values()].reduce((sum, cost) => sum + cost, 0)",
  "        * (intervalCount + 1 + minimumTrials * (solver.method === 'rk4' ? 4 : 7));",
  "    if (minimumOperations > (hooks.maxOperations ?? 50000000))",
  "        fail('RUNTIME_OPERATION_BUDGET', '최소 계산 연산량이 한도를 초과했습니다.');",
  "    let operations = 0;",
  "    const charge = (node: IRNode): void => {",
  "        const nextOperations = operations + costs.get(node.id)!;",
  "        if (nextOperations > (hooks.maxOperations ?? 50000000))",
  "            fail('RUNTIME_OPERATION_BUDGET', '계산 연산 한도를 초과했습니다.', node.id);",
  "        operations = nextOperations;",
  "        hooks.check?.();",
  "    };",
  "    const machine = createContinuousMachine(compiled, charge);",
  "    const discrete = createDiscreteMachine(discreteNodes, discreteIds, solver.discreteStep, execution.startTime, charge, nodes);",
  "    let frozen = discrete.snapshot(), state = [...machine.initial], time = execution.startTime, outputIndex = 0, tick = 0;",
  "    let previousTickValues: ContinuousValues | undefined, previousTick: number | undefined;",
  "    let stepSize = Math.min(solver.initialStep, machine.maximumDelayStep);",
  "    let values: ContinuousValues = new Map(), started = false, finished = false;",
  "    const samples: RunSample[] = [], events: SimulationEvent[] = [];",
  "    const stats: SolverStatistics = { method: solver.method, acceptedSteps: 0, rejectedSteps: 0, evaluations: 0, events: 0, lastStep: 0, minAcceptedStep: 0, maxAcceptedStep: 0 };",
  "    const near = (a: number, b: number): boolean => Number.isFinite(a) && Number.isFinite(b) && Math.abs(a - b) <= Math.max(Number.EPSILON * Math.max(1, Math.abs(a), Math.abs(b)) * 8, execution.step * 1e-12);",
  "    const outputTime = (): number => execution.startTime + outputIndex * execution.step;",
  "    const tickTime = (): number => execution.startTime + tick * solver.discreteStep;",
  "    const lastEventTimes = new Map<string, number>();",
  "    const lastRecordedEvents = new Map<string, number>();",
  "    function record(): void {",
  "        samples.push({ time: outputTime(), values: Object.fromEntries(compiled.outputIds.map((id) => [id, copySignal(checkSignal(values.get(id)?.out, compiled.outputTypes[id]!, id))])) });",
  "        outputIndex += 1;",
  "    }",
  "    function tickBoundary(mask = new Set<string>()): Set<string> {",
  "        // Expose the preceding tick's atomic commit only at its next tick. The",
  "        // frozen published outputs between ticks preserve M2 read-before-write.",
  "        if (previousTickValues && previousTick !== undefined)",
  "            discrete.transition(previousTickValues, previousTick);",
  "        // Resolve only a capture's producer ancestry before publishing that hold.",
  "        // Temporary initial hold values must never be evaluated by downstream math.",
  "        const evaluateBoundary = (capture: boolean, old = false): ContinuousValues => {",
  "            const resolved: ContinuousValues = new Map(), resolving = new Set<string>();",
  "            const resolve = (id: string): Record<string, SignalValue> => {",
  "                if (resolved.has(id))",
  "                    return resolved.get(id)!;",
  "                const node = byId.get(id)!;",
  "                if (resolving.has(id))",
  "                    fail('CYCLIC_CAPTURE_DEPENDENCY', '같은 시각의 샘플 capture에 대수 순환이 있습니다.', id);",
  "                resolving.add(id);",
  "                const read = (port: string) => { const endpoint = node.inputs[port]!; return resolve(endpoint.nodeId)[endpoint.portId]!; };",
  "                const hold = node.blockType === 'time.zero-order-hold' || node.blockType === 'time.first-order-hold';",
  "                if (capture && hold && tick >= node.sampleTime.offset && (tick - node.sampleTime.offset) % node.sampleTime.period === 0) {",
  "                    const endpoint = node.inputs.in!;",
  "                    resolve(endpoint.nodeId);",
  "                    machine.captureHolds(time, tick, resolved, undefined, node.id);",
  "                }",
  "                const outputs = node.executionDomain === 'discrete' && !hold",
  "                    ? old ? frozen.get(id)! : discrete.evaluateNode(node, tick, time, read)",
  "                    : machine.evaluateNode(node, time, state, read, mask);",
  "                resolved.set(id, outputs);",
  "                resolving.delete(id);",
  "                return outputs;",
  "            };",
  "            if (old) {",
  "                for (const node of nodes) {",
  "                    const guard = node.blockType === 'logic.hit-crossing' || node.blockType === 'nonlinear.relay'",
  "                        || node.blockType === 'nonlinear.saturation' && node.outputs.out?.shape.length === 0;",
  "                    const endpoint = guard ? node.inputs.in : node.blockType === 'continuous.integrator' && node.parameters.reset === 'rising' ? node.inputs.reset : undefined;",
  "                    if (endpoint) {",
  "                        try {",
  "                            resolve(endpoint.nodeId);",
  "                        }",
  "                        catch (error) {",
  "                            // No prior publication exists at initialization. Its guard starts",
  "                            // from the actual first value if a placeholder is outside domain.",
  "                            if (!(error instanceof ModelError) || !error.diagnostics.every((diagnostic) => diagnostic.code.startsWith('NUMERIC_')))",
  "                                throw error;",
  "                            resolving.clear();",
  "                        }",
  "                    }",
  "                }",
  "            }",
  "            else",
  "                for (const node of nodes)",
  "                    resolve(node.id);",
  "            return resolved;",
  "        };",
  "        let before = values.size ? values : evaluateBoundary(false, true);",
  "        values = evaluateBoundary(true);",
  "        frozen = discrete.snapshot();",
  "        // Fill only guards that had no meaningful pre-publication value at start.",
  "        for (const node of nodes)",
  "            for (const endpoint of Object.values(node.inputs))",
  "                if (!before.has(endpoint.nodeId))",
  "                    before.set(endpoint.nodeId, values.get(endpoint.nodeId)!);",
  "        // Settle instantaneous publications without integrating or drawing RNG again.",
  "        // This also initializes a Relay outside its hysteresis band at startTime.",
  "        while (true) {",
  "            const detected = [...machine.eventCandidates(before, values), ...machine.relaySettlingEvents(values)];",
  "            const boundary = detected.filter((event, index) => detected.findIndex((other) => other.nodeId === event.nodeId && other.kind === event.kind) === index);",
  "            if (!boundary.length)",
  "                break;",
  "            const previous = values, applied = machine.applyEvents(state, boundary, time, frozen);",
  "            state = applied.state;",
  "            mask = new Set([...mask, ...applied.mask]);",
  "            appendEvents(boundary);",
  "            boundary.forEach((event) => lastEventTimes.set(event.nodeId, time));",
  "            const postEvent = machine.evaluate(time, state, frozen, mask);",
  "            const resets = machine.eventCandidates(previous, postEvent).filter((event) => event.kind === 'reset' && !boundary.some((other) => other.nodeId === event.nodeId));",
  "            if (resets.length)",
  "                appendEvents(resets);",
  "            before = previous;",
  "            values = evaluateBoundary(true);",
  "            frozen = discrete.snapshot();",
  "        }",
  "        previousTickValues = new Map(values);",
  "        previousTick = tick;",
  "        tick += 1;",
  "        return mask;",
  "    }",
  "    function appendEvents(boundary: ContinuousEvent[]): void {",
  "        for (const kind of ['reset', 'crossing', 'relay'] as const) {",
  "            const nodeIds = [...new Set(boundary.filter((event) => event.kind === kind).map((event) => event.nodeId))]",
  "                .filter((id) => kind === 'relay' || lastRecordedEvents.get(`${kind}:${id}`) !== time).sort();",
  "            if (nodeIds.length) {",
  "                events.push({ time, nodeIds, kind });",
  "                stats.events += nodeIds.length;",
  "                nodeIds.forEach((id) => lastRecordedEvents.set(`${kind}:${id}`, time));",
  "            }",
  "        }",
  "        if (stats.events > solver.maxEvents)",
  "            fail('RUNTIME_EVENT_BUDGET', '이벤트 처리 한도를 초과했습니다.');",
  "    }",
  "    function settleRelayPublications(mask: Set<string>): Set<string> {",
  "        let detected = machine.relaySettlingEvents(values);",
  "        while (detected.length) {",
  "            const boundary = detected.filter((event, index) => detected.findIndex((other) => other.nodeId === event.nodeId && other.kind === event.kind) === index);",
  "            const previous = values, applied = machine.applyEvents(state, boundary, time, frozen);",
  "            state = applied.state;",
  "            mask = new Set([...mask, ...applied.mask]);",
  "            appendEvents(boundary);",
  "            boundary.forEach((event) => lastEventTimes.set(event.nodeId, time));",
  "            values = machine.evaluate(time, state, frozen, mask);",
  "            detected = [...machine.eventCandidates(previous, values), ...machine.relaySettlingEvents(values)];",
  "        }",
  "        return mask;",
  "    }",
  "    function sourceBoundary(): number {",
  "        let next = machine.nextDelayBoundary(time);",
  "        const consider = (value: number): void => { if (value > time && !near(value, time))",
  "            next = Math.min(next, value); };",
  "        for (const node of nodes) {",
  "            if (node.blockType === 'source.step')",
  "                consider(Number(node.parameters.stepTime));",
  "            if (node.blockType === 'source.ramp')",
  "                consider(Number(node.parameters.startTime));",
  "            if (node.blockType === 'source.dataset' && node.executionDomain === 'continuous') {",
  "                const times = node.parameters.times as number[];",
  "                let low = 0, high = times.length;",
  "                while (low < high) {",
  "                    const middle = (low + high) >>> 1;",
  "                    if (times[middle]! <= time || near(times[middle]!, time))",
  "                        low = middle + 1;",
  "                    else",
  "                        high = middle;",
  "                }",
  "                if (low < times.length)",
  "                    consider(times[low]!);",
  "            }",
  "            if (node.blockType === 'source.repeating-sequence') {",
  "                const times = node.parameters.times as number[], period = times.at(-1)!, cycle = Math.floor(time / period);",
  "                for (const offset of times) {",
  "                    consider(cycle * period + offset);",
  "                    consider((cycle + 1) * period + offset);",
  "                }",
  "            }",
  "        }",
  "        return next;",
  "    }",
  "    function trial(h: number, leftEndpoint?: number): {",
  "        state: number[];",
  "        error: number[];",
  "    } {",
  "        return rkTrial(solver.method, time, state, h, (stageTime, trialState) => {",
  "            failureTime = stageTime;",
  "            stats.evaluations += 1;",
  "            if (stats.evaluations > solver.maxEvaluations)",
  "                fail('RUNTIME_EVALUATION_BUDGET', '솔버 단계 평가 한도를 초과했습니다.');",
  "            const sourceTime = leftEndpoint !== undefined && near(stageTime, leftEndpoint)",
  "                ? stageTime - Math.max(h * 1e-10, Math.abs(stageTime) * Number.EPSILON * 2, Number.MIN_VALUE)",
  "                : stageTime === time ? rightSourceTime(stageTime) : stageTime;",
  "            return machine.derivative(stageTime, trialState, frozen, sourceTime);",
  "        });",
  "    }",
  "    function rightSourceTime(at: number): number {",
  "        // Raw playback includes its final knot. After that isolated endpoint, an",
  "        // outside-zero source contributes its right limit to RHS and delay history.",
  "        if (!nodes.some(node => node.blockType === 'source.dataset' && node.executionDomain === 'continuous' && node.parameters.outside === 'zero' && (node.parameters.times as number[]).at(-1) === at))",
  "            return at;",
  "        if (at === 0)",
  "            return Number.MIN_VALUE;",
  "        const bits = new DataView(new ArrayBuffer(8));",
  "        bits.setFloat64(0, at);",
  "        bits.setBigUint64(0, bits.getBigUint64(0) + (at > 0 ? 1n : -1n));",
  "        return bits.getFloat64(0);",
  "    }",
  "    function refine(event: ContinuousEvent, h: number): number {",
  "        let low = 0, high = h;",
  "        for (let iteration = 0; iteration < 64 && high - low > Math.max(solver.eventTolerance, Math.abs(time + high) * Number.EPSILON * 8); iteration += 1) {",
  "            const middle = (low + high) / 2, candidate = trial(middle).state;",
  "            const evaluated = machine.evaluate(time + middle, candidate, frozen);",
  "            if (machine.eventReached(event, evaluated))",
  "                high = middle;",
  "            else",
  "                low = middle;",
  "        }",
  "        return high;",
  "    }",
  "    function advanceInternal(): boolean {",
  "        hooks.check?.();",
  "        if (finished)",
  "            return false;",
  "        if (!started) {",
  "            started = true;",
  "            tickBoundary();",
  "            const sourceTime = rightSourceTime(time);",
  "            machine.acceptMemory(time, values, sourceTime === time ? values : machine.evaluate(time, state, frozen, new Set(), sourceTime), values);",
  "            record();",
  "            if (intervalCount === 0)",
  "                finished = true;",
  "            return !finished;",
  "        }",
  "        if (stats.acceptedSteps >= solver.maxSteps)",
  "            fail('RUNTIME_INTERNAL_STEP_BUDGET', '내부 적분 스텝 한도를 초과했습니다.');",
  "        const discontinuity = sourceBoundary();",
  "        const target = Math.min(outputTime(), hasDiscreteBoundary ? tickTime() : Infinity, discontinuity, execution.stopTime);",
  "        let h = Math.min(stepSize, target - time, solver.maxStep, machine.maximumDelayStep);",
  "        if (!(h > 0) || time + h === time)",
  "            fail('RUNTIME_TIME_RESOLUTION', '현재 시각에서 적분 간격을 표현할 수 없습니다.');",
  "        const atSourceBoundary = near(time + h, discontinuity);",
  "        const before = machine.evaluate(time, state, frozen);",
  "        let candidate = trial(h, atSourceBoundary ? discontinuity : undefined);",
  "        machine.validateState(candidate.state);",
  "        const norm = solver.method === 'rk45' ? rkErrorNorm(state, candidate.state, candidate.error, solver.atol, solver.rtol) : 0;",
  "        if (!Number.isFinite(norm))",
  "            fail('NUMERIC_NONFINITE', '솔버 오차 추정이 유한하지 않습니다.');",
  "        if (norm > 1) {",
  "            stats.rejectedSteps += 1;",
  "            if (stats.rejectedSteps > solver.maxRejects)",
  "                fail('RUNTIME_REJECTION_BUDGET', '솔버 스텝 거절 한도를 초과했습니다.');",
  "            if (h <= solver.minStep * (1 + 1e-12))",
  "                fail('RUNTIME_MIN_STEP', '최소 적분 간격에서도 허용오차를 만족하지 못했습니다.');",
  "            stepSize = rkNextStep(h, norm, false, solver.minStep, solver.maxStep);",
  "            return true;",
  "        }",
  "        let after = machine.evaluate(time + h, candidate.state, frozen);",
  "        const candidates = machine.eventCandidates(before, after).filter((event) => !near(lastEventTimes.get(event.nodeId) ?? -Infinity, time));",
  "        let boundaryEvents: ContinuousEvent[] = [];",
  "        if (candidates.length) {",
  "            const located = candidates.map((event) => ({ event, h: refine(event, h) }));",
  "            const first = Math.min(...located.map((event) => event.h));",
  "            boundaryEvents = located.filter((event) => Math.abs(event.h - first) <= solver.eventTolerance).map((event) => event.event);",
  "            if (first < h && !near(first, h)) {",
  "                h = first;",
  "                candidate = trial(h);",
  "                after = machine.evaluate(time + h, candidate.state, frozen);",
  "            }",
  "        }",
  "        const previousValues = values;",
  "        const leftValues = machine.evaluate(time + h, candidate.state, frozen, new Set(), near(time + h, discontinuity)",
  "            ? time + h - Math.max(h * 1e-10, Math.abs(time + h) * Number.EPSILON * 2, Number.MIN_VALUE) : time + h);",
  "        state = candidate.state;",
  "        time = near(time + h, target) ? target : time + h;",
  "        failureTime = time;",
  "        stats.acceptedSteps += 1;",
  "        stats.lastStep = h;",
  "        stats.minAcceptedStep = stats.minAcceptedStep === 0 ? h : Math.min(stats.minAcceptedStep, h);",
  "        stats.maxAcceptedStep = Math.max(stats.maxAcceptedStep, h);",
  "        let mask = new Set<string>();",
  "        if (boundaryEvents.length) {",
  "            const applied = machine.applyEvents(state, boundaryEvents, time, frozen);",
  "            state = applied.state;",
  "            mask = applied.mask;",
  "            boundaryEvents.forEach((event) => lastEventTimes.set(event.nodeId, time));",
  "            appendEvents(boundaryEvents);",
  "            // Record resets driven by a HitCrossing in the same boundary explicitly.",
  "            const resetEvents = machine.eventCandidates(before, machine.evaluate(time, state, frozen, mask)).filter((event) => event.kind === 'reset' && !boundaryEvents.some((current) => current.nodeId === event.nodeId));",
  "            if (resetEvents.length)",
  "                appendEvents(resetEvents);",
  "        }",
  "        values = machine.evaluate(time, state, frozen, mask);",
  "        mask = settleRelayPublications(mask);",
  "        if (hasDiscreteBoundary && near(time, tickTime()))",
  "            mask = tickBoundary(mask);",
  "        const sourceTime = rightSourceTime(time);",
  "        machine.acceptMemory(time, previousValues, sourceTime === time ? values : machine.evaluate(time, state, frozen, mask, sourceTime), leftValues);",
  "        values = machine.evaluate(time, state, frozen, mask);",
  "        if (near(time, outputTime()))",
  "            record();",
  "        stepSize = solver.method === 'rk45' ? rkNextStep(h, norm, true, solver.minStep, solver.maxStep) : solver.initialStep;",
  "        if (near(time, execution.stopTime))",
  "            finished = true;",
  "        return !finished;",
  "    }",
  "    function result(status: RunResult['status'], elapsedMs = 0): RunResult {",
  "        const projected = values.size ? machine.finalState(state, values) : {};",
  "        return { samples: samples.map((sample) => ({ time: sample.time, values: Object.fromEntries(Object.entries(sample.values).map(([id, value]) => [id, copySignal(value)])) })),",
  "            finalState: { ...projected, ...discrete.finalState() }, stateMemory: { ...machine.stateMemory(state), ...discrete.stateMemory(true) }, stateTime: time, status, elapsedMs, steps: samples.length, ...(hooks.trackOperations ? { resources: { operations } } : {}),",
  "            solverStatistics: { ...stats }, events: events.map((event) => ({ ...event, nodeIds: [...event.nodeIds] })) };",
  "    }",
  "    function advance(): boolean {",
  "        const saved = { state, time, values, frozen, outputIndex, tick, previousTickValues, previousTick, started, finished,",
  "            sampleLength: samples.length, eventLength: events.length, memory: machine.checkpoint(), discrete: discrete.checkpoint(),",
  "            lastEvents: new Map(lastEventTimes), recordedEvents: new Map(lastRecordedEvents), acceptedSteps: stats.acceptedSteps, eventCount: stats.events,",
  "            lastStep: stats.lastStep, minStep: stats.minAcceptedStep, maxStep: stats.maxAcceptedStep };",
  "        try {",
  "            return advanceInternal();",
  "        }",
  "        catch (error) {",
  "            state = saved.state;",
  "            time = saved.time;",
  "            values = saved.values;",
  "            frozen = saved.frozen;",
  "            outputIndex = saved.outputIndex;",
  "            tick = saved.tick;",
  "            previousTickValues = saved.previousTickValues;",
  "            previousTick = saved.previousTick;",
  "            started = saved.started;",
  "            finished = saved.finished;",
  "            samples.length = saved.sampleLength;",
  "            events.length = saved.eventLength;",
  "            machine.restore(saved.memory);",
  "            discrete.restore(saved.discrete);",
  "            lastEventTimes.clear();",
  "            saved.lastEvents.forEach((value, id) => lastEventTimes.set(id, value));",
  "            lastRecordedEvents.clear();",
  "            saved.recordedEvents.forEach((value, id) => lastRecordedEvents.set(id, value));",
  "            stats.acceptedSteps = saved.acceptedSteps;",
  "            stats.events = saved.eventCount;",
  "            stats.lastStep = saved.lastStep;",
  "            stats.minAcceptedStep = saved.minStep;",
  "            stats.maxAcceptedStep = saved.maxStep;",
  "            if (error instanceof ModelError)",
  "                throw new ModelError(error.diagnostics.map((diagnostic) => ({ ...diagnostic, time: diagnostic.time ?? failureTime })), result('failed'));",
  "            throw error;",
  "        }",
  "    }",
  "    return { advance, result, get currentTime() { return time; }, get sampleCount() { return samples.length; }, stats };",
  "}"
].join('\n');
