import { getBlockDefinition } from '../../block-library/src';
import { ModelError } from '../../model/src/types';
import type { CompiledModel } from '../../model/src/types';
import { nodeOperationCost, signalElements } from '../../runtime/src/kernels';
import { discreteMemoryElementCount } from '../../model/src/discrete';
import { KERNEL_TEMPLATE } from './kernels-template';
import { DISCRETE_TEMPLATE } from './discrete-template';
import { SIGNAL_TYPES_TEMPLATE } from './signal-types-template';
import { manifestForHash, type ExportManifest } from './manifest';
import { sha256 } from './sha256';
import { exportContinuousTypeScript } from './continuous';
export { createExportManifest, type ExportManifest } from './manifest';

/** Generate an import-free program from validated IR and fixed numerical sources. */
export function exportTypeScript(compiled: CompiledModel, manifest?: ExportManifest): string {
  const metadata = manifestForHash(compiled, sha256(compiled.semanticKey));
  if (manifest && manifest.modelHash !== metadata.modelHash) throw new ModelError([{ code: 'EXPORT_MANIFEST_MISMATCH', message: 'manifest의 모델 hash가 실행 스냅샷과 다릅니다.' }]);
  const byId = new Map(compiled.nodes.map((node) => [node.id, node]));
  for (const node of compiled.nodes) {
    if (!getBlockDefinition(node.blockType)?.exportTargets.includes('typescript')) {
      throw new ModelError([{ code: 'EXPORT_UNSUPPORTED_BLOCK', message: 'TypeScript export를 지원하지 않는 블럭입니다.', nodeId: node.id }]);
    }
    for (const endpoint of Object.values(node.inputs)) {
      if (!byId.get(endpoint.nodeId)?.outputs[endpoint.portId]) {
        throw new ModelError([{ code: 'EXPORT_INVALID_IR', message: '연결된 출력 포트가 중간 표현에 없습니다.', nodeId: node.id }]);
      }
    }
  }
  if (compiled.model.execution.mode === 'continuous') return exportContinuousTypeScript(compiled, metadata);
  const data = {
    settings: compiled.model.execution,
    nodes: compiled.nodes.map((node) => ({
      id: node.id, blockType: node.blockType,
      // Expressions are represented only by their bounded compiler-owned AST.
      parameters: Object.fromEntries(Object.entries(node.parameters).filter(([key]) => node.blockType !== 'math.expression' || key !== 'expression')),
      inputs: node.inputs, outputs: node.outputs, sampleTime: node.sampleTime,
      ...(node.expression ? { expression: node.expression } : {}),
      cost: nodeOperationCost(node, byId),
    })),
    states: compiled.stateIds, outputs: compiled.outputIds,
    outputTypes: compiled.outputTypes,
    stateElements: discreteMemoryElementCount(compiled.nodes),
    recordedElements: compiled.outputIds.reduce((count, id) => count + signalElements(compiled.outputTypes[id]!), 1),
  };
  // Validated IDs and values are data, never executable identifiers or snippets.
  const literal = JSON.stringify(data).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  const manifestLiteral = JSON.stringify(metadata).replace(/\u2028/g, '\\u2028').replace(/\u2029/g, '\\u2029');
  return `// Generated by CalcWeave M2. Standalone typed static/fixed-tick discrete execution.
${SIGNAL_TYPES_TEMPLATE}
type ExpressionNode =
  | { type: 'number'; value: number }
  | { type: 'variable'; name: 'x' | 'pi' | 'e' }
  | { type: 'unary'; operator: '+' | '-'; argument: ExpressionNode }
  | { type: 'binary'; operator: '+' | '-' | '*' | '/' | '^'; left: ExpressionNode; right: ExpressionNode }
  | { type: 'call'; name: string; args: ExpressionNode[] };
type IRNode = { id: string; blockType: string; parameters: Record<string, unknown>; inputs: Record<string, { nodeId: string; portId: string }>; outputs: Record<string, SignalDescriptor>; sampleTime: { period: number; offset: number }; expression?: ExpressionNode; cost: number };
type Sample = { time: number; values: Record<string, SignalValue> };
type Result = { samples: Sample[]; finalState: Record<string, SignalValue>; stateMemory?: Record<string, StateValue>; status: 'completed' | 'failed'; steps: number };
const data: { settings: { mode: string; startTime: number; stopTime: number; step: number }; nodes: IRNode[]; states: string[]; outputs: string[]; outputTypes: Record<string, SignalDescriptor>; recordedElements: number; stateElements: number } = ${literal};
const exportManifest = ${manifestLiteral};
/** The generator computed SHA-256 synchronously over the same canonical semantic key as Web Crypto. */
export function getManifest(): typeof exportManifest { return JSON.parse(JSON.stringify(exportManifest)) as typeof exportManifest; }
${KERNEL_TEMPLATE}
${DISCRETE_TEMPLATE}
export function run(): Result {
  const { settings, nodes, states, outputs } = data;
  const failure = (code: string, message: string): never => { throw new ModelError([{code,message}]); };
  const sampleStep = <T>(tick: number, time: number, operation: ()=>T): T => {
    try { return operation(); }
    catch (error) { if (error instanceof ModelError) throw new ModelError(error.diagnostics.map((diagnostic)=>({...diagnostic,tick,time}))); throw error; }
  };
  const intervals = settings.mode === 'static' ? 0 : Math.round((settings.stopTime - settings.startTime) / settings.step);
  if (!Number.isSafeInteger(intervals) || intervals < 0 || intervals > 10000) failure('RUNTIME_STEP_BUDGET','실행 tick 수가 한도를 초과했습니다.');
  if ((intervals + 1) * data.recordedElements > 1000000) failure('RUNTIME_RECORD_BUDGET','결과 기록 한도를 초과했습니다. 시간 범위나 기록 신호를 줄여 주세요.');
  if (data.stateElements > 100000) failure('RUNTIME_STATE_BUDGET','상태와 hold 메모리 한도를 초과했습니다.');
  const perTickCost = nodes.reduce((count, node) => count + node.cost, 0);
  const stateCost = settings.mode === 'discrete' ? nodes.filter((node) => states.includes(node.id)).reduce((count, node) => count + node.cost, 0) * intervals : 0;
  if ((intervals + 1) * perTickCost + stateCost > 50000000) failure('RUNTIME_OPERATION_BUDGET','계산 연산 한도를 초과했습니다.');
  const byId = new Map(nodes.map((node) => [node.id, node]));
  const samples: Sample[] = [];
  const clock = (globalThis as { performance?: { now(): number } }).performance;
  const now = typeof clock?.now === 'function' ? () => clock.now() : () => Date.now();
  const started = now();
  let operations = 0, nextBudgetCheck = 64;
  const checkBudget = (): void => {
    if (now() - started > 30000) failure('RUNTIME_WALL_BUDGET','실행 시간 한도를 초과했습니다.');
    if (operations > 50000000) failure('RUNTIME_OPERATION_BUDGET','계산 연산 한도를 초과했습니다.');
  };
  const charge = (node: IRNode): void => {
    operations += node.cost;
    if (operations >= nextBudgetCheck) { checkBudget(); nextBudgetCheck = operations + 64; }
  };
  const machine = settings.mode === 'discrete' ? sampleStep(0,settings.startTime,()=>createDiscreteMachine(nodes, states, settings.step, settings.startTime, charge)) : undefined;
  const snapshot = (status: Result['status']): Result => {
    const stateMemory = machine?.stateMemory();
    return { samples, finalState: machine?.finalState() ?? {}, ...(stateMemory === undefined ? {} : { stateMemory }), status, steps: samples.length };
  };
  let previousValues: Map<string, Record<string, SignalValue>> | undefined;
  let tickCheckpoint: ReturnType<NonNullable<typeof machine>['checkpoint']> | undefined;
  try {
  for (let tick = 0; tick <= intervals; tick += 1) {
    checkBudget();
    tickCheckpoint = machine?.checkpoint();
    if (machine && previousValues) sampleStep(tick-1,settings.startTime+(tick-1)*settings.step,()=>machine.transition(previousValues!, tick - 1));
    const time = settings.startTime + tick * settings.step;
    const values = machine ? sampleStep(tick,time,()=>machine.evaluate(tick, time)) : new Map<string, Record<string, SignalValue>>();
    const input = (node: IRNode, port: string): SignalValue => {
      const endpoint = node.inputs[port];
      const value = endpoint && values.get(endpoint.nodeId)?.[endpoint.portId];
      if (value === undefined) numericFailure('RUNTIME_INVALID_IR', node.id, '연결된 출력 값을 읽을 수 없습니다.');
      return value;
    };
    for (const node of machine ? [] : nodes) {
      charge(node);
      const emitted = evaluateSignalNode(node, (port) => input(node, port), undefined, time);
      for (const [port, descriptor] of Object.entries(node.outputs)) checkSignal(emitted[port], descriptor, node.id);
      values.set(node.id, emitted);
    }
    samples.push({ time, values: Object.fromEntries(outputs.map((id) => [id, copySignal(checkSignal(values.get(id)?.out, data.outputTypes[id]!, id))])) });
    tickCheckpoint = undefined;
    previousValues = values;
  }
  checkBudget();
  } catch (error) {
    if (error instanceof ModelError) {
      if (tickCheckpoint) machine!.restore(tickCheckpoint);
      throw new ModelError(error.diagnostics, snapshot('failed'));
    }
    throw error;
  }
  return snapshot('completed');
}
`;
}
