// Generated from repository-owned runtime sources by sync-runtime-templates.ts.
export const KERNEL_TEMPLATE = [
  "class ModelError extends Error {",
  "  constructor(public readonly diagnostics: { code: string; nodeId?: string; message: string; tick?: number; time?: number }[], public readonly partialResult?: unknown) {",
  "    super(diagnostics[0]?.code + (diagnostics[0]?.nodeId ? ': ' + diagnostics[0].nodeId : ''));",
  "    this.name = 'ModelError';",
  "  }",
  "}",
  "function fail(code: string, message: string): never { throw new ModelError([{ code, message }]); }",
  "function finite(value: number): number {",
  "    if (!Number.isFinite(value))",
  "        fail('NUMERIC_NONFINITE', '수식에서 유한하지 않은 계산값이 발생했습니다.');",
  "    return value;",
  "}",
  "/** Evaluate a compiler-owned AST, never the original expression string. */",
  "function evaluateExpression(ast: ExpressionNode, x: number): number {",
  "    finite(x);",
  "    function evaluate(node: ExpressionNode): number {",
  "        if (node.type === 'number')",
  "            return finite(node.value);",
  "        if (node.type === 'variable')",
  "            return node.name === 'x' ? x : node.name === 'pi' ? Math.PI : Math.E;",
  "        if (node.type === 'unary')",
  "            return finite((node.operator === '-' ? -1 : 1) * evaluate(node.argument));",
  "        if (node.type === 'binary') {",
  "            const a = evaluate(node.left), b = evaluate(node.right);",
  "            if (node.operator === '/' && b === 0)",
  "                fail('NUMERIC_DIVIDE_BY_ZERO', '수식에서 0으로 나눌 수 없습니다.');",
  "            if (node.operator === '^' && a < 0 && !Number.isInteger(b))",
  "                fail('NUMERIC_DOMAIN', '음수의 비정수 거듭제곱은 실수 범위를 벗어납니다.');",
  "            switch (node.operator) {",
  "                case '+': return finite(a + b);",
  "                case '-': return finite(a - b);",
  "                case '*': return finite(a * b);",
  "                case '/': return finite(a / b);",
  "                case '^': return finite(a ** b);",
  "            }",
  "        }",
  "        const args = node.args.map(evaluate);",
  "        const a = args[0]!;",
  "        if (node.name === 'sqrt' && a < 0)",
  "            fail('NUMERIC_DOMAIN', 'sqrt의 입력은 0 이상이어야 합니다.');",
  "        if ((node.name === 'log' || node.name === 'log10') && a <= 0)",
  "            fail('NUMERIC_DOMAIN', 'log의 입력은 0보다 커야 합니다.');",
  "        if ((node.name === 'asin' || node.name === 'acos') && (a < -1 || a > 1))",
  "            fail('NUMERIC_DOMAIN', 'asin·acos의 입력은 -1~1이어야 합니다.');",
  "        switch (node.name) {",
  "            case 'abs': return finite(Math.abs(a));",
  "            case 'sqrt': return finite(Math.sqrt(a));",
  "            case 'sin': return finite(Math.sin(a));",
  "            case 'cos': return finite(Math.cos(a));",
  "            case 'tan': return finite(Math.tan(a));",
  "            case 'asin': return finite(Math.asin(a));",
  "            case 'acos': return finite(Math.acos(a));",
  "            case 'atan': return finite(Math.atan(a));",
  "            case 'exp': return finite(Math.exp(a));",
  "            case 'log': return finite(Math.log(a));",
  "            case 'log10': return finite(Math.log10(a));",
  "            case 'floor': return finite(Math.floor(a));",
  "            case 'ceil': return finite(Math.ceil(a));",
  "            case 'round': return finite(Math.round(a));",
  "            case 'trunc': return finite(Math.trunc(a));",
  "            case 'min': return finite(Math.min(a, args[1]!));",
  "            case 'max': return finite(Math.max(a, args[1]!));",
  "            default: return fail('EXPRESSION_SYNTAX', '허용하지 않는 수식 함수입니다.');",
  "        }",
  "    }",
  "    return evaluate(ast);",
  "}",
  "const ADVANCED_MATH_LIMITS = Object.freeze({ maxAxis: 32, maxElements: 1024, minBreakpoints: 2, maxBreakpoints: 32, pivotEpsilonMultiplier: 32 });",
  "type NumericMatrix = number[][];",
  "type LookupExtrapolation = 'clip' | 'linear' | 'error';",
  "interface Lookup2DOptions {",
  "    rowBreakpoints: number[];",
  "    columnBreakpoints: number[];",
  "    table: NumericMatrix;",
  "    interpolation: 'linear' | 'nearest' | 'previous';",
  "    extrapolation: LookupExtrapolation;",
  "}",
  "interface PrelookupResult {",
  "    index: number;",
  "    fraction: number;",
  "}",
  "interface LUResult {",
  "    lower: NumericMatrix;",
  "    upper: NumericMatrix;",
  "    permutation: number[];",
  "}",
  "function advancedFail(code: string, message: string): never { throw new ModelError([{ code, message }]); }",
  "function advancedFinite(value: number): number {",
  "    if (!Number.isFinite(value))",
  "        advancedFail('MATRIX_NUMERIC_NONFINITE', '계산 결과가 유한한 float64 범위를 초과했습니다.');",
  "    return value;",
  "}",
  "function advancedDenseArray(input: unknown, min: number, max: number, code: string): unknown[] {",
  "    if (!Array.isArray(input) || Object.getPrototypeOf(input) !== Array.prototype || input.length < min || input.length > max)",
  "        advancedFail(code, `길이 ${min}~${max}의 일반 배열이 필요합니다.`);",
  "    const descriptors = Object.getOwnPropertyDescriptors(input);",
  "    if (Reflect.ownKeys(descriptors).length !== input.length + 1)",
  "        advancedFail(code, '배열에는 빈 칸이나 추가 필드를 사용할 수 없습니다.');",
  "    const result: unknown[] = [];",
  "    for (let index = 0; index < input.length; index += 1) {",
  "        const descriptor = descriptors[String(index)];",
  "        if (!descriptor || !('value' in descriptor) || !descriptor.enumerable)",
  "            advancedFail(code, '배열에는 빈 칸·접근자·숨김 항목을 사용할 수 없습니다.');",
  "        result.push(descriptor.value);",
  "    }",
  "    return result;",
  "}",
  "/** Return a defensive dense finite real matrix, with independently bounded axes. */",
  "function validateMatrix(input: unknown): NumericMatrix {",
  "    const rows = advancedDenseArray(input, 1, ADVANCED_MATH_LIMITS.maxAxis, 'INVALID_MATRIX');",
  "    let columns = 0;",
  "    return rows.map(row => {",
  "        const values = advancedDenseArray(row, 1, ADVANCED_MATH_LIMITS.maxAxis, 'INVALID_MATRIX');",
  "        if (columns && columns !== values.length)",
  "            advancedFail('INVALID_MATRIX', '행렬의 모든 행은 같은 길이여야 합니다.');",
  "        columns = values.length;",
  "        return values.map(value => {",
  "            if (typeof value !== 'number' || !Number.isFinite(value))",
  "                advancedFail('INVALID_MATRIX', '행렬 원소는 유한한 실수 float64여야 합니다.');",
  "            return value;",
  "        });",
  "    });",
  "}",
  "function validateBreakpoints(input: unknown): number[] {",
  "    const values = advancedDenseArray(input, ADVANCED_MATH_LIMITS.minBreakpoints, ADVANCED_MATH_LIMITS.maxBreakpoints, 'INVALID_BREAKPOINTS');",
  "    const points: number[] = [];",
  "    for (const value of values) {",
  "        if (typeof value !== 'number' || !Number.isFinite(value) || (points.length && value <= points.at(-1)!))",
  "            advancedFail('INVALID_BREAKPOINTS', 'breakpoint는 유한한 숫자 2~32개이며 엄격하게 증가해야 합니다.');",
  "        points.push(value);",
  "    }",
  "    return points;",
  "}",
  "function validateLookup2DOptions(input: unknown): Lookup2DOptions {",
  "    if (input === null || typeof input !== 'object' || (Object.getPrototypeOf(input) !== Object.prototype && Object.getPrototypeOf(input) !== null))",
  "        advancedFail('INVALID_LOOKUP_2D', '2D lookup 설정은 일반 객체여야 합니다.');",
  "    const properties = Object.getOwnPropertyDescriptors(input);",
  "    const keys = ['rowBreakpoints', 'columnBreakpoints', 'table', 'interpolation', 'extrapolation'];",
  "    if (Reflect.ownKeys(properties).length !== keys.length || Reflect.ownKeys(properties).some(key => typeof key !== 'string' || !keys.includes(key) || !('value' in properties[key]!) || !properties[key]!.enumerable))",
  "        advancedFail('INVALID_LOOKUP_2D', '2D lookup에는 명시적인 breakpoint·table·보간·범위 밖 옵션만 사용할 수 있습니다.');",
  "    const rowBreakpoints = validateBreakpoints(properties.rowBreakpoints!.value), columnBreakpoints = validateBreakpoints(properties.columnBreakpoints!.value);",
  "    const table = validateMatrix(properties.table!.value);",
  "    if (table.length !== rowBreakpoints.length || table[0]!.length !== columnBreakpoints.length)",
  "        advancedFail('LOOKUP_TABLE_SHAPE', '2D table의 행/열은 각 breakpoint 개수와 같아야 합니다.');",
  "    const interpolation = properties.interpolation!.value, extrapolation = properties.extrapolation!.value;",
  "    if (!['linear', 'nearest', 'previous'].includes(interpolation) || !['clip', 'linear', 'error'].includes(extrapolation) || (extrapolation === 'linear' && interpolation !== 'linear'))",
  "        advancedFail('INVALID_LOOKUP_2D', '선형 외삽은 linear 보간에서만 사용할 수 있습니다.');",
  "    return { rowBreakpoints, columnBreakpoints, table, interpolation, extrapolation };",
  "}",
  "function advancedCompensatedSum(values: readonly number[]): number {",
  "    let sum = 0, correction = 0;",
  "    for (const value of values) {",
  "        const next = sum + value;",
  "        correction += Math.abs(sum) >= Math.abs(value) ? (sum - next) + value : (value - next) + sum;",
  "        sum = next;",
  "    }",
  "    return advancedFinite(sum + correction);",
  "}",
  "interface AdvancedScaledNumber {",
  "    mantissa: number;",
  "    exponent: number;",
  "}",
  "function advancedScaledNumber(value: number): AdvancedScaledNumber {",
  "    if (value === 0)",
  "        return { mantissa: 0, exponent: 0 };",
  "    const exponent = Math.min(1023, Math.floor(Math.log2(Math.abs(value))));",
  "    return { mantissa: value / 2 ** exponent, exponent };",
  "}",
  "function advancedNormalizeScaled(value: AdvancedScaledNumber): AdvancedScaledNumber {",
  "    if (value.mantissa === 0)",
  "        return { mantissa: 0, exponent: 0 };",
  "    const part = advancedScaledNumber(value.mantissa);",
  "    return { mantissa: part.mantissa, exponent: value.exponent + part.exponent };",
  "}",
  "function advancedScaledFactors(factors: readonly number[], denominators: readonly number[] = []): AdvancedScaledNumber {",
  "    let value: AdvancedScaledNumber = { mantissa: 1, exponent: 0 };",
  "    for (const factor of factors) {",
  "        if (factor === 0)",
  "            return { mantissa: 0, exponent: 0 };",
  "        const part = advancedScaledNumber(factor);",
  "        value = advancedNormalizeScaled({ mantissa: value.mantissa * part.mantissa, exponent: value.exponent + part.exponent });",
  "    }",
  "    for (const divisor of denominators) {",
  "        const part = advancedScaledNumber(divisor);",
  "        value = advancedNormalizeScaled({ mantissa: value.mantissa / part.mantissa, exponent: value.exponent - part.exponent });",
  "    }",
  "    return value;",
  "}",
  "function advancedMaterializeScaled(input: AdvancedScaledNumber): number {",
  "    const value = advancedNormalizeScaled(input);",
  "    if (value.mantissa === 0)",
  "        return 0;",
  "    if (value.exponent > 1023)",
  "        advancedFail('MATRIX_NUMERIC_NONFINITE', '계산 결과가 유한한 float64 범위를 초과했습니다.');",
  "    if (value.exponent < -1074)",
  "        advancedFail('MATRIX_NUMERIC_UNDERFLOW', '0이 아닌 계산 결과가 float64 최소 표현 범위보다 작습니다.');",
  "    const result = advancedFinite(value.mantissa * 2 ** value.exponent);",
  "    if (result === 0)",
  "        advancedFail('MATRIX_NUMERIC_UNDERFLOW', '0이 아닌 계산 결과가 float64 최소 표현 범위보다 작습니다.');",
  "    return result;",
  "}",
  "function advancedScaledProduct(factors: readonly number[], denominators: readonly number[] = []): number { return advancedMaterializeScaled(advancedScaledFactors(factors, denominators)); }",
  "/** Group product exponents so large cancelling terms need not overflow before summation. */",
  "function advancedScaledDot(terms: readonly (readonly number[])[]): number {",
  "    const groups = new Map<number, number[]>();",
  "    for (const factors of terms) {",
  "        const part = advancedScaledFactors(factors);",
  "        if (part.mantissa === 0)",
  "            continue;",
  "        const group = groups.get(part.exponent) ?? [];",
  "        group.push(part.mantissa);",
  "        groups.set(part.exponent, group);",
  "    }",
  "    let total: AdvancedScaledNumber = { mantissa: 0, exponent: 0 };",
  "    for (const exponent of [...groups.keys()].sort((a, b) => b - a)) {",
  "        const mantissa = advancedCompensatedSum(groups.get(exponent)!);",
  "        if (mantissa === 0)",
  "            continue;",
  "        const term = advancedNormalizeScaled({ mantissa, exponent });",
  "        if (total.mantissa === 0) {",
  "            total = term;",
  "            continue;",
  "        }",
  "        const scale = Math.max(total.exponent, term.exponent);",
  "        total = advancedNormalizeScaled({ mantissa: advancedCompensatedSum([total.mantissa * 2 ** (total.exponent - scale), term.mantissa * 2 ** (term.exponent - scale)]), exponent: scale });",
  "    }",
  "    return advancedMaterializeScaled(total);",
  "}",
  "function matrixMultiply(a: NumericMatrix, b: NumericMatrix): NumericMatrix {",
  "    const left = validateMatrix(a), right = validateMatrix(b);",
  "    if (left[0]!.length !== right.length)",
  "        advancedFail('MATRIX_DIMENSION_MISMATCH', '행렬 곱의 왼쪽 열 수와 오른쪽 행 수가 같아야 합니다.');",
  "    return left.map(row => right[0]!.map((_, column) => advancedScaledDot(row.map((value, index) => [value, right[index]![column]!]))));",
  "}",
  "function transpose(a: NumericMatrix): NumericMatrix { const matrix = validateMatrix(a); return matrix[0]!.map((_, column) => matrix.map(row => row[column]!)); }",
  "function advancedSquare(a: NumericMatrix): NumericMatrix { const matrix = validateMatrix(a); if (matrix.length !== matrix[0]!.length)",
  "    advancedFail('MATRIX_NOT_SQUARE', '이 연산에는 정사각 행렬이 필요합니다.'); return matrix; }",
  "function advancedInfinityNorm(a: NumericMatrix): number { return Math.max(...a.map(row => advancedCompensatedSum(row.map(Math.abs)))); }",
  "interface AdvancedLUFactors {",
  "    lower: NumericMatrix;",
  "    upper: NumericMatrix;",
  "    permutation: number[];",
  "    scale: number;",
  "    sign: number;",
  "    norm: number;",
  "    singular: boolean;",
  "}",
  "function advancedFactorize(a: NumericMatrix, allowSingular = false): AdvancedLUFactors {",
  "    const size = a.length, scale = Math.max(...a.flat().map(Math.abs));",
  "    const lower: NumericMatrix = Array.from({ length: size }, (_, row) => Array.from({ length: size }, (_, column) => row === column ? 1 : 0));",
  "    const permutation = Array.from({ length: size }, (_, index) => index);",
  "    if (scale === 0) {",
  "        if (!allowSingular)",
  "            advancedFail('MATRIX_SINGULAR', '행렬이 특이하여 역행렬 또는 유일한 해를 구할 수 없습니다.');",
  "        return { lower, upper: a.map(row => [...row]), permutation, scale, sign: 1, norm: 0, singular: true };",
  "    }",
  "    const upper = a.map(row => row.map(value => {",
  "        const normalized = value / scale;",
  "        if (value !== 0 && normalized === 0)",
  "            advancedFail('MATRIX_ILL_CONDITIONED', '행렬 원소의 척도 차이가 너무 커 안정적으로 계산할 수 없습니다.');",
  "        return normalized;",
  "    }));",
  "    const norm = advancedInfinityNorm(upper), tolerance = ADVANCED_MATH_LIMITS.pivotEpsilonMultiplier * size * Number.EPSILON * norm;",
  "    let sign = 1;",
  "    for (let column = 0; column < size; column += 1) {",
  "        let pivot = column;",
  "        for (let row = column + 1; row < size; row += 1)",
  "            if (Math.abs(upper[row]![column]!) > Math.abs(upper[pivot]![column]!))",
  "                pivot = row;",
  "        const pivotValue = Math.abs(upper[pivot]![column]!);",
  "        if (pivotValue === 0) {",
  "            if (!allowSingular)",
  "                advancedFail('MATRIX_SINGULAR', '행렬이 특이하여 역행렬 또는 유일한 해를 구할 수 없습니다.');",
  "            return { lower, upper, permutation, scale, sign, norm, singular: true };",
  "        }",
  "        if (pivotValue <= tolerance)",
  "            advancedFail('MATRIX_ILL_CONDITIONED', '행렬 pivot가 척도 상대 허용오차보다 작습니다. 행렬의 조건을 개선해 주세요.');",
  "        if (pivot !== column) {",
  "            [upper[column], upper[pivot]] = [upper[pivot]!, upper[column]!];",
  "            [permutation[column], permutation[pivot]] = [permutation[pivot]!, permutation[column]!];",
  "            for (let previous = 0; previous < column; previous += 1)",
  "                [lower[column]![previous], lower[pivot]![previous]] = [lower[pivot]![previous]!, lower[column]![previous]!];",
  "            sign = -sign;",
  "        }",
  "        for (let row = column + 1; row < size; row += 1) {",
  "            const multiplier = upper[row]![column]! / upper[column]![column]!;",
  "            lower[row]![column] = multiplier;",
  "            upper[row]![column] = 0;",
  "            for (let following = column + 1; following < size; following += 1)",
  "                upper[row]![following] = advancedFinite(upper[row]![following]! - multiplier * upper[column]![following]!);",
  "        }",
  "    }",
  "    return { lower, upper, permutation, scale, sign, norm, singular: false };",
  "}",
  "function advancedIdentity(size: number): NumericMatrix { return Array.from({ length: size }, (_, row) => Array.from({ length: size }, (_, column) => row === column ? 1 : 0)); }",
  "function advancedSolveFactors(factors: AdvancedLUFactors, rhs: NumericMatrix): NumericMatrix {",
  "    const { lower, upper, permutation } = factors, size = upper.length, columns = rhs[0]!.length;",
  "    const result = permutation.map(row => [...rhs[row]!]);",
  "    for (let row = 0; row < size; row += 1)",
  "        for (let column = 0; column < columns; column += 1)",
  "            result[row]![column] = advancedFinite(result[row]![column]! - advancedCompensatedSum(Array.from({ length: row }, (_, k) => lower[row]![k]! * result[k]![column]!)));",
  "    for (let row = size - 1; row >= 0; row -= 1)",
  "        for (let column = 0; column < columns; column += 1)",
  "            result[row]![column] = advancedFinite((result[row]![column]! - advancedCompensatedSum(Array.from({ length: size - row - 1 }, (_, k) => upper[row]![row + k + 1]! * result[row + k + 1]![column]!))) / upper[row]![row]!);",
  "    return result;",
  "}",
  "function advancedConditionedInverse(factors: AdvancedLUFactors): NumericMatrix {",
  "    const inverse = advancedSolveFactors(factors, advancedIdentity(factors.upper.length));",
  "    const condition = factors.norm * advancedInfinityNorm(inverse);",
  "    const limit = 1 / (ADVANCED_MATH_LIMITS.pivotEpsilonMultiplier * factors.upper.length * Number.EPSILON);",
  "    if (!Number.isFinite(condition) || condition > limit)",
  "        advancedFail('MATRIX_ILL_CONDITIONED', '행렬의 추정 infinity 조건수가 승인 안정성 범위를 초과했습니다.');",
  "    return inverse;",
  "}",
  "function determinant(a: NumericMatrix): number {",
  "    const factors = advancedFactorize(advancedSquare(a), true);",
  "    if (factors.singular)",
  "        return 0;",
  "    return advancedScaledProduct([factors.sign, ...factors.upper.map((row, index) => row[index]!), ...Array.from({ length: factors.upper.length }, () => factors.scale)]);",
  "}",
  "function inverse(a: NumericMatrix): NumericMatrix {",
  "    const factors = advancedFactorize(advancedSquare(a)), result = advancedConditionedInverse(factors);",
  "    return result.map(row => row.map(value => advancedScaledProduct([value], [factors.scale])));",
  "}",
  "function solve(a: NumericMatrix, b: NumericMatrix): NumericMatrix {",
  "    const matrix = advancedSquare(a), rhs = validateMatrix(b);",
  "    if (rhs.length !== matrix.length)",
  "        advancedFail('MATRIX_DIMENSION_MISMATCH', '우변 행 수는 정사각 계수 행렬의 행 수와 같아야 합니다.');",
  "    const factors = advancedFactorize(matrix);",
  "    advancedConditionedInverse(factors);",
  "    const scales = rhs[0]!.map((_, column) => Math.max(...rhs.map(row => Math.abs(row[column]!))));",
  "    const normalized = rhs.map(row => row.map((value, column) => {",
  "        if (scales[column] === 0)",
  "            return 0;",
  "        const result = value / scales[column]!;",
  "        if (value !== 0 && Math.abs(result) < 2 ** -1022)",
  "            advancedFail('MATRIX_NUMERIC_UNDERFLOW', '같은 우변 열 안의 척도 차이가 너무 커 0 아닌 입력의 유효자리를 보존할 수 없습니다.');",
  "        return result;",
  "    }));",
  "    return advancedSolveFactors(factors, normalized).map(row => row.map((value, column) => advancedScaledProduct([value, scales[column]!], [factors.scale])));",
  "}",
  "function lu(a: NumericMatrix): LUResult {",
  "    const factors = advancedFactorize(advancedSquare(a));",
  "    advancedConditionedInverse(factors);",
  "    return { lower: factors.lower.map(row => [...row]), upper: factors.upper.map(row => row.map(value => advancedScaledProduct([value, factors.scale]))), permutation: [...factors.permutation] };",
  "}",
  "function cholesky(a: NumericMatrix): NumericMatrix {",
  "    const matrix = advancedSquare(a), size = matrix.length, scale = Math.max(...matrix.flat().map(Math.abs));",
  "    if (scale === 0)",
  "        advancedFail('MATRIX_NOT_POSITIVE_DEFINITE', 'Cholesky에는 대칭 양의 정부호 행렬이 필요합니다.');",
  "    const normalized = matrix.map(row => row.map(value => {",
  "        const result = value / scale;",
  "        if (value !== 0 && result === 0)",
  "            advancedFail('MATRIX_ILL_CONDITIONED', '행렬 원소의 척도 차이가 너무 큽니다.');",
  "        return result;",
  "    }));",
  "    const tolerance = ADVANCED_MATH_LIMITS.pivotEpsilonMultiplier * size * Number.EPSILON * advancedInfinityNorm(normalized);",
  "    for (let row = 0; row < size; row += 1)",
  "        for (let column = 0; column < row; column += 1)",
  "            if (Math.abs(normalized[row]![column]! - normalized[column]![row]!) > tolerance)",
  "                advancedFail('MATRIX_NOT_SYMMETRIC', 'Cholesky 입력은 척도 상대 허용오차 이내의 대칭 행렬이어야 합니다.');",
  "    const lower = Array.from({ length: size }, () => Array.from({ length: size }, () => 0));",
  "    for (let row = 0; row < size; row += 1) {",
  "        for (let column = 0; column <= row; column += 1) {",
  "            const residual = normalized[row]![column]! - advancedCompensatedSum(Array.from({ length: column }, (_, k) => lower[row]![k]! * lower[column]![k]!));",
  "            if (row === column) {",
  "                if (residual <= 0)",
  "                    advancedFail('MATRIX_NOT_POSITIVE_DEFINITE', 'Cholesky에는 양의 정부호 행렬이 필요합니다.');",
  "                if (residual <= tolerance)",
  "                    advancedFail('MATRIX_ILL_CONDITIONED', 'Cholesky pivot가 척도 상대 허용오차보다 작습니다.');",
  "                lower[row]![column] = Math.sqrt(residual);",
  "            }",
  "            else",
  "                lower[row]![column] = advancedFinite(residual / lower[column]![column]!);",
  "        }",
  "    }",
  "    // Use the same condition policy as LU-backed inverse and solve.",
  "    advancedConditionedInverse(advancedFactorize(matrix));",
  "    return lower.map(row => row.map(value => advancedScaledProduct([value, Math.sqrt(scale)])));",
  "}",
  "function selectMatrix(a: NumericMatrix, rows: number[], columns: number[]): NumericMatrix {",
  "    const matrix = validateMatrix(a);",
  "    const indexes = (input: unknown, size: number): number[] => advancedDenseArray(input, 1, ADVANCED_MATH_LIMITS.maxAxis, 'INVALID_MATRIX_SELECTION').map(value => {",
  "        if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 0 || value >= size)",
  "            advancedFail('INVALID_MATRIX_SELECTION', '선택 index는 범위 안의 0부터 시작하는 정수여야 합니다.');",
  "        return value;",
  "    });",
  "    const selectedRows = indexes(rows, matrix.length), selectedColumns = indexes(columns, matrix[0]!.length);",
  "    return selectedRows.map(row => selectedColumns.map(column => matrix[row]![column]!));",
  "}",
  "function lookupPrelookupValidated(value: number, points: number[], extrapolation: LookupExtrapolation): PrelookupResult {",
  "    if (typeof value !== 'number' || !Number.isFinite(value))",
  "        advancedFail('INVALID_LOOKUP_VALUE', 'lookup 입력은 유한한 scalar 실수여야 합니다.');",
  "    if (!['clip', 'linear', 'error'].includes(extrapolation))",
  "        advancedFail('INVALID_LOOKUP_EXTRAPOLATION', '범위 밖 옵션은 clip·linear·error여야 합니다.');",
  "    const last = points.length - 1;",
  "    if (value < points[0]! || value > points[last]!) {",
  "        if (extrapolation === 'error')",
  "            advancedFail('LOOKUP_OUT_OF_RANGE', 'lookup 입력이 breakpoint 범위를 벗어났습니다.');",
  "        if (extrapolation === 'clip')",
  "            value = Math.max(points[0]!, Math.min(points[last]!, value));",
  "    }",
  "    let index = 0;",
  "    if (value >= points[last]!)",
  "        index = last - 1;",
  "    else {",
  "        let low = 0, high = last;",
  "        while (low + 1 < high) {",
  "            const mid = Math.floor((low + high) / 2);",
  "            if (value >= points[mid]!)",
  "                low = mid;",
  "            else",
  "                high = mid;",
  "        }",
  "        index = low;",
  "    }",
  "    const lower = points[index]!, upper = points[index + 1]!;",
  "    const numerator = value - lower, denominator = upper - lower;",
  "    let fraction: number;",
  "    if (Number.isFinite(numerator) && Number.isFinite(denominator))",
  "        fraction = numerator / denominator;",
  "    else {",
  "        const scale = Math.max(Math.abs(value), Math.abs(lower), Math.abs(upper));",
  "        fraction = (value / scale - lower / scale) / (upper / scale - lower / scale);",
  "    }",
  "    return { index, fraction: advancedFinite(fraction) };",
  "}",
  "function prelookup(value: number, breakpoints: number[], extrapolation: LookupExtrapolation): PrelookupResult { return lookupPrelookupValidated(value, validateBreakpoints(breakpoints), extrapolation); }",
  "function lookup2D(row: number, column: number, input: Lookup2DOptions): number {",
  "    const options = validateLookup2DOptions(input);",
  "    const r = lookupPrelookupValidated(row, options.rowBreakpoints, options.extrapolation), c = lookupPrelookupValidated(column, options.columnBreakpoints, options.extrapolation);",
  "    if (options.interpolation !== 'linear') {",
  "        const offset = (fraction: number): number => options.interpolation === 'nearest' ? (fraction > 0.5 ? 1 : 0) : (fraction === 1 ? 1 : 0);",
  "        return options.table[r.index + offset(r.fraction)]![c.index + offset(c.fraction)]!;",
  "    }",
  "    if (r.fraction < 0 || r.fraction > 1 || c.fraction < 0 || c.fraction > 1) {",
  "        // Expanding the bilinear polynomial preserves its constant and affine terms",
  "        // when extrapolation fractions are so large that float64 rounds 1-f to -f.",
  "        const z00 = options.table[r.index]![c.index]!, z01 = options.table[r.index]![c.index + 1]!;",
  "        const z10 = options.table[r.index + 1]![c.index]!, z11 = options.table[r.index + 1]![c.index + 1]!;",
  "        return advancedScaledDot([",
  "            [z00], [z10, r.fraction], [-z00, r.fraction], [z01, c.fraction], [-z00, c.fraction],",
  "            [z11, r.fraction, c.fraction], [-z10, r.fraction, c.fraction], [-z01, r.fraction, c.fraction], [z00, r.fraction, c.fraction],",
  "        ]);",
  "    }",
  "    return advancedScaledDot([",
  "        [options.table[r.index]![c.index]!, 1 - r.fraction, 1 - c.fraction],",
  "        [options.table[r.index]![c.index + 1]!, 1 - r.fraction, c.fraction],",
  "        [options.table[r.index + 1]![c.index]!, r.fraction, 1 - c.fraction],",
  "        [options.table[r.index + 1]![c.index + 1]!, r.fraction, c.fraction],",
  "    ]);",
  "}",
  "interface FixedQuantizationOptions {",
  "    wordLength: number;",
  "    fractionLength: number;",
  "    signedness: 'signed' | 'unsigned';",
  "    rounding: 'nearest-even' | 'floor' | 'ceil' | 'toward-zero';",
  "    overflow: 'saturate' | 'wrap' | 'error';",
  "}",
  "interface QuantizedFixed {",
  "    value: number;",
  "    stored: number;",
  "}",
  "function quantizationFailure(code: string, message: string): never { throw new ModelError([{ code, message }]); }",
  "/** Validate before reading fields: no hooks, accessors, prototype objects, or ignored options. */",
  "function validateFixedQuantizationOptions(input: unknown): FixedQuantizationOptions {",
  "    if (input === null || typeof input !== 'object' || Array.isArray(input)",
  "        || (Object.getPrototypeOf(input) !== Object.prototype && Object.getPrototypeOf(input) !== null)) {",
  "        quantizationFailure('INVALID_QUANTIZATION_OPTIONS', '고정소수점 설정은 일반 객체여야 합니다.');",
  "    }",
  "    const descriptors = Object.getOwnPropertyDescriptors(input);",
  "    const fields = ['wordLength', 'fractionLength', 'signedness', 'rounding', 'overflow'];",
  "    const keys = Reflect.ownKeys(descriptors);",
  "    if (keys.length !== fields.length || keys.some((key) => typeof key !== 'string' || !fields.includes(key)",
  "        || !('value' in descriptors[key]!) || !descriptors[key]!.enumerable)",
  "        || fields.some((key) => !Object.hasOwn(descriptors, key))) {",
  "        quantizationFailure('INVALID_QUANTIZATION_OPTIONS', '고정소수점 설정의 필드·접근자·숨김 속성을 확인하세요.');",
  "    }",
  "    const wordLength = descriptors.wordLength!.value as unknown;",
  "    const fractionLength = descriptors.fractionLength!.value as unknown;",
  "    const signedness = descriptors.signedness!.value as unknown;",
  "    const rounding = descriptors.rounding!.value as unknown;",
  "    const overflow = descriptors.overflow!.value as unknown;",
  "    if (typeof wordLength !== 'number' || !Number.isInteger(wordLength) || wordLength < 1 || wordLength > 32",
  "        || typeof fractionLength !== 'number' || !Number.isInteger(fractionLength) || fractionLength < 0 || fractionLength > 32",
  "        || (signedness !== 'signed' && signedness !== 'unsigned')",
  "        || (rounding !== 'nearest-even' && rounding !== 'floor' && rounding !== 'ceil' && rounding !== 'toward-zero')",
  "        || (overflow !== 'saturate' && overflow !== 'wrap' && overflow !== 'error')) {",
  "        quantizationFailure('INVALID_QUANTIZATION_OPTIONS', 'wordLength 1~32, fractionLength 0~32와 승인한 부호·반올림·overflow 방식을 사용하세요.');",
  "    }",
  "    return { wordLength, fractionLength, signedness, rounding, overflow };",
  "}",
  "/**",
  " * Quantize the exact IEEE-754 input rational, then bound the rounded integer code.",
  " * BigInt shifts are bounded by binary64 exponents (at most 1,074 bits), never user text.",
  " * This is one boundary quantizer; subsequent arithmetic remains ordinary float64.",
  " */",
  "function quantizeFixed(value: number, inputOptions: FixedQuantizationOptions): QuantizedFixed {",
  "    const options = validateFixedQuantizationOptions(inputOptions);",
  "    if (typeof value !== 'number' || !Number.isFinite(value))",
  "        quantizationFailure('FIXED_POINT_INPUT', '고정소수점 입력은 유한한 float64여야 합니다.');",
  "    const view = new DataView(new ArrayBuffer(8));",
  "    view.setFloat64(0, value, false);",
  "    const bits = view.getBigUint64(0, false), negative = (bits >> 63n) !== 0n;",
  "    const encodedExponent = Number((bits >> 52n) & 0x7ffn), fraction = bits & ((1n << 52n) - 1n);",
  "    const significand = encodedExponent === 0 ? fraction : (1n << 52n) | fraction;",
  "    const exponent = (encodedExponent === 0 ? -1074 : encodedExponent - 1075) + options.fractionLength;",
  "    let magnitude: bigint;",
  "    if (exponent >= 0)",
  "        magnitude = significand << BigInt(exponent);",
  "    else {",
  "        const shift = BigInt(-exponent), denominator = 1n << shift;",
  "        magnitude = significand >> shift;",
  "        const remainder = significand - (magnitude << shift);",
  "        if (remainder !== 0n) {",
  "            if (options.rounding === 'nearest-even') {",
  "                const twice = remainder << 1n;",
  "                if (twice > denominator || (twice === denominator && (magnitude & 1n) !== 0n))",
  "                    magnitude += 1n;",
  "            }",
  "            else if (options.rounding === 'floor' && negative || options.rounding === 'ceil' && !negative)",
  "                magnitude += 1n;",
  "        }",
  "    }",
  "    let stored = negative ? -magnitude : magnitude;",
  "    const modulus = 1n << BigInt(options.wordLength);",
  "    const signBoundary = modulus >> 1n;",
  "    const minimum = options.signedness === 'signed' ? -signBoundary : 0n;",
  "    const maximum = options.signedness === 'signed' ? signBoundary - 1n : modulus - 1n;",
  "    if (stored < minimum || stored > maximum) {",
  "        if (options.overflow === 'error')",
  "            quantizationFailure('FIXED_POINT_OVERFLOW', '반올림한 고정소수점 값이 지정한 정수 코드 범위를 벗어났습니다.');",
  "        if (options.overflow === 'saturate')",
  "            stored = stored < minimum ? minimum : maximum;",
  "        else {",
  "            stored = ((stored % modulus) + modulus) % modulus;",
  "            if (options.signedness === 'signed' && stored >= signBoundary)",
  "                stored -= modulus;",
  "        }",
  "    }",
  "    const storedNumber = Number(stored);",
  "    // Every stored code is exactly representable in binary64; division by a power of two is exact.",
  "    return { value: storedNumber / (2 ** options.fractionLength), stored: storedNumber };",
  "}",
  "const expansionFunctions: Readonly<Record<string, (x: number) => number>> = Object.freeze({",
  "    'math.cbrt': Math.cbrt, 'math.expm1': Math.expm1, 'math.log1p': Math.log1p, 'math.log2': Math.log2,",
  "    'math.exp2': x => 2 ** x, 'math.sinh': Math.sinh, 'math.cosh': Math.cosh, 'math.tanh': Math.tanh,",
  "    'math.asinh': Math.asinh, 'math.acosh': Math.acosh, 'math.atanh': Math.atanh,",
  "});",
  "function expansionFail(nodeId: string, code: string, message: string): never { throw new ModelError([{ code, nodeId, message }]); }",
  "function expansionFinite(value: unknown, nodeId: string): number {",
  "    if (typeof value !== 'number' || !Number.isFinite(value))",
  "        expansionFail(nodeId, 'NUMERIC_NONFINITE', '신규 연산의 입력·중간값·출력은 유한한 실수여야 합니다.');",
  "    return value as number;",
  "}",
  "function expansionFlat(value: SignalValue): (number | boolean)[] { return !Array.isArray(value) ? [value] : Array.isArray(value[0]) ? (value as number[][] | boolean[][]).flat() : [...value] as number[] | boolean[]; }",
  "function expansionShape(values: (number | boolean)[], shape: number[]): SignalValue {",
  "    if (!shape.length)",
  "        return values[0]!;",
  "    if (shape.length === 1)",
  "        return values as number[] | boolean[];",
  "    return Array.from({ length: shape[0]! }, (_, row) => values.slice(row * shape[1]!, (row + 1) * shape[1]!)) as number[][] | boolean[][];",
  "}",
  "function expansionMean(values: number[], nodeId: string): number {",
  "    let sum = 0, compensation = 0;",
  "    for (const value of values) {",
  "        const next = sum + value;",
  "        if (!Number.isFinite(next)) {",
  "            const scale = Math.max(...values.map(Math.abs));",
  "            return expansionFinite(expansionMean(values.map(item => item / scale), nodeId) * scale, nodeId);",
  "        }",
  "        compensation += Math.abs(sum) >= Math.abs(value) ? (sum - next) + value : (value - next) + sum;",
  "        sum = next;",
  "    }",
  "    const total = sum + compensation;",
  "    if (Number.isFinite(total))",
  "        return expansionFinite(total / values.length, nodeId);",
  "    const scale = Math.max(...values.map(Math.abs));",
  "    return expansionFinite(expansionMean(values.map(item => item / scale), nodeId) * scale, nodeId);",
  "}",
  "function expansionAveragePair(a: number, b: number, nodeId: string): number {",
  "    if (a === b)",
  "        return a;",
  "    const sum = a + b;",
  "    return expansionFinite(Number.isFinite(sum) ? sum / 2 : a / 2 + b / 2, nodeId);",
  "}",
  "function expansionStd(values: number[], nodeId: string): number {",
  "    // Translate before scaling so a large common offset does not erase small differences.",
  "    // Opposite extreme signs can overflow subtraction; raw scaling remains safe in that case.",
  "    const shifted = values.map(value => value - values[0]!);",
  "    const centered = shifted.every(Number.isFinite) ? shifted : values;",
  "    const scale = Math.max(...centered.map(Math.abs));",
  "    if (scale === 0)",
  "        return 0;",
  "    const normalized = centered.map(value => value / scale), mean = expansionMean(normalized, nodeId);",
  "    const variance = normalized.reduce((sum, value) => sum + (value - mean) ** 2 / values.length, 0);",
  "    return expansionFinite(scale * Math.sqrt(variance), nodeId);",
  "}",
  "/** Fixed mathematical kernels. Arbitrary model text is never used as JS source or a function name. */",
  "function evaluateExpansionNode(node: IRNode, input: (port: string) => SignalValue): Record<string, SignalValue> | undefined {",
  "    const id = node.id, kind = node.blockType, p = node.parameters, shape = node.outputs.out?.shape ?? [];",
  "    const finite = (value: unknown): number => expansionFinite(value, id);",
  "    const numbers = (port = 'in'): number[] => expansionFlat(input(port)).map(finite);",
  "    const unary = (operation: (x: number) => number | boolean): SignalValue => expansionShape(numbers().map(x => { const value = operation(x); return typeof value === 'boolean' ? value : finite(value); }), shape);",
  "    const binary = (operation: (a: number, b: number) => number | boolean): SignalValue => {",
  "        const a = numbers('a'), b = numbers('b'), count = shape.reduce((n, axis) => n * axis, 1);",
  "        return expansionShape(Array.from({ length: count }, (_, index) => { const value = operation(a[a.length === 1 ? 0 : index]!, b[b.length === 1 ? 0 : index]!); return typeof value === 'boolean' ? value : finite(value); }), shape);",
  "    };",
  "    const domain = (valid: boolean): void => { if (!valid)",
  "        expansionFail(id, 'NUMERIC_DOMAIN', '신규 연산의 실수 정의역을 벗어났습니다.'); };",
  "    const array = (port = 'in'): (number | boolean)[] => expansionFlat(input(port));",
  "    const matrix = (port = 'in'): (number | boolean)[][] => input(port) as number[][] | boolean[][];",
  "    let value: SignalValue;",
  "    if (Object.hasOwn(expansionFunctions, kind))",
  "        return { out: unary(x => {",
  "                if (kind === 'math.log1p')",
  "                    domain(x > -1);",
  "                if (kind === 'math.log2')",
  "                    domain(x > 0);",
  "                if (kind === 'math.acosh')",
  "                    domain(x >= 1);",
  "                if (kind === 'math.atanh')",
  "                    domain(Math.abs(x) < 1);",
  "                return expansionFunctions[kind]!(x);",
  "            }) };",
  "    switch (kind) {",
  "        case 'math.bias':",
  "            value = unary(x => x + finite(p.bias));",
  "            break;",
  "        case 'math.sign':",
  "            value = unary(Math.sign);",
  "            break;",
  "        case 'math.sinc':",
  "            value = unary(x => x === 0 ? 1 : Number.isInteger(x) ? 0 : Math.sin(Math.PI * x) / (Math.PI * x));",
  "            break;",
  "        case 'math.polynomial':",
  "            value = unary(x => (p.coefficients as number[]).reduce((acc, coefficient) => finite(finite(acc * x) + coefficient), 0));",
  "            break;",
  "        case 'math.power':",
  "            value = binary((a, b) => { domain(!(a < 0 && !Number.isInteger(b)) && !(a === 0 && b < 0)); return a ** b; });",
  "            break;",
  "        case 'math.hypot':",
  "            value = binary(Math.hypot);",
  "            break;",
  "        case 'math.atan2':",
  "            value = binary(Math.atan2);",
  "            break;",
  "        case 'math.mod':",
  "        case 'math.remainder':",
  "            value = binary((a, b) => { if (b === 0)",
  "                expansionFail(id, 'NUMERIC_DIVIDE_BY_ZERO', '나머지의 제수는 0이 아니어야 합니다.'); const rem = a % b; return kind === 'math.mod' && rem !== 0 && Math.sign(rem) !== Math.sign(b) ? rem + b : rem; });",
  "            break;",
  "        case 'nonlinear.dead-zone':",
  "            value = unary(x => x < (p.lower as number) ? x - (p.lower as number) : x > (p.upper as number) ? x - (p.upper as number) : 0);",
  "            break;",
  "        case 'nonlinear.quantizer':",
  "            value = unary(x => { const quotient = finite(x / finite(p.step)), absolute = Math.abs(quotient), base = Math.floor(absolute); return Math.sign(quotient) * (base + (absolute - base >= .5 ? 1 : 0)) * finite(p.step); });",
  "            break;",
  "        case 'logic.interval':",
  "            value = unary(x => x >= (p.lower as number) && x <= (p.upper as number));",
  "            break;",
  "        case 'logic.is-integer':",
  "            value = unary(Number.isInteger);",
  "            break;",
  "        case 'logic.approx-equal':",
  "            value = binary((a, b) => Math.abs(a - b) <= (p.tolerance as number));",
  "            break;",
  "        case 'reduce.all':",
  "            value = array().every(item => item === true);",
  "            break;",
  "        case 'reduce.any':",
  "            value = array().some(item => item === true);",
  "            break;",
  "        case 'reduce.sum':",
  "            value = numbers().reduce((sum, x) => finite(sum + x), 0);",
  "            break;",
  "        case 'reduce.product':",
  "            value = numbers().reduce((product, x) => finite(product * x), 1);",
  "            break;",
  "        case 'reduce.mean':",
  "            value = expansionMean(numbers(), id);",
  "            break;",
  "        case 'reduce.median': {",
  "            const values = numbers().sort((a, b) => a < b ? -1 : a > b ? 1 : 0), middle = Math.floor(values.length / 2);",
  "            value = values.length % 2 ? values[middle]! : expansionAveragePair(values[middle - 1]!, values[middle]!, id);",
  "            break;",
  "        }",
  "        case 'reduce.variance': {",
  "            const std = expansionStd(numbers(), id);",
  "            value = finite(std * std);",
  "            break;",
  "        }",
  "        case 'reduce.std':",
  "            value = expansionStd(numbers(), id);",
  "            break;",
  "        case 'reduce.norm1':",
  "            value = numbers().reduce((sum, x) => finite(sum + Math.abs(x)), 0);",
  "            break;",
  "        case 'reduce.norm2':",
  "            value = finite(Math.hypot(...numbers()));",
  "            break;",
  "        case 'reduce.norm-inf':",
  "            value = Math.max(...numbers().map(Math.abs));",
  "            break;",
  "        case 'reduce.rms': {",
  "            const values = numbers(), scale = Math.max(...values.map(Math.abs));",
  "            value = scale === 0 ? 0 : finite(scale * Math.sqrt(values.reduce((sum, x) => sum + (x / scale) ** 2 / values.length, 0)));",
  "            break;",
  "        }",
  "        case 'vector.dot': {",
  "            const a = numbers('a'), b = numbers('b');",
  "            value = a.reduce((sum, x, index) => finite(sum + finite(x * b[index]!)), 0);",
  "            break;",
  "        }",
  "        case 'vector.cross': {",
  "            const a = numbers('a'), b = numbers('b');",
  "            value = [finite(finite(a[1]! * b[2]!) - finite(a[2]! * b[1]!)), finite(finite(a[2]! * b[0]!) - finite(a[0]! * b[2]!)), finite(finite(a[0]! * b[1]!) - finite(a[1]! * b[0]!))];",
  "            break;",
  "        }",
  "        case 'vector.normalize': {",
  "            const values = numbers(), scale = Math.max(...values.map(Math.abs));",
  "            domain(scale > 0);",
  "            const norm = Math.hypot(...values.map(x => x / scale));",
  "            value = values.map(x => finite((x / scale) / norm));",
  "            break;",
  "        }",
  "        case 'vector.reverse':",
  "            value = array().reverse() as number[] | boolean[];",
  "            break;",
  "        case 'vector.sort':",
  "            value = numbers().sort((a, b) => (a < b ? -1 : a > b ? 1 : 0) * (p.order === 'ascending' ? 1 : -1));",
  "            break;",
  "        case 'vector.cumsum':",
  "        case 'vector.cumprod': {",
  "            let accumulated = kind === 'vector.cumsum' ? 0 : 1;",
  "            value = numbers().map(x => accumulated = finite(kind === 'vector.cumsum' ? accumulated + x : accumulated * x));",
  "            break;",
  "        }",
  "        case 'vector.difference': {",
  "            const values = numbers();",
  "            value = values.slice(1).map((x, index) => finite(x - values[index]!));",
  "            break;",
  "        }",
  "        case 'vector.select': {",
  "            const values = array();",
  "            value = (p.indices as number[]).map(index => values[index]!) as number[] | boolean[];",
  "            break;",
  "        }",
  "        case 'vector.slice':",
  "            value = array().slice(p.start as number, (p.start as number) + (p.count as number)) as number[] | boolean[];",
  "            break;",
  "        case 'vector.repeat': {",
  "            const values = array();",
  "            value = Array.from({ length: p.count as number }, () => values).flat() as number[] | boolean[];",
  "            break;",
  "        }",
  "        case 'vector.convolve': {",
  "            const a = numbers('a'), b = numbers('b'), out = Array(a.length + b.length - 1).fill(0) as number[];",
  "            for (let i = 0; i < a.length; i++)",
  "                for (let j = 0; j < b.length; j++)",
  "                    out[i + j] = finite(out[i + j]! + finite(a[i]! * b[j]!));",
  "            value = out;",
  "            break;",
  "        }",
  "        case 'matrix.trace':",
  "            value = matrix().reduce((sum: number, row, index) => finite(sum + finite(row[index])), 0);",
  "            break;",
  "        case 'matrix.diagonal': {",
  "            const values = matrix();",
  "            value = Array.from({ length: Math.min(values.length, values[0]!.length) }, (_, index) => values[index]![index]!) as number[] | boolean[];",
  "            break;",
  "        }",
  "        case 'matrix.diag-create': {",
  "            const values = array(), zero = typeof values[0] === 'boolean' ? false : 0;",
  "            value = values.map((x, row) => values.map((_, column) => row === column ? x : zero)) as number[][] | boolean[][];",
  "            break;",
  "        }",
  "        case 'matrix.identity':",
  "            value = Array.from({ length: p.size as number }, (_, row) => Array.from({ length: p.size as number }, (_, column) => row === column ? 1 : 0));",
  "            break;",
  "        case 'matrix.select': {",
  "            const values = matrix();",
  "            value = (p.rows as number[]).map(row => (p.columns as number[]).map(column => values[row]![column]!)) as number[][] | boolean[][];",
  "            break;",
  "        }",
  "        case 'matrix.row':",
  "            value = [...matrix()[p.index as number]!] as number[] | boolean[];",
  "            break;",
  "        case 'matrix.column':",
  "            value = matrix().map(row => row[p.index as number]!) as number[] | boolean[];",
  "            break;",
  "        case 'matrix.horizontal': {",
  "            const a = matrix('a'), b = matrix('b');",
  "            value = a.map((row, index) => [...row, ...b[index]!]) as number[][] | boolean[][];",
  "            break;",
  "        }",
  "        case 'matrix.vertical':",
  "            value = [...matrix('a').map(row => [...row]), ...matrix('b').map(row => [...row])] as number[][] | boolean[][];",
  "            break;",
  "        case 'matrix.triangle': {",
  "            const values = matrix(), zero = typeof values[0]![0] === 'boolean' ? false : 0;",
  "            value = values.map((row, i) => row.map((x, j) => (p.part === 'upper' ? j >= i : j <= i) ? x : zero)) as number[][] | boolean[][];",
  "            break;",
  "        }",
  "        case 'matrix.symmetrize': {",
  "            const values = matrix();",
  "            value = values.map((row, i) => row.map((x, j) => expansionAveragePair(finite(x), finite(values[j]![i]), id)));",
  "            break;",
  "        }",
  "        case 'matrix.kronecker': {",
  "            const a = matrix('a'), b = matrix('b');",
  "            value = Array.from({ length: a.length * b.length }, (_, row) => Array.from({ length: a[0]!.length * b[0]!.length }, (_, column) => finite(finite(a[Math.floor(row / b.length)]![Math.floor(column / b[0]!.length)]) * finite(b[row % b.length]![column % b[0]!.length]))));",
  "            break;",
  "        }",
  "        case 'source.linspace':",
  "        case 'source.logspace': {",
  "            const start = finite(p.start), stop = finite(p.stop), count = p.count as number;",
  "            value = Array.from({ length: count }, (_, index) => { const t = count === 1 ? 0 : index / (count - 1); const x = index === 0 || start === stop ? start : index === count - 1 ? stop : finite(start * (1 - t) + stop * t); return finite(kind === 'source.logspace' ? 10 ** x : x); });",
  "            break;",
  "        }",
  "        case 'source.zeros':",
  "            value = p.form === 'matrix' ? Array.from({ length: p.rows as number }, () => Array(p.columns as number).fill(0)) : Array(p.length as number).fill(0);",
  "            break;",
  "        default: return undefined;",
  "    }",
  "    return { out: value };",
  "}",
  "/** Pure functions of absolute simulation seconds. No host time, state, files or random source. */",
  "function evaluateTimeSourceNode(node: IRNode, time: number): Record<string, SignalValue> | undefined {",
  "    if (!['source.chirp', 'source.gaussian-pulse', 'source.damped-sine', 'source.exponential', 'source.logistic', 'source.sinc-pulse'].includes(node.blockType))",
  "        return undefined;",
  "    const fail = (code: string, message: string): never => { throw new ModelError([{ code, nodeId: node.id, message }]); };",
  "    const finite = (value: unknown): number => typeof value === 'number' && Number.isFinite(value) ? value : fail('NUMERIC_NONFINITE', '시간 신호의 입력 또는 결과가 유한한 실수가 아닙니다.');",
  "    const p = (key: string): number => finite(node.parameters[key]);",
  "    const positive = (key: string): number => { const value = p(key); if (value <= 0)",
  "        fail('NUMERIC_DOMAIN', '시간 폭과 스윕 기간은 양수여야 합니다.'); return value; };",
  "    const t = finite(time), amplitude = p('amplitude'), bias = p('bias');",
  "    let waveform: number;",
  "    switch (node.blockType) {",
  "        case 'source.chirp': {",
  "            const initial = p('initialFrequency'), final = p('finalFrequency'), duration = positive('duration');",
  "            // Integrate frequency to retain phase and derivative continuity at 0 and duration.",
  "            const cycles = t <= 0 ? initial * t : t < duration ? initial * t + (final - initial) * t * t / (2 * duration) : (initial + final) * duration / 2 + final * (t - duration);",
  "            waveform = Math.sin(finite(2 * Math.PI * cycles + p('phase')));",
  "            break;",
  "        }",
  "        case 'source.gaussian-pulse': {",
  "            const normalized = (t - p('center')) / positive('width');",
  "            waveform = Math.exp(-0.5 * normalized * normalized);",
  "            break;",
  "        }",
  "        case 'source.damped-sine':",
  "            waveform = Math.exp(finite(-p('decay') * t)) * Math.sin(finite(2 * Math.PI * p('frequency') * t + p('phase')));",
  "            break;",
  "        case 'source.exponential':",
  "            waveform = Math.exp(finite(p('rate') * t));",
  "            break;",
  "        case 'source.logistic': {",
  "            const z = finite(p('slope') * (t - p('center')));",
  "            waveform = z >= 0 ? 1 / (1 + Math.exp(-z)) : Math.exp(z) / (1 + Math.exp(z));",
  "            break;",
  "        }",
  "        case 'source.sinc-pulse': {",
  "            const normalized = finite((t - p('center')) / positive('width'));",
  "            const phase = finite(Math.PI * normalized);",
  "            waveform = normalized === 0 ? 1 : Math.sin(phase) / phase;",
  "            break;",
  "        }",
  "        default: return undefined;",
  "    }",
  "    return { out: finite(amplitude * finite(waveform) + bias) };",
  "}",
  "function numericFailure(code: string, nodeId: string, message: string): never {",
  "    throw new ModelError([{ code, nodeId, message }]);",
  "}",
  "function finiteNumber(value: unknown, nodeId: string): number {",
  "    if (typeof value !== 'number' || !Number.isFinite(value)) {",
  "        numericFailure('NUMERIC_NONFINITE', nodeId, '계산 결과 또는 입력이 유한한 실수가 아닙니다.');",
  "    }",
  "    return value;",
  "}",
  "function signalElements(descriptor: SignalDescriptor): number {",
  "    return descriptor.shape.reduce((size, dimension) => size * dimension, 1);",
  "}",
  "/** Results own their array storage; editing a result cannot mutate the next run's inputs. */",
  "function copySignal(value: SignalValue): SignalValue {",
  "    if (!Array.isArray(value))",
  "        return value;",
  "    return Array.isArray(value[0])",
  "        ? (value as number[][] | boolean[][]).map((row) => [...row]) as number[][] | boolean[][]",
  "        : [...value] as number[] | boolean[];",
  "}",
  "function flatten(value: SignalValue): (number | boolean)[] {",
  "    if (!Array.isArray(value))",
  "        return [value];",
  "    return Array.isArray(value[0]) ? (value as number[][] | boolean[][]).flat() : value as number[] | boolean[];",
  "}",
  "function shaped(values: (number | boolean)[], shape: number[]): SignalValue {",
  "    if (shape.length === 0)",
  "        return values[0]!;",
  "    if (shape.length === 1)",
  "        return values as number[] | boolean[];",
  "    return Array.from({ length: shape[0]! }, (_, row) => values.slice(row * shape[1]!, (row + 1) * shape[1]!)) as number[][] | boolean[][];",
  "}",
  "/** Verify every emitted port against immutable compiler metadata, including multi-output nodes. */",
  "function checkSignal(value: SignalValue | undefined, descriptor: SignalDescriptor, nodeId: string): SignalValue {",
  "    if (value === undefined)",
  "        numericFailure('RUNTIME_INVALID_IR', nodeId, '실행 출력이 중간 표현에 없습니다.');",
  "    const shape = descriptor.shape;",
  "    if (shape.length === 0 ? Array.isArray(value)",
  "        : shape.length === 1 ? !Array.isArray(value) || value.length !== shape[0] || value.some(Array.isArray)",
  "            : !Array.isArray(value) || value.length !== shape[0] || value.some((row) => !Array.isArray(row) || row.length !== shape[1] || row.some(Array.isArray))) {",
  "        numericFailure('RUNTIME_SHAPE_MISMATCH', nodeId, '실행 출력의 차원이 검증한 포트와 다릅니다.');",
  "    }",
  "    for (const element of flatten(value)) {",
  "        if (descriptor.valueType === 'float64')",
  "            finiteNumber(element, nodeId);",
  "        else if (typeof element !== 'boolean')",
  "            numericFailure('RUNTIME_TYPE_MISMATCH', nodeId, '실행 출력의 자료형이 검증한 포트와 다릅니다.');",
  "    }",
  "    return value;",
  "}",
  "/** M1 finite real/boolean kernels. Arbitrary model text never becomes executable syntax. */",
  "function evaluateSignalNode(node: IRNode, input: (port: string) => SignalValue, state?: SignalValue, time = 0): Record<string, SignalValue> {",
  "    const expansion = evaluateExpansionNode(node, input);",
  "    if (expansion)",
  "        return expansion;",
  "    const timeSource = evaluateTimeSourceNode(node, time);",
  "    if (timeSource)",
  "        return timeSource;",
  "    const id = node.id;",
  "    const descriptor = node.outputs.out;",
  "    const shape = descriptor?.shape ?? [];",
  "    const count = descriptor ? signalElements(descriptor) : 1;",
  "    const parameter = (key: string): number => finiteNumber(node.parameters[key], id);",
  "    const option = (key: string): string => String(node.parameters[key]);",
  "    const unary = (operation: (value: number) => number): SignalValue => shaped(flatten(input('in')).map((value) => finiteNumber(operation(finiteNumber(value, id)), id)), shape);",
  "    const numericPair = (operation: (a: number, b: number) => number | boolean): SignalValue => {",
  "        const a = flatten(input('a')), b = flatten(input('b'));",
  "        return shaped(Array.from({ length: count }, (_, index) => {",
  "            const result = operation(finiteNumber(a[a.length === 1 ? 0 : index], id), finiteNumber(b[b.length === 1 ? 0 : index], id));",
  "            return typeof result === 'boolean' ? result : finiteNumber(result, id);",
  "        }), shape);",
  "    };",
  "    const domain = (valid: boolean): void => { if (!valid)",
  "        numericFailure('NUMERIC_DOMAIN', id, '입력값이 함수의 실수 정의역을 벗어났습니다.'); };",
  "    const divide = (a: number, b: number): number => {",
  "        if (b === 0)",
  "            numericFailure('NUMERIC_DIVIDE_BY_ZERO', id, '0으로 나눌 수 없습니다. 제수 입력을 확인해 주세요.');",
  "        return a / b;",
  "    };",
  "    const advanced = <T>(operation: () => T): T => {",
  "        try {",
  "            return operation();",
  "        }",
  "        catch (error) {",
  "            if (error instanceof ModelError)",
  "                throw new ModelError(error.diagnostics.map(diagnostic => ({ ...diagnostic, nodeId: id })));",
  "            throw error;",
  "        }",
  "    };",
  "    let value: SignalValue;",
  "    switch (node.blockType) {",
  "        case 'annotation.note':",
  "        case 'annotation.model-info': return {};",
  "        case 'source.dataset':",
  "            value = replayDataset(node, time);",
  "            break;",
  "        case 'unit.convert':",
  "            value = unary(x => x * parameter('unitScale') + parameter('unitOffset'));",
  "            break;",
  "        case 'route.bus-create':",
  "            value = [input('a'), input('b')] as number[] | boolean[];",
  "            break;",
  "        case 'route.bus-select':",
  "            value = (input('in') as number[] | boolean[])[parameter('fieldIndex')]!;",
  "            break;",
  "        case 'source.constant':",
  "        case 'io.input':",
  "            value = node.parameters.value as SignalValue;",
  "            break;",
  "        case 'math.gain':",
  "            value = unary((x) => x * parameter('gain'));",
  "            break;",
  "        case 'math.sum': {",
  "            const signs = option('signs');",
  "            value = numericPair((a, b) => (signs[0] === '-' ? -a : a) + (signs[1] === '-' ? -b : b));",
  "            break;",
  "        }",
  "        case 'math.multiply':",
  "            value = numericPair(option('operation') === 'divide' ? divide : (a, b) => a * b);",
  "            break;",
  "        case 'math.abs':",
  "            value = unary(Math.abs);",
  "            break;",
  "        case 'math.sqrt':",
  "            value = unary((x) => { domain(x >= 0); return Math.sqrt(x); });",
  "            break;",
  "        case 'math.function':",
  "            value = unary((x) => {",
  "                switch (option('operation')) {",
  "                    case 'exp': return Math.exp(x);",
  "                    case 'log':",
  "                        domain(x > 0);",
  "                        return Math.log(x);",
  "                    case 'log10':",
  "                        domain(x > 0);",
  "                        return Math.log10(x);",
  "                    case 'square': return x * x;",
  "                    case 'reciprocal': return divide(1, x);",
  "                    default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 수학 함수입니다.');",
  "                }",
  "            });",
  "            break;",
  "        case 'math.trigonometric':",
  "            value = unary((x) => {",
  "                switch (option('operation')) {",
  "                    case 'sin': return Math.sin(x);",
  "                    case 'cos': return Math.cos(x);",
  "                    case 'tan': return Math.tan(x);",
  "                    case 'asin':",
  "                        domain(x >= -1 && x <= 1);",
  "                        return Math.asin(x);",
  "                    case 'acos':",
  "                        domain(x >= -1 && x <= 1);",
  "                        return Math.acos(x);",
  "                    case 'atan': return Math.atan(x);",
  "                    default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 삼각 함수입니다.');",
  "                }",
  "            });",
  "            break;",
  "        case 'math.round':",
  "            value = unary((x) => {",
  "                switch (option('operation')) {",
  "                    case 'round': return Math.round(x);",
  "                    case 'floor': return Math.floor(x);",
  "                    case 'ceil': return Math.ceil(x);",
  "                    case 'trunc': return Math.trunc(x);",
  "                    default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 반올림 방식입니다.');",
  "                }",
  "            });",
  "            break;",
  "        case 'math.minmax': {",
  "            const operation = option('operation') === 'max' ? Math.max : Math.min;",
  "            if (option('strategy') === 'reduce') {",
  "                const elements = flatten(input('in')).map((element) => finiteNumber(element, id));",
  "                value = elements.reduce((a, b) => operation(a, b));",
  "            }",
  "            else",
  "                value = numericPair(operation);",
  "            break;",
  "        }",
  "        case 'logic.compare':",
  "            value = numericPair((a, b) => {",
  "                switch (option('operation')) {",
  "                    case 'eq': return a === b;",
  "                    case 'ne': return a !== b;",
  "                    case 'lt': return a < b;",
  "                    case 'le': return a <= b;",
  "                    case 'gt': return a > b;",
  "                    case 'ge': return a >= b;",
  "                    default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 비교 연산입니다.');",
  "                }",
  "            });",
  "            break;",
  "        case 'logic.boolean': {",
  "            const a = flatten(input('a')), b = option('operation') === 'not' ? [] : flatten(input('b'));",
  "            value = shaped(Array.from({ length: count }, (_, index) => {",
  "                const first = a[a.length === 1 ? 0 : index], second = b[b.length === 1 ? 0 : index];",
  "                if (typeof first !== 'boolean' || (option('operation') !== 'not' && typeof second !== 'boolean'))",
  "                    numericFailure('RUNTIME_TYPE_MISMATCH', id, '논리 연산에는 boolean 입력이 필요합니다.');",
  "                switch (option('operation')) {",
  "                    case 'not': return !first;",
  "                    case 'and': return first && second!;",
  "                    case 'or': return first || second!;",
  "                    case 'xor': return first !== second;",
  "                    default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 논리 연산입니다.');",
  "                }",
  "            }), shape);",
  "            break;",
  "        }",
  "        case 'route.switch': {",
  "            const condition = input('condition');",
  "            if (typeof condition !== 'boolean')",
  "                numericFailure('RUNTIME_TYPE_MISMATCH', id, '선택 조건에는 boolean scalar가 필요합니다.');",
  "            value = input(condition ? 'a' : 'b');",
  "            break;",
  "        }",
  "        case 'nonlinear.saturation':",
  "            value = unary((x) => Math.min(parameter('upper'), Math.max(parameter('lower'), x)));",
  "            break;",
  "        case 'route.mux':",
  "        case 'math.concatenate':",
  "            value = [...flatten(input('a')), ...flatten(input('b'))] as number[] | boolean[];",
  "            break;",
  "        case 'route.demux': {",
  "            const elements = flatten(input('in'));",
  "            return Object.fromEntries(Object.keys(node.outputs).map((port) => [port, elements[Number(port.slice(3)) - 1]!]));",
  "        }",
  "        case 'matrix.reshape':",
  "            value = shaped(flatten(input('in')), shape);",
  "            break;",
  "        case 'math.matrix-multiply':",
  "            value = advanced(() => matrixMultiply(input('a') as number[][], input('b') as number[][]));",
  "            break;",
  "        case 'matrix.transpose':",
  "            value = advanced(() => transpose(input('in') as number[][]));",
  "            break;",
  "        case 'matrix.determinant':",
  "            value = advanced(() => determinant(input('in') as number[][]));",
  "            break;",
  "        case 'matrix.inverse':",
  "            value = advanced(() => inverse(input('in') as number[][]));",
  "            break;",
  "        case 'matrix.solve':",
  "            value = advanced(() => solve(input('a') as number[][], input('b') as number[][]));",
  "            break;",
  "        case 'matrix.cholesky':",
  "            value = advanced(() => cholesky(input('in') as number[][]));",
  "            break;",
  "        case 'matrix.lu': return advanced(() => {",
  "            const decomposition = lu(input('in') as number[][]);",
  "            const permutation = decomposition.permutation.map(index => Array.from({ length: decomposition.permutation.length }, (_, column) => column === index ? 1 : 0));",
  "            return { lower: decomposition.lower, upper: decomposition.upper, permutation };",
  "        });",
  "        case 'lookup.2d':",
  "            value = advanced(() => lookup2D(finiteNumber(input('row'), id), finiteNumber(input('column'), id), node.parameters as unknown as Parameters<typeof lookup2D>[2]));",
  "            break;",
  "        case 'lookup.prelookup': return advanced(() => {",
  "            const found = prelookup(finiteNumber(input('in'), id), node.parameters.breakpoints as number[], option('extrapolation') as Parameters<typeof prelookup>[2]);",
  "            return { index: found.index, fraction: found.fraction };",
  "        });",
  "        case 'fixed.quantize': return advanced(() => {",
  "            const codes = flatten(input('in')).map(element => quantizeFixed(finiteNumber(element, id), node.parameters as unknown as FixedQuantizationOptions));",
  "            return { out: shaped(codes.map(code => code.value), shape), stored: shaped(codes.map(code => code.stored), shape) };",
  "        });",
  "        case 'sink.display':",
  "        case 'sink.scope':",
  "        case 'io.output':",
  "        case 'io.terminator':",
  "            value = input('in');",
  "            break;",
  "        case 'lookup.interpolated':",
  "            value = unary((x) => interpolateTable(x, node.parameters.breakpoints as number[], node.parameters.values as number[], option('interpolation'), option('extrapolation'), id));",
  "            break;",
  "        case 'logic.bitwise': {",
  "            const width = parameter('width'), mask = width === 32 ? 0xffffffff : 2 ** width - 1;",
  "            const unsigned = (port: string): number => {",
  "                const number = finiteNumber(input(port), id);",
  "                if (!Number.isSafeInteger(number) || number < 0 || number > mask)",
  "                    numericFailure('NUMERIC_INTEGER_RANGE', id, '비트 입력은 ' + width + '비트 unsigned 정수여야 합니다.');",
  "                return number;",
  "            };",
  "            const a = unsigned('a');",
  "            let bits: number;",
  "            switch (option('operation')) {",
  "                case 'and':",
  "                    bits = a & unsigned('b');",
  "                    break;",
  "                case 'or':",
  "                    bits = a | unsigned('b');",
  "                    break;",
  "                case 'xor':",
  "                    bits = a ^ unsigned('b');",
  "                    break;",
  "                case 'not':",
  "                    bits = ~a;",
  "                    break;",
  "                case 'shift-left':",
  "                    bits = a << parameter('shift');",
  "                    break;",
  "                case 'shift-right':",
  "                    bits = a >>> parameter('shift');",
  "                    break;",
  "                default: return numericFailure('RUNTIME_INVALID_IR', id, '지원하지 않는 비트 연산입니다.');",
  "            }",
  "            value = (bits & mask) >>> 0;",
  "            break;",
  "        }",
  "        case 'math.expression': {",
  "            if (!node.expression)",
  "                numericFailure('RUNTIME_INVALID_IR', id, '검증한 수식 AST가 없습니다.');",
  "            value = unary((x) => {",
  "                try {",
  "                    return evaluateExpression(node.expression!, x);",
  "                }",
  "                catch (error) {",
  "                    if (error instanceof ModelError)",
  "                        throw new ModelError(error.diagnostics.map((diagnostic) => ({ ...diagnostic, nodeId: id })));",
  "                    throw error;",
  "                }",
  "            });",
  "            break;",
  "        }",
  "        case 'discrete.unit-delay':",
  "            if (state === undefined)",
  "                numericFailure('RUNTIME_INVALID_IR', id, '상태 값이 없습니다.');",
  "            value = state;",
  "            break;",
  "        case 'continuous.integrator':",
  "            value = finiteNumber(state, id);",
  "            break;",
  "        default: return numericFailure('RUNTIME_UNSUPPORTED_BLOCK', id, '지원하지 않는 실행 블럭입니다.');",
  "    }",
  "    return { out: value };",
  "}",
  "/** Binary search on a validated immutable time axis; previous never reads ahead. */",
  "function replayDataset(node: IRNode, time: number): number | boolean {",
  "    const times = node.parameters.times as number[], values = node.parameters.values as (number | boolean)[];",
  "    const first = times[0]!, last = times.at(-1)!;",
  "    if (time < first || time > last) {",
  "        if (node.parameters.outside === 'error')",
  "            numericFailure('DATASET_TIME_RANGE', node.id, '실행 시각이 데이터 시간 범위를 벗어났습니다.');",
  "        if (node.parameters.outside === 'zero')",
  "            return node.parameters.dataKind === 'boolean' ? false : 0;",
  "        return values[time < first ? 0 : values.length - 1]!;",
  "    }",
  "    let low = 0, high = times.length - 1;",
  "    while (low < high) {",
  "        const middle = Math.ceil((low + high) / 2);",
  "        if (times[middle]! <= time)",
  "            low = middle;",
  "        else",
  "            high = middle - 1;",
  "    }",
  "    if (times[low] === time || low === times.length - 1 || node.parameters.interpolation === 'previous')",
  "        return values[low]!;",
  "    const ratio = (time - times[low]!) / (times[low + 1]! - times[low]!);",
  "    return finiteNumber((1 - ratio) * (values[low] as number) + ratio * (values[low + 1] as number), node.id);",
  "}",
  "/** Bounded binary search; exact endpoints preserve the supplied table values. */",
  "function interpolateTable(x: number, breakpoints: number[], values: number[], interpolation: string, extrapolation: string, nodeId: string): number {",
  "    if (x < breakpoints[0]! || x > breakpoints.at(-1)!) {",
  "        if (extrapolation === 'error')",
  "            numericFailure('LOOKUP_RANGE', nodeId, '입력이 Lookup 표 범위를 벗어났습니다.');",
  "        return x < breakpoints[0]! ? values[0]! : values.at(-1)!;",
  "    }",
  "    let low = 0, high = breakpoints.length - 1;",
  "    while (low + 1 < high) {",
  "        const middle = Math.floor((low + high) / 2);",
  "        if (x < breakpoints[middle]!)",
  "            high = middle;",
  "        else",
  "            low = middle;",
  "    }",
  "    if (x === breakpoints[high]!)",
  "        return values[high]!;",
  "    if (interpolation === 'previous' || x === breakpoints[low]!)",
  "        return values[low]!;",
  "    // Weighted interpolation avoids overflow in a difference between large endpoints.",
  "    const scale = Math.max(Math.abs(x), Math.abs(breakpoints[low]!), Math.abs(breakpoints[high]!));",
  "    const difference = breakpoints[high]! - breakpoints[low]!;",
  "    const ratio = Number.isFinite(difference) ? (x - breakpoints[low]!) / difference",
  "        : (x / scale - breakpoints[low]! / scale) / (breakpoints[high]! / scale - breakpoints[low]! / scale);",
  "    return finiteNumber(values[low]! * (1 - ratio) + values[high]! * ratio, nodeId);",
  "}"
].join('\n');
