// Generated from repository-owned runtime sources by sync-runtime-templates.ts.
export const SIGNAL_TYPES_TEMPLATE = [
  "type LegacySignalValue = number | boolean | number[] | boolean[] | number[][] | boolean[][];",
  "/** JSON preserves tagged IEEE special values, signed zero, and exact integer codes. */",
  "type TypedFloat = number | '-0' | 'NaN' | 'Infinity' | '-Infinity';",
  "interface TypedComplex {",
  "    re: TypedFloat;",
  "    im: TypedFloat;",
  "}",
  "type TypedDType = 'float64' | 'float32' | 'boolean' | 'int8' | 'uint8' | 'int16' | 'uint16' | 'int32' | 'uint32' | 'int64' | 'uint64' | 'complex128' | 'fixed' | 'string' | 'enum';",
  "interface TypedFixedSpec {",
  "    signed: boolean;",
  "    wordLength: number;",
  "    fractionLength: number;",
  "}",
  "interface TypedEnumSpec {",
  "    name: string;",
  "    labels: string[];",
  "}",
  "interface TypedDataType {",
  "    dtype: TypedDType;",
  "    fixed?: TypedFixedSpec;",
  "    enum?: TypedEnumSpec;",
  "}",
  "type TypedRounding = 'floor' | 'ceil' | 'zero' | 'nearest' | 'away' | 'even';",
  "type TypedOverflow = 'wrap' | 'saturate' | 'error';",
  "type TypedCell = TypedFloat | boolean | string | TypedComplex;",
  "interface TypedSignal extends TypedDataType {",
  "    kind: 'typed';",
  "    /** Fixed, row-major rank 0..8; data stores exact decimal integer/fixed codes. */",
  "    shape: number[];",
  "    data: TypedCell[];",
  "}",
  "type SignalValue = LegacySignalValue | TypedSignal;",
  "type StateValue = number | boolean | string | null | TypedSignal | StateValue[] | {",
  "    [key: string]: StateValue;",
  "};",
  "interface SignalDescriptor {",
  "    valueType: 'float64' | 'boolean' | 'typed';",
  "    /** Scalar [], vector [length], or row-major matrix [rows, columns]. */",
  "    shape: number[];",
  "    unit: string;",
  "    /** Present only when valueType is typed. No implicit conversion to legacy kernels. */",
  "    typed?: TypedDataType;",
  "    /** A homogeneous scalar bus is represented as a vector with named fields. */",
  "    fields?: string[];",
  "    /** Compiler representation contract for explicitly converted homogeneous buses. */",
  "    representation?: 'copy' | 'virtual' | 'nonvirtual';",
  "}"
].join('\n');
