import type { BlockType } from '../../../packages/model/src';

// Explicit compact symbols keep every registered block recognizable in the library.
// Completeness is checked against BlockType so future additions cannot silently render empty.
export const BLOCK_SYMBOLS: Readonly<Record<string, string>> = Object.freeze({
  'adapter.wasm-affine': 'f', 'adapter.wasm-accumulator': 'Σ', 'adapter.entity-transport': 'FIFO',
  'dashboard.control': '↕', 'dashboard.indicator': '▥', 'dashboard.action': '▶', 'sink.record': '●', 'sink.xy-graph': 'XY', 'sink.floating-scope': '▥', 'sink.stop': '■', 'signal.probe': 'i', 'math.slider-gain': '×', 'data.output-file': '↓', 'data.output-dataset': '▤', 'data.input-table': '▤', 'data.signal-editor': '∿', 'source.waveform': '∿', 'source.string-constant': 'S', 'string.ascii-to-string': 'S', 'string.compose': 'fmt', 'string.scan': 'scan', 'string.string-compare': '=', 'string.string-concatenate': '+', 'string.string-contains': '∈', 'string.string-count': 'n', 'string.string-find': 'i', 'string.string-length': 'n', 'string.string-to-ascii': 'ASCII', 'string.parse-number': 'N', 'string.parse-enum': 'E', 'string.substring': '[ ]', 'string.to-string': 'S', 'model.support-catalog': 'i',
  'continuous.descriptor': 'Eẋ', 'continuous.integrator-limited': '∫', 'continuous.second-order-limited': '∫²', 'continuous.pid-2dof': 'PID', 'time.variable-delay': 'τ(t)', 'time.variable-transport-delay': 'q', 'nonlinear.backlash': '⇄', 'nonlinear.rate-limiter-continuous': 'Δ/t', 'nonlinear.rate-limiter-dynamic': 'Δ/t', 'solver.algebraic-constraint': 'f=0', 'analysis.linearization': 'J',
  'source.constant': '1', 'io.input': '↗', 'math.gain': '×', 'math.sum': '+',
  'math.multiply': '∏', 'sink.display': '▥', 'discrete.unit-delay': 'z⁻¹', 'continuous.integrator': '∫',
  'math.abs': '|x|', 'math.function': 'f', 'math.trigonometric': 'sin', 'math.round': '≈', 'math.minmax': '↧',
  'math.sqrt': '√', 'logic.compare': '<', 'logic.boolean': '∧', 'route.switch': '?', 'nonlinear.saturation': '↔',
  'route.mux': '⊞', 'route.demux': '⇉', 'math.concatenate': '⊕', 'matrix.reshape': '↔', 'io.output': '↗',
  'io.terminator': '⊣', 'math.expression': 'fx',
  'source.step': '⌐', 'source.ramp': '∕', 'source.sine-wave': '∿', 'source.pulse': '⌜',
  'source.clock': 't', 'source.digital-clock': 'tₖ', 'source.random': '⚄', 'source.repeating-sequence': '↻',
  'discrete.delay': 'z⁻ⁿ', 'discrete.integrator': 'Σ', 'discrete.difference': 'Δ', 'discrete.derivative': 'Δt',
  'discrete.fir': 'FIR', 'discrete.transfer-function': 'H', 'discrete.state-space': 'xₖ',
  'logic.edge-detect': '↑', 'time.rate-transition': 'RT', 'lookup.interpolated': '▱', 'logic.bitwise': '&', 'sink.scope': '▥',
  'continuous.second-order-integrator': '∫²', 'continuous.state-space': 'ẋ', 'continuous.transfer-function': 'H(s)',
  'continuous.zero-pole': 'ZP', 'continuous.pid': 'PID', 'continuous.derivative': 'd/dt',
  'time.memory': 'M', 'time.zero-order-hold': 'ZOH', 'time.first-order-hold': 'FOH', 'time.transport-delay': 'τ',
  'logic.hit-crossing': '↗', 'nonlinear.relay': '⇄',
  'source.dataset': '▤', 'unit.convert': '↔', 'route.bus-create': '⊞', 'route.bus-select': '⇥',
  'hierarchy.subsystem': '▦', 'annotation.note': '¶', 'annotation.model-info': 'i',
  'math.matrix-multiply': 'AB', 'matrix.transpose': 'Aᵀ', 'matrix.determinant': '|A|',
  'matrix.inverse': 'A⁻¹', 'matrix.solve': 'A\\b', 'matrix.cholesky': 'LLᵀ', 'matrix.lu': 'LU',
  'lookup.2d': '▦', 'lookup.prelookup': 'k,f', 'fixed.quantize': 'Q',
  'math.bias': '+b', 'math.sign': '±', 'math.cbrt': '∛', 'math.expm1': 'eˣ−1', 'math.log1p': 'ln1+',
  'math.log2': 'log₂', 'math.exp2': '2ˣ', 'math.sinh': 'sh', 'math.cosh': 'ch', 'math.tanh': 'th',
  'math.asinh': 'ash', 'math.acosh': 'ach', 'math.atanh': 'ath', 'math.sinc': 'sinc', 'math.polynomial': 'P(x)',
  'math.power': 'xʸ', 'math.hypot': '√∑', 'math.atan2': 'θ', 'math.mod': 'mod', 'math.remainder': 'rem',
  'nonlinear.dead-zone': 'DZ', 'nonlinear.quantizer': 'QΔ', 'logic.interval': '[ ]', 'logic.is-integer': 'ℤ', 'logic.approx-equal': '≈',
  'reduce.sum': 'Σ', 'reduce.product': 'Π', 'reduce.mean': 'μ', 'reduce.median': 'Med', 'reduce.variance': 'σ²',
  'reduce.std': 'σ', 'reduce.rms': 'RMS', 'reduce.norm1': 'L₁', 'reduce.norm2': 'L₂', 'reduce.norm-inf': 'L∞',
  'reduce.all': '∀', 'reduce.any': '∃', 'vector.dot': '·', 'vector.cross': '×', 'vector.normalize': 'v̂',
  'vector.reverse': '⇆', 'vector.sort': '↕', 'vector.cumsum': 'Σₖ', 'vector.cumprod': 'Πₖ', 'vector.difference': 'Δv',
  'vector.select': 'vᵢ', 'vector.slice': '[i:j]', 'vector.repeat': '↻', 'vector.convolve': '∗',
  'matrix.trace': 'tr', 'matrix.diagonal': '↘', 'matrix.diag-create': 'D', 'matrix.identity': 'I', 'matrix.select': 'Aᵢⱼ',
  'matrix.row': 'Aᵢ', 'matrix.column': 'Aⱼ', 'matrix.horizontal': 'A|B', 'matrix.vertical': 'A/B',
  'matrix.triangle': '△', 'matrix.symmetrize': 'S', 'matrix.kronecker': '⊗',
  'source.linspace': 'Lin', 'source.logspace': 'Log', 'source.zeros': '0', 'source.chirp': 'f↗',
  'source.gaussian-pulse': 'G', 'source.damped-sine': 'e∿', 'source.exponential': 'eˣ', 'source.logistic': 'S', 'source.sinc-pulse': 'sinc',
  'discrete.filter': 'H', 'discrete.filter-time-varying': 'Hₖ', 'discrete.pid': 'PID', 'discrete.pid-2dof': 'PID',
  'discrete.zero-pole': 'ZP', 'discrete.delay-configured': 'z⁻ⁿ', 'discrete.tapped-delay': '⇉', 'discrete.propagation-delay': 'τ',
  'discrete.integrator-configured': 'Σ', 'discrete.state-space-mimo': 'xₖ', 'discrete.difference-configured': 'Δ',
  'logic.numeric-edge': '↗', 'math.running-minmax': '↧', 'time.weighted-math': 'Tₛ', 'time.decrement-to-zero': 'T−',
  'signal.initial-condition': 'IC', 'source.band-limited-noise': '⚄', 'source.counter': 'k', 'source.pwm': '⌜',
  'source.variable-pulse': '⌜', 'source.signal-generator': '∿', 'source.sine-configured': '∿',
  'source.sequence-configured': '↻', 'source.random-configured': '⚄', 'verify.gradient': 'Δ?', 'verify.resolution': 'Q?',
  'source.typed': 'T', 'source.enum': 'E', 'signal.cast': 'T→', 'signal.cast-inherited': 'T↘', 'signal.to-legacy': '↗',
  'signal.type-duplicate': 'T=', 'signal.type-propagation': 'T←', 'signal.scaling-strip': 'Q→', 'signal.representation': '↔',
  'signal.specification': 'T?', 'signal.width': 'n', 'signal.bus-to-vector': '⇥', 'signal.unit-system': 'SI',
  'logic.bit-mask': 'bit', 'logic.extract-bits': '[b]', 'logic.float-extract-bits': 'IEEE', 'logic.integer-to-bits': '→b',
  'logic.bits-to-integer': 'b→', 'logic.shift-arithmetic': '≫', 'logic.bitwise-typed': '&', 'fixed.integer-increment': '+1',
  'fixed.trigonometric': 'sin', 'fixed.state-space': 'Qx', 'complex.from-parts': '+i', 'complex.to-parts': 'Re',
  'complex.from-polar': '∠', 'complex.to-polar': '|z|', 'complex.hermitian': 'Aᴴ', 'complex.is-hermitian': 'H?',
  'typed.math': 'T+', 'tensor.reshape': '↔', 'tensor.permute': '⇄', 'tensor.squeeze': '⇥',
  'source.signal': '{ }', 'hierarchy.atomic': '▦', 'hierarchy.enabled': 'E', 'hierarchy.triggered': '↗',
  'hierarchy.enabled-triggered': 'E↗', 'hierarchy.resettable': '↺', 'hierarchy.action': '?', 'hierarchy.function-call': 'f()',
  'hierarchy.for-iterator': 'for', 'hierarchy.while-iterator': 'while', 'hierarchy.for-each': 'each', 'hierarchy.variant': '◇',
  'hierarchy.array-processing': '[ ]', 'hierarchy.neighborhood-processing': '▦', 'hierarchy.pixel-processing': '·',
  'functions.call': 'f()', 'functions.initialize': 'f₀', 'functions.reinitialize': '↺f', 'functions.reset': '↺', 'functions.terminate': 'f₁',
  'functions.element': 'f', 'functions.typed': 'f(x)', 'hierarchy.if': 'if', 'hierarchy.switch-case': 'case',
  'route.structured-bus': '{ }', 'route.structured-select': '{}→', 'route.structured-assign': '→{}',
  'events.send': '↑', 'events.queue': 'Q', 'events.receive': '↓', 'events.message-merge': '⇉',
  'events.function-call-generator': 'f↗', 'events.function-call-split': 'f⇉', 'events.feedback-latch': 'z⁻¹', 'events.hit-scheduler': 't↗',
  'route.merge': '⇉', 'route.goto': '→G', 'route.from': 'G→', 'route.tag-visibility': 'G',
  'route.data-store-memory': 'D', 'route.data-store-read': 'D→', 'route.data-store-write': '→D',
  'state.reader': 'x→', 'state.writer': '→x', 'state.parameter-writer': '→p', 'sink.sequence-viewer': '⇅',
  'io.structured-input': '{}→', 'io.structured-output': '→{}',
  // Dynamic limits, mathematical transforms, and variable-width routing.
  'nonlinear.friction': 'μ', 'nonlinear.dead-zone-dynamic': 'DZ↕', 'nonlinear.saturation-dynamic': '↔↕', 'nonlinear.wrap-to-zero': '→0',
  'logic.compare-constant': '<C', 'logic.interval-dynamic': '[↕]', 'logic.truth-table': '01',
  'math.signed-sqrt': '±√', 'math.reciprocal-sqrt': '1/√', 'math.negate': '−', 'math.sine-wave-function': 'sin', 'math.increment': '+Δ',
  'matrix.assign': 'A←', 'matrix.find-nonzero': '≠0', 'matrix.permute-dimensions': '⇄', 'matrix.squeeze': '⇥',
  'matrix.expand-scalar': '1→A', 'matrix.is-symmetric': 'Aᵀ?', 'matrix.is-triangular': '△?', 'matrix.square': 'AᵀA', 'matrix.permute-rows-cols': 'PAQ',
  'route.manual-switch': '1|2', 'route.multiport-switch': '⇥n', 'verify.assert': '✓', 'verify.bounds': '[✓]',
  'lookup.direct': '[i]', 'lookup.interpolate-prelookup': 'k→f', 'lookup.dynamic': '▱↕', 'lookup.nd': 'nD',
  'math.gain-matrix': 'Ku', 'math.sum-inputs': 'Σ', 'math.product-inputs': 'Π', 'logic.combine': '∧', 'route.switch-threshold': '>?',
  'vector.select-dynamic': 'v[i]', 'matrix.select-dynamic': 'A[i]', 'route.mux-inputs': '⊞n', 'route.demux-widths': '⇉w',
  'math.concatenate-inputs': '⊕n', 'matrix.reshape-column-major': 'A↓', 'reduce.axis': 'Σᵢ', 'complex.dot': 'zᴴw',
} satisfies Record<BlockType, string>);

/** Unknown imported or future IDs use a neutral block mark rather than an empty icon. */
export function getBlockSymbol(type: string): string {
  return Object.hasOwn(BLOCK_SYMBOLS, type) ? BLOCK_SYMBOLS[type] : 'B';
}
