import { getBlockDefinition } from '../../../packages/block-library/src';
import type { CalcEdge, CalcModel, CalcNode, SubsystemDefinition } from '../../../packages/model/src';
import type { CalcExample } from './examples';

function block(id: string, blockType: string, label: string, overrides: Record<string, unknown> = {}): CalcNode {
  const definition = getBlockDefinition(blockType);
  if (!definition) throw new Error(`예제 블록을 찾을 수 없습니다: ${blockType}`);
  return { id, blockType, blockVersion: 1, label, parameters: { ...structuredClone(Object.fromEntries(Object.entries(definition.parameters).map(([key, parameter]) => [key, parameter.default]))), ...overrides } };
}
function wire(source: string, target: string, portId = 'in', sourcePort = 'out'): CalcEdge { return { id: `${source}-${sourcePort}-${target}-${portId}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId } }; }
function gainDefinition(id: string, gain: number): SubsystemDefinition {
  return { id, version: 1, name: `배율 ${gain} 정의`, nodes: [block('input', 'io.input', '외부 입력'), block('gain', 'math.gain', '내부 배율', { gain }), block('output', 'io.output', '외부 출력')], edges: [wire('input', 'gain'), wire('gain', 'output')], layout: { input: { x: 40, y: 140 }, gain: { x: 300, y: 140 }, output: { x: 560, y: 140 } }, inputs: [{ id: 'in', nodeId: 'input' }], outputs: [{ id: 'out', nodeId: 'output' }] };
}
function accumulatorDefinition(): SubsystemDefinition {
  return { id: 'accumulator', version: 1, name: '호출마다 입력 더하기', nodes: [block('input', 'io.input', '외부 입력'), block('memory', 'discrete.unit-delay', '이전 합', { initial: 0 }), block('sum', 'math.sum', '새 합'), block('output', 'io.output', '외부 출력')], edges: [wire('input', 'sum', 'a'), wire('memory', 'sum', 'b'), wire('sum', 'memory'), wire('sum', 'output')], layout: { input: { x: 40, y: 40 }, memory: { x: 300, y: 250 }, sum: { x: 300, y: 40 }, output: { x: 580, y: 40 } }, inputs: [{ id: 'in', nodeId: 'input' }], outputs: [{ id: 'out', nodeId: 'output' }] };
}
function example(id: string, title: string, description: string, nodes: CalcNode[], edges: CalcEdge[], notes: string, definitions: SubsystemDefinition[] = [], mode: 'static' | 'discrete' = 'discrete', stopTime = 5): CalcExample {
  const layout = Object.fromEntries(nodes.map((node, index) => [node.id, { x: 40 + Math.floor(index / 2) * 320, y: 40 + index % 2 * 240 }]));
  const model: CalcModel = { schemaVersion: 1, modelId: id, name: title, nodes, edges, layout, execution: { mode, startTime: 0, stopTime: mode === 'static' ? 0 : stopTime, step: 1 }, notes, ...(definitions.length ? { subsystems: definitions } : {}) };
  return { id, title, description, category: 'hierarchy', model };
}

export function createM11Examples(): CalcExample[] {
  const accumulator = accumulatorDefinition(), pulse = () => block('pulse', 'source.pulse', '두 번 켜고 두 번 쉬기', { amplitude: 1, period: 4, width: 2, phase: 0 });
  const reference = { definitionId: accumulator.id, version: 1, initialOutputs: '{"out":0}' };
  const iteration: SubsystemDefinition = { id: 'iteration', version: 1, name: '반복 번호의 두 배', nodes: [block('iteration', 'io.input', '반복 번호'), block('gain', 'math.gain', '두 배', { gain: 2 }), block('output', 'io.output', '반복 결과')], edges: [wire('iteration', 'gain'), wire('gain', 'output')], layout: { iteration: { x: 40, y: 140 }, gain: { x: 300, y: 140 }, output: { x: 560, y: 140 } }, inputs: [{ id: 'iteration', nodeId: 'iteration' }], outputs: [{ id: 'out', nodeId: 'output' }] };
  const whileDefinition: SubsystemDefinition = { id: 'whileBody', version: 1, name: '세 번째 반복에서 마치기', nodes: [block('iteration', 'io.input', '반복 번호'), block('bias', 'math.bias', '번호에 1 더하기', { bias: 1 }), block('compare', 'logic.compare', '번호가 2보다 작은가', { operation: 'lt' }), block('limit', 'source.constant', '조건 상한', { value: 2 }), block('output', 'io.output', '반복 결과'), block('continue', 'io.output', '다음 반복 조건')], edges: [wire('iteration', 'bias'), wire('iteration', 'compare', 'a'), wire('limit', 'compare', 'b'), wire('bias', 'output'), wire('compare', 'continue')], layout: { iteration: { x: 40, y: 140 }, bias: { x: 340, y: 40 }, limit: { x: 40, y: 400 }, compare: { x: 340, y: 320 }, output: { x: 640, y: 40 }, continue: { x: 640, y: 320 } }, inputs: [{ id: 'iteration', nodeId: 'iteration' }], outputs: [{ id: 'out', nodeId: 'output' }, { id: 'continue', nodeId: 'continue' }] };
  const payload = { kind: 'bus', fields: [{ name: 'counter', value: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } }, { name: 'ready', value: true }] };
  return [
    example('controlled-independent-states', '같은 정의, 서로 다른 상태', '같은 누적 정의를 두 인스턴스로 실행해 입력 1과 3의 상태를 따로 확인합니다.', [block('one', 'source.constant', '입력 1', { value: 1 }), block('three', 'source.constant', '입력 3', { value: 3 }), block('first', 'hierarchy.atomic', '첫 누적', reference), block('second', 'hierarchy.atomic', '둘째 누적', reference), block('first-result', 'sink.scope', '첫 상태'), block('second-result', 'sink.scope', '둘째 상태')], [wire('one', 'first'), wire('three', 'second'), wire('first', 'first-result'), wire('second', 'second-result')], '두 인스턴스는 정의를 공유하지만 상태는 공유하지 않습니다. 첫 누적은 1,2,3,…, 둘째 누적은 3,6,9,…입니다. 인스턴스를 더블클릭하면 공통 정의를 편집합니다. 정의 수정 후 전체 인스턴스 버전 갱신으로 다른 참조를 갱신하세요.', [accumulator]),
    example('controlled-enable-state', '다시 켤 때 상태 유지와 초기화', 'enable 펄스로 두 누적 도식의 hold와 reset을 비교합니다.', [block('one', 'source.constant', '매 호출에 1', { value: 1 }), pulse(), block('hold', 'hierarchy.enabled', '상태 이어가기', { ...reference, stateOnEnable: 'hold' }), block('reset', 'hierarchy.enabled', '다시 켜면 초기화', { ...reference, stateOnEnable: 'reset' }), block('hold-result', 'sink.scope', '유지 기록'), block('reset-result', 'sink.scope', '초기화 기록')], [wire('one', 'hold'), wire('one', 'reset'), wire('pulse', 'hold', 'enable'), wire('pulse', 'reset', 'enable'), wire('hold', 'hold-result'), wire('reset', 'reset-result')], 'enable은 1,1,0,0,1,1입니다. 두 도식은 비활성 출력을 유지합니다. 재활성 시 hold는 이전 합을 이어가고 reset은 내부 초기 상태에서 다시 시작합니다.', [accumulator]),
    example('controlled-trigger-reset', '트리거 호출과 상태 초기화', '같은 펄스의 상승 변화에서 호출하거나 누적 상태를 초기화합니다.', [block('one', 'source.constant', '매 호출에 1', { value: 1 }), pulse(), block('triggered', 'hierarchy.triggered', '상승 변화에 호출', { ...reference, trigger: 'rising' }), block('resettable', 'hierarchy.resettable', '상승 변화에 초기화', { ...reference, resetMode: 'rising' }), block('reset-condition', 'logic.compare-constant', '양수 펄스를 boolean으로', { operator: 'gt', constant: 0 }), block('trigger-result', 'sink.scope', '호출 기록'), block('reset-result', 'sink.scope', '초기화 기록')], [wire('one', 'triggered'), wire('one', 'resettable'), wire('pulse', 'triggered', 'trigger'), wire('pulse', 'reset-condition'), wire('reset-condition', 'resettable', 'reset'), wire('triggered', 'trigger-result'), wire('resettable', 'reset-result')], 'Triggered는 펄스의 rising에서만 누적을 한 번 호출하고 사이에는 값을 유지합니다. Resettable은 모든 due에 실행하며 rising 경계에서 상태를 초기화합니다. 첫 양수 입력의 경계 처리는 각 실행 계약을 따릅니다.', [accumulator]),
    example('controlled-for-iteration', '한 시각에서 네 번 반복', '반복 번호 0,1,2,3을 내부 도식에 전달해 마지막 값 6을 얻습니다.', [block('loop', 'hierarchy.for-iterator', '네 번 반복', { definitionId: iteration.id, version: 1, count: 4, iterationPort: 'iteration', initialOutputs: '{"out":0}' }), block('result', 'sink.scope', '마지막 반복 결과')], [wire('loop', 'result')], '각 tick 안에서 반복 번호 0~3에 배율 2를 적용합니다. 시간이 반복마다 전진하지 않습니다. 반복 횟수 0은 호출하지 않고 초기 또는 이전 출력을 유지하며 최대 횟수는 64입니다.', [iteration], 'discrete', 2),
    example('controlled-while-iteration', '조건으로 반복 마치기', '내부 continue가 false가 되는 세 번째 반복의 값 3을 기록합니다.', [block('condition', 'source.constant', '반복 시작', { value: true }), block('loop', 'hierarchy.while-iterator', '최대 네 번 반복', { definitionId: whileDefinition.id, version: 1, maxIterations: 4, conditionOutput: 'continue', iterationPort: 'iteration', initialOutputs: '{"out":0}' }), block('result', 'sink.scope', '마지막 반복 결과')], [wire('condition', 'loop', 'condition'), wire('loop', 'result')], '반복 번호 0,1,2에서 값을 1,2,3으로 계산합니다. 번호 2에서 continue가 false가 되어 종료합니다. continue는 내부 제어 출력이라 부모 도식의 데이터 포트에 표시하지 않습니다. 상한까지 계속 true이면 진단합니다.', [whileDefinition], 'discrete', 2),
    example('controlled-variant', '정의 하나만 선택해 실행', '입력 3을 두 배 또는 다섯 배 정의로 계산합니다.', [block('value', 'source.constant', '입력 3', { value: 3 }), block('variant', 'hierarchy.variant', '선택한 배율', { definitionId: 'double', version: 1, alternateDefinitionId: 'fivefold', alternateVersion: 1, active: 'first' }), block('result', 'sink.scope', '선택 결과')], [wire('value', 'variant'), wire('variant', 'result')], '첫 정의를 선택하면 6, 두 번째 정의를 선택하면 15입니다. 선택하지 않은 정의는 실행하지 않습니다. 두 정의의 외부 입출력 포트 계약을 같게 유지하세요. 하위 도식 열기는 현재 선택한 정의를 엽니다.', [gainDefinition('double', 2), gainDefinition('fivefold', 5)], 'discrete', 2),
    example('structured-nested-bus', '자료형을 보존하는 이름 있는 버스', 'uint64 끝값과 고정소수점·boolean을 중첩 버스로 묶습니다.', [block('counter', 'source.typed', '정확한 카운터', { value: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } }), block('status', 'source.signal', '상태 필드', { value: { kind: 'bus', fields: [{ name: 'ready', value: true }, { name: 'temperature', value: { kind: 'typed', dtype: 'fixed', fixed: { signed: true, wordLength: 16, fractionLength: 8 }, shape: [], data: ['385'] } }] } }), block('bus', 'route.structured-bus', '이름으로 묶기', { count: 2, fields: '["counter","status"]' }), block('select', 'route.structured-select', '준비 상태 선택', { field: 'status.ready' }), block('result', 'sink.display', '원본 버스'), block('ready-result', 'sink.display', '선택 필드')], [wire('counter', 'bus', 'in1'), wire('status', 'bus', 'in2'), wire('bus', 'select'), wire('bus', 'result'), wire('select', 'ready-result')], 'counter는 18446744073709551615를 정수 문자열로 보존합니다. temperature 저장 코드 385는 1.50390625이며 ready는 boolean입니다. 결과의 각 필드를 펼치면 타입과 정확한 값을 볼 수 있습니다. CSV는 표시용 기록이고 복원은 모델 JSON을 사용합니다.', [], 'static'),
    example('structured-message-queue', '메시지를 저장하고 다음 tick에 읽기', '버스 payload를 발행하고 큐의 이전 메시지를 순서대로 꺼냅니다.', [block('payload', 'source.signal', '정확한 payload', { value: payload }), block('send', 'source.constant', '발행하기', { value: true }), block('sender', 'events.send', '센서 메시지', { producer: 'sensor', priority: 0 }), block('receive', 'source.constant', '한 개씩 읽기', { value: true }), block('queue', 'events.queue', '이전 메시지 큐', { capacity: 8, maxDequeue: 1, overflow: 'error' }), block('messages', 'sink.sequence-viewer', '받은 메시지'), block('size', 'sink.scope', '큐 저장 개수')], [wire('payload', 'sender', 'payload'), wire('send', 'sender', 'send'), wire('sender', 'queue'), wire('receive', 'queue', 'receive'), wire('queue', 'messages'), wire('queue', 'size', 'in', 'size')], '큐는 기존 메시지를 먼저 dequeue한 뒤 새 메시지를 enqueue합니다. 첫 샘플은 빈 batch이고 다음 tick부터 이전 발행 메시지를 받습니다. 원본 기록에서 발행자 sensor, sequence, 발행 시각, priority와 정확한 bus payload를 확인하세요.', [], 'discrete', 4),
  ];
}
