import { getBlockDefinition } from '../../../packages/block-library/src';
import type { CalcEdge, CalcModel, CalcNode, SubsystemDefinition } from '../../../packages/model/src';
import type { CalcExample } from './examples';

function block(id: string, blockType: string, label: string, overrides: Record<string, unknown> = {}): CalcNode {
  const definition = getBlockDefinition(blockType);
  if (!definition) throw new Error(`예제 블록을 찾을 수 없습니다: ${blockType}`);
  return { id, blockType, blockVersion: 1, label, parameters: { ...structuredClone(Object.fromEntries(Object.entries(definition.parameters).map(([key, parameter]) => [key, parameter.default]))), ...overrides } };
}
function wire(source: string, target: string, portId = 'in', sourcePort = 'out'): CalcEdge { return { id: `${source}-${sourcePort}-${target}-${portId}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId } }; }
function example(id: string, title: string, description: string, nodes: CalcNode[], edges: CalcEdge[], stopTime: number, step: number, notes: string, definitions: SubsystemDefinition[] = []): CalcExample {
  const model: CalcModel = { schemaVersion: 1, modelId: id, name: title, nodes, edges, layout: Object.fromEntries(nodes.map((node, index) => [node.id, { x: 40 + Math.floor(index / 3) * 320, y: 40 + index % 3 * 210 }])), execution: { mode: 'continuous', startTime: 0, stopTime, step, solver: { method: 'rk4', initialStep: Math.min(step, .05), maxStep: Math.min(step, .05) } }, notes, ...(definitions.length ? { subsystems: definitions } : {}) };
  return { id, title, description, category: 'solver', model };
}

export function createM12Examples(): CalcExample[] {
  const plant: SubsystemDefinition = { id: 'linearPlant', version: 1, name: '1상태 연속 분석 대상', nodes: [block('input', 'io.input', '분석 입력'), block('state', 'continuous.state-space', '실제 연속 상태', { A: [[-2]], B: [3], C: [4], D: 5, initial: [0] }), block('output', 'io.output', '분석 출력')], edges: [wire('input', 'state'), wire('state', 'output')], layout: { input: { x: 40, y: 140 }, state: { x: 320, y: 140 }, output: { x: 600, y: 140 } }, inputs: [{ id: 'in', nodeId: 'input' }], outputs: [{ id: 'out', nodeId: 'output' }] };
  const stiff = example('stiff-implicit-decay', '빠른 감쇠와 암시적 Euler', 'x′=−1000x, x(0)=1을 실제 오차 제어로 계산합니다.', [block('state', 'continuous.integrator', '감쇠 상태', { initial: 1 }), block('rate', 'math.gain', '빠른 변화율', { gain: -1000 }), block('result', 'sink.scope', '감쇠 기록')], [wire('state', 'rate'), wire('rate', 'state'), wire('state', 'result')], .005, .001, '해석해는 exp(−1000t)입니다. 암시적 Euler의 내부 스텝·오차 허용값·수렴 검사를 바꾸고, 분석의 모델 해상도로 두 실제 실행을 비교하세요.');
  stiff.model.execution.solver = { method: 'implicit-euler', initialStep: .001, maxStep: .001, minStep: 1e-8, atol: 1e-7, rtol: 1e-4 };
  return [
    stiff,
    example('algebraic-square-root', '도식으로 푸는 대수 제약', 'z²−9=0의 양수 해를 초기 추정 2에서 구합니다.', [block('unknown', 'solver.algebraic-constraint', '미지수 z', { initial: 2 }), block('residual', 'math.expression', '잔차 z²−9', { expression: 'x^2 - 9' }), block('result', 'sink.scope', '수렴한 z')], [wire('unknown', 'residual'), wire('residual', 'unknown'), wire('unknown', 'result')], 1, .2, '실제 도식의 잔차를 평가해 Newton solve합니다. 해가 없는 x²+1 또는 비매끄러운 loop로 바꾸면 수렴·구조 진단을 확인할 수 있습니다. 상수 정답을 출력하는 블록이 아닙니다.'),
    example('descriptor-index-one', '미분 상태와 대수 상태', 'x′=1−x와 z=1을 하나의 index-1 Descriptor 도식으로 계산합니다.', [block('input', 'source.constant', '입력 1', { value: 1 }), block('plant', 'continuous.descriptor', '두 종류의 상태', { E: [[1, 0], [0, 0]], A: [[-1, 0], [0, 1]], B: [[1], [-1]], C: [[1, 1]], D: [[0]], initial: [0, 1], differentialCount: 1 }), block('result', 'sink.scope', '합 x+z'), block('state-result', 'sink.scope', '전체 상태')], [wire('input', 'plant'), wire('plant', 'result'), wire('plant', 'state-result', 'in', 'state')], 1, .1, '명시 분할의 미분 상태는 x, 대수 상태는 z입니다. E의 대수 행은0이고 A의 대수 부분은 비특이입니다. 전체 초기값 [0,1]은 일관성을 만족하며 합의 해석해는 2−exp(−t)입니다.'),
    example('variable-delay-vs-transport', '시간 지연과 운송 나이', '1초에서 순간 지연을 1→0.5로 바꿔 두 이력 해석을 비교합니다.', [block('clock', 'source.ramp', '숫자 램프 t', { slope: 1, initial: 0 }), block('delay', 'source.step', '지연 변화', { stepTime: 1, before: 1, after: .5 }), block('time-delay', 'time.variable-delay', '시간 차이로 찾기', { minDelay: .1, maxDelay: 2, initial: -1 }), block('transport', 'time.variable-transport-delay', '운송 나이로 찾기', { minDelay: .1, maxDelay: 2, initial: -1 }), block('time-result', 'sink.scope', '시간 지연 출력'), block('transport-result', 'sink.scope', '운송 지연 출력')], [wire('clock', 'time-delay'), wire('delay', 'time-delay', 'delay'), wire('clock', 'transport'), wire('delay', 'transport', 'delay'), wire('time-delay', 'time-result'), wire('transport', 'transport-result')], 1.25, .25, '시간 지연은 t−delay를 찾습니다. 운송 지연은 q′=1/delay를 적분해 나이1의 입력을 찾습니다. t=1.25에서 각각0.75와0.5가 되어 별도 시간 의미를 보여줍니다. 승인된 이력과 양의 지연 하한을 사용합니다.'),
    example('continuous-state-limits', '상태가 경계에 닿는 순간', '제한 적분과 제한 2차 적분의 값·속도·경계 상태를 함께 확인합니다.', [block('input', 'source.constant', '입력 2', { value: 2 }), block('first', 'continuous.integrator-limited', '0에서1까지 적분', { lower: 0, upper: 1 }), block('second', 'continuous.second-order-limited', '위치0.25에서 멈춤', { positionLower: -1, positionUpper: .25, velocityLower: -5, velocityUpper: 5 }), block('first-result', 'sink.scope', '제한 적분 기록'), block('second-result', 'sink.scope', '제한 위치 기록'), block('velocity-result', 'sink.scope', '경계의 속도'), block('limit-result', 'sink.scope', '위치 경계 여부')], [wire('input', 'first'), wire('input', 'second'), wire('first', 'first-result'), wire('second', 'second-result'), wire('second', 'velocity-result', 'in', 'velocity'), wire('second', 'limit-result', 'in', 'positionLimited')], 1, .1, '첫 상태는0.5초에1에 닿습니다. 2차 상태는 x=t²이므로0.5초에0.25에 닿고 속도를0으로 초기화합니다. 이벤트 기록과 boolean 경계 출력은 실제 상태 투영 결과입니다.'),
    example('backlash-and-rate-bounds', '기억하는 틈과 변화율 한도', '삼각 입력에 백래시·연속 변화율·명시 이산 동적 변화율을 적용합니다.', [block('input', 'source.repeating-sequence', '왕복 입력', { times: [0, 1, 2, 3, 4], values: [0, 2, 0, -2, 0] }), block('backlash', 'nonlinear.backlash', '폭1의 틈', { width: 1 }), block('rate', 'nonlinear.rate-limiter-continuous', '초당0.5 한도', { rising: .5, falling: -.5 }), block('hold', 'time.zero-order-hold', '동적 한도의 입력 샘플'), block('rising', 'source.constant', '상승0.5', { value: .5 }), block('falling', 'source.constant', '하강−0.5', { value: -.5 }), block('dynamic', 'nonlinear.rate-limiter-dynamic', 'due-grid 동적 한도'), block('backlash-result', 'sink.scope', '백래시 기록'), block('rate-result', 'sink.scope', '연속 한도 기록'), block('dynamic-result', 'sink.scope', '동적 한도 기록')], [wire('input', 'backlash'), wire('input', 'rate'), wire('input', 'hold'), wire('hold', 'dynamic'), wire('rising', 'dynamic', 'rising'), wire('falling', 'dynamic', 'falling'), wire('backlash', 'backlash-result'), wire('rate', 'rate-result'), wire('dynamic', 'dynamic-result')], 4, .25, '백래시는 이전 승인 출력 중심의 deadband를 기억합니다. 연속 한도는 승인 major-step 사이의 envelope를 계산하고, 동적 한도는 Zero-Order Hold 입력을 이산 기본 간격의 due-grid에서 읽고 갱신합니다.'),
    example('pid-two-degree-weighting', '기준값에 가중치를 주는 PID', 'P 기준 가중치0.5인 2DOF와 일반 P=2 제어기의 출력을 비교합니다.', [block('reference', 'source.step', '기준값', { stepTime: .5, before: 0, after: 1 }), block('measurement', 'source.constant', '측정값 0', { value: 0 }), block('weighted', 'continuous.pid-2dof', '기준값 절반 반영', { kp: 2, ki: 0, kd: 0, b: .5, c: 0, controller: 'P' }), block('plain', 'continuous.pid', '기준값 전체 반영', { kp: 2, ki: 0, kd: 0 }), block('weighted-result', 'sink.scope', '2DOF 출력'), block('plain-result', 'sink.scope', '일반 P 출력')], [wire('reference', 'weighted', 'r'), wire('measurement', 'weighted', 'y'), wire('reference', 'plain'), wire('weighted', 'weighted-result'), wire('plain', 'plain-result')], 1, .1, '측정값0에서 기준값이1이 되면 2DOF P 출력은2×0.5×1=1, 일반 P 출력은2입니다. I/D·필터·출력 제한·적분 포화 보정은 블록 설정에서 명시 선택합니다.'),
    example('local-linearization-requests', '운전점에서 A/B/C/D', '같은 실제 연속 정의를 지정 시각과 boolean 상승 요청으로 분석합니다.', [block('clock', 'source.ramp', '요청 시각 램프', { slope: 1, initial: 0 }), block('trigger', 'logic.hit-crossing', '0.5초 상승 경계', { threshold: .5, direction: 'rising' }), block('timed', 'analysis.linearization', '시각 요청', { definitionId: plant.id, version: 1, operatingInputs: [2], operatingState: [3], times: [0, .5, 1], mode: 'timed' }), block('triggered', 'analysis.linearization', '상승 요청', { definitionId: plant.id, version: 1, operatingInputs: [2], operatingState: [3], times: [0], mode: 'triggered' }), block('timed-result', 'sink.scope', '시각 분석 행렬'), block('triggered-result', 'sink.scope', '상승 분석 행렬')], [wire('clock', 'trigger'), wire('trigger', 'triggered', 'trigger'), wire('timed', 'timed-result'), wire('triggered', 'triggered-result')], 1, .1, '정의는 x′=−2x+3u, y=4x+5u입니다. 입력2·상태3의 운전점에서 실제 중심차분 행렬 A=−2,B=3,C=4,D=5를 계산합니다. 요청 사이에는 마지막 결과를 유지합니다. 분석 블록을 더블클릭해 대상 정의를 편집하세요.', [plant]),
  ];
}
