import type { CalcEdge, CalcModel, CalcNode } from '../../../packages/model/src';
import { getBlockDefinition } from '../../../packages/block-library/src';
import { importLocalDataSource, scenarioSource } from '../../../packages/data/src';
import type { CalcExample } from './examples';
function block(id: string, blockType: string, label: string, overrides: Record<string, unknown> = {}): CalcNode { const definition = getBlockDefinition(blockType); if (!definition) throw new Error(blockType); return { id, blockType, blockVersion: 1, label, parameters: { ...structuredClone(Object.fromEntries(Object.entries(definition.parameters).map(([key, parameter]) => [key, parameter.default]))), ...overrides } }; }
const wire = (source: string, target: string, portId = 'in', sourcePort = 'out'): CalcEdge => ({ id: `${source}-${sourcePort}-${target}-${portId}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId } });
function example(id: string, title: string, description: string, nodes: CalcNode[], edges: CalcEdge[], category: CalcExample['category'], stopTime = 1, step = .1): CalcExample { return { id, title, description, category, model: { schemaVersion: 1, modelId: id, name: title, nodes, edges, layout: Object.fromEntries(nodes.map((node, index) => [node.id, { x: 40 + Math.floor(index / 3) * 320, y: 40 + index % 3 * 190 }])), execution: { mode: 'discrete', startTime: 0, stopTime, step }, notes: description } }; }
export function createM13Examples(): CalcExample[] {
  const names = example('string-unicode-search', '문자열을 찾고 세기', 'Unicode 문자열의 길이·위치·반복 횟수를 계산합니다. 찾기는1부터 시작하며 case-insensitive는 ASCII A–Z만 비교합니다.', [block('text', 'source.string-constant', '원문', { value: 'A🙂A🙂' }), block('pattern', 'source.string-constant', '찾을 패턴', { value: '🙂' }), block('length', 'string.string-length', '문자 개수'), block('find', 'string.string-find', '첫 위치'), block('count', 'string.string-count', '출현 횟수'), block('length-result', 'io.structured-output', '길이'), block('find-result', 'io.structured-output', '위치'), block('count-result', 'io.structured-output', '횟수')], [wire('text', 'length'), wire('text', 'find'), wire('pattern', 'find', 'pattern'), wire('text', 'count'), wire('pattern', 'count', 'pattern'), wire('length', 'length-result'), wire('find', 'find-result'), wire('count', 'count-result')], 'strings');
  const format = example('string-compose-scan', '형식 문자열로 만들고 읽기', '7과2.5를 "7,2.50"으로 만든 뒤 int32·float64로 읽습니다. 형식 토큰을 검증하며 임의 코드나 정규식을 실행하지 않습니다.', [block('integer', 'source.constant', '정수7', { value: 7 }), block('fraction', 'source.constant', '소수2.5', { value: 2.5 }), block('compose', 'string.compose', '문자열 조립', { format: '%d,%.2f' }), block('scan', 'string.scan', '형식 읽기', { format: '%d,%lf' }), block('text-result', 'io.structured-output', '조립한 문자열'), block('integer-result', 'io.structured-output', '읽은 정수'), block('fraction-result', 'io.structured-output', '읽은 소수')], [wire('integer', 'compose', 'arg1'), wire('fraction', 'compose', 'arg2'), wire('compose', 'scan'), wire('compose', 'text-result'), wire('scan', 'integer-result', 'in', 'out1'), wire('scan', 'fraction-result', 'in', 'out2')], 'strings');
  const ascii = example('string-ascii-roundtrip', 'ASCII와 문자열 왕복', '"Hi"를8칸 uint8 배열로 보내고 NUL에서 종료해 문자열로 되돌립니다. UTF-8 byte 변환과 구분하여 ASCII 범위를 검사합니다.', [block('text', 'source.string-constant', 'Hi 문자열', { value: 'Hi' }), block('bytes', 'string.string-to-ascii', '8칸 ASCII', { capacity: 8 }), block('restored', 'string.ascii-to-string', '문자열 복원'), block('bytes-result', 'io.structured-output', 'ASCII 배열'), block('length-result', 'io.structured-output', '유효 길이'), block('text-result', 'io.structured-output', '복원 문자열')], [wire('text', 'bytes'), wire('bytes', 'restored'), wire('bytes', 'bytes-result'), wire('bytes', 'length-result', 'in', 'length'), wire('restored', 'text-result')], 'strings');
  const dashboard = example('dashboard-recorded-controls', '다음 시점의 조작과 게이지', '슬라이더가0→0.4→0.8로 바뀌는 시간·순서 기록을 재현합니다. 실행 중 조작도 실제 적용 시각을 모델에 보관합니다.', [block('control', 'dashboard.control', '입력 슬라이더', { kind: 'slider', initial: 0, events: '[{"time":0.3,"order":0,"value":0.4},{"time":0.6,"order":1,"value":0.8}]' }), block('display', 'dashboard.indicator', '현재 값', { kind: 'display' }), block('gauge', 'dashboard.indicator', '반원 게이지', { kind: 'gauge', gaugeStyle: 'half', appearance: 'custom' }), block('lamp', 'dashboard.indicator', '구간 표시', { kind: 'lamp', thresholds: [.5], labels: '["낮음","높음"]' }), block('result', 'sink.scope', '조작 기록'), block('fit', 'dashboard.action', '도식 맞추기', { action: 'fit' })], [wire('control', 'display'), wire('control', 'gauge'), wire('control', 'lamp'), wire('control', 'result')], 'dashboard');
  const choices = example('dashboard-choice-and-gain', '선택 값과 조작 배율', '선택 상자는 검증한1·2·4만 보냅니다. 배율은1→3으로 바뀌고 두 입력의 실제 곱을 기록합니다.', [block('choice', 'dashboard.control', '선택 상자', { kind: 'combo-box', initial: 1, min: 1, max: 4, choices: [1, 2, 4], events: '[{"time":0.5,"order":0,"value":4}]', appearance: 'custom' }), block('gain', 'math.slider-gain', '조작 배율', { gain: 1, min: 0, max: 5, events: '[{"time":0.7,"order":0,"value":3}]' }), block('result', 'sink.scope', '선택과 배율 출력')], [wire('choice', 'gain'), wire('gain', 'result')], 'dashboard');
  const records = example('waveform-xy-and-record', '파형의 XY와 로컬 기록', '사인·삼각 파형의 같은 시각 X·Y 쌍을 기록합니다. 참조 Scope와 제한된 기록의 JSON·CSV·데이터셋 저장을 비교하세요.', [block('x', 'source.waveform', '사인 X', { kind: 'sine', frequency: 1 }), block('y', 'source.waveform', '삼각 Y', { kind: 'triangle', frequency: 1 }), block('xy', 'sink.xy-graph', '실제 XY 궤적'), block('record', 'sink.record', 'X 원형 기록'), block('file', 'data.output-file', '파일 기록', { name: 'waveform', format: 'csv' }), block('dataset', 'data.output-dataset', '데이터셋 기록', { name: 'waveform-series' }), block('floating', 'sink.floating-scope', '참조 Scope', { sourceNodeId: 'x', sourcePortId: 'out' })], [wire('x', 'xy', 'x'), wire('y', 'xy', 'y'), wire('x', 'record'), wire('x', 'file'), wire('x', 'dataset')], 'dashboard', 1, .05);
  const source = scenarioSource({ name: '두 번의 변화', points: [{ time: 0, value: 0 }, { time: .5, value: 2 }, { time: 1, value: 1 }] }); const dataset = importLocalDataSource(source, { id: 'editedSignal', name: '두 번의 변화', timeColumn: 'time', columns: [{ name: 'time', kind: 'number', unit: 's' }, { name: 'value', kind: 'number', unit: '1' }] });
  const scenario = example('named-signal-editor-playback', '이름 있는 신호와 표 재생', '직접 편집한0→2→1 신호를 선형 보간과 이전 값 유지로 읽습니다. 출처 hash와 정리 기록은 프로젝트 데이터에 함께 보관됩니다.', [block('edited', 'data.signal-editor', '선형 편집 신호', { datasetId: dataset.id, column: 'value', interpolation: 'linear' }), block('table', 'data.input-table', '이전 값의 표 신호', { datasetId: dataset.id, column: 'value', interpolation: 'previous' }), block('linear-result', 'sink.scope', '선형 재생'), block('previous-result', 'sink.scope', '이전 값 재생')], [wire('edited', 'linear-result'), wire('table', 'previous-result')], 'workspace'); scenario.model.datasets = [dataset];
  const stop = example('bounded-record-and-stop', '기록을 마치고 정상 종료', '시계가0.5초에 도달하면 Stop Simulation이 완전한 마지막 샘플을 기록하고 정상 종료합니다. 신호 사양 표도 실제 descriptor를 보여 줍니다.', [block('clock', 'source.clock', '실제 시간'), block('threshold', 'source.constant', '0.5초', { value: .5 },), block('compare', 'logic.compare', '종료 조건', { operation: 'ge' }), block('stop', 'sink.stop', '정상 종료 요청'), block('record', 'sink.record', '종료 전 기록', { capacity: 6 }), block('probe', 'signal.probe', '시간 신호 사양'), block('probe-result', 'io.structured-output', '사양 결과'), block('catalog', 'model.support-catalog', '사양 표'), block('catalog-result', 'io.structured-output', '실행 사양')], [wire('clock', 'compare', 'a'), wire('threshold', 'compare', 'b'), wire('compare', 'stop'), wire('clock', 'record'), wire('clock', 'probe'), wire('probe', 'probe-result'), wire('catalog', 'catalog-result')], 'dashboard', 2, .1); stop.model.nodes.find(node => node.id === 'threshold')!.unit = 's';
  return [names, format, ascii, dashboard, choices, records, scenario, stop];
}
