import { getBlockDefinition } from '../../../packages/block-library/src';
import type { CalcEdge, CalcNode } from '../../../packages/model/src';
import type { CalcExample } from './examples';

function block(id: string, blockType: string, label: string, overrides: Record<string, unknown> = {}): CalcNode {
  const definition = getBlockDefinition(blockType);
  if (!definition) throw new Error(`예제 블록을 찾을 수 없습니다: ${blockType}`);
  return { id, blockType, blockVersion: 1, label, parameters: { ...structuredClone(Object.fromEntries(Object.entries(definition.parameters).map(([key, parameter]) => [key, parameter.default]))), ...overrides } };
}
const wire = (source: string, target: string, portId = 'in', sourcePort = 'out'): CalcEdge => ({ id: `${source}-${sourcePort}-${target}-${portId}`, source: { nodeId: source, portId: sourcePort }, target: { nodeId: target, portId } });
function example(id: string, title: string, description: string, nodes: CalcNode[], edges: CalcEdge[], stopTime = .6): CalcExample {
  return { id, title, description, category: 'adapters', model: { schemaVersion: 1, modelId: id, name: title, nodes, edges, execution: { mode: 'discrete', startTime: 0, stopTime, step: .1 }, layout: Object.fromEntries(nodes.map((node, index) => [node.id, { x: 40 + Math.floor(index / 3) * 310, y: 40 + index % 3 * 180 }])), notes: description } };
}

export function createM14Examples(): CalcExample[] {
  const affine = example('wasm-affine-and-expression', '고정 WASM과 제한 수식 비교', '2 × 3 + 1을 내장 WASM과 제한 수식으로 각각 계산합니다. MATLAB 해석기를 실행하는 대신 수학식을 직접 옮긴 독립 예제입니다.', [block('value', 'source.constant', '입력2', { value: 2 }), block('affine', 'adapter.wasm-affine', 'WASM 배율', { gain: 3, bias: 1 }), block('expression', 'math.expression', '옮긴 수식', { expression: '3*x+1' }), block('wasm-result', 'sink.display', 'WASM 계산'), block('expression-result', 'sink.display', '수식 계산')], [wire('value', 'affine'), wire('value', 'expression'), wire('affine', 'wasm-result'), wire('expression', 'expression-result')], 0);
  affine.model.execution.mode = 'static';
  const decay = example('wasm-continuous-decay', 'WASM으로 계산하는 연속 변화', 'x′ = −2x, x(0) = 1의 변화율을 고정 WASM으로 계산합니다. 순수 affine 프로파일을 연속 solver에서도 실제 사용합니다.', [block('state', 'continuous.integrator', '현재 값', { initial: 1 }), block('affine', 'adapter.wasm-affine', '변화율', { gain: -2, bias: 0 }), block('result', 'sink.scope', '감쇠 기록')], [wire('state', 'affine'), wire('affine', 'state'), wire('state', 'result')], 1);
  decay.model.execution.mode = 'continuous'; decay.model.execution.step = .05;
  const resets = example('wasm-accumulator-resets', '상승 변화와 유지 초기화', '같은 입력1을 누적하다0.3초부터 reset=true로 둡니다. rising은 한 번 초기화하고, level은 참인 시점마다 초기값을 출력합니다.', [block('one', 'source.constant', '입력1', { value: 1 }), block('clock', 'source.clock', '실제 시간'), block('reset', 'logic.compare-constant', '0.3초부터 초기화', { operator: 'gte', constant: .3 }), block('rising', 'adapter.wasm-accumulator', '상승 초기화', { resetMode: 'rising' }), block('level', 'adapter.wasm-accumulator', '유지 초기화', { resetMode: 'level' }), block('rising-result', 'sink.scope', '상승 누적'), block('level-result', 'sink.scope', '유지 누적')], [wire('clock', 'reset'), wire('one', 'rising'), wire('one', 'level'), wire('reset', 'rising', 'reset'), wire('reset', 'level', 'reset'), wire('rising', 'rising-result'), wire('level', 'level-result')]);
  const independent = example('wasm-independent-instances', '두 WASM 상태를 따로 누적', '첫 인스턴스는0에서1씩, 둘째는10에서2씩 누적합니다. 출력은 현재 상태이며 다음 승인 시점에 이전 입력을 더합니다.', [block('one', 'source.constant', '입력1', { value: 1 }), block('reset', 'source.signal', '초기화 없음', { value: false }), block('first', 'adapter.wasm-accumulator', '첫 상태', { initial: 0, gain: 1 }), block('second', 'adapter.wasm-accumulator', '둘째 상태', { initial: 10, gain: 2 }), block('first-result', 'sink.scope', '첫 누적'), block('second-result', 'sink.scope', '둘째 누적')], [wire('one', 'first'), wire('one', 'second'), wire('reset', 'first', 'reset'), wire('reset', 'second', 'reset'), wire('first', 'first-result'), wire('second', 'second-result')], .3);
  const fifo = example('entity-fifo-delay', '도착 순서를 지키는 전달', '메시지 봉투로 전달하는 제한된 엔티티 대체입니다. 첫 항목의0.3초 대기를 후속0초 지연이 추월하지 않으며, 시점당 하나씩 원래 ID·payload를 내보냅니다.', [block('payload', 'source.typed', '정확한 티켓', { value: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } }), block('clock', 'source.clock', '발행 시각'), block('send', 'logic.compare-constant', '0.4초 전 발행', { operator: 'lt', constant: .4 }), block('sender', 'events.send', '티켓 발행', { producer: 'ticket' }), block('delay', 'source.step', '첫 대기 이후0', { stepTime: .1, before: .3, after: 0 }), block('transport', 'adapter.entity-transport', 'FIFO 전달', { maxRelease: 1 }), block('messages', 'io.structured-output', '전달 항목'), block('count', 'sink.scope', '대기 개수')], [wire('clock', 'send'), wire('payload', 'sender', 'payload'), wire('send', 'sender', 'send'), wire('sender', 'transport'), wire('delay', 'transport', 'delay'), wire('transport', 'messages'), wire('transport', 'count', 'in', 'count')]);
  fifo.model.nodes.find(node => node.id === 'delay')!.unit = 's';
  const batch = { kind: 'messages', items: [
    { producer: 'batch', sequence: 1, time: 0, priority: 0, payload: { kind: 'typed', dtype: 'uint64', shape: [], data: ['18446744073709551615'] } },
    { producer: 'batch', sequence: 2, time: 0, priority: 0, payload: { kind: 'typed', dtype: 'uint64', shape: [], data: ['9223372036854775808'] } },
  ] };
  const overflow = example('entity-capacity-policies', '용량 한도에서 새 항목과 이전 항목', '용량1의 두 전달 경로에 같은 두 항목을 보냅니다. drop-newest는 첫 항목을, drop-oldest는 둘째 항목을 보존하며 일반 신호 지연이나 SimEvents 엔진과 구분합니다.', [block('batch', 'source.signal', '두 항목', { value: batch }), block('delay', 'source.constant', '0.2초 대기', { value: .2 }), block('newest', 'adapter.entity-transport', '새 항목 제외', { capacity: 1, overflow: 'drop-newest' }), block('oldest', 'adapter.entity-transport', '이전 항목 제외', { capacity: 1, overflow: 'drop-oldest' }), block('newest-result', 'io.structured-output', '첫 항목 보존'), block('oldest-result', 'io.structured-output', '둘째 항목 보존')], [wire('batch', 'newest'), wire('batch', 'oldest'), wire('delay', 'newest', 'delay'), wire('delay', 'oldest', 'delay'), wire('newest', 'newest-result'), wire('oldest', 'oldest-result')], .3);
  overflow.model.nodes.find(node => node.id === 'delay')!.unit = 's';
  return [affine, decay, resets, independent, fifo, overflow];
}
