import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import type { CalcModel, Dataset } from '../../../../packages/model/src';
import { createInteropArchive, inspectInteropArchive, inspectNativeImport, matVariableDataset, NATIVE_IMPORT_LIMITS, type NativeInspection } from '../../../../packages/interop/src';
import { downloadText } from './M4WorkspaceTools';
import { ModalDialog } from './ModalDialog';
import { Icon } from './Icon';

export interface InteropImportDialogProps { model: CalcModel; busy?: boolean; invalidDraft?: boolean; onApplyModel: (model: CalcModel) => void; onApplyDataset: (dataset: Dataset) => void; onClose: () => void }
function downloadOriginal(inspection: NativeInspection): void { const url = URL.createObjectURL(new Blob([new Uint8Array(inspection.sourceBytes).buffer], { type: 'application/octet-stream' })); const link = document.createElement('a'); link.href = url; link.download = inspection.filename.replace(/[\\/\u0000-\u001f]/g, '_'); link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1_000); }
export function InteropImportDialog({ model, busy = false, invalidDraft = false, onApplyModel, onApplyDataset, onClose }: InteropImportDialogProps) {
  const [inspection, setInspection] = useState<NativeInspection | null>(null), [selected, setSelected] = useState(''), [drafts, setDrafts] = useState<Record<string, string>>({}), [reviewed, setReviewed] = useState(false), [pending, setPending] = useState(false), [error, setError] = useState('');
  const fileInput = useRef<HTMLInputElement>(null), request = useRef(0), alive = useRef(true), originalModel = useRef(model); const changed = originalModel.current !== model;
  useEffect(() => { alive.current = true; return () => { alive.current = false; request.current++; }; }, []);
  const inspectFile = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const id = ++request.current; setPending(true); setError(''); setInspection(null); setSelected(''); setDrafts({}); setReviewed(false);
    try { const archive = /\.cwinterop\.json$/i.test(file.name), max = archive ? NATIVE_IMPORT_LIMITS.maxArchiveBytes : NATIVE_IMPORT_LIMITS.maxInputBytes; if (file.size > max) throw new Error(archive ? '상호운용 보관 파일은 5 MiB 이하여야 합니다.' : '외부 원본은 2 MiB 이하여야 합니다.');
      const checked = archive ? await inspectInteropArchive(await file.text()) : { inspection: await inspectNativeImport(new Uint8Array(await file.arrayBuffer()), file.name) }; if (!alive.current || id !== request.current) return; setInspection(checked.inspection); setSelected('selectedVariable' in checked ? checked.selectedVariable ?? '' : ''); setDrafts(Object.fromEntries(checked.inspection.inports.map(port => [port.nativeId, checked.inspection.options.inports?.[port.nativeId] === undefined ? '' : String(checked.inspection.options.inports[port.nativeId])])));
    } catch (error) { if (alive.current && id === request.current) setError(error instanceof Error ? error.message : '파일을 확인하지 못했습니다.'); }
    finally { if (alive.current && id === request.current) setPending(false); }
  };
  const recheck = async () => { if (!inspection) return; const values: Record<string, number> = Object.create(null); for (const port of inspection.inports) { const text = (drafts[port.nativeId] ?? '').trim(); if (!text) continue; if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(text) || !Number.isFinite(Number(text))) { setError(`${port.name} 입력에 유한 scalar 숫자를 지정하세요.`); return; } values[port.nativeId] = Number(text); } const id = ++request.current; setPending(true); setError(''); setReviewed(false); try { const checked = await inspectNativeImport(inspection.sourceBytes, inspection.filename, { inports: values }); if (alive.current && request.current === id) { setInspection(checked); setDrafts(Object.fromEntries(checked.inports.map(port => [port.nativeId, checked.options.inports?.[port.nativeId] === undefined ? '' : String(checked.options.inports[port.nativeId])]))); } } catch (error) { if (alive.current && request.current === id) setError(error instanceof Error ? error.message : '입력을 확인하지 못했습니다.'); } finally { if (alive.current && request.current === id) setPending(false); } };
  const archive = async () => { if (!inspection) return; setPending(true); setError(''); try { const text = await createInteropArchive(inspection, selected || undefined); if (alive.current) downloadText(text, 'CalcWeave-import.cwinterop.json', 'application/json'); } catch (error) { if (alive.current) setError(error instanceof Error ? error.message : '원본 보관 파일을 만들지 못했습니다.'); } finally { if (alive.current) setPending(false); } };
  const mat = inspection?.variables.find(variable => variable.name === selected), dirty = !!inspection?.inports.some(port => (drafts[port.nativeId] ?? '').trim() !== (inspection.options.inports?.[port.nativeId] === undefined ? '' : String(inspection.options.inports[port.nativeId])));
  const canApply = !!inspection && !pending && !busy && !invalidDraft && !changed && !dirty && reviewed && (inspection.model !== undefined || mat?.supported === true);
  const apply = () => { if (!canApply || !inspection) return; try { if (inspection.format === 'mat-v5') onApplyDataset(matVariableDataset(inspection, selected)); else if (inspection.model) onApplyModel(structuredClone(inspection.model)); onClose(); } catch (error) { setError(error instanceof Error ? error.message : '변환 결과를 적용하지 못했습니다.'); } };
  return <ModalDialog labelId="interop-title" className="interop-dialog" onClose={onClose} initialFocus=".interop-select">
    <div className="dialog-heading"><div><h2 id="interop-title">외부 형식 가져오기</h2><p>MAT·SLX·MDL 선택 profile · 원본은 로컬 파일로 보존합니다.</p></div><button className="icon-button" aria-label="외부 형식 가져오기 닫기" onClick={onClose}><Icon name="close"/></button></div>
    <div className="dialog-content interop-content"><p>유한 scalar float64 도식과 첫 열 시각 MAT 데이터표를 확인합니다. MATLAB 표현식·callback·외부 참조·모델 코드를 실행하지 않습니다.</p><div className="dialog-actions"><button className="button interop-select" disabled={pending} onClick={() => fileInput.current?.click()}>외부 파일 선택</button><input ref={fileInput} type="file" className="visually-hidden" accept=".mat,.slx,.mdl,.cwinterop.json" aria-label="외부 형식 파일 선택" onChange={event => void inspectFile(event)}/></div>
      {pending && <p role="status">파일과 원본 보존 계약을 확인하고 있습니다.</p>}{error && <p className="dialog-error" role="alert">{error}</p>}{changed && <p className="dialog-error">확인 중 현재 모델이 바뀌었습니다. 창을 닫고 다시 가져오세요.</p>}
      {inspection && <><h3>{inspection.filename}</h3><dl className="support-metadata interop-stages" data-testid="interop-stages"><div><dt>파일 해석</dt><dd>{inspection.report.parse === 'passed' ? '성공' : '실패'}</dd></div><div><dt>그래프 컴파일</dt><dd>{inspection.report.graphCompile === 'passed' ? '통과' : inspection.report.graphCompile === 'failed' ? '실패' : '해당 없음'}</dd></div><div><dt>계산 지원</dt><dd>{inspection.report.execution === 'supported' ? '선택 profile 지원' : inspection.report.execution === 'unsupported' ? '미지원 항목 확인 필요' : '데이터표 선택'}</dd></div><div><dt>수치 동등성</dt><dd>native 참조 실행 미검증</dd></div><div><dt>왕복 보존</dt><dd>원본 bytes 보존 · 수정 모델의 native 재출력 미지원</dd></div><div><dt>원본 SHA-256</dt><dd className="interop-hash" data-testid="interop-source-hash">{inspection.sourceHash}</dd></div></dl>
        <p>{inspection.report.convertedBlocks}개 블록 변환 · {inspection.sourceBytes.length.toLocaleString()} bytes 원본. 실행 지원과 native 수치 동등성은 별도 상태입니다.</p>
        {inspection.inports.length > 0 && <section className="interop-inputs"><h3>Inport 실행 입력</h3><p>값을 지정하지 않은 Inport는 실행하지 않습니다. 이 입력은 고정 scalar이며 native 외부 시계열을 대신하지 않습니다.</p>{inspection.inports.map(port => <label className="field" key={port.nativeId}><span className="field-label">{port.name}</span><input aria-label={`외부 입력 ${port.name}`} inputMode="decimal" maxLength={80} value={drafts[port.nativeId] ?? ''} onChange={event => { setDrafts(values => ({ ...values, [port.nativeId]: event.target.value })); setReviewed(false); }}/></label>)}<button className="button" disabled={pending} onClick={() => void recheck()}>입력 설정 다시 검사</button></section>}
        {inspection.format === 'mat-v5' && <section><label className="field"><span className="field-label">MAT 변수</span><select aria-label="MAT 변수" value={selected} onChange={event => { setSelected(event.target.value); setReviewed(false); }}><option value="">변수 선택</option>{inspection.variables.map(variable => <option key={variable.name} value={variable.name}>{variable.name} · {variable.dimensions.join('×')}{variable.supported ? '' : ' · 미지원'}</option>)}</select></label><p>첫 열은 시각(s), 나머지 열은 단위 1입니다. Simulink From File의 첫 행 시각 배열과 다릅니다.</p>{mat && <><p>{mat.supported ? `${mat.dimensions[0]}행 · ${mat.dimensions[1] - 1}개 신호` : mat.reason}</p>{mat.rows && <div className="interop-table"><table><caption>처음 5행 · 변환 전 값</caption><thead><tr><th>시각(s)</th>{Array.from({ length: mat.dimensions[1] - 1 }, (_, index) => <th key={index}>신호 {index + 1}</th>)}</tr></thead><tbody>{mat.rows.slice(0, 5).map((row, index) => <tr key={index}>{row.map((value, col) => <td key={col}>{String(value)}</td>)}</tr>)}</tbody></table></div>}</>}</section>}
        <details className="interop-losses" open={inspection.report.issues.some(issue => issue.severity === 'unsupported')}><summary>변환 손실·옵션 보고 · {inspection.report.issues.length}개</summary><ul>{inspection.report.issues.map((issue, index) => <li key={index}><strong>{issue.code} · {issue.severity === 'unsupported' ? '미지원' : '보존'}</strong><p>{issue.message}</p><small>{issue.location.member ?? inspection.filename}{issue.location.line ? `:${issue.location.line}:${issue.location.column}` : ` · offset ${issue.location.offset}`}{issue.nativeId && ` · ${issue.nativeId}`}{issue.parameter && ` · ${issue.parameter}`}</small>{issue.original !== undefined && <pre>{issue.original}</pre>}</li>)}</ul></details><details><summary>변환 가정 · {inspection.report.assumptions.length}개</summary><ul>{inspection.report.assumptions.map((item, index) => <li key={index}>{item}</li>)}</ul></details>
        <label className="interop-review"><input type="checkbox" aria-label="변환 손실과 미검증 항목 확인" checked={reviewed} onChange={event => setReviewed(event.target.checked)}/><span>변환 손실과 가정, native 수치 동등성·재출력 미검증 항목을 확인했습니다.</span></label><div className="dialog-actions"><button className="button primary" disabled={!canApply} onClick={apply}>{inspection.format === 'mat-v5' ? '선택 데이터표 적용' : '변환 모델 적용'}</button><button className="button" disabled={pending || dirty} onClick={() => void archive()}>원본·변환 보관 파일</button><button className="button" onClick={() => downloadOriginal(inspection)}>원본 파일 다운로드</button><button className="button" onClick={() => downloadText(JSON.stringify(inspection.report, null, 2), 'CalcWeave-conversion-report.json', 'application/json')}>변환 보고서 다운로드</button></div>
      </>}
    </div><div className="dialog-footnote">파일과 보고서는 이 브라우저에서만 처리합니다. 적용 후 자동으로 실행하지 않습니다.<button className="text-button" onClick={onClose}>닫기</button></div>
  </ModalDialog>;
}
