import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import type { CalcModel } from '../../../../packages/model/src';
import { createWorkspaceBackup, parseWorkspaceBackup, WORKSPACE_BACKUP_LIMITS, noteWorkspaceBackupCreated, getLocalStorageStatus, exportLocalOperationLog, clearLocalOperationLog, getLocalOperationLog, recordLocalOperation, type WorkspaceBackup } from '../local-operations';
import { loadRecoveryDetails, recoverySlotText, restoreWorkspaceBackup, resetLocalWorkspace } from '../persistence';
import type { HistoryRecord } from '../run-history';
import { downloadText } from './M4WorkspaceTools';
import { Icon } from './Icon';
import { ModalDialog } from './ModalDialog';

const bytes = (value: number | null) => value === null ? '확인 불가' : `${(value / 1024 / 1024).toFixed(2)} MiB`;
const SLOT_LABELS = { current: '현재 모델', 'previous-valid': '이전 유효 모델', recovery: '모델 원본 복구본', 'run-history-v1': '실행 기록', 'run-history-recovery-v1': '실행 기록 원본 복구본' };
const STATUS_LABELS = { empty: '없음', valid: '유효함', invalid: '손상된 형식', unsupported: '지원하지 않는 버전' };

export function LocalDataDialog({ model, history, historyError, busy, invalidDraft, onClose, onMutation }: { model: CalcModel; history: HistoryRecord[]; historyError: string; busy: boolean; invalidDraft: boolean; onClose: () => void; onMutation: (action: () => Promise<void>, kind?: 'restore' | 'reset') => Promise<void> }) {
  const [page, setPage] = useState<'backup' | 'recovery' | 'diagnostics' | 'reset'>('backup');
  const [status, setStatus] = useState<Awaited<ReturnType<typeof getLocalStorageStatus>> | null>(null);
  const [details, setDetails] = useState<Awaited<ReturnType<typeof loadRecoveryDetails>> | null>(null);
  const [includeHistory, setIncludeHistory] = useState(!historyError);
  const [preview, setPreview] = useState<{ backup: WorkspaceBackup; text: string; revision: string } | null>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [resetConfirm, setResetConfirm] = useState(false);
  const [resetAcknowledged, setResetAcknowledged] = useState(false);
  const [logs, setLogs] = useState(getLocalOperationLog);
  const input = useRef<HTMLInputElement>(null);
  useEffect(() => { let alive = true; void getLocalStorageStatus().then(value => { if (alive) setStatus(value); }); void loadRecoveryDetails().then(value => { if (alive) setDetails(value); }).catch(cause => { if (alive) setError(cause instanceof Error ? cause.message : '저장 상태를 확인하지 못했습니다.'); }); return () => { alive = false; }; }, []);
  const act = async (action: () => void | Promise<void>, backupValidation = false) => { if (pending) return; setError(''); setMessage(''); setPending(true); try { await action(); } catch (cause) { if (backupValidation) recordLocalOperation('WORKSPACE_BACKUP_INVALID', 'backup'); setError(cause instanceof Error ? cause.message : '작업을 완료하지 못했습니다. 원본은 유지됩니다.'); } finally { setPending(false); } };
  const backup = () => act(async () => { downloadText(createWorkspaceBackup(model, includeHistory ? history : []), 'CalcWeave-workspace.cwbackup.json', 'application/json'); noteWorkspaceBackupCreated(); setStatus(await getLocalStorageStatus()); setMessage('백업 파일을 생성했습니다. 다운로드한 파일을 별도로 보관하세요.'); });
  const readBackup = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]; event.target.value = ''; if (!file) return;
    setPreview(null);
    await act(async () => { if (file.size > WORKSPACE_BACKUP_LIMITS.bytes) throw new Error('백업 파일은 26 MiB 이하여야 합니다.'); const text = await file.text(), backup = parseWorkspaceBackup(text), current = await loadRecoveryDetails(); setDetails(current); setPreview({ backup, text, revision: current.revision }); setMessage('백업을 검증했습니다. 아래 내용을 확인하고 복구하세요.'); }, true);
  };
  const restore = () => act(async () => { if (!preview) return; await onMutation(async () => { await restoreWorkspaceBackup(preview.text, { expectedRevision: preview.revision }); }); });
  return <ModalDialog labelId="local-data-title" className="management-dialog" onClose={() => { if (!pending) onClose(); }}>
    <div className="dialog-heading"><div><h2 id="local-data-title">로컬 데이터 관리</h2><p>현재 브라우저의 저장 상태와 백업·복구를 확인합니다.</p></div><button className="icon-button" aria-label="로컬 데이터 관리 닫기" disabled={pending} onClick={onClose}><Icon name="close"/></button></div>
    <nav className="dialog-navigation" aria-label="데이터 관리"><button disabled={pending} aria-pressed={page === 'backup'} onClick={() => setPage('backup')}>백업·복구</button><button disabled={pending} aria-pressed={page === 'recovery'} onClick={() => setPage('recovery')}>저장 상태</button><button disabled={pending} aria-pressed={page === 'diagnostics'} onClick={() => setPage('diagnostics')}>로컬 진단</button><button disabled={pending} aria-pressed={page === 'reset'} onClick={() => setPage('reset')}>데이터 삭제</button></nav>
    <div className="dialog-content">{error && <p className="field-message local-management-error" role="alert">{error}</p>}{message && <p className="local-management-message" role="status">{message}</p>}
      {page === 'backup' && <section className="support-copy"><h3>작업 공간 백업</h3><p>현재 모델·데이터·하위 도식·대시보드·노트를 파일로 보관합니다. 실행 기록 포함 여부를 직접 선택하세요. 아직 적용하지 않은 편집 중 입력은 포함되지 않습니다.</p><label className="management-check"><input type="checkbox" checked={includeHistory} disabled={!!historyError || pending} onChange={event => setIncludeHistory(event.target.checked)}/>실행 기록 {history.length}개 포함</label>{historyError && <p className="field-help">실행 기록의 원본을 읽지 못했습니다. 저장 상태에서 원본을 다운로드할 수 있습니다.</p>}{invalidDraft && <p className="field-message">편집 중인 입력값을 확인한 뒤 백업하세요.</p>}<button className="button primary" disabled={pending || invalidDraft} onClick={() => void backup()}><Icon name="download"/>작업 공간 백업 다운로드</button><p className="field-help">최근 백업 생성: {status?.backup.lastCreatedAt ? new Date(status.backup.lastCreatedAt).toLocaleString('ko-KR') : '없음'}{status?.backup.reminder ? ' · 변경된 작업을 백업하세요.' : ''}</p><h3>백업 파일 복구</h3><p>형식·버전·SHA-256·모델과 실행 기록을 먼저 검증합니다. 복구하면 현재 모델과 실행 기록 전체를 함께 교체하고 앱을 다시 엽니다. 유효하지 않은 파일은 기존 저장본을 바꾸지 않습니다.</p><button className="button" disabled={pending || busy} onClick={() => input.current?.click()}><Icon name="upload"/>백업 파일 선택</button><input ref={input} className="visually-hidden" type="file" accept=".json,application/json" aria-label="작업 공간 백업 파일 선택" onChange={event => void readBackup(event)}/>{preview && <section className="backup-preview" aria-label="백업 복구 미리보기"><h4>{preview.backup.model.name}</h4><dl className="support-metadata"><div><dt>모델</dt><dd>{preview.backup.model.nodes.length}개 블록 · {preview.backup.model.datasets?.length ?? 0}개 데이터 · {preview.backup.model.subsystems?.length ?? 0}개 하위 도식</dd></div><div><dt>실행 기록</dt><dd>{preview.backup.history.length}개로 전체 교체</dd></div><div><dt>버전</dt><dd>백업 v{preview.backup.version} · {preview.backup.engineVersion}</dd></div><div><dt>생성 시각</dt><dd>{new Date(preview.backup.createdAt).toLocaleString('ko-KR')}</dd></div><div><dt>SHA-256</dt><dd>{preview.backup.manifest.payloadSha256}</dd></div></dl><button className="button primary" disabled={pending || busy} onClick={() => void restore()}>검증한 백업으로 복구 후 다시 열기</button></section>}</section>}
      {page === 'recovery' && <section className="support-copy"><h3>저장 공간 상태</h3><dl className="support-metadata"><div><dt>사이트 사용량 추정</dt><dd>{bytes(status?.estimatedUsageBytes ?? null)}</dd></div><div><dt>사이트 할당량 추정</dt><dd>{bytes(status?.estimatedQuotaBytes ?? null)}</dd></div><div><dt>영구 저장 여부</dt><dd>{status?.persistent === null || !status ? '확인 불가' : status.persistent ? '브라우저가 유지하도록 설정됨' : '브라우저가 정리할 수 있음'}</dd></div></dl><p>추정치는 앱 캐시를 포함한 같은 사이트 전체 값입니다. 브라우저 설정으로 저장 공간을 지우면 별도 파일 백업이 필요합니다.</p><div className="recovery-slot-list">{details?.slots.map(slot => <section key={slot.slot}><h4>{SLOT_LABELS[slot.slot]}</h4><p>{STATUS_LABELS[slot.status]} · {bytes(slot.bytes)}</p><button className="button" disabled={!slot.downloadable || pending} onClick={() => void act(async () => { downloadText(await recoverySlotText(slot.slot), `CalcWeave-${slot.slot}-recovery.json`, 'application/json'); setMessage('원본을 다운로드했습니다. 저장 공간의 원본은 유지됩니다.'); })}>{SLOT_LABELS[slot.slot]} 원본 다운로드</button></section>)}</div></section>}
      {page === 'diagnostics' && <section className="support-copy"><h3>로컬 진단 기록</h3><p>오류 코드·종류·시각·엔진 버전만 현재 기기에 최대 50개 보관합니다. 모델 이름·수치·데이터·URL·예외 문자열은 기록하지 않으며 외부로 전송하지 않습니다.</p><div className="management-actions"><button className="button" onClick={() => { downloadText(exportLocalOperationLog(), 'CalcWeave-local-diagnostics.json', 'application/json'); setMessage('로컬 진단 파일을 생성했습니다. 전달 여부는 직접 결정하세요.'); }}>로컬 진단 다운로드</button><button className="button" onClick={() => { clearLocalOperationLog(); setLogs([]); setMessage('로컬 진단 기록을 지웠습니다.'); }}>진단 기록 지우기</button></div><p role="status">{logs.length}개 기록</p><ol className="operation-log">{logs.map((log, index) => <li key={`${log.at}-${index}`}><strong>{log.code}</strong><span>{log.context} · {new Date(log.at).toLocaleString('ko-KR')} · {log.engineVersion}</span></li>)}</ol></section>}
      {page === 'reset' && <section className="support-copy"><h3>이 브라우저의 CalcWeave 데이터 삭제</h3><p>현재 모델·데이터·실행 기록·복구본과 CalcWeave 설정을 지웁니다. 다른 사이트의 데이터는 지우지 않습니다. 삭제 전에 작업 공간 백업을 다운로드하세요.</p>{!resetConfirm ? <button className="button danger" disabled={pending || busy} onClick={() => setResetConfirm(true)}>로컬 데이터 삭제 확인</button> : <div className="reset-confirmation"><p>삭제한 저장본과 복구본은 이 브라우저에서 되돌릴 수 없습니다.</p><label className="management-check"><input type="checkbox" checked={resetAcknowledged} onChange={event => setResetAcknowledged(event.target.checked)}/>백업을 확인했으며 로컬 데이터를 삭제합니다.</label><div className="management-actions"><button className="button danger" disabled={!resetAcknowledged || pending || busy} onClick={() => void act(async () => { await onMutation(resetLocalWorkspace, 'reset'); })}>영구 삭제 후 다시 열기</button><button className="button" disabled={pending} onClick={() => { setResetConfirm(false); setResetAcknowledged(false); }}>삭제 취소</button></div></div>}</section>}
    </div><div className="dialog-footnote">{busy ? '실행을 마친 뒤 복구·삭제할 수 있습니다.' : '모든 작업은 현재 기기에서 처리합니다.'}<button className="text-button" disabled={pending} onClick={onClose}>닫기</button></div>
  </ModalDialog>;
}
