import { useCallback, useState } from 'react';
import { importLocalDataSource, scenarioSource } from '../../../../packages/data/src';
import type { CalcModel, Dataset } from '../../../../packages/model/src';
import { NumericField, NumericValidityContext } from './NumericField';
export function SignalScenarioEditor({ model, onChange, notice, onPlayback }: { model: CalcModel; onChange: (model: CalcModel) => void; notice: (message: string) => void; onPlayback: (dataset: Dataset, column: string, type?: string) => void }) {
  const [name, setName] = useState('새 시나리오'), [draft, setDraft] = useState('0, 0\n1, 1\n2, 0'), [error, setError] = useState(''), [preview, setPreview] = useState<Dataset | null>(null);
  const [kind, setKind] = useState('sine'), [amplitude, setAmplitude] = useState(1), [frequency, setFrequency] = useState(1), [duration, setDuration] = useState(2), [step, setStep] = useState(.1), [invalid, setInvalid] = useState<Record<string, boolean>>({});
  const setValidity = useCallback((id: string, invalid: boolean) => setInvalid(current => current[id] === invalid ? current : { ...current, [id]: invalid }), []);
  const invalidNumber = Object.values(invalid).some(Boolean);
  const generate = () => {
    if (invalidNumber) return;
    const count = Math.floor(duration / step) + 1; if (count > 1000 || count < 2) { setError('파형은 2~1,000개 점으로 만드세요. 시간 간격을 조절하세요.'); return; }
    setDraft(Array.from({ length: count }, (_, index) => { const time = Number((index * step).toPrecision(12)), phase = time * frequency % 1; const value = amplitude * (kind === 'sine' ? Math.sin(2 * Math.PI * phase) : kind === 'square' ? phase < .5 ? 1 : -1 : kind === 'triangle' ? 1 - 4 * Math.abs(phase - .5) : 2 * phase - 1); return `${time}, ${Number(value.toPrecision(12))}`; }).join('\n')); setPreview(null); setError('');
  };
  const build = () => {
    try {
      if (draft.length > 64_000 || !name.trim()) throw new Error('시나리오 이름과 점을 확인하세요.');
      const lines = draft.trim().split(/\r?\n/); if (lines.length > 1000) throw new Error('최대 1,000개 점을 편집합니다.');
      const points = lines.map(line => { const parts = line.trim().split(/[,\t]/).map(value => value.trim()); if (parts.length !== 2 || parts.some(value => !/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?$/i.test(value))) throw new Error('각 행에 시간, 값 두 숫자를 입력하세요.'); return { time: Number(parts[0]), value: Number(parts[1]) }; });
      const source = scenarioSource({ name, points });
      setPreview(importLocalDataSource(source, { id: `data-${crypto.randomUUID()}`, name, timeColumn: 'time', columns: [{ name: 'time', kind: 'number', unit: 's' }, { name: 'value', kind: 'number', unit: '1' }] })); setError('');
    } catch (caught) { setPreview(null); setError(caught instanceof Error ? caught.message : '신호 점을 확인하세요.'); }
  };
  return <section className="tool-section signal-scenario-editor"><h3>신호 편집기</h3><p className="field-help">이름 있는 시나리오를 직접 편집하거나 파형에서 시작하세요. 시간과 값을 검증해 프로젝트 데이터로 보관합니다.</p><label className="field"><span className="field-label">시나리오 이름</span><input aria-label="시나리오 이름" maxLength={100} value={name} onChange={event => { setName(event.target.value); setPreview(null); }}/></label><details><summary>파형으로 점 만들기</summary><NumericValidityContext.Provider value={setValidity}><div className="tool-field-grid"><label className="field"><span className="field-label">파형</span><select aria-label="편집기 파형" value={kind} onChange={event => setKind(event.target.value)}><option value="sine">사인파</option><option value="square">구형파</option><option value="triangle">삼각파</option><option value="sawtooth">톱니파</option></select></label>{[['진폭', amplitude, setAmplitude, 0], ['주파수', frequency, setFrequency, 0], ['길이', duration, setDuration, .000001], ['점 간격', step, setStep, .000001]].map(([label, value, change, min]) => <NumericField key={String(label)} label={`편집기 ${label}`} value={value as number} min={min as number} max={label === '주파수' ? 1e6 : 1e9} onChange={change as (value: number) => void}/>)} </div></NumericValidityContext.Provider><button className="button" disabled={invalidNumber} onClick={generate}>파형 점 생성</button></details><label className="field"><span className="field-label">시간, 값</span><textarea aria-label="시나리오 점" className="scenario-points" rows={8} maxLength={64_000} value={draft} spellCheck={false} onChange={event => { setDraft(event.target.value); setPreview(null); }}/><span className="field-help">행마다 시간, 값 · 중복 없는 증가 시각 · 최대 1,000개 점</span></label><div className="tool-actions"><button className="button" onClick={build}>신호 검증</button>{preview && <><button className="button primary" disabled={(model.datasets?.length ?? 0) >= 8} onClick={() => { onChange({ ...model, datasets: [...(model.datasets ?? []), preview] }); notice(`${preview.name} 신호를 보관했습니다.`); setPreview(null); }}>시나리오 보관</button><span role="status">{preview.rows.length}개 점 · 검증됨</span></>}</div>{error && <p className="tool-error" role="alert">{error}</p>}<div className="tool-actions">{model.datasets?.filter(dataset => dataset.provenance?.format === 'editor').map(dataset => <button className="button" key={dataset.id} onClick={() => onPlayback(dataset, 'value', 'data.signal-editor')}>{dataset.name} 재생 블록 추가</button>)}</div></section>;
}
