import { useMemo, useState } from 'react';
import { type ParameterDefinition } from '../../../../packages/block-library/src';
import { type ExecutionMode } from '../../../../packages/model/src';
import { getReleaseCatalog } from '../../../../packages/release/src';
import { Icon } from './Icon';
import { ModalDialog } from './ModalDialog';

const MODES: Record<ExecutionMode, string> = { static: '정적 계산', discrete: '이산 시뮬레이션', continuous: '연속·혼합 시뮬레이션' };
const RELEASE = getReleaseCatalog();
const BLOCK_REGISTRY = RELEASE.blocks;
function parameterConstraint(parameter: ParameterDefinition) {
  return [parameter.options?.join(' · '), parameter.min !== undefined || parameter.max !== undefined ? `${parameter.min ?? '−∞'} ~ ${parameter.max ?? '∞'}` : '', parameter.minLength !== undefined || parameter.maxLength !== undefined ? `길이 ${parameter.minLength ?? 0} ~ ${parameter.maxLength ?? '제한 없음'}` : ''].filter(Boolean).join(' / ') || '신호 형식·유한값을 확인합니다.';
}

export function SupportDialog({ onClose, onManage }: { onClose: () => void; onManage: () => void }) {
  const [page, setPage] = useState<'support' | 'keyboard' | 'limits' | 'policy'>('support');
  const [query, setQuery] = useState('');
  const [mode, setMode] = useState<ExecutionMode | ''>('');
  const [selectedId, setSelectedId] = useState('source.constant');
  const blocks = useMemo(() => BLOCK_REGISTRY.filter(block => (!mode || block.supportedModes.includes(mode)) && `${block.id} ${block.label} ${block.englishName} ${block.aliases?.join(' ')} ${block.description} ${block.category} ${Object.entries(block.parameters).map(([key, parameter]) => `${key} ${parameter.label} ${parameter.kind} ${parameter.options?.join(' ')}`).join(' ')} ${block.valueType} ${block.shape} ${block.unit}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())), [query, mode]);
  const selected = BLOCK_REGISTRY.find(block => block.id === selectedId)!;
  return <ModalDialog labelId="support-title" className="support-dialog" onClose={onClose} initialFocus="[aria-label='지원 블록 검색']">
    <div className="dialog-heading"><div><h2 id="support-title">지원·릴리스</h2><p>CalcWeave {RELEASE.version} · 엔진 {RELEASE.engineVersion} · {BLOCK_REGISTRY.length}개 블록</p><p>로컬 베타 릴리스 후보 · {RELEASE.browserSupport}</p></div><button className="icon-button" aria-label="지원·릴리스 닫기" onClick={onClose}><Icon name="close"/></button></div>
    <nav className="dialog-navigation" aria-label="지원 정보"><button aria-pressed={page === 'support'} onClick={() => setPage('support')}>지원 블록</button><button aria-pressed={page === 'keyboard'} onClick={() => setPage('keyboard')}>사용 방법</button><button aria-pressed={page === 'limits'} onClick={() => setPage('limits')}>범위와 상한</button><button aria-pressed={page === 'policy'} onClick={() => setPage('policy')}>정책·로컬 저장</button></nav>
    <div className="dialog-content">
      {page === 'support' && <><div className="support-filters"><label className="field"><span className="field-label">블록·파라미터 검색</span><input aria-label="지원 블록 검색" maxLength={120} value={query} onChange={event => setQuery(event.target.value)} placeholder="LU, 적분, wordLength…"/></label><label className="field"><span className="field-label">실행 방식</span><select aria-label="지원 실행 방식" value={mode} onChange={event => setMode(event.target.value as ExecutionMode | '')}><option value="">전체 방식</option>{Object.entries(MODES).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><p className="support-result-count" role="status">{blocks.length} / {BLOCK_REGISTRY.length}개 블록</p><div className="support-layout"><div className="support-block-list" aria-label="지원 블록 목록">{blocks.map(block => <button key={block.id} aria-pressed={selectedId === block.id} onClick={() => setSelectedId(block.id)}><strong>{block.label} · {block.englishName}</strong><span>{block.category} · {block.supportedModes.map(item => MODES[item]).join(' / ')}</span></button>)}{!blocks.length && <p className="muted-copy">일치하는 블록이 없습니다.</p>}</div><section className="support-block-detail" aria-label="선택한 블록의 지원 정보"><h3>{selected.label} · {selected.englishName}</h3><p>{selected.description}</p><dl className="support-metadata"><div><dt>ID</dt><dd>{selected.id} · v{selected.version}</dd></div><div><dt>실행 방식</dt><dd>{selected.supportedModes.map(item => MODES[item]).join(' · ')}</dd></div><div><dt>입력 / 출력</dt><dd>{selected.inputs.join(', ') || '없음'} / {selected.outputs.join(', ') || '없음'}<small>동적 포트는 블록의 설정과 하위 도식 정의에 따라 바뀝니다.</small></dd></div><div><dt>타입 · 모양</dt><dd>{selected.valueType} · {selected.shape}</dd></div><div><dt>단위</dt><dd>{selected.unit === 'dimensionless' ? '1 · 단위 없음' : '입력·파라미터에서 추론'}</dd></div><div><dt>시간 · 상태</dt><dd>{selected.sampleTime} · {selected.state}</dd></div></dl><h4>파라미터와 기본값</h4>{Object.keys(selected.parameters).length ? <div className="support-parameter-list">{Object.entries(selected.parameters).map(([key, parameter]) => <div key={key}><strong>{parameter.label} <code>{key}</code></strong><p>{parameter.kind} · 기본값 <code>{JSON.stringify(parameter.default)}</code></p><p>{parameterConstraint(parameter)}</p></div>)}</div> : <p>설정할 파라미터가 없습니다.</p>}<p className="field-help">타입·shape·단위·연결 조건은 현재 모델을 실행하기 전에 검증합니다. 입력값을 추론하는 블록의 최종 모양은 블록 속성에서 확인하세요.</p></section></div></>}
      {page === 'keyboard' && <section className="support-copy"><h3>블록으로 계산을 엮어 보세요.</h3><ol><li>라이브러리에서 블록을 추가합니다.</li><li>출력 → 입력 포트를 연결합니다. 블록 속성의 연결 메뉴는 키보드로도 사용할 수 있습니다.</li><li>블록을 선택하고 값을 바꾼 뒤 실행합니다.</li></ol><dl className="support-metadata"><div><dt>캔버스</dt><dd>휠 버튼 드래그 이동 · 왼쪽 드래그 영역 선택 · Space 도식 맞추기</dd></div><div><dt>키보드 편집</dt><dd>Tab으로 블록 이동 · Enter로 속성 편집 · Tab으로 입력값과 연결 메뉴 이동</dd></div><div><dt>빠른 추가</dt><dd>Ctrl+K · ↑ ↓ 선택 · Enter 추가 · Escape 닫기</dd></div><div><dt>선택</dt><dd>Ctrl+A 전체 선택 · Ctrl+C/V 복사·붙여넣기 · Ctrl+D 복제 · Delete 삭제</dd></div><div><dt>실행</dt><dd>Ctrl+Enter 실행 · Ctrl+Z 실행 취소 · Ctrl+Shift+Z 다시 실행</dd></div></dl><p>데이터는 CSV·JSON을 미리 본 뒤 재생합니다. 선택 블록은 하위 도식으로 묶고 내부를 편집할 수 있습니다. 실험에서는 반복 실행과 비교를, 대시보드에서는 다음 실행의 입력 조절을, 노트에서는 설명을 보관합니다.</p><p>Scope의 시작·종료 시간을 적용하면 그 범위까지 실제 계산을 다시 실행합니다. solver 내부 간격과 결과 기록 간격은 별도로 설정합니다.</p></section>}
      {page === 'limits' && <section className="support-copy"><h3>지원 범위</h3><p>실수 float64·boolean·벡터·2D 신호, scalar 연속 ODE의 RK4·RK45와 이산 상태의 혼합 실행을 지원합니다. 행렬 계산은 실수 2D 범위이며, 최대 32-bit 양자화는 decoded 값과 저장 정수 코드를 출력합니다.</p><ul className="unsupported-list">{RELEASE.unsupported.map(item => <li key={item}>{item}</li>)}</ul><p>단위는 검증하며 unit.convert를 제외한 자동 변환은 수행하지 않습니다.</p><h3>실행 상한</h3><dl className="support-metadata">{Object.entries(RELEASE.limits).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl><details><summary>연속 solver 상한</summary><dl className="support-metadata">{Object.entries(RELEASE.solverLimits).map(([key, value]) => <div key={key}><dt>{key}</dt><dd>{String(value)}</dd></div>)}</dl></details><p>행렬 각 축 최대 32, lookup 각 축 2~32, 계층 깊이 최대 8, 데이터 파일 최대 2 MiB. 반복 실험은 최대 16회와 총 30초 상한을 공유합니다. 실행 기록은 최대 5개·20 MiB로 유지하며, 기록당 수치 원소는 200,000개를 넘을 수 없습니다.</p></section>}
      {page === 'policy' && <section className="support-copy"><h3>이 브라우저의 로컬 작업 공간</h3><p>모델과 데이터, 실행 기록은 현재 브라우저에 저장됩니다. 백업 파일은 직접 내려받아 보관하고 다른 기기에서 복원할 수 있습니다. 브라우저 저장 공간을 지우면 저장된 작업이 사라질 수 있습니다.</p><button className="button primary" onClick={onManage}>로컬 데이터 관리 열기</button><h3>정책</h3><div className="policy-links"><a href={RELEASE.policyLinks.privacy} target="_blank" rel="noopener noreferrer">개인정보 처리방침</a><a href={RELEASE.policyLinks.terms} target="_blank" rel="noopener noreferrer">이용약관</a><a href={RELEASE.policyLinks.cookies} target="_blank" rel="noopener noreferrer">쿠키·로컬 저장 안내</a></div><p>운영자 {RELEASE.operator} · 문의 <a href={`mailto:${RELEASE.contact}`}>{RELEASE.contact}</a></p><p>브랜딩 예정 도메인: {RELEASE.domain}. 공개 서비스 운영 전 필요한 확인은 릴리스 체크리스트에 기록합니다.</p><a href={RELEASE.policyLinks.notices} target="_blank" rel="noopener noreferrer">릴리스·오픈소스 고지</a></section>}
    </div>
    <div className="dialog-footnote">Escape 닫기 · Tab으로 창 안의 항목 이동<button className="text-button" onClick={onClose}>닫기</button></div>
  </ModalDialog>;
}
