import { compileModel } from '../../compiler/src';
import { MODEL_LIMITS, ModelError, parseModel, type CalcModel, type CalcNode } from '../../model/src';
import { nativeFail, nativeTextLocator, nativeUtf8, parseNativeXml, readNativeZip, xmlDescendants, type NativeXml } from './bounded-format';
import { NATIVE_IMPORT_LIMITS, nativeReport, type NativeFormat, type NativeImportOptions, type NativeImportReport, type NativeInport, type NativeIssue, type NativeLocation, type NativeSourceOrigin } from './native-types';

interface Field { value: string; location: NativeLocation }
interface Section { name: string; fields: Map<string, Field>; children: Section[]; location: NativeLocation }
interface NativeBlock { id: string; type: string; name: string; fields: Map<string, Field>; location: NativeLocation }
interface NativeWire { source: string; sourcePort: number; target: string; targetPort: number; location: NativeLocation }
interface NativeGraph { name: string; fields: Map<string, Field>; blocks: NativeBlock[]; wires: NativeWire[]; issues: NativeIssue[] }
const cosmetic = new Set(['Position', 'ZOrder', 'Orientation', 'Mirror', 'ShowName', 'ForegroundColor', 'BackgroundColor', 'FontName', 'FontSize', 'FontWeight', 'FontAngle', 'DropShadow', 'NamePlacement', 'Description', 'AttributesFormatString', 'Tag', 'IconShape']);
const supportedTypes = new Set(['Constant', 'Gain', 'Sum', 'Product', 'UnitDelay', 'Integrator', 'Scope', 'Inport', 'Outport']);
function issue(issues: NativeIssue[], code: string, message: string, location: NativeLocation, severity: NativeIssue['severity'] = 'unsupported', extras: Partial<NativeIssue> = {}): void { if (issues.length >= NATIVE_IMPORT_LIMITS.maxIssues) nativeFail('NATIVE_ISSUE_LIMIT', '미지원 옵션 보고 수가 상한을 넘었습니다.'); issues.push({ code, severity, message, location, ...extras }); }
/** Balanced braces/quoted strings with source positions; no MATLAB parser or evaluation. */
function parseMdl(text: string): Section {
  const location = nativeTextLocator(text), keyToken = /\$?[A-Za-z_][A-Za-z0-9_]*/y;
  if (/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(text)) nativeFail('MDL_TEXT', 'MDL에 잘못된 제어 문자가 있습니다.');
  const root: Section = { name: '#', fields: new Map(), children: [], location: { offset: 0 } }; let at = text.startsWith('\uFEFF') ? 1 : 0, nodes = 0;
  const skip = () => { while (at < text.length) { if (/\s/.test(text[at])) at++; else if (text[at] === '#') { while (at < text.length && text[at] !== '\n') at++; } else break; } };
  const quoted = () => { at++; let value = ''; while (at < text.length) { const ch = text[at++]; if (ch === '"') return value; if (ch === '\\') { if (at === text.length) nativeFail('MDL_STRING', 'MDL 문자열이 잘렸습니다.'); const escaped = text[at++]; if (escaped === 'n') value += '\n'; else if (escaped === 'r') value += '\r'; else if (escaped === 't') value += '\t'; else if (escaped === '"' || escaped === '\\') value += escaped; else nativeFail('MDL_STRING', '이 MDL profile에서 지원하지 않는 escape입니다.'); } else value += ch; if (value.length > 16_384) nativeFail('MDL_STRING_LIMIT', 'MDL 문자열이 상한을 넘었습니다.'); } return nativeFail('MDL_STRING', 'MDL 문자열이 닫히지 않았습니다.'); };
  const section = (parent: Section, depth: number, closed: boolean) => { if (depth > NATIVE_IMPORT_LIMITS.maxDepth) nativeFail('MDL_DEPTH', 'MDL 깊이는 32단계 이하여야 합니다.');
    while (true) { skip(); if (at === text.length) { if (closed) nativeFail('MDL_BRACE', 'MDL section이 닫히지 않았습니다.'); return; } if (text[at] === '}') { if (!closed) nativeFail('MDL_BRACE', '예상하지 않은 MDL 닫기 brace입니다.'); at++; return; }
      const start = at; keyToken.lastIndex = at; const key = keyToken.exec(text); if (!key || key[0].length > 128) nativeFail('MDL_TOKEN', 'MDL field 이름이 잘못되었습니다.'); at += key[0].length; while (text[at] === ' ' || text[at] === '\t' || text[at] === '\r') at++;
      if (text[at] === '{') { at++; if (++nodes > NATIVE_IMPORT_LIMITS.maxXmlNodes) nativeFail('MDL_NODE_LIMIT', 'MDL section 수가 상한을 넘었습니다.'); const child: Section = { name: key[0], fields: new Map(), children: [], location: location(start, key[0]) }; parent.children.push(child); section(child, depth + 1, true); }
      else { let value: string; if (text[at] === '"') { value = quoted(); while (text[at] === ' ' || text[at] === '\t' || text[at] === '\r') at++; if (at < text.length && !['\n', '}'].includes(text[at])) nativeFail('MDL_TOKEN', 'MDL quoted field 뒤의 구문은 선택 profile에 없습니다.'); }
        else { const valueStart = at; while (at < text.length && text[at] !== '\n' && text[at] !== '}') { if (text[at] === '{') nativeFail('MDL_TOKEN', '잘못된 MDL field입니다.'); at++; } value = text.slice(valueStart, at).trim(); }
        if (value.length > 16_384 || parent.fields.has(key[0])) nativeFail('MDL_FIELD', '중복되거나 너무 큰 MDL field입니다.'); if (++nodes > NATIVE_IMPORT_LIMITS.maxXmlNodes) nativeFail('MDL_NODE_LIMIT', 'MDL field 수가 상한을 넘었습니다.'); parent.fields.set(key[0], { value, location: location(start, `${parent.name}/${key[0]}`) }); }
    }
  }; section(root, 0, false); if (root.fields.size || root.children.length !== 1 || root.children[0].name !== 'Model') nativeFail('MDL_ROOT', '선택 MDL profile은 하나의 Model section을 읽습니다.'); return root.children[0];
}
function mdlGraph(text: string): NativeGraph {
  const model = parseMdl(text), issues: NativeIssue[] = [], systems = model.children.filter(child => child.name === 'System'); if (systems.length !== 1) nativeFail('MDL_SYSTEM', 'root System이 하나인 MDL만 지원합니다.'); const system = systems[0], blocks: NativeBlock[] = [], wires: NativeWire[] = [];
  const knownSections = new Set(['System', 'BlockDefaults', 'AnnotationDefaults', 'LineDefaults', 'ConfigSet']); for (const child of model.children) if (!knownSections.has(child.name)) issue(issues, 'NATIVE_SECTION_UNSUPPORTED', `${child.name} section은 실행 변환을 지원하지 않습니다.`, child.location);
  for (const child of model.children.filter(child => ['BlockDefaults', 'AnnotationDefaults', 'LineDefaults'].includes(child.name))) { if (child.children.length) issue(issues, 'NATIVE_DEFAULTS_UNSUPPORTED', '복합 defaults section은 선택 profile에서 지원하지 않습니다.', child.location); for (const [key, value] of child.fields) if (!cosmetic.has(key) && !['LineWidth', 'LineStyle', 'Name', 'FontSize', 'HorizontalAlignment', 'VerticalAlignment'].includes(key)) issue(issues, 'NATIVE_DEFAULTS_UNSUPPORTED', `${key} 기본값은 선택 profile에서 지원하지 않습니다.`, value.location, 'unsupported', { parameter: key, original: value.value }); }
  for (const child of model.children.filter(child => child.name === 'ConfigSet')) issue(issues, 'NATIVE_DEFAULTS_UNSUPPORTED', '별도 ConfigSet object 실행 설정은 선택 profile에서 지원하지 않습니다.', child.location);
  for (const child of system.children) { if (child.name === 'Block') { const type = child.fields.get('BlockType')?.value ?? '', name = child.fields.get('Name')?.value ?? ''; if (!name) nativeFail('MDL_BLOCK_NAME', '블록 이름이 필요합니다.'); blocks.push({ id: name, type, name, fields: child.fields, location: child.location }); if (child.children.length) issue(issues, 'NATIVE_NESTING_UNSUPPORTED', '하위 System·mask·object section은 변환하지 않습니다.', child.children[0].location, 'unsupported', { nativeId: name }); }
    else if (child.name !== 'Line' && child.name !== 'Annotation') issue(issues, 'NATIVE_SECTION_UNSUPPORTED', `${child.name} root section은 실행 변환을 지원하지 않습니다.`, child.location); }
  const port = (field?: Field) => { const value = field?.value ?? '1'; if (!/^\d+$/.test(value) || Number(value) < 1 || Number(value) > 16) nativeFail('NATIVE_PORT', '포트는 1~16 정수여야 합니다.'); return Number(value); };
  const line = (section: Section, src?: { id: string; port: number }) => { const source = section.fields.has('SrcBlock') ? { id: section.fields.get('SrcBlock')!.value, port: port(section.fields.get('SrcPort')) } : src; if (!source) nativeFail('MDL_LINE', 'Line source가 없습니다.'); const destination = section.fields.get('DstBlock'); if (destination) wires.push({ source: source.id, sourcePort: source.port, target: destination.value, targetPort: port(section.fields.get('DstPort')), location: section.location }); for (const [key, f] of section.fields) if (!['SrcBlock', 'SrcPort', 'DstBlock', 'DstPort', 'Points', 'Name', 'Labels', 'FontName', 'FontSize', 'FontWeight', 'FontAngle'].includes(key)) issue(issues, 'NATIVE_LINE_OPTION', `${key} Line 옵션은 지원하지 않습니다.`, f.location, 'unsupported', { parameter: key, original: f.value }); for (const child of section.children) { if (child.name !== 'Branch') issue(issues, 'NATIVE_LINE_OPTION', 'Line 하위 옵션을 지원하지 않습니다.', child.location); else line(child, source); } if (!destination && !section.children.length) nativeFail('MDL_LINE', 'Line destination이 없습니다.'); };
  for (const child of system.children.filter(child => child.name === 'Line')) line(child);
  for (const [key, field] of system.fields) if (!['Name', 'Location', 'Open', 'ZoomFactor', 'ScreenColor', 'ReportName', 'PaperOrientation', 'PaperPosition', 'PaperType', 'PaperUnits', 'TiledPaperMargins', 'TiledPageScale', 'ShowPageBoundaries'].includes(key)) issue(issues, 'NATIVE_SYSTEM_OPTION', `${key} System 옵션은 지원하지 않습니다.`, field.location, 'unsupported', { parameter: key, original: field.value });
  return { name: model.fields.get('Name')?.value ?? 'Imported MDL', fields: model.fields, blocks, wires, issues };
}
function xmlFields(node: NativeXml): Map<string, Field> { const result = new Map<string, Field>(); for (const p of node.children.filter(child => child.name.split(':').at(-1) === 'P')) { const name = p.attrs.Name; if (!name || result.has(name) || p.children.length) nativeFail('SLX_PARAMETER', '중복 또는 복합 XML parameter는 지원하지 않습니다.'); result.set(name, { value: p.text, location: { ...p.location, path: `${p.location.path}[@Name=${name}]` } }); } return result; }
async function slxGraph(bytes: Uint8Array): Promise<NativeGraph> {
  const entries = await readNativeZip(bytes), xml = new Map<string, NativeXml>(), budget = { nodes: 0 }, issues: NativeIssue[] = [];
  if (!entries.has('[Content_Types].xml') || !entries.has('simulink/blockdiagram.xml')) nativeFail('SLX_PROFILE', 'OPC content types와 simulink/blockdiagram.xml이 필요한 선택 SLX profile입니다.');
  for (const [name, content] of entries) if (/\.(xml|rels)$/i.test(name)) { const tree = parseNativeXml(nativeUtf8(content), name, budget); xml.set(name, tree); for (const relation of xmlDescendants(tree, 'Relationship')) { const target = relation.attrs.Target ?? ''; if (relation.attrs.TargetMode === 'External' || /^(?:[a-z][a-z0-9+.-]*:|\/\/)/i.test(target)) issue(issues, 'SLX_EXTERNAL_REFERENCE', '외부 relationship을 읽거나 실행하지 않습니다.', relation.location, 'unsupported', { original: target }); }
    if (/simulink\/(?:stateflow|modelworkspace|dictionary|plugins|systems\/)/i.test(name) && !/^simulink\/systems\/system_[A-Za-z0-9_-]+\.xml$/.test(name)) issue(issues, 'SLX_PART_UNSUPPORTED', '실행에 관련된 추가 SLX part를 지원하지 않습니다.', { member: name, offset: 0 }); }
  const document = xml.get('simulink/blockdiagram.xml')!, models = xmlDescendants(document, 'Model'); if (models.length !== 1) nativeFail('SLX_MODEL', 'root Model이 하나인 SLX profile만 지원합니다.'); const model = models[0], fields = xmlFields(model);
  for (const [key, value] of Object.entries(model.attrs)) if (key !== 'Name') issue(issues, 'SLX_MODEL_ATTRIBUTE', `${key} Model attribute는 선택 profile 밖입니다.`, model.location, 'unsupported', { parameter: key, original: value });
  for (const [name, tree] of xml) if (/^simulink\/configSet\d*\.xml$/.test(name)) for (const p of xmlDescendants(tree, 'P')) { const key = p.attrs.Name; if (key && ['StartTime', 'StopTime', 'SolverType', 'Solver', 'FixedStep'].includes(key)) { if (fields.has(key) && fields.get(key)!.value !== p.text) nativeFail('SLX_CONFIGURATION', 'SLX 모델과 ConfigSet 값이 충돌합니다.'); fields.set(key, { value: p.text, location: p.location }); } else if (key) issue(issues, 'SLX_CONFIG_OPTION', `${key} ConfigSet 옵션은 실행 변환하지 않습니다.`, p.location, 'unsupported', { parameter: key, original: p.text }); }
  const directSystems = model.children.filter(child => child.name.split(':').at(-1) === 'System'); if (directSystems.length !== 1) nativeFail('SLX_SYSTEM', 'root System이 하나인 SLX profile만 지원합니다.'); let system = directSystems[0];
  if (system.attrs.Ref) { const ref = system.attrs.Ref; if (!/^[A-Za-z0-9_-]+$/.test(ref)) nativeFail('SLX_SYSTEM_REFERENCE', 'System reference 형식이 지원되지 않습니다.');
    if (system.text.trim()) issue(issues, 'SLX_REFERENCE_CONTENT_UNSUPPORTED', 'System Ref stub의 inline 텍스트를 병합하거나 실행하지 않습니다.', system.location, 'unsupported', { original: system.text });
    for (const child of system.children) issue(issues, 'SLX_REFERENCE_CONTENT_UNSUPPORTED', 'System Ref stub에 inline parameter·블록·callback이 있어 선택 참조 profile을 적용할 수 없습니다.', child.location, 'unsupported', { ...(child.attrs.Name ? { parameter: child.attrs.Name } : {}), ...(child.text ? { original: child.text } : {}) });
    for (const [key, value] of Object.entries(system.attrs)) if (key !== 'Ref') issue(issues, 'SLX_REFERENCE_ATTRIBUTE_UNSUPPORTED', `${key} System Ref attribute는 선택 profile 밖입니다.`, system.location, 'unsupported', { parameter: key, original: value });
    const referenced = xml.get(`simulink/systems/${ref}.xml`); if (!referenced || referenced.name.split(':').at(-1) !== 'System') nativeFail('SLX_SYSTEM_REFERENCE', '선택 root System part가 없습니다.'); system = referenced; }
  for (const [key, value] of Object.entries(system.attrs)) issue(issues, 'SLX_SYSTEM_ATTRIBUTE_UNSUPPORTED', `${key} inline System attribute는 선택 profile 밖입니다.`, system.location, 'unsupported', { parameter: key, original: value });
  for (const [key, f] of xmlFields(system)) if (!['Name', 'Location', 'Open', 'ZoomFactor', 'ScreenColor', 'ReportName', 'PaperOrientation', 'PaperPosition', 'PaperType', 'PaperUnits', 'TiledPaperMargins', 'TiledPageScale', 'ShowPageBoundaries'].includes(key)) issue(issues, 'NATIVE_SYSTEM_OPTION', `${key} System 옵션은 지원하지 않습니다.`, f.location, 'unsupported', { parameter: key, original: f.value });
  const blocks: NativeBlock[] = [], wires: NativeWire[] = [];
  for (const child of system.children) { const kind = child.name.split(':').at(-1); if (kind === 'Block') { const id = child.attrs.SID; if (!id || !/^\d+$/.test(id)) nativeFail('SLX_BLOCK_ID', '선택 SLX 블록에는 숫자 SID가 필요합니다.'); blocks.push({ id, type: child.attrs.BlockType ?? '', name: child.attrs.Name ?? id, fields: xmlFields(child), location: child.location }); for (const nested of child.children.filter(x => x.name.split(':').at(-1) !== 'P')) issue(issues, 'NATIVE_NESTING_UNSUPPORTED', '복합 블록·하위 도식 XML을 지원하지 않습니다.', nested.location, 'unsupported', { nativeId: id }); for (const [key, value] of Object.entries(child.attrs)) if (!['SID', 'Name', 'BlockType'].includes(key)) issue(issues, 'NATIVE_BLOCK_ATTRIBUTE', `${key} 블록 attribute는 선택 profile 밖입니다.`, child.location, 'unsupported', { original: value, nativeId: id }); }
    else if (!['Line', 'P', 'Annotation'].includes(kind!)) issue(issues, 'SLX_SYSTEM_CHILD', `${kind} System 요소는 선택 profile 밖입니다.`, child.location); }
  const endpoint = (value: string, role: 'in' | 'out') => { const match = /^(\d+)#(in|out):(\d+)$/.exec(value); if (!match || match[2] !== role || Number(match[3]) < 1 || Number(match[3]) > 16) nativeFail('SLX_PORT', 'SLX SID#in/out:port endpoint가 잘못되었습니다.'); return { id: match[1], port: Number(match[3]) }; };
  const line = (node: NativeXml, src?: { id: string; port: number }) => { const f = xmlFields(node), source = f.has('Src') ? endpoint(f.get('Src')!.value, 'out') : src; if (!source) nativeFail('SLX_LINE', 'SLX Line source가 없습니다.'); if (f.has('Dst')) { const dst = endpoint(f.get('Dst')!.value, 'in'); wires.push({ source: source.id, sourcePort: source.port, target: dst.id, targetPort: dst.port, location: node.location }); } for (const [key, field] of f) if (!['Src', 'Dst', 'Points', 'Name', 'Labels', 'ZOrder'].includes(key)) issue(issues, 'NATIVE_LINE_OPTION', `${key} Line 옵션은 지원하지 않습니다.`, field.location, 'unsupported', { parameter: key, original: field.value }); const branches = node.children.filter(x => x.name.split(':').at(-1) === 'Branch'); for (const child of node.children.filter(x => !['P', 'Branch'].includes(x.name.split(':').at(-1)!))) issue(issues, 'NATIVE_LINE_OPTION', 'Line 하위 요소를 지원하지 않습니다.', child.location); for (const branch of branches) line(branch, source); if (!f.has('Dst') && !branches.length) nativeFail('SLX_LINE', 'SLX Line destination이 없습니다.'); };
  for (const child of system.children.filter(x => x.name.split(':').at(-1) === 'Line')) line(child);
  for (const child of model.children.filter(x => !['P', 'System'].includes(x.name.split(':').at(-1)!))) issue(issues, 'SLX_MODEL_CHILD', '추가 Model 요소를 실행 변환하지 않습니다.', child.location);
  for (const [name, tree] of xml) if (/^simulink\/systems\//.test(name) && tree !== system) issue(issues, 'SLX_UNUSED_SYSTEM', '선택 root 밖의 추가 System part는 실행 변환하지 않습니다.', { member: name, offset: 0 });
  for (const [name] of entries) if (!/^(?:\[Content_Types\]\.xml|_rels\/|docProps\/|metadata\/|simulink\/(?:blockdiagram\.xml|configSet\d*\.xml|configSetInfo\.xml|bddefaults\.xml|_rels\/|systems\/system_[A-Za-z0-9_-]+\.xml)|thumbnail\.)/.test(name)) issue(issues, 'SLX_PART_PRESERVED', '추가 package part는 원본 sidecar로만 보존됩니다. 실행 의미는 지원하지 않습니다.', { member: name, offset: 0 });
  if (entries.has('simulink/bddefaults.xml')) { const tree = xml.get('simulink/bddefaults.xml')!; for (const p of xmlDescendants(tree, 'P')) if (!cosmetic.has(p.attrs.Name) && !['LineWidth', 'LineStyle', 'Name', 'FontSize', 'HorizontalAlignment', 'VerticalAlignment'].includes(p.attrs.Name)) issue(issues, 'NATIVE_DEFAULTS_UNSUPPORTED', 'bddefaults의 실행 기본값 변경은 선택 profile에서 지원하지 않습니다.', p.location, 'unsupported', { parameter: p.attrs.Name, original: p.text }); for (const block of xmlDescendants(tree, 'Block')) issue(issues, 'NATIVE_DEFAULTS_UNSUPPORTED', 'bddefaults의 블록별 실행 기본값은 선택 profile에서 지원하지 않습니다.', block.location); }
  return { name: model.attrs.Name ?? fields.get('Name')?.value ?? 'Imported SLX', fields, blocks, wires, issues };
}
const modelCosmetic = new Set(['Name', 'Version', 'SavedCharacterEncoding', 'LastModifiedDate', 'LastModifiedBy', 'Created', 'Creator', 'ModelVersion', 'GraphicalInterface', 'UpdateHistory', 'ModifiedByFormat', 'ModifiedDateFormat', 'ModelVersionFormat', 'LibraryType', 'Location', 'Open', 'ZoomFactor']);
function literal(value: string): number | undefined { if (!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(value.trim())) return undefined; const n = Number(value); return Number.isFinite(n) ? n : undefined; }
export async function convertNativeModel(bytes: Uint8Array, format: 'slx' | 'mdl', options: NativeImportOptions): Promise<{ report: NativeImportReport; model?: CalcModel; inports: NativeInport[]; locations: NativeSourceOrigin[] }> {
  const graph = format === 'mdl' ? mdlGraph(nativeUtf8(bytes)) : await slxGraph(bytes), report = nativeReport(format); report.issues = graph.issues; const inports: NativeInport[] = [], nodes: CalcNode[] = [], ids = new Map<string, string>(), ports = new Map<string, { inputs: number; output: boolean; multi: boolean }>();
  if (!graph.blocks.length || graph.blocks.length > MODEL_LIMITS.maxNodes || graph.wires.length > MODEL_LIMITS.maxEdges) nativeFail('NATIVE_GRAPH_LIMIT', '선택 native 그래프는 1~1,000개 블록·5,000개 연결 이하여야 합니다.');
  report.assumptions.push('유한 scalar float64, 단위 1의 선택 profile입니다. native dtype·단위·solver 전체 동등성을 검증하지 않았습니다.', '미지원 옵션과 원본 package 정보는 .cwinterop.json에 보존됩니다. 수정 모델을 SLX/MDL로 다시 저장하지 않습니다.');
  const modelFields = graph.fields, numericField = (name: string, fallback: number) => { const f = modelFields.get(name); if (!f) { report.assumptions.push(`${name} 미기재: CalcWeave 선택값 ${fallback} 적용`); return fallback; } const n = literal(f.value); if (n === undefined) { issue(report.issues, 'NATIVE_EXPRESSION_UNSUPPORTED', `${name}의 MATLAB 표현식은 실행하지 않습니다.`, f.location, 'unsupported', { parameter: name, original: f.value }); return fallback; } return n; };
  const startTime = numericField('StartTime', 0), stopTime = numericField('StopTime', 1), step = numericField('FixedStep', .1), hasIntegrator = graph.blocks.some(block => block.type === 'Integrator'), hasDelay = graph.blocks.some(block => block.type === 'UnitDelay');
  for (const key of ['StartTime', 'StopTime', 'FixedStep']) { const f = modelFields.get(key); if (f && Object.is(literal(f.value), -0)) issue(report.issues, 'NATIVE_SIGNED_ZERO_UNSUPPORTED', 'signed zero(-0)는 기존 JSON scalar 모델이 정확히 보존하지 못합니다.', f.location, 'unsupported', { parameter: key, original: f.value }); }
  const nativeSolver = modelFields.get('Solver')?.value, solverType = modelFields.get('SolverType')?.value;
  if (hasIntegrator && nativeSolver !== 'ode4') issue(report.issues, 'NATIVE_SOLVER_UNSUPPORTED', '연속 모델은 명시된 fixed-step ode4 선택 profile만 실행 변환합니다.', modelFields.get('Solver')?.location ?? { offset: 0 }, 'unsupported', { original: nativeSolver ?? '(inherited)' });
  if (solverType && solverType !== 'Fixed-step') issue(report.issues, 'NATIVE_SOLVER_UNSUPPORTED', '선택 profile은 fixed-step 실행만 지원합니다.', modelFields.get('SolverType')!.location, 'unsupported', { original: solverType });
  if (hasIntegrator && hasDelay) issue(report.issues, 'NATIVE_MIXED_MODE_UNSUPPORTED', '연속·이산 상태 혼합은 샘플 경계의 native 의미를 변환하지 않습니다.', { offset: 0 });
  for (const [key, f] of modelFields) if (!modelCosmetic.has(key) && !['StartTime', 'StopTime', 'FixedStep', 'SolverType', 'Solver'].includes(key)) issue(report.issues, 'NATIVE_MODEL_OPTION', `${key} 모델 옵션은 선택 profile 밖입니다.`, f.location, 'unsupported', { parameter: key, original: f.value });
  for (const block of graph.blocks) {
    if (ids.has(block.id)) nativeFail('NATIVE_DUPLICATE_BLOCK', '중복 native 블록 ID/이름입니다.'); const id = `Native${ids.size + 1}`; ids.set(block.id, id); if (!supportedTypes.has(block.type)) { issue(report.issues, 'NATIVE_BLOCK_UNSUPPORTED', `${block.type || '(unknown)'} 블록을 변환하지 않습니다.`, block.location, 'unsupported', { nativeId: block.id }); continue; }
    const accepted = new Set(['BlockType', 'Name', 'SID', ...cosmetic]), parameter = (key: string, defaultValue: string) => { accepted.add(key); const f = block.fields.get(key); if (!f) report.assumptions.push(`${block.name}.${key} 미기재: 선택 기본값 ${defaultValue}`); return f?.value ?? defaultValue; }, number = (key: string, defaultValue: string) => { const value = parameter(key, defaultValue), n = literal(value); if (n === undefined) { issue(report.issues, 'NATIVE_EXPRESSION_UNSUPPORTED', `${block.name}.${key}는 유한 scalar literal이어야 합니다.`, block.fields.get(key)?.location ?? block.location, 'unsupported', { nativeId: block.id, parameter: key, original: value }); return 0; } return n; }, requireOption = (key: string, defaultValue: string, choices: string[]) => { const v = parameter(key, defaultValue); if (!choices.includes(v)) issue(report.issues, 'NATIVE_BLOCK_OPTION', `${block.name}.${key}=${v}는 선택 profile 밖입니다.`, block.fields.get(key)?.location ?? block.location, 'unsupported', { nativeId: block.id, parameter: key, original: v }); };
    let blockType = '', parameters: Record<string, unknown> = {}, inputs = 1, output = true, multi = false;
    if (block.type === 'Constant') { blockType = 'source.constant'; parameters = { value: number('Value', '1') }; inputs = 0; requireOption('SampleTime', 'inf', ['inf', 'Inf', '-1']); requireOption('VectorParams1D', 'on', ['on', 'off']); }
    if (block.type === 'Gain') { blockType = 'math.gain'; parameters = { gain: number('Gain', '1') }; requireOption('Multiplication', 'Element-wise(K.*u)', ['Element-wise(K.*u)', 'Matrix(K*u)', 'Matrix(u*K)', 'Matrix(K*u) (u vector)']); }
    if (block.type === 'Sum' || block.type === 'Product') { let value = parameter('Inputs', block.type === 'Sum' ? '++' : '**').replaceAll('|', ''); if (/^\d+$/.test(value)) { const count = Number(value); value = count >= 1 && count <= 16 ? (block.type === 'Sum' ? '+' : '*').repeat(count) : ''; } const valid = block.type === 'Sum' ? /^[+-]{1,16}$/.test(value) : /^[*/]{2,16}$/.test(value); if (!valid) issue(report.issues, 'NATIVE_INPUTS_UNSUPPORTED', '선택 scalar Sum은 1~16개 부호, Product는 2~16개 곱/나눗셈 입력을 지원합니다.', block.fields.get('Inputs')?.location ?? block.location, 'unsupported', { nativeId: block.id, original: value }); inputs = value.length || 2; multi = true; if (block.type === 'Sum') { blockType = 'math.sum-inputs'; parameters = { count: inputs, signs: [...value].map(ch => ch === '+' ? 1 : -1) }; requireOption('CollapseMode', 'All dimensions', ['All dimensions']); } else { blockType = 'math.product-inputs'; parameters = { count: inputs, operations: value || '**', mode: 'elementwise' }; requireOption('Multiplication', 'Element-wise(.*)', ['Element-wise(.*)', 'Matrix(*)']); } }
    if (block.type === 'UnitDelay') { blockType = 'discrete.unit-delay'; parameters = { initial: number('InitialCondition', '0'), reset: 'none' }; const sampling = number('SampleTime', '-1'); if (sampling !== -1 && sampling !== step) issue(report.issues, 'NATIVE_SAMPLE_TIME_UNSUPPORTED', '선택 Unit Delay 주기는 기본 FixedStep 또는 -1 상속이어야 합니다.', block.fields.get('SampleTime')?.location ?? block.location, 'unsupported', { nativeId: block.id, original: String(sampling) }); requireOption('InputProcessing', 'Elements as channels (sample based)', ['Elements as channels (sample based)']); }
    if (block.type === 'Integrator') { blockType = 'continuous.integrator'; parameters = { initial: number('InitialCondition', '0'), reset: 'none' }; requireOption('InitialConditionSource', 'internal', ['internal']); requireOption('ExternalReset', 'none', ['none']); requireOption('LimitOutput', 'off', ['off']); requireOption('WrapState', 'off', ['off']); requireOption('ShowStatePort', 'off', ['off']); requireOption('ShowSaturationPort', 'off', ['off']); requireOption('AbsoluteTolerance', 'auto', ['auto']); }
    if (block.type === 'Scope') { blockType = 'sink.scope'; parameters = {}; output = false; requireOption('NumInputPorts', '1', ['1']); }
    if (block.type === 'Outport') { blockType = 'io.output'; parameters = {}; output = false; const port = number('Port', '1'); if (!Number.isInteger(port) || port < 1 || port > 16) issue(report.issues, 'NATIVE_PORT', 'Outport Port 범위가 지원되지 않습니다.', block.location); }
    if (block.type === 'Inport') { blockType = 'io.input'; inputs = 0; inports.push({ nativeId: block.id, name: block.name, location: block.location }); const value = options.inports?.[block.id]; if (value === undefined) issue(report.issues, 'NATIVE_INPORT_REQUIRED', `${block.name}에 CalcWeave 실행용 scalar 입력을 지정하세요. 자동으로 0을 사용하지 않습니다.`, block.location, 'unsupported', { nativeId: block.id }); parameters = { value: value ?? 0 }; number('Port', '1'); requireOption('SampleTime', '-1', ['-1']); report.assumptions.push(`${block.name}: 사용자 지정 고정 입력이며 native 외부 시계열 입력의 동등성을 주장하지 않습니다.`); }
    requireOption('OutDataTypeStr', 'Inherit: Inherit via internal rule', ['double', 'Inherit: Inherit via internal rule', 'Inherit: Same as input', 'Inherit: Inherit via back propagation', 'Inherit: auto']); requireOption('SaturateOnIntegerOverflow', 'off', ['off', 'on']);
    if (block.fields.has('Ports')) { accepted.add('Ports'); const f = block.fields.get('Ports')!, expected = output ? `[${inputs}, 1]` : `[${inputs}]`, values = /^\[\s*(\d+)\s*(?:[, ]\s*(\d+)\s*)?\]$/.exec(f.value); if (!values || Number(values[1]) !== inputs || (output ? Number(values[2]) !== 1 : values[2] !== undefined && Number(values[2]) !== 0)) issue(report.issues, 'NATIVE_PORT_LAYOUT', `Ports 설정이 선택 포트 ${expected}와 다릅니다.`, f.location, 'unsupported', { nativeId: block.id, parameter: 'Ports', original: f.value }); }
    for (const [key, f] of block.fields) if (!accepted.has(key)) issue(report.issues, cosmetic.has(key) ? 'NATIVE_COSMETIC_PRESERVED' : 'NATIVE_BLOCK_OPTION', `${block.name}.${key}는 원본에 보존되며 실행 변환하지 않습니다.`, f.location, cosmetic.has(key) ? 'info' : 'unsupported', { nativeId: block.id, parameter: key, original: f.value });
    for (const key of ['Value', 'Gain', 'InitialCondition', 'SampleTime', 'Port']) { const f = block.fields.get(key); if (f && Object.is(literal(f.value), -0)) issue(report.issues, 'NATIVE_SIGNED_ZERO_UNSUPPORTED', 'signed zero(-0)는 기존 JSON scalar 모델이 정확히 보존하지 못합니다.', f.location, 'unsupported', { nativeId: block.id, parameter: key, original: f.value }); }
    if (block.type === 'Inport' && options.inports?.[block.id] === undefined) continue;
    nodes.push({ id, blockType, blockVersion: 1, label: block.name.slice(0, 100), parameters, unit: '1' }); ports.set(block.id, { inputs, output, multi });
  }
  report.convertedBlocks = nodes.length; const edges: CalcModel['edges'] = [];
  for (const wire of graph.wires) { const source = ports.get(wire.source), target = ports.get(wire.target); if (!source || !target || !source.output || wire.sourcePort !== 1 || wire.targetPort < 1 || wire.targetPort > target.inputs) { issue(report.issues, 'NATIVE_CONNECTION_UNSUPPORTED', '미지원 블록 또는 선택 포트 범위 밖의 연결입니다.', wire.location, 'unsupported', { original: `${wire.source}:${wire.sourcePort}→${wire.target}:${wire.targetPort}` }); continue; } edges.push({ id: `Wire${edges.length + 1}`, source: { nodeId: ids.get(wire.source)!, portId: 'out' }, target: { nodeId: ids.get(wire.target)!, portId: target.multi ? `in${wire.targetPort}` : 'in' } }); }
  let model: CalcModel | undefined;
  try { model = parseModel({ schemaVersion: 1, modelId: 'NativeImported', name: graph.name.slice(0, 120) || 'Imported model', nodes, edges, execution: { mode: hasIntegrator ? 'continuous' : hasDelay ? 'discrete' : 'static', startTime, stopTime, step, ...(hasIntegrator ? { solver: { method: 'rk4', initialStep: step, maxStep: step } } : {}) }, layout: Object.fromEntries(nodes.map((node, i) => [node.id, { x: (i % 5) * 220, y: Math.floor(i / 5) * 150 }])) }); compileModel(model); report.graphCompile = 'passed'; }
  catch (error) { report.graphCompile = 'failed'; const diagnostics = error instanceof ModelError ? error.diagnostics : [{ code: 'NATIVE_COMPILE', message: '변환 그래프 검증 실패' }]; for (const diagnostic of diagnostics) issue(report.issues, diagnostic.code, diagnostic.message, { offset: 0 }, 'unsupported', { nativeId: diagnostic.nodeId }); }
  report.execution = report.graphCompile === 'passed' && !report.issues.some(item => item.severity === 'unsupported') ? 'supported' : 'unsupported';
  for (const key of Object.keys(options.inports ?? {})) if (!inports.some(port => port.nativeId === key)) issue(report.issues, 'NATIVE_INPUT_UNUSED', '해당 native Inport가 없는 입력 설정입니다.', { offset: 0 }, 'unsupported', { nativeId: key });
  if (report.issues.some(item => item.severity === 'unsupported')) report.execution = 'unsupported';
  if (report.execution !== 'supported') model = undefined;
  const locations: NativeSourceOrigin[] = graph.blocks.map(block => ({ kind: 'block', nativeId: block.id, ...(ports.has(block.id) ? { convertedId: ids.get(block.id)! } : {}), location: block.location, parameters: [...block.fields].map(([name, field]) => ({ name, location: field.location })) }));
  const edgeIds = new Map(edges.map(edge => [`${edge.source.nodeId}|${edge.target.nodeId}|${edge.target.portId}`, edge.id]));
  for (const wire of graph.wires) { const converted = edgeIds.get(`${ids.get(wire.source)}|${ids.get(wire.target)}|${ports.get(wire.target)?.multi ? `in${wire.targetPort}` : 'in'}`); locations.push({ kind: 'connection', nativeId: `${wire.source}:${wire.sourcePort}->${wire.target}:${wire.targetPort}`, ...(converted ? { convertedId: converted } : {}), location: wire.location }); }
  return { report, model, inports, locations };
}
