import type { CalcNode } from '../../model/src/types';
import type { BlockDefinition, ParameterDefinition } from './index';

export const M12_BLOCK_IDS = ['continuous.descriptor', 'continuous.integrator-limited', 'continuous.second-order-limited', 'continuous.pid-2dof', 'time.variable-delay', 'time.variable-transport-delay', 'nonlinear.backlash', 'nonlinear.rate-limiter-continuous', 'nonlinear.rate-limiter-dynamic', 'solver.algebraic-constraint', 'analysis.linearization'] as const;
export type M12BlockType = typeof M12_BLOCK_IDS[number];
const number = (label: string, value: number, min = -Number.MAX_VALUE, max = Number.MAX_VALUE): ParameterDefinition => ({ kind: 'number', label, default: value, min, max });
const integer = (label: string, value: number, min: number, max: number): ParameterDefinition => ({ kind: 'integer', label, default: value, min, max });
const choice = (label: string, value: string, options: readonly string[]): ParameterDefinition => ({ kind: 'enum', label, default: value, options });
const vector = (label: string, value: number[], maximum = 16): ParameterDefinition => ({ kind: 'numeric-vector', label, default: value, minLength: 0, maxLength: maximum });
const matrix = (label: string, value: number[][]): ParameterDefinition => ({ kind: 'value', label, default: value });
const reset = choice('초기화', 'none', ['none', 'rising']);
const common = { version: 1, category: '연속 계산', inputs: ['in'], outputs: ['out'], parameters: {}, supportedModes: ['continuous'], directFeedthrough: false, valueType: 'float64', shape: 'scalar', unit: 'dimensionless', sampleTime: 'inherited', state: 'continuous-state', exportTargets: ['typescript'] } as const;
const define = (id: M12BlockType, label: string, englishName: string, description: string, overrides: Partial<BlockDefinition> = {}): BlockDefinition => ({ ...common, id, label, englishName, description, ...overrides });
const delays = { minDelay: number('최소 양의 지연 (s)', .01, 1e-9, 1e9), maxDelay: number('최대 지연 (s)', 10, 1e-9, 1e9), initial: number('초기 출력', 0), historyLimit: integer('승인 이력 상한', 4_096, 4, 40_000) };

export const M12_BLOCK_DEFINITIONS: readonly BlockDefinition[] = [
  define('continuous.descriptor', '음함수 상태 공간', 'Descriptor State-Space (Selected)', '비특이 질량 행렬 또는 명시 index-1 분할을 검증해 실제 미분·대수 상태를 계산합니다. 일반 DAE와 구분합니다.', { outputs: ['out', 'state'], directFeedthrough: true, shape: 'inherited', parameters: { E: matrix('E 질량 행렬', [[1]]), A: matrix('A', [[-1]]), B: matrix('B', [[1]]), C: matrix('C', [[1]]), D: matrix('D', [[0]]), initial: vector('전체 초기 상태', [0]), differentialCount: integer('미분 상태 수 (0: 비특이 E)', 0, 0, 16), initialPolicy: choice('대수 초기 일관성', 'error', ['error', 'project']), consistencyTolerance: number('일관성 허용오차', 1e-8, 1e-14, 1e-2), pivotTolerance: number('상대 pivot 허용오차', 1e-12, 1e-15, 1e-3) } }),
  define('continuous.integrator-limited', '제한 적분', 'Integrator Limited (Selected)', '상·하한 도달 사건에서 상태를 투영하고 안쪽 방향의 입력에서 다시 적분합니다.', { outputs: ['out', 'limited'], parameters: { initial: number('초기값', 0), lower: number('하한', -10), upper: number('상한', 10), reset } }),
  define('continuous.second-order-limited', '제한 2차 적분', 'Second-Order Integrator Limited (Selected)', '위치·속도 경계를 사건으로 처리합니다. 위치 경계에서 속도를0으로 초기화하며 안쪽 방향 가속도에서 이탈합니다.', { outputs: ['out', 'velocity', 'positionLimited', 'velocityLimited'], parameters: { initialPosition: number('초기 위치', 0), initialVelocity: number('초기 속도', 0), positionLower: number('위치 하한', -10), positionUpper: number('위치 상한', 10), velocityLower: number('속도 하한', -10), velocityUpper: number('속도 상한', 10), reset } }),
  define('continuous.pid-2dof', '연속 2DOF PID', 'PID Controller (2DOF, Selected)', '기준값·측정값을 P/D 가중하고 필터 미분, 출력 제한, 명시 anti-windup을 계산합니다. 자동 튜닝은 별도 기능입니다.', { inputs: ['r', 'y'], directFeedthrough: true, parameters: { kp: number('P', 1), ki: number('I', 1), kd: number('D', 0), filterN: number('미분 필터 N', 10, 1e-12, 1e12), b: number('P 기준 가중치', 1), c: number('D 기준 가중치', 1), initialIntegral: number('초기 I 출력', 0), initialFilter: number('초기 D 필터', 0), form: choice('형식', 'parallel', ['parallel', 'ideal']), controller: choice('제어기', 'PID', ['PID', 'PI', 'PD', 'P', 'I']), limit: choice('출력 제한', 'off', ['off', 'on']), lower: number('출력 하한', -10), upper: number('출력 상한', 10), antiWindup: choice('적분 포화 보정', 'none', ['none', 'clamp', 'back-calculation']), kb: number('역계산 배율', 1, 0, 1e12), reset } }),
  define('time.variable-delay', '가변 시간 지연', 'Variable Time Delay (Selected)', '승인된 신호 이력에서 t−delay를 보간합니다. 양의 지연 하한과0 지연 처리 정책을 명시합니다.', { category: '시간', inputs: ['in', 'delay'], directFeedthrough: true, state: 'discrete-state', parameters: { ...delays, handleZero: choice('0 지연 직접 연결', 'no', ['no', 'yes']) } }),
  define('time.variable-transport-delay', '가변 운송 지연', 'Variable Transport Delay (Selected)', 'q′=1/순간지연 상태와 승인 이력을 사용해 운송 나이1에 해당하는 입력을 찾습니다.', { category: '시간', inputs: ['in', 'delay'], directFeedthrough: true, parameters: delays }),
  define('nonlinear.backlash', '백래시', 'Backlash (Selected)', '이전 승인 출력 중심의 deadband를 유지하고 입력이 경계를 넘으면 실제 출력 상태를 이동합니다.', { category: '비선형', directFeedthrough: true, state: 'discrete-state', parameters: { width: number('Deadband 폭', 1, 0), initial: number('초기 출력', 0) } }),
  define('nonlinear.rate-limiter-continuous', '변화율 제한', 'Rate Limiter (Selected)', '승인 major-step 간격의 상승·하강 envelope를 계산합니다. 연속 초기 출력은 첫 입력이고 이산 초기값은 명시 설정입니다.', { category: '비선형', directFeedthrough: true, state: 'discrete-state', supportedModes: ['discrete', 'continuous'], parameters: { rising: number('상승 한도', 1, 0), falling: number('하강 한도', -1, -Number.MAX_VALUE, 0), initial: number('이산 초기 출력', 0) } }),
  define('nonlinear.rate-limiter-dynamic', '동적 변화율 제한', 'Rate Limiter Dynamic (Discrete Selected)', '외부 상승·하강 한도로 이산 read-before-write 상태를 갱신합니다. 연속 모델에서는 명시 이산 due-grid로 실행합니다.', { category: '비선형', inputs: ['in', 'rising', 'falling'], state: 'discrete-state', supportedModes: ['discrete', 'continuous'], sampleTime: 'fixed-tick', parameters: { initial: number('초기 출력', 0) } }),
  define('solver.algebraic-constraint', '대수 제약', 'Algebraic Constraint (Selected)', '실제 smooth scalar 도식의 unknown을 공동 Newton solve하여 입력 잔차를0 또는 unknown으로 맞춥니다.', { category: '솔버', directFeedthrough: true, state: 'discrete-state', parameters: { initial: number('초기 추정', 0), tolerance: number('잔차 허용오차', 1e-8, 1e-14, 1e-2), maxIterations: integer('Newton 상한', 24, 1, 32), constraint: choice('제약', 'zero', ['zero', 'fixed-point']) } }),
  define('analysis.linearization', '국소 선형화', 'Local Linearization (Independent Alternative)', '실제로 컴파일한 연속 정의의 operating point에서 중심차분으로 A/B/C/D를 계산합니다. 지정 시각 또는 rising trigger에 결과를 유지합니다.', { category: '분석', inputs: [], directFeedthrough: true, state: 'discrete-state', valueType: 'inherited', shape: 'inherited', parameters: { definitionId: { kind: 'text', label: '연속 정의 ID', default: 'plant', maxLength: 64 }, version: integer('정의 버전', 1, 1, 1_000_000), operatingInputs: vector('입력 operating point', [], 8), operatingState: vector('상태 operating point', [], 16), fdStep: number('중심차분 상대 간격', 1e-5, 1e-8, 1e-2), times: vector('요청 시각', [0], 64), mode: choice('요청 방식', 'timed', ['timed', 'triggered']) } }),
];

export function getM12Ports(node: Pick<CalcNode, 'blockType' | 'parameters'>): { inputs: string[]; outputs: string[] } | undefined {
  if (['continuous.integrator-limited', 'continuous.second-order-limited', 'continuous.pid-2dof'].includes(node.blockType)) return { inputs: [...(node.blockType === 'continuous.pid-2dof' ? ['r', 'y'] : ['in']), ...(node.parameters.reset === 'rising' ? ['reset'] : [])], outputs: node.blockType === 'continuous.integrator-limited' ? ['out', 'limited'] : node.blockType === 'continuous.second-order-limited' ? ['out', 'velocity', 'positionLimited', 'velocityLimited'] : ['out'] };
  if (node.blockType === 'analysis.linearization') return { inputs: node.parameters.mode === 'triggered' ? ['trigger'] : [], outputs: ['out'] };
  return undefined;
}
export function getM12DirectFeedthroughPorts(node: Pick<CalcNode, 'blockType' | 'parameters'>): string[] | undefined {
  if (node.blockType === 'time.variable-delay') return node.parameters.handleZero === 'yes' ? ['in', 'delay'] : ['delay'];
  if (node.blockType === 'time.variable-transport-delay') return ['delay'];
  if (node.blockType === 'continuous.descriptor') { const reduction = node.parameters.descriptorReduced as { D?: number[][]; algebraicB?: number[][] } | undefined; return reduction ? reduction.D?.some(row => row.some(value => value !== 0)) || reduction.algebraicB?.some(row => row.some(value => value !== 0)) ? ['in'] : [] : ['in']; }
  if (['continuous.integrator-limited', 'continuous.second-order-limited', 'nonlinear.rate-limiter-dynamic', 'solver.algebraic-constraint'].includes(node.blockType)) return [];
  if (node.blockType === 'continuous.pid-2dof') { const p = node.parameters, derivativeGain = Number(p.kd ?? 0) * (p.form === 'ideal' ? Number(p.kp ?? 1) : 1); return ['r', 'y'].filter(port => (['PID', 'PI', 'PD', 'P'].includes(String(p.controller ?? 'PID')) && Number(p.kp ?? 1) * (port === 'r' ? Number(p.b ?? 1) : -1) !== 0) || (['PID', 'PD'].includes(String(p.controller ?? 'PID')) && derivativeGain * (port === 'r' ? Number(p.c ?? 1) : -1) !== 0)); }
  if (node.blockType === 'analysis.linearization') return node.parameters.mode === 'triggered' ? ['trigger'] : [];
  return undefined;
}

