import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { blockRegistry, getBlockDefinition } from '../packages/block-library/src';
import { M14_BLOCK_IDS } from '../packages/block-library/src/m14';
import { compileModel } from '../packages/compiler/src';
import { ADAPTER_PROFILES, BUILTIN_ADAPTER_PROFILES, UNAVAILABLE_ADAPTER_PROFILES, ENGINE_VERSION, adapterAvailabilityDiagnostic, type ExecutionMode } from '../packages/model/src';
import { M14_WASM_BYTES, inspectM14Wasm } from '../packages/runtime/src/m14-wasm';
import { M14_INDEPENDENT_DEFINITION_FIXTURES, M14_INDEPENDENT_BOUNDARY_FIXTURES, M14_INDEPENDENT_FAILURE_FIXTURES } from '../tests/m14-independent-fixtures';

const args = process.argv.slice(2); assert(args.length === 1 && ['--check', '--write', '--verify'].includes(args[0]!), 'Use --check, --write or --verify');
const digest = (value: Buffer | string): string => createHash('sha256').update(value).digest('hex');
const canonical = (value: unknown): unknown => Array.isArray(value) ? value.map(canonical) : value && typeof value === 'object' ? Object.fromEntries(Object.keys(value).sort().map(key => [key, canonical((value as Record<string, unknown>)[key])])) : value;
const sourcePath = 'dataset/Simulink_Basic_Blocks_R2024b.md', coveragePath = 'docs/block-coverage.md', mapPath = 'docs/m14-implementation-map.json';
const evidencePath = 'docs/evidence/m14-verification.json', approvalPath = 'docs/evidence/m14-source-approvals.json', fixturePath = 'tests/m14-independent-fixtures.ts', uiPath = 'docs/evidence/m14-ui-workflow-verification.json';
const previous = JSON.parse(await readFile('docs/evidence/m13-source-approvals.json', 'utf8')) as { protectedArtifacts: Record<string, string>; currentSourceSubset: number };
const protectedArtifacts: Record<string, string> = { ...previous.protectedArtifacts,
  'docs/baselines/m13-registry.json': 'a4f8cadc0e8333cdc029c64de294077d90a98ae6d1f1746753649549f4f6a0d2',
  'docs/evidence/m13-source-approvals.json': 'bffe058d20baa23783f5682537787dbb9b6ac7aea06746d738b0972286af72bc',
  'docs/evidence/m13-verification.json': 'aa67d7976bd891f122f8a25eff41deb8b2054bc31ba660082b873e269883b598',
  'docs/baselines/m13-block-coverage.md': '8d736de7dbf8dbda6eaca70790b0162afe7c78a168a09006e752c5fe8401e8c6' };
async function verifyProtected() { assert.equal(Object.keys(protectedArtifacts).length, 22); for (const [path, hash] of Object.entries(protectedArtifacts)) assert.equal(digest(await readFile(path)), hash, `${path}: protected predecessor/source artifact changed`); }
await verifyProtected(); assert.equal(previous.currentSourceSubset, 364);
interface Selection { canonical: string; parameters: Record<string, unknown>; requiredBindings: string[]; classification: string; boundary: string }
interface Row { id: string; sourceName: string; sourceSection: number; sourceOrdinal: number; sourceLine: number; sourceSubgroup: string; sourceCondition: string; originalIdentitySha256: string; baselineCanonical: string; baselineStatus: string; baselineExistingSubset: boolean; baselineRoadmapRow: unknown; baselineRoadmapRowSha256: string; sourceOptionCompletionStatus: string; nativeFullEquivalent: false; executionEquivalenceClaimed: false; selectedImplementation: Selection | null; approvalStatus: string; nativeExecutionStatus: string; primarySourceRuntimeExecuted: false; approval?: Record<string, unknown> }
interface Proof { id: string; mode: ExecutionMode; sourceIds?: string[]; blockIds: string[]; modelHash: string; parameters: Record<string, { blockType: string; parameters: Record<string, unknown>; sampleTime: unknown }>; samples: number; maximumScaledError: number; oracleTolerance: number; parityTolerance: number; independentLiteralOracle: boolean; strictStandaloneTemplateModeVerified: boolean; importFreeStandalone: boolean; actualStandaloneTypeScript: boolean; fullSamplesFinalStateMemoryParity: boolean; exactManifest: boolean; jsonRoundtrip: boolean; insertionOrderIndependent: boolean; pythonUnsupportedNodeDiagnostics: boolean; targetVersion: string }
const implementation = JSON.parse(await readFile(mapPath, 'utf8')) as { baseline: { datasetSha256: string; roadmapSha256: string }; rows: Row[]; selectedDefinitions: { id: string; modes: ExecutionMode[]; approvalStatus: string }[]; counts: Record<string, number>; implementationStatus: string; deliveryGate: Record<string, unknown>; claimScope: string };
const evidenceBytes = await readFile(evidencePath), evidence = JSON.parse(evidenceBytes.toString('utf8')) as { engineVersion: string; registryDefinitions: number; addedDefinitions: number; predecessorDefinitionsUnchanged: number; fullSimulinkEquivalenceClaimed: boolean; counts: Record<string, number>; parityTolerance: number; fixtures: Proof[]; failures: { name: string; phase: string; diagnosticCode: string; actualTypeScriptExecuted: boolean; fullPartialParity?: boolean }[] };
assert.equal(evidence.engineVersion, '0.15.0-m14'); if (args[0] === '--write') assert.equal(ENGINE_VERSION, evidence.engineVersion);
assert.equal(evidence.registryDefinitions, 337); assert.equal(evidence.addedDefinitions, 3); assert.equal(evidence.predecessorDefinitionsUnchanged, 334); assert.equal(evidence.fullSimulinkEquivalenceClaimed, false); assert.equal(evidence.parityTolerance, 3e-12);
const predecessor = JSON.parse(await readFile('docs/baselines/m13-registry.json', 'utf8')) as typeof blockRegistry;
assert.equal(predecessor.length, 334); for (const definition of predecessor) assert.deepEqual(getBlockDefinition(definition.id), definition, definition.id); assert(blockRegistry.length >= 337);
assert.equal(BUILTIN_ADAPTER_PROFILES.length, 3); assert.equal(UNAVAILABLE_ADAPTER_PROFILES.length, 8); assert.equal(ADAPTER_PROFILES.length, 11);
for (const profile of ADAPTER_PROFILES) { assert(Object.isFrozen(profile)); assert.equal(profile.rights.license, 'NOASSERTION'); assert.equal(profile.rights.externalCodeRedistribution, 'NOASSERTION'); assert.equal(profile.nativeRuntimeEquivalenceClaimed, false); assert(Object.values(profile.capabilities).every(value => value === false)); }
for (const profile of BUILTIN_ADAPTER_PROFILES.filter(value => value.artifact)) {
  const bytes = M14_WASM_BYTES[profile.id]!; assert.equal(digest(Buffer.from(bytes)), profile.artifact!.sha256); assert.equal(bytes.length, profile.artifact!.byteLength);
  const inspected = inspectM14Wasm(bytes, profile.id); assert.deepEqual(inspected.sections, [1, 3, 7, 10]); assert.deepEqual(inspected.exports, profile.artifact!.exports); assert.equal(inspected.imports + inspected.memories + inspected.tables + inspected.globals, 0); assert(!inspected.start && !inspected.loops && !inspected.calls);
}
for (const profile of UNAVAILABLE_ADAPTER_PROFILES) { assert.equal(profile.availability, 'unavailable'); assert.equal(adapterAvailabilityDiagnostic(profile.id)?.code, 'M14_NATIVE_ENVIRONMENT_UNAVAILABLE'); assert.equal(getBlockDefinition(profile.id), undefined); assert.equal(profile.supportedModes.length, 0); }
const raw = [...M14_INDEPENDENT_DEFINITION_FIXTURES, ...M14_INDEPENDENT_BOUNDARY_FIXTURES];
assert.equal(evidence.counts.rawFixtures, raw.length); assert.equal(evidence.counts.definitionFixtures, M14_INDEPENDENT_DEFINITION_FIXTURES.length); assert.equal(evidence.counts.modeExecutions, evidence.fixtures.length); assert.equal(evidence.counts.failures, M14_INDEPENDENT_FAILURE_FIXTURES.length); assert.equal(evidence.failures.length, M14_INDEPENDENT_FAILURE_FIXTURES.length); assert.equal(evidence.counts.actualTypeScript, evidence.fixtures.length + evidence.failures.filter(entry => entry.phase === 'runtime').length);
assert.equal(evidence.counts.checkedSamples, evidence.fixtures.reduce((sum, proof) => sum + proof.samples, 0)); assert.equal(evidence.counts.strictTypeScriptPrograms, 3);
const proofKey = (proof: Proof) => `${proof.id}/${proof.mode}`; assert.equal(new Set(evidence.fixtures.map(proofKey)).size, evidence.fixtures.length);
for (const proof of evidence.fixtures) {
  assert(proof.independentLiteralOracle && proof.strictStandaloneTemplateModeVerified && proof.importFreeStandalone && proof.actualStandaloneTypeScript && proof.fullSamplesFinalStateMemoryParity && proof.exactManifest && proof.jsonRoundtrip && proof.insertionOrderIndependent && proof.pythonUnsupportedNodeDiagnostics, proofKey(proof));
  assert.equal(proof.targetVersion, 'typescript-m14-v1'); assert.equal(proof.parityTolerance, 3e-12); assert(proof.maximumScaledError >= 0 && proof.maximumScaledError <= proof.oracleTolerance);
  const fixture = raw.find(entry => entry.name === proof.id); assert(fixture); assert.equal(proof.oracleTolerance, fixture.oracleTolerance); assert.deepEqual(proof.sourceIds ?? [], fixture.sourceIds ?? []);
  const model = structuredClone(fixture.model); model.execution.mode = proof.mode; if (proof.mode === 'static') model.execution.stopTime = model.execution.startTime;
  const compiled = compileModel(model); assert.equal(proof.modelHash, digest(compiled.semanticKey));
  assert.deepEqual(proof.parameters, Object.fromEntries(compiled.nodes.filter(node => (M14_BLOCK_IDS as readonly string[]).includes(node.blockType)).map(node => [node.id, { blockType: node.blockType, parameters: node.parameters, sampleTime: node.sampleTime }])));
}
for (const fixture of raw) for (const mode of fixture.declaredModes) assert(evidence.fixtures.some(proof => proof.id === fixture.name && proof.mode === mode));
for (const id of M14_BLOCK_IDS) for (const mode of getBlockDefinition(id)!.supportedModes) assert(evidence.fixtures.some(proof => proof.blockIds.includes(id) && proof.mode === mode));
for (const failure of evidence.failures) { const fixture = M14_INDEPENDENT_FAILURE_FIXTURES.find(entry => entry.name === failure.name); assert(fixture); assert.equal(failure.phase, fixture.phase); assert.equal(failure.diagnosticCode, fixture.code); if (failure.phase === 'runtime') assert(failure.actualTypeScriptExecuted && failure.fullPartialParity); }

// A real UI report must point to passing raw unit/browser reports; metadata declaration is not execution evidence.
const uiBytes = await readFile(uiPath), ui = JSON.parse(uiBytes.toString('utf8')) as { status: string; unit: { passed: number; failed: number; log: string }; browser: { passed: number; failed: number; report: string }; adapterProfiles: { profileId: string; availability: string; metadataRendered: boolean; executeValidated: boolean; nativeRuntimeEquivalenceClaimed: false }[]; nativeUnavailable: { profileId: string; diagnosticCode: string }[]; arbitraryCodeControls: false; legacyManualPort: { expression: string; actualExpected: number; safeAST: boolean; noMatlabExecuted: boolean } };
assert.equal(ui.status, 'passed'); assert.equal(ui.unit.failed + ui.browser.failed, 0); assert(ui.unit.passed > 0 && ui.browser.passed > 0); assert.equal(ui.arbitraryCodeControls, false);
assert.equal(ui.legacyManualPort.expression, '3*x+1'); assert.equal(ui.legacyManualPort.actualExpected, 7); assert(ui.legacyManualPort.safeAST && ui.legacyManualPort.noMatlabExecuted);
const unitBytes = await readFile(ui.unit.log), unit = JSON.parse(unitBytes.toString('utf8')) as { success: boolean; numPassedTests: number; numFailedTests: number }; assert(unit.success); assert.equal(unit.numPassedTests, ui.unit.passed); assert.equal(unit.numFailedTests, 0);
const browserBytes = await readFile(ui.browser.report), browser = JSON.parse(browserBytes.toString('utf8')) as { stats: { expected: number; unexpected: number; flaky: number; skipped: number } }; assert.equal(browser.stats.expected, ui.browser.passed); assert.equal(browser.stats.unexpected + browser.stats.flaky + browser.stats.skipped, 0);
for (const profile of ADAPTER_PROFILES) { const observed = ui.adapterProfiles.find(entry => entry.profileId === profile.id); assert(observed?.metadataRendered, profile.id); assert.equal(observed.availability, profile.availability); assert.equal(observed.nativeRuntimeEquivalenceClaimed, false); assert.equal(observed.executeValidated, profile.availability === 'bundled'); }
for (const profile of UNAVAILABLE_ADAPTER_PROFILES) assert(ui.nativeUnavailable.some(entry => entry.profileId === profile.id && entry.diagnosticCode === 'M14_NATIVE_ENVIRONMENT_UNAVAILABLE'));

assert.equal(implementation.baseline.datasetSha256, protectedArtifacts[sourcePath]); assert.equal(implementation.baseline.roadmapSha256, protectedArtifacts['docs/simulink-coverage-roadmap.json']);
const roadmap = JSON.parse(await readFile('docs/simulink-coverage-roadmap.json', 'utf8')) as { rows: { id: string; firstWorkMilestone: string; name: string; section: number; ordinal: number; line: number; subgroup: string; condition: string }[] };
const expectedRows = roadmap.rows.filter(row => row.firstWorkMilestone === 'M14'); assert.equal(expectedRows.length, 8); assert.deepEqual(implementation.rows.map(row => row.id), expectedRows.map(row => row.id));
const baselineLines = (await readFile('docs/baselines/m13-block-coverage.md', 'utf8')).split('\n'), currentCoverage = await readFile(coveragePath, 'utf8'), currentLines = currentCoverage.split('\n');
const approvals = implementation.rows.flatMap(row => {
  const original = expectedRows.find(item => item.id === row.id)!;
  assert.deepEqual({ id: row.id, name: row.sourceName, section: row.sourceSection, ordinal: row.sourceOrdinal, line: row.sourceLine, subgroup: row.sourceSubgroup, condition: row.sourceCondition }, { id: original.id, name: original.name, section: original.section, ordinal: original.ordinal, line: original.line, subgroup: original.subgroup, condition: original.condition });
  assert.deepEqual(row.baselineRoadmapRow, original); assert.equal(row.baselineRoadmapRowSha256, digest(JSON.stringify(canonical(original)))); assert.equal(row.originalIdentitySha256, digest(JSON.stringify({ id: original.id, name: original.name, section: original.section, ordinal: original.ordinal, line: original.line, subgroup: original.subgroup, condition: original.condition })));
  assert.equal(row.sourceOptionCompletionStatus, 'open'); assert.equal(row.nativeExecutionStatus, 'unavailable'); assert.equal(row.nativeFullEquivalent, false); assert.equal(row.executionEquivalenceClaimed, false); assert.equal(row.primarySourceRuntimeExecuted, false);
  assert.equal(row.baselineStatus, '미구현'); assert.equal(row.baselineExistingSubset, false);
  const selection = row.selectedImplementation; if (!selection) { assert.equal(row.approvalStatus, 'unavailable-not-counted'); assert.equal(currentLines.find(line => line.startsWith(`| [${row.id}]`)), baselineLines.find(line => line.startsWith(`| [${row.id}]`))); return []; }
  assert.equal(selection.classification, 'independent-alternative'); const definition = getBlockDefinition(selection.canonical)!;
  const fixtures = raw.filter(entry => entry.sourceIds?.includes(row.id) && entry.model.nodes.some(node => node.blockType === selection.canonical)); assert(fixtures.length > 0, row.id);
  const profiles = fixtures.map(fixture => { const node = fixture.model.nodes.find(item => item.blockType === selection.canonical)!;
    const selectedParameters = Object.fromEntries(Object.entries(definition.parameters).map(([key, param]) => [key, Object.hasOwn(node.parameters, key) ? structuredClone(node.parameters[key]) : structuredClone(param.default)]));
    const matched = evidence.fixtures.filter(proof => proof.id === fixture.name && proof.sourceIds?.includes(row.id)); for (const mode of fixture.declaredModes) assert(matched.some(proof => proof.mode === mode));
    const compiledNode = compileModel(fixture.model).nodes.find(item => item.id === node.id)!; for (const port of selection.requiredBindings) assert(compiledNode.inputs[port]);
    return { rawFixtureId: fixture.name, configuredNodeId: node.id, selectedParameters, declaredModes: fixture.declaredModes, requiredBindingsActuallyConnected: Object.keys(compiledNode.inputs), evidenceFixtureIds: matched.map(proofKey) };
  });
  assert(profiles.some(profile => Object.entries(selection.parameters).every(([key, value]) => profile.selectedParameters[key] === value)), `${row.id}: exact selected source profile missing`);
  const boundary = `${selection.boundary} · 실제 선택 구성 ${JSON.stringify(profiles.map(profile => ({ parameters: profile.selectedParameters, modes: profile.declaredModes })))}; literal numerical/state/lifecycle·실제 TS/JSON/삽입 역순·신뢰된 module/ABI·화면 workflow만 확인. Native 실행 unavailable·전체 원본 옵션/MathWorks parity open.`; assert(!boundary.includes('|'));
  return [{ sourceId: row.id, sourceName: row.sourceName, sourceLine: row.sourceLine, canonical: selection.canonical, selectedParameters: profiles[0]!.selectedParameters, configuredProfiles: profiles, evidenceFixtureIds: profiles.flatMap(profile => profile.evidenceFixtureIds), selectionKind: 'verified-independent-alternative', status: 'M14 독립 대체 subset', boundary, newlyApproved: true, nativeExecutionStatus: 'unavailable', nativeFullEquivalent: false, sourceOptionCompletionStatus: 'open', uiWorkflowEvidencePath: uiPath }];
});
assert.equal(approvals.length, 3); assert.deepEqual(approvals.map(entry => entry.sourceId).sort(), ['02-016', '19-001', '19-002']);
const approvedById = new Map(approvals.map(entry => [entry.sourceId, entry]));
const newLines = currentLines.map(line => { const match = /^\| \[(\d{2}-\d{3})\]\([^)]*\) \(L(\d+)\) \|/.exec(line), approved = match && approvedById.get(match[1]!); if (!approved) return line;
  const cells = line.slice(1, -1).split('|').map(cell => cell.trim()); assert.equal(cells.length, 9); const originalCells = baselineLines.find(value => value.startsWith(`| [${approved.sourceId}]`))!.slice(1, -1).split('|').map(cell => cell.trim()); for (const unchanged of [0, 1, 2, 3, 5, 6]) assert.equal(cells[unchanged], originalCells[unchanged], `${approved.sourceId}: original source identity/plan changed`); assert(cells[8] === '미구현' || cells[8] === approved.status); cells[4] = `\`${approved.canonical}\``; cells[7] = approved.boundary; cells[8] = approved.status; return `| ${cells.join(' | ')} |`; });
const untouched = baselineLines.filter(line => /^\| \[\d{2}-\d{3}\]/.test(line) && !approvedById.has(/^\| \[(\d{2}-\d{3})\]/.exec(line)![1]!)); assert.equal(untouched.length, 382);
for (const line of untouched) { const id = /^\| \[(\d{2}-\d{3})\]/.exec(line)![1]!; assert.equal(newLines.find(value => value.startsWith(`| [${id}]`)), line, `${id}: predecessor identity/mapping/status changed`); }
const summary = '- 현재 M14 승인 범위: 원본385행 중 독립 대체3행을 추가해 선택 subset367행·미구현18행. 기존334정의 보존·실제3정의 추가로337종이다. 최초 배정8행의 native 환경은 모두unavailable이고 나머지5행은 실행 승격하지 않았다. [M14 계약](m14-contract.md)·[실제 TS 증거](evidence/m14-verification.json)·[source 승인](evidence/m14-source-approvals.json). 전체옵션8행 모두open·native runtime동등성 미승인.';
const index = newLines.findIndex(line => line.startsWith('- 현재 M14 승인 범위:')); if (index >= 0) newLines[index] = summary; else newLines.splice(4, 0, summary);
const record = { generatedAt: new Date().toISOString(), stage: 'M14', engineVersion: evidence.engineVersion, datasetSha256: protectedArtifacts[sourcePath], sourceRows: 385, uniqueSourceNameStrings: 339, firstWorkSourceRows: 8, registryDefinitions: 337, approvedAdditionalSourceRows: 3, existingMappingExtensions: 0, approvedSourceRows: 3, currentSourceSubset: 367, missingSourceRows: 18, nativeUnavailableRows: 8, nonExecutableRowsNotCounted: 5, fullSourceOptionsClosed: 0, evidencePath, evidenceSha256: digest(evidenceBytes), fixturePath, fixtureSha256: digest(await readFile(fixturePath)), uiWorkflowEvidencePath: uiPath, uiWorkflowEvidenceSha256: digest(uiBytes), uiBackingReports: { [ui.unit.log]: digest(unitBytes), [ui.browser.report]: digest(browserBytes) }, adapterCatalogPath: 'packages/model/src/m14-adapters.ts', adapterCatalogSha256: digest(await readFile('packages/model/src/m14-adapters.ts')), protectedArtifacts, predecessorSourceRowsUnchanged: 382, unavailableSourceIds: implementation.rows.filter(row => !row.selectedImplementation).map(row => row.id), approvals, primarySourceRuntimeExecuted: false, fullSimulinkEquivalenceClaimed: false };
const updatedMap = structuredClone(implementation); Object.assign(updatedMap.counts, { sourceApprovals: 3, approvedAdditionalSourceRows: 3, nativeUnavailableRows: 8, nonExecutableRowsNotCounted: 5, fullSourceOptionsClosed: 0 });
if (updatedMap.implementationStatus === 'in-progress') updatedMap.implementationStatus = 'verified-selected-independent-alternatives';
if (updatedMap.deliveryGate.status === 'pending-engineering-validation') updatedMap.deliveryGate.status = 'passed-engineering-selected-scope';
Object.assign(updatedMap.deliveryGate, { actualStandaloneStatus: 'passed', browserStatus: 'passed-ui-workflows', sourceApprovalStatus: '3-independent-alternatives-only' });
updatedMap.claimScope = 'Three source-specific independently authored bounded alternatives verified by actual numerical/state/lifecycle/standalone/UI proof. All eight native environments remain unavailable and full options open. Five unavailable source rows are not upgraded; predecessor382 mappings/statuses and334 definitions are preserved. No MathWorks runtime equivalence or arbitrary adapter execution is claimed.';
for (const definition of updatedMap.selectedDefinitions) definition.approvalStatus = 'verified-selected-independent-alternative';
for (const row of updatedMap.rows) { const approved = approvedById.get(row.id); if (approved) { row.approvalStatus = 'verified-independent-alternative'; row.approval = { stageStatus: 'verified-independent-alternative', configuredProfiles: approved.configuredProfiles, evidenceFixtureIds: approved.evidenceFixtureIds, sourceApprovalPath: approvalPath, nativeExecutionStatus: 'unavailable', nativeFullEquivalent: false }; } }
if (args[0] === '--write') { await writeFile(coveragePath, newLines.join('\n')); await writeFile(approvalPath, JSON.stringify(record, null, 2) + '\n'); await writeFile(mapPath, JSON.stringify(updatedMap, null, 2) + '\n'); }
if (args[0] === '--verify') { assert.equal(currentCoverage, newLines.join('\n')); const stored = JSON.parse(await readFile(approvalPath, 'utf8')) as typeof record; const { generatedAt: _old, ...before } = stored, { generatedAt: _now, ...after } = record; assert.deepEqual(before, after); assert.deepEqual(implementation, updatedMap); }
await verifyProtected(); console.log(JSON.stringify({ registryDefinitions: 337, firstWorkSourceRows: 8, sourceApprovals: 3, sourceSubset: 367, missingSourceRows: 18, nativeUnavailableRows: 8, fullSourceOptionsClosed: 0, predecessorSourceRowsUnchanged: 382, protectedArtifacts: 22, mutated: args[0] === '--write' }));
