import assert from 'node:assert/strict';
import { registryWithoutApprovedObserverInputs } from './m16-support-source';
import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { blockRegistry, getBlockDefinition } from '../packages/block-library/src';
import { M12_BLOCK_IDS } from '../packages/block-library/src/m12';
import { compileModel } from '../packages/compiler/src';
import { ENGINE_VERSION, type ExecutionMode } from '../packages/model/src';
import { M12_INDEPENDENT_DEFINITION_FIXTURES, M12_INDEPENDENT_BOUNDARY_FIXTURES, M12_INDEPENDENT_FAILURE_FIXTURES } from '../tests/m12-independent-fixtures';

const args=process.argv.slice(2);assert(args.length===1&&['--check','--write','--verify'].includes(args[0]!), 'Use --check, --write or --verify');
const digest=(bytes:Buffer|string):string=>createHash('sha256').update(bytes).digest('hex');
const canonical=(value:unknown):unknown=>Array.isArray(value)?value.map(canonical):value!==null&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical((value as Record<string,unknown>)[key])])):value;
const sourcePath='dataset/Simulink_Basic_Blocks_R2024b.md',coveragePath='docs/block-coverage.md',mapPath='docs/m12-implementation-map.json',evidencePath='docs/evidence/m12-verification.json',approvalPath='docs/evidence/m12-source-approvals.json',fixturePath='tests/m12-independent-fixtures.ts';
const previous=JSON.parse(await readFile('docs/evidence/m11-source-approvals.json','utf8')) as{protectedArtifacts:Record<string,string>};
const protectedArtifacts:Record<string,string>={...previous.protectedArtifacts,
  'docs/baselines/m11-registry.json':'daaf1ec9df9b5b7b43efdfd57863d0467b3f5636b3bcb4fd3b5450322fe8bf2e',
  'docs/evidence/m11-source-approvals.json':'492abedeb09b84e601d206cf85ead66b3ba7596af0894f0f9519fd9af8aac8c7',
  'docs/evidence/m11-verification.json':'716939d06a20c53a3fb9655820fb5c366fde0b1bb0fd5fd37adb39abadafea76'};
async function verifyProtected(){for(const[path,hash]of Object.entries(protectedArtifacts))assert.equal(digest(await readFile(path)),hash,`${path}: frozen predecessor/source artifact changed`);}
await verifyProtected();
interface Route{canonical:string|null;parameters:Record<string,unknown>;requiredBindings:string[];independentAlternative:boolean;boundary:string;sourceFullEquivalent:false;evidenceFixtureIds:string[];runtimeLiteralFixtureIds:string[]}
interface Row{sourceId:string;sourceName:string;sourceLine:number;sourceSubgroup:string;sourceCondition:string;baselineCanonical:string;baselineStatus:string;baselineExistingSubset:boolean;baselineRoadmapRow:unknown;baselineRoadmapRowSha256:string;sourceOptionCompletionStatus:string;delivery:Route;approval:Record<string,unknown>}
interface Proof{id:string;mode:ExecutionMode;sourceIds?:string[];blockIds:string[];parameters:Record<string,{blockType:string;parameters:Record<string,unknown>;sampleTime:unknown}>;samples:number;maximumScaledError:number;oracleTolerance:number;parityTolerance:number;independentLiteralOracle:boolean;strictStandaloneTemplateModeVerified:boolean;strictProgramIndividuallyChecked:boolean;importFreeStandalone:boolean;actualStandaloneTypeScript:boolean;fullSamplesFinalStateMemoryParity:boolean;exactManifest:boolean;jsonRoundtrip:boolean;insertionOrderIndependent:boolean;pythonUnsupportedNodeDiagnostics:boolean;targetVersion:string}
const implementation=JSON.parse(await readFile(mapPath,'utf8'))as{baseline:{sourceRows:number;uniqueSourceNameStrings:number;datasetSha256:string};counts:Record<string,number|string>;rows:Row[];observedApi?:Record<string,unknown>;validationStatus?:Record<string,unknown>};
const evidenceBytes=await readFile(evidencePath),evidence=JSON.parse(evidenceBytes.toString('utf8'))as{engineVersion:string;registryDefinitions:number;addedDefinitions:number;predecessorDefinitionsUnchanged:number;fullSimulinkEquivalenceClaimed:boolean;counts:Record<string,number>;parityTolerance:number;fixtures:Proof[];failures:{name:string;phase:string;diagnosticCode:string;actualTypeScriptExecuted:boolean;fullPartialParity?:boolean}[]};
assert.equal(implementation.baseline.sourceRows,385);assert.equal(implementation.baseline.uniqueSourceNameStrings,339);assert.equal(implementation.baseline.datasetSha256,protectedArtifacts[sourcePath]);
assert.equal(evidence.engineVersion,'0.13.0-m12');if(args[0]==='--write')assert.equal(ENGINE_VERSION,evidence.engineVersion,'Write only from final M12 implementation');
assert.equal(evidence.registryDefinitions,304);assert.equal(evidence.addedDefinitions,11);assert.equal(evidence.predecessorDefinitionsUnchanged,293);assert.equal(evidence.fullSimulinkEquivalenceClaimed,false);assert.equal(evidence.parityTolerance,3e-12);
const predecessor=JSON.parse(await readFile('docs/baselines/m11-registry.json','utf8'))as typeof blockRegistry;
const historicalRegistry=registryWithoutApprovedObserverInputs(blockRegistry);
assert.equal(predecessor.length,293);for(const definition of predecessor)assert.deepEqual(historicalRegistry.find(block=>block.id===definition.id),definition,`${definition.id}: historical predecessor changed beyond two approved observer inputCount declarations`);assert(blockRegistry.length>=304);
const rawFixtures=[...M12_INDEPENDENT_DEFINITION_FIXTURES,...M12_INDEPENDENT_BOUNDARY_FIXTURES];
assert.equal(evidence.counts.rawFixtures,rawFixtures.length);assert.equal(evidence.counts.modeExecutions,evidence.fixtures.length);assert.equal(evidence.counts.failures,evidence.failures.length);assert.equal(evidence.counts.actualTypeScript,evidence.fixtures.length+evidence.failures.filter(entry=>entry.phase==='runtime').length);
const proofKey=(proof:Proof)=>`${proof.id}/${proof.mode}`;assert.equal(new Set(evidence.fixtures.map(proofKey)).size,evidence.fixtures.length);
for(const proof of evidence.fixtures){
  assert(proof.independentLiteralOracle&&proof.strictStandaloneTemplateModeVerified&&proof.importFreeStandalone&&proof.actualStandaloneTypeScript&&proof.fullSamplesFinalStateMemoryParity&&proof.exactManifest&&proof.jsonRoundtrip&&proof.insertionOrderIndependent&&proof.pythonUnsupportedNodeDiagnostics,`${proofKey(proof)}: incomplete actual proof`);
  assert.equal(proof.targetVersion,'typescript-m12-v1');assert.equal(proof.parityTolerance,3e-12);assert(Number.isFinite(proof.maximumScaledError)&&proof.maximumScaledError>=0&&proof.maximumScaledError<=proof.oracleTolerance);
  const raw=rawFixtures.find(entry=>entry.name===proof.id);assert(raw,proof.id);assert.equal(proof.oracleTolerance,raw.oracleTolerance);
  const model=structuredClone(raw.model);model.execution.mode=proof.mode;if(proof.mode==='static')model.execution.stopTime=model.execution.startTime;
  const compiled=compileModel(model);assert.deepEqual(proof.parameters,Object.fromEntries(compiled.nodes.filter(node=>(M12_BLOCK_IDS as readonly string[]).includes(node.blockType)).map(node=>[node.id,{blockType:node.blockType,parameters:node.parameters,sampleTime:node.sampleTime}])),`${proofKey(proof)}: configured IR drift`);
  assert.equal(proof.samples,proof.mode==='static'?1:Object.values(raw.expected)[0]!.length);
}
for(const fixture of rawFixtures)for(const mode of fixture.declaredModes)assert(evidence.fixtures.some(entry=>entry.id===fixture.name&&entry.mode===mode),`${fixture.name}/${mode}: missing declared mode`);
for(const mode of ['discrete','continuous'])assert(evidence.fixtures.some(entry=>entry.mode===mode&&entry.strictProgramIndividuallyChecked),`${mode}: standalone strict template missing`);
for(const id of M12_BLOCK_IDS)for(const mode of getBlockDefinition(id)!.supportedModes)assert(evidence.fixtures.some(entry=>entry.blockIds.includes(id)&&entry.mode===mode),`${id}/${mode}: definition mode proof missing`);
assert.equal(evidence.failures.length,M12_INDEPENDENT_FAILURE_FIXTURES.length);for(const failure of evidence.failures){const raw=M12_INDEPENDENT_FAILURE_FIXTURES.find(entry=>entry.name===failure.name);assert(raw);assert.equal(failure.diagnosticCode,raw.code);assert.equal(failure.phase,raw.phase);if(failure.phase==='runtime')assert(failure.actualTypeScriptExecuted&&failure.fullPartialParity);}
const sourceLines=(await readFile(sourcePath,'utf8')).split(/\r?\n/),baselineText=await readFile('docs/baselines/catalog-block-coverage.md','utf8');
const sourceRows=new Map(baselineText.split(/\r?\n/).flatMap(line=>{const match=/^\| \[(\d{2}-\d{3})\]\([^)]*\) \(L(\d+)\) \|/.exec(line);return match?[[match[1]!,{line:Number(match[2]),cells:line.slice(1,-1).split('|').map(cell=>cell.trim())}]as const]:[];}));
const roadmap=JSON.parse(await readFile('docs/simulink-coverage-roadmap.json','utf8'))as{rows:{id:string;firstWorkMilestone:string}[]};
assert.equal(sourceRows.size,385);assert.equal(implementation.rows.length,26);assert.equal(new Set(implementation.rows.map(row=>row.sourceId)).size,26);assert.deepEqual(implementation.rows.map(row=>row.sourceId),roadmap.rows.filter(row=>row.firstWorkMilestone==='M12').map(row=>row.id));
for(const row of implementation.rows){const base=sourceRows.get(row.sourceId);assert(base);assert.equal(base.line,row.sourceLine);assert.deepEqual(base.cells.slice(1,4),[row.sourceName,row.sourceSubgroup,row.sourceCondition]);assert.equal(base.cells[4]!.replace(/^`|`$/g,''),row.baselineCanonical);assert.equal(base.cells[8],row.baselineStatus);assert.equal(row.baselineExistingSubset,row.baselineStatus!=='미구현');assert.deepEqual(row.baselineRoadmapRow,roadmap.rows.find(source=>source.id===row.sourceId));assert.equal(row.baselineRoadmapRowSha256,digest(JSON.stringify(canonical(row.baselineRoadmapRow))));assert.equal(sourceLines[row.sourceLine-1]!.trim(),`| ${row.sourceName} | ${row.sourceCondition} |`);assert.equal(row.sourceOptionCompletionStatus,'open');assert.equal(row.delivery.sourceFullEquivalent,false);}
const currentCoverage=await readFile(coveragePath,'utf8'),currentLines=currentCoverage.split(/\r?\n/);
const preserved: {sourceId:string;rowSha256:string;reason:string}[]=[];
const approvals=implementation.rows.flatMap(row=>{
  if(row.baselineExistingSubset){const line=currentLines.find(value=>value.startsWith(`| [${row.sourceId}]`));assert(line);preserved.push({sourceId:row.sourceId,rowSha256:digest(line),reason:'Previous selected source mapping retained; additional full source options or native parity are not inferred from a solver update.'});return[];}
  const route=row.delivery;assert(route.canonical&&(M12_BLOCK_IDS as readonly string[]).includes(route.canonical),row.sourceId);
  const sourceFixtures=rawFixtures.filter(entry=>entry.sourceIds?.includes(row.sourceId)&&entry.model.nodes.some(item=>item.blockType===route.canonical));
  const raw=sourceFixtures[0];assert(raw,`${row.sourceId}: genuine source-specific configured oracle absent`);
  const node=raw.model.nodes.find(item=>item.blockType===route.canonical);assert(node,row.sourceId);
  if(row.sourceId==='12-004')assert.equal(node.parameters.mode??'timed','timed');if(row.sourceId==='12-005')assert.equal(node.parameters.mode,'triggered');
  const definition=getBlockDefinition(route.canonical)!,selectedParameters=Object.fromEntries(Object.entries(definition.parameters).map(([key,param])=>[key,Object.hasOwn(node.parameters,key)?structuredClone(node.parameters[key]):structuredClone(param.default)]));
  const matched=evidence.fixtures.filter(proof=>sourceFixtures.some(entry=>entry.name===proof.id)&&proof.sourceIds?.includes(row.sourceId)&&proof.blockIds.includes(route.canonical!));
  const configuredProfiles=sourceFixtures.map(fixture=>{const configured=fixture.model.nodes.find(item=>item.blockType===route.canonical)!;return{rawFixtureId:fixture.name,configuredNodeId:configured.id,selectedParameters:Object.fromEntries(Object.entries(definition.parameters).map(([key,param])=>[key,Object.hasOwn(configured.parameters,key)?structuredClone(configured.parameters[key]):structuredClone(param.default)])),declaredModes:fixture.declaredModes,evidenceFixtureIds:matched.filter(proof=>proof.id===fixture.name).map(proofKey)};});
  assert(definition.supportedModes.every(mode=>matched.some(proof=>proof.mode===mode)),`${row.sourceId}: selected declared modes missing`);
  const compiledNode=compileModel(raw.model).nodes.find(item=>item.id===node.id)!;const bindings=Object.keys(compiledNode.inputs);for(const port of route.requiredBindings)if(!port.includes(' '))assert(bindings.includes(port),`${row.sourceId}: actual binding ${port} missing`);
  const selectionKind=route.independentAlternative?'verified-independent-alternative':'verified-native-scope',status=route.independentAlternative?'M12 독립 대체 subset':'M12 승인 subset';
  const boundary=`${route.boundary} · 실제 선택 구성 ${JSON.stringify(configuredProfiles.map(profile=>({parameters:profile.selectedParameters,modes:profile.declaredModes})))}; 독립 수치 oracle·TS/JSON·삽입 역순과 승인 상태 경계만 확인. 원본 전체 옵션·MathWorks 실행 parity는 미승인(open).`;
  assert(!boundary.includes('|'));
  return[{sourceId:row.sourceId,sourceName:row.sourceName,sourceLine:row.sourceLine,canonical:route.canonical,selectedParameters,configuredProfiles,configuredNodeId:node.id,rawFixtureId:raw.name,evidenceFixtureIds:matched.map(proofKey),declaredModes:[...definition.supportedModes],requiredBindingsActuallyConnected:bindings,selectionKind,status,boundary,newlyApproved:true,nativeFullEquivalent:false,sourceOptionCompletionStatus:'open'}];
});
assert.equal(approvals.length,12);assert.equal(preserved.length,14);
const approvedById=new Map(approvals.map(entry=>[entry.sourceId,entry])),newLines=currentLines.map(line=>{const match=/^\| \[(\d{2}-\d{3})\]\([^)]*\) \(L(\d+)\) \|/.exec(line),approved=match&&approvedById.get(match[1]!);if(!approved)return line;const cells=line.slice(1,-1).split('|').map(cell=>cell.trim());assert.equal(cells.length,9);assert(cells[8]==='미구현'||cells[8]===approved.status);cells[4]=`\`${approved.canonical}\``;cells[7]=approved.boundary;cells[8]=approved.status;return`| ${cells.join(' | ')} |`;});
const summary='- 현재 M12 승인 범위: 원본385행 중 선택 subset305행·미구현80행. 최초 배정26행의 신규12행을 승인하고 기존14행은 이전 선택 mapping을 유지한다. registry304 정의와 source행은 별도 집계다. [M12 계약](01-technical-whitepaper.md)·[실제 TS 증거](evidence/m12-verification.json)·[source 승인](evidence/m12-source-approvals.json)를 따른다. 전체옵션26행 모두open·원본실행동등성 미승인이다.';
// Keep the consolidated current header; historical approvals remain in frozen JSON.
const consolidatedHeader = currentCoverage.includes('[기계 판독 지원표](support-matrix.json)');
if (!consolidatedHeader) { const summaryIndex=newLines.findIndex(line=>line.startsWith('- 현재 M12 승인 범위:'));if(summaryIndex>=0)newLines[summaryIndex]=summary;else newLines.splice(4,0,summary); }
for(const row of preserved)assert.equal(digest(newLines.find(line=>line.startsWith(`| [${row.sourceId}]`))!),row.rowSha256);
const record={generatedAt:new Date().toISOString(),stage:'M12',engineVersion:evidence.engineVersion,datasetSha256:protectedArtifacts[sourcePath],sourceRows:385,uniqueSourceNameStrings:339,firstWorkSourceRows:26,registryDefinitions:304,approvedAdditionalSourceRows:12,existingMappingExtensions:0,approvedSourceRows:12,currentSourceSubset:305,missingSourceRows:80,fullSourceOptionsClosed:0,evidencePath,evidenceSha256:digest(evidenceBytes),fixturePath,fixtureSha256:digest(await readFile(fixturePath)),protectedArtifacts,preservedSourceRows:preserved,approvals,primarySourceRuntimeExecuted:false,fullSimulinkEquivalenceClaimed:false};
const updatedMap=structuredClone(implementation);Object.assign(updatedMap.counts,{approvedSourceRows:12,approvedAdditionalSourceRows:12,existingMappingExtensions:0,preservedPredecessorSourceRows:14,pendingSourceWorkflowRows:0,fullSourceOptionsClosed:0});
if(updatedMap.observedApi)Object.assign(updatedMap.observedApi,{actualStandaloneStatus:'passed-selected-scope',sourceApprovals:12});
if(updatedMap.validationStatus)Object.assign(updatedMap.validationStatus,{compilerRuntime:'passed-selected-scope',actualStandalone:'passed-35-executions',sourceApproval:'12-selected-source-rows'});
for(const row of updatedMap.rows){const approved=approvedById.get(row.sourceId);row.approval=approved?{stageStatus:approved.selectionKind,selectedParameters:approved.selectedParameters,rawFixtureId:approved.rawFixtureId,evidenceFixtureIds:approved.evidenceFixtureIds,sourceApprovalPath:approvalPath,nativeFullEquivalent:false}:{stageStatus:'preserved-predecessor-subset',reason:preserved.find(item=>item.sourceId===row.sourceId)!.reason,evidenceFixtureIds:[],sourceApprovalPath:approvalPath,nativeFullEquivalent:false};if(approved){row.delivery.evidenceFixtureIds=approved.evidenceFixtureIds;row.delivery.runtimeLiteralFixtureIds=[approved.rawFixtureId];}}
if(args[0]==='--write'){await writeFile(coveragePath,newLines.join('\n'));await writeFile(approvalPath,JSON.stringify(record,null,2)+'\n');await writeFile(mapPath,JSON.stringify(updatedMap,null,2)+'\n');}
if(args[0]==='--verify'){assert.equal(currentCoverage,newLines.join('\n'));const stored=JSON.parse(await readFile(approvalPath,'utf8'))as typeof record;const{generatedAt:_old,...before}=stored,{generatedAt:_new,...after}=record;assert.deepEqual(before,after);assert.deepEqual(implementation,updatedMap);}
await verifyProtected();console.log(JSON.stringify({sourceRows:385,registryDefinitions:304,firstWorkSourceRows:26,additionalSourceApprovals:12,preservedPredecessorRows:14,currentSourceSubset:305,missingSourceRows:80,fullSourceOptionsClosed:0,mutated:args[0]==='--write'}));
